### ISSUE TITLE
Error in executing Invoke-RemoteScript

### ISSUE THREAD

**Issue by ramzam062086** [SitecorePowerShell/Console#1007]
### Expected Behavior

I follow the instruction in YouTube (https://www.youtube.com/watch?v=fGvT8eDdWrg) and expecting to get a successful response from the CM server.

### Actual Behavior

It always throwing the below error.
Exception calling "ExecuteScriptBlock2" with "5" argument(s): "The request failed with an empty response."
At \\RPMAFN01\Users\W39668\My Documents\WindowsPowerShell\Modules\SPE\Invoke-RemoteScript.ps1:257 char:13
+             $response = $singleConnection.Proxy.ExecuteScriptBlock2($Username, $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

### Steps to Reproduce the Problem
We just followed the steps in youtube.

SPE 3.3 & SPE 4.7
Sitecore 8.1 & 8.2

 - [Yes] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [No] Asked questions on the Sitecore Slack Chat channel.
 
 - [No] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Please see issue #1005. Does that apply for you?

**Comment by ramzam062086** [comment]
Hi michaell,  Yeah, this works with me. Thank you so much.
