### ISSUE TITLE
JavaScript error in console when running Receive-File

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1008]
While running the following command:

```powershell
Receive-File (get-item "master:\media library\Files") -AdvancedDialog
```
I see the following error:

![image](https://user-images.githubusercontent.com/933163/40571541-185f4aca-6060-11e8-8e4b-5648411e5bd3.png)

Happens with 4.7.2 on Sitecore 8.2.7.

**Comment by michaellwest** [comment]
@alan-null Turns out this error is caused by sc_ext.

**Comment by alan-null** [comment]
@michaellwest errors are red, this is nicely caught exception 😆 
nothing critical, we can sleep well.
btw. thank you for using **sc_ext** 😄
