### ISSUE TITLE
Error in Invoke-Remote Script

### ISSUE THREAD

**Issue by ramzam062086** [SitecorePowerShell/Console#1011]
### Expected Behavior
The script below is working fine when installing packages in my local machine sitecore instance but i got an error when i tried it in our dev server.

    $session = New-ScriptSession -Username $sitecoreInstanceUserName -Password $sitecoreInstancePassword -ConnectionUri $sitecoreInstanceUri 
   
    $jobDetails = Invoke-RemoteScript -Session $session -ScriptBlock {             
        Install-UpdatePackage -Path $using:package -UpgradeAction Upgrade -InstallMode Install} -Verbose

        Start-Sleep -Seconds 5

    if (!$jobDetails) {
        $serverLog = [string]::Format("No jobId was created. Please check if your Powershell Remoting is activated on the target instance: [{0}]",$sitecoreInstanceUri)
        Write-Host $serverLog
    }
    else{
        $jobDetails
    }
        
    Stop-ScriptSession -Session $session 

Take note, i got a successful response when doing the below script in our dev server.
Import-Module -Name SPE
$session = New-ScriptSession -Username 'admin' -Password 'b' -ConnectionUri https://dev1.cm.global.wemshowcase.com

Invoke-RemoteScript -Session $session -ScriptBlock { Get-User -Id admin }

### Actual Behavior
```
Invoke-RemoteScript : Error while opening file 'D:\AgentPool\Utility\Package\KC.WEM.Feature.BuyNow.Core.scitems.update'
At D:\AgentPool\Utility\Scripts\Common Scripts\SitecoreSmartPublish.ps1:121 char:19
+     $jobDetails = Invoke-RemoteScript -Session $session -ScriptBlock {
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-RemoteScript
```
### Steps to Reproduce the Problem
Installing the same packages in our dev server that running under load balancer. 

_Please include the version number of SPE and Sitecore._
SPE 4.7 & Sitecore 8.2

 - [Yes] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [NO] Asked questions on the Sitecore Slack Chat channel.
 
 - [NO] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Is this still an issue for you? Doesn't look like all of your error appears in the comment above.

**Comment by manishmawat** [comment]
I am also facing same issue.. any options to solve..
I tried to enable the powershell remoting on sitecore still same error
<remoting enabled="true" requireSecureConnection="false">

**Comment by manishmawat** [comment]
I am also facing same issue.. any options to solve. I am executing this script through octopus server.
I tried to enable the powershell remoting on sitecore still same error.

**Comment by AdamNaj** [comment]
This looks like a permission issue. The ticket does not provide enough details to reproduce and is itself stale enough to close it. Please reopen if you're still experiencing the issue.
