### ISSUE TITLE
Add-ItemVersion should respect field ID rather than Name

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1017]
Reported by @ekapus on Slack.

Should make a call to `field.ID` rather than `field.Name`.

https://github.com/SitecorePowerShell/Console/blob/bf1e23da55de28deb2ba6c83af38f58fb0783a7c/Cognifide.PowerShell/Commandlets/Data/AddItemVersionCommand.cs#L124

**Comment by ekapus** [comment]
I just fixed this (as promised). Will be submitting my pull request momentarily.
