### ISSUE TITLE
Using Standard PowerShell Console

### ISSUE THREAD

**Issue by sgtoj** [SitecorePowerShell/Console#1018]
Is is possible to import the Sitecore PowerShell module in to a standard PS console? If so, which DLLs need to be imported. Additionally, how would I log in to Sitecore. 

My end goal is to invoke reindexing of the site via CLI command. It would be one step in many of a CI pipeline.

**Comment by michaellwest** [comment]
No, this is not possible. You can however use the SPE Remoting capabilities to achieve this.

https://doc.sitecorepowershell.com/remoting
