### ISSUE TITLE
 About Sitecore PowerShell Extensions Fails - HTTPS

### ISSUE THREAD

**Issue by TylerOrtiz** [SitecorePowerShell/Console#1029]
### Expected Behavior

Click on the `About` button in the PowerShell ISE, details about this module are displayed in the window.

### Actual Behavior

The window opens but nothing is displayed, no errors are shown. 

### Steps to Reproduce the Problem
Upon inspection of the DevTools console, the module is making an HTTP request for a resource:

`Mixed Content: The page at 'https://example.com/sitecore/shell/Applications/PowerShell/PowerShellIse?sc_bw=1' was loaded over HTTPS, but requested an insecure resource 'http://spe.najmanowicz.com/?ps=4.0&sc=8.2&spe=4.7.0.38819'. This request has been blocked; the content must be served over HTTPS.`

Sitecore PowerShell Extensions 4.7.0.38819
Sitecore 8.2
Windows PowerShell 4.0

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Thank you for reporting this @TylerOrtiz . Fixed with commit 1bb3c812f38c1c857af8943a024ee6f55849ad56.
