### ISSUE TITLE
PS code don't work properly when run in scheduled task but same code works fine when ran using execute now

### ISSUE THREAD

**Issue by biprajit** [SitecorePowerShell/Console#1031]
Hi All,
The below mentioned powershell syntax (in bold) don't work correctly when run through Sitecore scheduled task but works fine when run using "execute now" as well as in debug mode.

foreach ($role in $userRole)
                            {
                                **$itemRole = Test-ItemAcl -Identity $role -Path $parentPath -AccessRight item:read**
                                if ($itemRole -eq $TRUE)
                                {
                                    $documentList += $doc
                                }
                            }
The "Test-ItemAcl" line always returns "True" when ran using Scheduled task.
Can you please advice/suggest us on this.
Thanks for all the help.

**Comment by michaellwest** [comment]
Here are the steps I followed, and it appears to work as expected.

1. Created a new role called "sitecore\Demo Role"
2. Added user "sitecore\ca" to the role.
3. Selected an item and set deny read for the role.
4. Ran the script in the console which returned False.
5. Created a new PowerShell scripted task to run the script, which also returned false.

```powershell
$result = Get-Item -Path "master:" -ID "{614C498F-F392-496C-A461-92DD641087B7}" | 
    Test-ItemAcl -Identity "sitecore\Demo Role" -AccessRight item:read
Write-Log "The role sitecore\Demo Role has read access: $($result)"
```

**Comment by biprajit** [comment]
Thanks a lot michaellwest for your prompt reply.
We are comparing each role of the user with the role assigned to the immediate parent folder of the item. If any of the users role matches the item parent folder role, it should return true else it should return false.
We tried running the same code using Sitecore scheduled task again, but it always returns true. (**It woks fine if we run the same script code using execute now or in debug mode**) Kindly suggest if we need to make any changes to access/config settings. PFB, the script code details: (We are facing issue only with code line in bold)

$numberOfBatches = [Math]::floor(($userEmailPreferences.Keys.Count + $BATCH_SIZE - 1) / $BATCH_SIZE)
for ($i = 0; $i -lt $numberOfBatches; $i++)
{
    $msg = ([string]::Format("{0} Email Notifications: Batch {1}/{2} (batch size: {3})",(Get-Date).ToLongTimeString(), $i + 1,$numberOfBatches,$BATCH_SIZE))
    $global:logMsg += $msg + $carriageReturn
    Write-Host $msg
	
    $userEmailPreferencesBatch = $userEmailPreferences.Keys | Select-Object -First $BATCH_SIZE -Skip ($i * $BATCH_SIZE)
	
	#$index = 1			
    foreach ($userLocalName in $userEmailPreferencesBatch)
    {
        $user = Get-User -Identity "$DOMAIN\$($userLocalName)" -ErrorAction SilentlyContinue
        $itemRole = $false
        #if ($user)
        #{
            #Write-Host "$($index). $userLocalName"
            #$index = $index + 1
            #New-UsingBlock (New-Object Sitecore.Security.Accounts.UserSwitcher $user) {
                foreach ($notificationType in $userEmailPreferences[$userLocalName])
                {
                    $notification = $notificationsFolder.Children | Where-Object { $_["Value"] -eq $notificationType } 
                    $documents = Get-ChildItem -Path (Get-Item web: -ID $notification["Documents Root Folder"]).Paths.FullPath -Recurse |
                        Where-Object { $_.Fields["Catalog Updated On"] -ne $null -and $_.Fields["Catalog Updated On"].HasValue -and [Sitecore.DateUtil]::IsoDateToDateTime($_["Catalog Updated On"]) -gt [DateTime]::UtcNow.Date.AddDays(-1) }
                    
                    if ($documents)
                    {
                        $documentList= @()
                        foreach ($doc in $documents)
                        {
                            $userRole = $user.Roles.Name
                            $parentName = $doc.Parent
                            $parentPath = $parentName.Paths.FullPath
                            foreach ($role in $userRole)
                            {
                                **$itemRole = Test-ItemAcl -Identity $role -Path $parentPath -AccessRight item:read**
                                if ($itemRole -eq $TRUE)
                                {
                                    $documentList += $doc
                                }
                            }
                        }
                        $finalDocuments = $documentList | Select-Object -Unique
                        $finalDocuments = $documentList | Sort-Object -Unique
                        SendEmail -documents $finalDocuments -emailTemplate (Get-Item web: -ID $notification["Email Template"]) -user $user
                    }
                }
            #}
        #}
    }
}

**Comment by michaellwest** [comment]
Given that your example is far more complex, can you test with the script I provided? Would like to eliminate any possibility that other commands or code is causing the issue.

**Comment by biprajit** [comment]
Hi Michaellwest,
I tried with the script that you provided but getting (results variable) always true while ran using scheduled task. But it works fine if I run using execute now. PFB, the updated code. Can you please help?
if ($documents)
                    {
                        $documentList= @()
                        foreach ($doc in $documents)
                        {
                            $userRole = $user.Roles.Name
                            $parentName = $doc.Parent
                            $parentPath = $parentName.Paths.FullPath
                            foreach ($role in $userRole)
                            {
                                #$itemRole = Test-ItemAcl -Identity $role -Path $parentPath -AccessRight item:read
                                $result = Get-Item -Path $parentPath | Test-ItemAcl -Identity $role -AccessRight item:read
                                if ($result -eq $TRUE)
                                {
                                    $documentList += $doc
                                }
                            }
                        }
                        $finalDocuments = $documentList | Select-Object -Unique
                        $finalDocuments = $documentList | Sort-Object -Unique
                        SendEmail -documents $finalDocuments -emailTemplate (Get-Item web: -ID $notification["Email Template"]) -user $user
                    }

**Comment by biprajit** [comment]
Hi Michaellwest,

Can you please help with any update?

**Comment by michaellwest** [comment]
Will need a more concise example reproduced on a vanilla instance to help troubleshoot further. If you can provide that please reopen the issue.
