### ISSUE TITLE
Add translations for Danish, German, Japanese + Chinese languages

### ISSUE THREAD

**Issue by vini-2007** [SitecorePowerShell/Console#1037]
**Environment:** 
Sitecore 9.0.2, 9.1.0
Sitecore PowerShell Extensions-4.7.2 for Sitecore 8
**Issue:**
“Console” and “Scripts” are absent in context menu in Danish, German, Chinese languages
**Scenario:**
1. Login to Sitecore
2. Install SPE, SXA
2. Add Danish, German, or Chinese language
3. Import translations for added language in core, master db
4. Go to Content Editor
5. Right click on any item in Content tree
Actual result: “Console” and “Scripts” are absent in context menu
![image](https://user-images.githubusercontent.com/10813623/45866098-512e7080-bd88-11e8-91e3-e632f323d882.png)
Note: not reproduced in Japanese.
![image](https://user-images.githubusercontent.com/10813623/45866142-8044e200-bd88-11e8-8754-443bc5ab3d62.png)
It's because Sitecore PowerShell Extensions-4.7.2 for Sitecore 8.zip has Console and Scripts items with Japanese version inside
![image](https://user-images.githubusercontent.com/10813623/45866495-b6cf2c80-bd89-11e8-83fc-d8dc534bc198.png)

**Comment by michaellwest** [comment]
@AdamNaj Is this something we can do like with #682? I'm not sure how you generated the translation packages.

**Comment by AlexKasaku** [comment]
This would be great to get in I think. It looks like Adam's exports were using Sitecore's XML Language Export functionality, so I'll see if I can generate something similar.

That said, we may need some support from kind users who could offer translations of the texts for us to import.

**Comment by AlexKasaku** [comment]
Big update to support translations:

- Default Sitecore dictionary items used where possible
- Dialog XML files now used when generating dictionary items
- Translation file generation now uses unicorn configuration to get items
- Translation files generated for da, de-de, ja-jp and zh-cn
- Scripts added for importing / exporting XML translation files from / to CSV

**Comment by AlexKasaku** [comment]
I've added japanese back into this, as though there was a translation for this previously, it is now due to be updated with all of the additional content that has been added into it.

**Comment by AlexKasaku** [comment]
Translation XML files can be downloaded from the repo, or pull-requests made with updates:

https://github.com/SitecorePowerShell/Console/tree/master/Cognifide.PowerShell/Data/Translations

For ease of translation, the `ExportTranslationCsv.ps1` script can be run to turn the XML files into CSV. This has no dependency on Sitecore and can be run from Windows PowerShell.

**Comment by michaellwest** [comment]
@vini20072007 We are ready to give this a go. How best can we provide you with the translation files to start working on it?

**Comment by vini20072007** [comment]
We already have planned activities to test translations of Sitecore PowerShell Extensions for Sitecore 9.3.
We can take translations files from here.

**Comment by michaellwest** [comment]
@vini-2007 Are you still interested in helping with translations?

**Comment by vini-2007** [comment]
Hi Michael, I’m not interested, because I don’t work for Sitecore anymore.
