### ISSUE TITLE
Powershell Toolbox - entries order

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#1047]
### Expected Behavior/Actual Behavior
LEFT - Actual - **SPE 5.0**
RIGHT - Previous - **SPE 4.7.2**

![image](https://user-images.githubusercontent.com/6848691/46467160-569aaa80-c7cd-11e8-86f9-ee71a62344a4.png)

I am not sure if it worked previously but right now toolbox entries are sorted alphabetically and I cannot change the order unless I change name/display name

![image](https://user-images.githubusercontent.com/6848691/46467352-cf9a0200-c7cd-11e8-96b5-87c3996a31de.png)

What if I really want something like "Windows Firewall" on the top?

### Steps to Reproduce the Problem

- Open Desktop
- Click on `Powershell Toolbox`

**Comment by michaellwest** [comment]
There was a tradeoff between having it in random order and alphabetical. Perhaps one thing that can be done is to alpha sort and then sort by the Sort Order field.

**Comment by alan-null** [comment]
Sounds good to me. 
If @SitecorePowerShell/console  team thinks that this will be useful, let's do diz

**Comment by michaellwest** [comment]
Related to #1009. Need to ensure alpha sort happens when the sort order is empty or equal.

![image](https://user-images.githubusercontent.com/933163/47059271-47810880-d18e-11e8-853f-451925dbcdee.png)
