### ISSUE TITLE
Install Cognifide.PowerShell configs in \App_Config\Modules\SPE folder instead of \App_Config\Include

### ISSUE THREAD

**Issue by vini-2007** [SitecorePowerShell/Console#1050]
According to [Sitecore Configuration layers](https://doc.sitecore.net/sitecore_experience_platform/developing/developing_with_sitecore/customizing_server_configuration/configuration_layers), Sitecore PowerShell Extensions (SPE) module should install Cognifide.PowerShell config files in \App_Config\Modules\SPE folder.
Please implement this functionality.

**Comment by michaellwest** [comment]
Hi @vini20072007 . Thank you for using the module. The module continues to support Sitecore 8.x which doesn't not require that configuration. We'll consider it for a future release.
