### ISSUE TITLE
[SPE 5.0] The style of Progress Bar doesn't match to Sitecore style

### ISSUE THREAD

**Issue by vini-2007** [SitecorePowerShell/Console#1057]
The style of Progress Bar doesn't match to general style in Sitecore

**Actual result:**
![wrongstyle](https://user-images.githubusercontent.com/10813623/47265052-99c57f00-d52a-11e8-8dbc-47ed29233d74.png)

**Expected result:**
![correctstyle](https://user-images.githubusercontent.com/10813623/47265059-a1852380-d52a-11e8-842d-ad3a1c0bf245.png)

**Comment by michaellwest** [comment]
Prayer to version 5.0 module included a progress bar plug-in that gave it the Aero look seen in Windows Vista.

Do you have a screenshot in Sitecore where there's a progress bar that I can copy?

**Comment by vini20072007** [comment]
Hi Michael,
There are some dialogs in Content Editor > Developer tab
![rebuild](https://user-images.githubusercontent.com/10813623/47288066-1cb70a00-d5fd-11e8-8e92-b460bcb8d333.png)
![load](https://user-images.githubusercontent.com/10813623/47288067-1d4fa080-d5fd-11e8-8b12-ebcd98f72785.png)

**Comment by vini20072007** [comment]
Hi Michael,

There are some dialogs in Content Editor > Developer tab


________________________________

**Comment by michaellwest** [comment]
Yeah, guess I forgot about those when I made the change.
