### ISSUE TITLE
Show-Listview -Title 'test' -Modal does not show title

### ISSUE THREAD

**Issue by mortenengel** [SitecorePowerShell/Console#1068]
### Expected Behavior

[Sitecore.Jobs.JobManager]::GetJobs() | Show-ListView -Title 'Test' -Modal

Expected to see "Test" as the title in the modal window (which it is without -Modal).

### Actual Behavior

No title shown in modal

### Steps to Reproduce the Problem

SPE 4.7.2, Sitecore 9.0.2 & Sitecore 8.2

 - [ x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
You're in luck @mortenengel. Upgrade to 5.0 and this is fixed.

![image](https://user-images.githubusercontent.com/933163/47811443-ca1fd100-dd13-11e8-90e5-02260eb46c40.png)

**Comment by mortenengel** [comment]
awesome, thanks! figures that I even install it on a 9.0 system to doublecheck, but I miss that there's a new version out :)
