### ISSUE TITLE
Ancestor queries not working with Get-Item

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1069]
### Expected Behavior

The queries return items like that seen in the XPathBuilder.

https://spe.dev.local/sitecore/shell/default.aspx?xmlcontrol=IDE.XPath.Builder

![image](https://user-images.githubusercontent.com/933163/47859580-9d73c400-ddbc-11e8-8126-3f5c99725d80.png)

### Actual Behavior

No results returned.

### Steps to Reproduce the Problem

Run the following commands:

```powershell
Get-Item master: -Query "ancestor-or-self::*"
Get-Item master: -Query "./ancestor-or-self::*"
Get-Item master: -Query "ancestor-or-self::*[@@templatename='Sample Item']"
Get-Item master: -Query "./ancestor-or-self::*[@@templatename='Sample Item']"
```

Thanks for reporting @jammykam!

**Comment by michaellwest** [comment]
Looks like this can be achieved @jammykam.

```powershell
# Set the current location in ISE to master:\content\home\demo
$query = "ancestor-or-self::*[@@templatename='Sample Item']"
$SitecoreContextItem.Axes.SelectItems($query)
[Sitecore.Data.Query.Query]::SelectItems($query, $SitecoreContextItem)
Get-Item -Path "master:" -Query ("$($SitecoreContextItem.Paths.Path)/$query")

<#

Name                             Children Language Version Id                                     TemplateName
----                             -------- -------- ------- --                                     ------------
Demo                             False    en       1       {E3D16DC4-D258-4000-8D75-8187446C6D19} Sample Item
Demo                             False    en       1       {E3D16DC4-D258-4000-8D75-8187446C6D19} Sample Item
Demo                             False    en       1       {E3D16DC4-D258-4000-8D75-8187446C6D19} Sample Item
#>
```

**Comment by jammykam** [comment]
Yes, it can be achieved using those methods, but it's a workaround to running an actual Xpath query when passing in a `-Query` parameter.

Take the following example, which also does not work:
`
cd "master:/content/Project/Home/Test1/Test2"
Get-Item master: -Query "../../../*"
`

As you say, we can workaround this limitation:

`
$SitecoreContextItem = Get-Item -Path "master:/content/Project/Home/Test1/Test2"
$SitecoreContextItem.Axes.SelectItems("../../../*")
`
 Alternatively:
`
cd "master:/content/Project/Home/Test1/Test2"
$item = gi .
$item.Axes.SelectItems("../../../*")
`

These are probably infrequently used types of queries. Perhaps it will be sufficient to add these snippets in the book, so people are aware of the limitation.

**Comment by michaellwest** [comment]
Good idea on adding to the docs. That's posted now.
