### ISSUE TITLE
$SitecoreContextItem not available from Console

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1070]
Scripts always have access to the variable $SitecoreContextItem. For some reason it is missing from the console.

**Comment by AlexKasaku** [comment]
Think I have a fix for this, just need to take a bit of a longer look at it to check I haven't overlooked anything.

**Comment by AlexKasaku** [comment]
Implemented.

![image](https://user-images.githubusercontent.com/1439631/49833633-0a05b980-fd92-11e8-8a08-da13133ed796.png)

**Comment by michaellwest** [comment]
@AlexKasaku Looks like the Immediate Window console breaks while debugging.

**Comment by AlexKasaku** [comment]
Thanks for discovering @michaellwest! Have fixed the issue.
