### ISSUE TITLE
Get-User Filter returns no users when no wildcard provided

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1071]
No results:
`Get-User -Filter "exact@email.com"`

Some results:
`Get-User -Filter "exact@*email.com"`

Reported by immanuel79 Slack.

**Comment by AlexKasaku** [comment]
It looks like this is expected to contain a wildcard character - *, % or ?. If it doesn't contain these, it doesn't do anything. 

I think it could just fallback to the default behaviour and treat it the same as the Identity property, if no wildcard is included?

**Comment by michaellwest** [comment]
I think that is the way to go for this. Making sure that it works for both user name and email.

**Comment by michaellwest** [comment]
Fixed.
