### ISSUE TITLE
Show-ListView - page navigation section

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#1076]
### Expected Behavior

**Page** section in **ListView** is visible only if necessary (if there are pages to paginate)

### Actual Behavior

**Page** section in **ListView** is visible always, regardless of number of pages
![image](https://user-images.githubusercontent.com/6848691/49645552-ac354280-fa1c-11e8-9e13-99a732252d71.png)

### Steps to Reproduce the Problem

Invoke this script and see **ListView** output

```powershell
gci "/sitecore/templates" | Show-ListView
```

**Comment by michaellwest** [comment]
Easy enough. Implemented.
