### ISSUE TITLE
Add commands to manage archived items

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1084]
Currently the only command related to the archives is `Get-Archive`.

Makes sense to have commands like 

* Get-ArchiveItem
* Restore-ArchiveItem
* Remove-ArchiveItem

These articles helped:
* [Matthew Dresser](http://www.matthewdresser.com/sitecore/recycle-bin-finding-items-by-id)
* [Brian Pedersen](https://briancaos.wordpress.com/2014/01/14/sitecore-data-id-the-call-is-ambiguous/)

**Comment by michaellwest** [comment]
First example:

```powershell
$database = Get-Database -Name "master"
$archiveName = "recyclebin"
$archive = Get-Archive -Database $database -Name $archiveName
Get-ArchiveItem -Archive $archive -ItemId "{1BB32980-66B4-4ADA-9170-10A9D3336613}"
Get-ArchiveItem -Archive $archive -Identity "sitecore\admin"
```

**Comment by AlexKasaku** [comment]
Awesome!

**Comment by michaellwest** [comment]
Updated book branch with the new help docs.
