### ISSUE TITLE
ISE Null Reference Exception running script

### ISSUE THREAD

**Issue by Armaggoth** [SitecorePowerShell/Console#1092]
### Expected Behavior

When I write a script in the ISE and click on Run, I expect the script to run

### Actual Behavior

When I write a script in the ISE and click on Run, I get a yellow screen with a null reference exception message:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--
[NullReferenceException: Object reference not set to an instance of an object.]
   Cognifide.PowerShell.Core.Settings.<>c__DisplayClass88_0.<Save>b__0(ItemEditArgs p) +265
   Cognifide.PowerShell.Core.Extensions.ItemExtensions.Edit(Item item, Action`1 action) +688
   Cognifide.PowerShell.Core.Settings.ApplicationSettings.Save() +277
   Cognifide.PowerShell.Client.Applications.PowerShellIse.JobExecuteScript(ClientPipelineArgs args, String scriptToExecute, ScriptSession scriptSession, Boolean autoDispose, Boolean debug) +1792
   Cognifide.PowerShell.Client.Applications.PowerShellIse.JobExecuteScript(ClientPipelineArgs args, String scriptToExecute, Boolean debug) +1212
   Cognifide.PowerShell.Client.Applications.PowerShellIse.JobExecute(ClientPipelineArgs args) +195

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +142
   Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj) +89
   Sitecore.Nexus.Pipelines.NexusPipelineApi.Resume(PipelineArgs args, Pipeline pipeline) +313
   Sitecore.Pipelines.Pipeline.Start(PipelineArgs args, Boolean atomic) +167
   Sitecore.Web.UI.Sheer.ClientPage.RunPipelines() +459
   Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e) +801
   System.Web.UI.Control.PreRenderRecursiveInternal() +162
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +6875

### Steps to Reproduce the Problem
Just write a scritp in the ISE and click Run.
I have reinstalled the package with no luck

_Sitecore PSE 4.7.2. Sitecore 8.2 update 6_

**Comment by michaellwest** [comment]
The error may be occurring while trying to save the last executed script to the settings item under PowerShell directory. 

Are you running as Admin?

**Comment by michaellwest** [comment]
Please reopen the issue if you can reproduce using SPE 5.1 or newer in a vanilla instance of Sitecore.
