### ISSUE TITLE
Cannot define ribbon buttons for ListView with items of generic type 

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#1093]
Right now I cannot generate buttons for objects of generic type passed to ListView 
Because type which will be returned in **line 22** will contain special characters which cannot be used in item name/path
```
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    GenericBase`1                           System.Object
```

![image](https://user-images.githubusercontent.com/6848691/52129602-2f979c80-2638-11e9-87f6-cca050649e1c.png)

**Comment by michaellwest** [comment]
Looks like this will be a nice enhancement. Are you planning to take a stab at it @alan-null ?

**Comment by alan-null** [comment]
@michaellwest you can pick it if you want. 
@AdamNaj suggested removing special characters so we would have something like `GenericBase1`

**Comment by michaellwest** [comment]
I used the following example the verify that this feature now works.

```powershell
$friends = @()

Add-Type -typedef @"

public interface IPerson { }
public class Person : IPerson { }
public class Friend<T> where T : IPerson
{
    public string Name { get; set; }
    public string Comment { get; set; }
}
"@

$friend = New-Object "Friend[Person]"
$friend.Name = "Akshay"
$friend.Comment = "Great contributor to the Sitecore community!"

$friends += $friend

$props = @{
    Title = "Friends list"
    Property = @("Name", "Comment")
}
    
$friends | Show-ListView @props
Close-Window
```

Here is an example before:

![image](https://user-images.githubusercontent.com/933163/63562220-5826ab80-c522-11e9-844f-aa5b8a4b741d.png)

Here is an example after:

![image](https://user-images.githubusercontent.com/933163/63562262-8a380d80-c522-11e9-832b-b0780d822d81.png)

**Comment by alan-null** [comment]
@michaellwest
Awesome!
