### ISSUE TITLE
SPE Installation fails and throwing null reference exception.

### ISSUE THREAD

**Issue by KazTamai** [SitecorePowerShell/Console#1095]
### Expected Behavior

SPE 5.0 is successfully installed on Sitecore XP 9.1 from installation wizard.

### Actual Behavior

When I install SPE 5.0 from installation wizard, I get the error message saying "Object reference not set to an instance of an object." on Sitecore Dialog. 
I get the error message as shown below:

    ManagedPoolThread #3 16:37:48 ERROR Error installing 
    items/master/sitecore/system/Settings/Rules/Definitions/Elements/PowerShell 
    Experience Buttons/Chrome Type/of Type/{F5D1B95B-30D3-4738-B41E-6884517CB485}/en/1/xml
    Exception: System.NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: Sitecore.Kernel
    Location Sitecore.Data.DataProviders.Sql.SqlDataProvider.ResolvePathRec(String[] path, PathCache cache, CallContext context)
    Location Sitecore.Data.DataProviders.DataProvider.ResolvePath(String itemPath, CallContext context, DataProviderCollection providers)
    Location Sitecore.Nexus.Data.DataCommands.ResolvePathCommand.​‏⁮⁯⁪⁫‬‎⁯⁪‏‭‮‬‎‫⁭⁬‭‍‮‎⁪⁪⁯⁪⁮‭‪‮⁭⁪‍⁭‌⁭‌⁭‬‫‮(String , Database )
    Location Sitecore.Data.Engines.EngineCommand`2.Execute()
    Location Sitecore.Data.Managers.ItemProvider.GetItem(String itemPath, Language language, Version version, Database database, SecurityCheck securityCheck)
    Location Sitecore.ContentTesting.Pipelines.ItemProvider.GetItem.GetItemUnderTestProcessor.Process(GetItemArgs args)
    Location (Object , Object )
    Location Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
    Location Sitecore.Data.Managers.DefaultItemManager.GetItem(String itemPath, Language language, Version version, Database database, SecurityCheck securityCheck)
    Location Sitecore.Data.Managers.DefaultItemManager.GetItem(String itemPath, Language language, Version version, Database database)
    Location Sitecore.Data.Managers.ItemManager.GetItem(String itemPath, Language language, Version version, Database database)
    Location Sitecore.Install.Items.ItemReference.GetItem()
    Location Sitecore.Install.Items.ItemInstaller.GetTargetItem(ItemReference reference, Boolean& ignorePathCollision)
    Location Sitecore.Install.Items.ItemInstaller.GetVersionInstallMode(PackageEntry entry, ItemReference reference, XmlVersionParser parser, ItemInstallerContext context, Boolean& removeVersions)
    Location Sitecore.Install.Items.ItemInstaller.InstallEntry(PackageEntry entry)

### Steps to Reproduce the Problem

SPE version: 5.0 (tried 4.7.2 but got exact same error message)
Sitecore version: Sitecore XP 9.1

Clean Sitecore XP 9.1 and just installed SPE 5.0 from installation wizard.

**Comment by michaellwest** [comment]
Any idea why the Content Testing code appears in the error?

**Comment by AdamNaj** [comment]
This feels more like an issue with the user environment as it's not been reported by anyone else for 5 years.
