### ISSUE TITLE
Content Editor Ribbon integration for custom tabs

### ISSUE THREAD

**Issue by ozkansayin** [SitecorePowerShell/Console#1100]
### Expected Behavior

When you have a script under "$$AnyPowershellModule$$/Content Editor/Ribbon/$$CustomTabLibrary$$/$$CustomChunkLibrary$$", and click the button "Sync Library with Content Editor Ribbon" on ISE under _Settings_ tab - _Integration_ chunk, either the custom tab & chunk should be created properly so that it's visible, or no items in core database should be created.

### Actual Behavior
Let 

- $stripRoot be "/sitecore/content/Applications/Content Editor/Ribbons/Strips"
- $ribbonRoot be "/sitecore/content/Applications/Content Editor/Ribbons/Ribbons/Default"

The sync script creates the strip, chunk and the buttons under $stripRoot, but does not create a reference under $ribbonRoot, which results in the new tab not being visible. If you have a custom tab manually created, with a reference to an existing strip, the reference to that strip gets broken as the script deletes the existing strip, and creates a new one.

### Steps to Reproduce the Problem

Create a script under "$$AnyPowershellModule$$/Content Editor/Ribbon/$$CustomTabLibrary$$/$$CustomChunkLibrary$$", and click the button "Sync Library with Content Editor Ribbon" on ISE under _Settings_ tab - _Integration_ chunk. The custom tab $$CustomTabLibrary$$ will not be visible, but there will be items created on core database.

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by ozkansayin** [comment]
We have noticed this during the Sitecore Hackathon. As a workaround we have created the ribbon reference & the strip item manually, but since the script removes the strip if there are no chunks under it, the reference got broken.

I have seen in the [documentation](https://doc.sitecorepowershell.com/modules/integration-points/content-editor) that it reads "_Choose a name such as Home or Developer (this should match an existing tab name)_". However, that made us think that creating the strip ourselves would avoid this issue.
On one of our projects, I have updated the script "/sitecore/system/Modules/PowerShell/Script Library/SPE/Core/Platform/Internal/Integrations/Content Editor Ribbon" so that it creates the strip reference as well, and removes the reference if the strip being referenced is removed. However, I'm not sure if this is the desired behavior on your end. Feel free to let me know if this makes sense, and I can create a pull request.

If the integration script is not supposed to handle the custom strips, then I would suggest checking if there is a reference to that strip, and not creating strips - chunks - buttons if there is no reference, and preferably log this into console as a warning, something like "Skipping custom strip $$StripName$$".

**Comment by michaellwest** [comment]
Thanks for reporting this @ozkansayin. Do you think you could take a stab at it and then provide your updated script, possibly as a pull request?

**Comment by ozkansayin** [comment]
Pull request created. Also noticed a couple of bugs in the Contextual Ribbon integration when checking if there could be a related issue on other integrations, I'll create separate issues for those.

**Comment by michaellwest** [comment]
Thanks for contributing @ozkansayin . I can already tell it's working better.
