### ISSUE TITLE
Elevate access doesn't work for users logged in though the identity provider (for instance Azure AD)

### ISSUE THREAD

**Issue by dmborel** [SitecorePowerShell/Console#1102]
Elevate access doesn't work for users logged in though the identity provider (for instance Azure AD)

**Comment by michaellwest** [comment]
Do all the users login through the same way? The purpose of the Elevate Access prompt was to prevent users from running/saving by mistake. If an immediate solution is needed, you can patch each `token` (such as the ISE) with an `elevationAction` of **Allow**.

**Comment by Morksen** [comment]
I'm not sure, if it's related: when I'm submitting the elevation form, I get stuck in an endless loop of ExecuteCommand and request the Powershell Session 

WIth the following config change (on CM) I fixed it:
https://gist.github.com/Morksen/d963854801ab0ebf61cf69ae8b3d47d9

**Comment by michaellwest** [comment]
Thank you @Morksen . Can test for me the change included with 5.1? There is a config included for Identity Server. Enable that config and disable the one you provided.

**Comment by mitchclemens** [comment]
We're experiencing this issue as well.

Sitecore Version - Sitecore 9.0 Update 1
Powershell Version - 5.1
Identity Provider - Azure AD

We are forcing all users to log in to Sitecore through AAD. 
The config included for Identity Server does not work for Sitecore versions below 9.1 as the namespace does not exist.

@michaellwest Are there any other solutions we can do asides from changing the elevationaction to allow?

**Comment by michaellwest** [comment]
@mitchclemens The purpose of the Elevated Access is to (optionally) require the user to input a password. If the developer or admin would not know the password then there is little value in using this feature.
