### ISSUE TITLE
1HvhK3RCM3m3j2dKAXroKXrtELyZ1nnwEn

### ISSUE THREAD

**Issue by AlexandraAndreevna** [SitecorePowerShell/Console#1103]
### Expected Behavior

_Please describe the expected behavior._

### Actual Behavior

_Please describe the actual behavior._

### Steps to Reproduce the Problem

_Please include the version number of SPE and Sitecore._

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by alan-null** [comment]
@AlexandraAndreevna Could you please provide a description? Otherwise, I will be forced to remove this issue.
