### ISSUE TITLE
Install-UpdatePackage : Error while opening file 'C:\RamFiles\KC\Sitecore Package\SC9\KC.WEM.Foundation.All.Master.scitems.update'

### ISSUE THREAD

**Issue by ramzam062086** [SitecorePowerShell/Console#1108]
### Expected Behavior
Expected behavior should install the TDS package.

### Actual Behavior
Its throwing the below error.

Install-UpdatePackage : Error while opening file 'C:\RamFiles\KC\Sitecore Package\SC9\KC.WEM.Foundation.All.Master.scitems.update'
At line:6 char:9
+         Install-UpdatePackage -Path "C:\RamFiles\KC\Sitecore Package\ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-UpdatePackage], Exception
    + FullyQualifiedErrorId : System.Exception,Cognifide.PowerShell.Commandlets.UpdatePackages.InstallUpdatePackageCommand

### Steps to Reproduce the Problem
Sitecore: 9.1
SPE: 5.0

Set-ExecutionPolicy -Scope Process -Force Bypass
Import-Module -Name "C:\Users\w39668\Documents\WindowsPowerShell\Modules\SPE.Remoting-5.0\SPE"

$session = New-ScriptSession -Username 'admin' -Password 'b' -ConnectionUri http://server1.direct.tccwest.dev2.cm.wemshowcase.com

#Invoke-RemoteScript -Session $session -ScriptBlock { Get-User -Id admin }

Invoke-RemoteScript -Session $session -ScriptBlock {
       # $instanceLog = [string]::Format("{0}",$using:serverLog)
       # Write-Log $instanceLog
        
        
        Install-UpdatePackage -Path "C:\RamFiles\KC\Sitecore Package\SC9\KC.WEM.Foundation.All.Master.scitems.update" -UpgradeAction upgrade -InstallMode Install -Verbose} #-AsJob

 - [Yes] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [No ] Asked questions on the Sitecore Slack Chat channel.
 
 - [No ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Any chance you can provide a sample update package for me to test?

**Comment by ramzam062086** [comment]
Hi, i'm not sure how to add an attachment, but got new updates with the error from sitecore SPE logs. 
5316 20:42:00 INFO Installing Sitecore update package:[KC.WEM.Foundation.All.Master.scitems.update]
5316 20:42:00 WARN Error while opening file '\\in11wad550\http\01\com.wemshowcase_2\root\TDSPackages\KC.WEM.Foundation.All.Master.scitems.update'At line:7 char:9
+ Install-UpdatePackage -Path $params.__using_package -UpgradeA ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exception: System.Exception
Message: Error while opening file '\\in11wad550\http\01\com.wemshowcase_2\root\TDSPackages\KC.WEM.Foundation.All.Master.scitems.update'
Source: Sitecore.Zip
at Sitecore.Zip.ZipReader..ctor(String filename, Encoding encoding)
at Sitecore.Install.Zip.PackageReader.Populate(ISink`1 sink)
at Sitecore.Update.UpdateHelper.LoadMetadata(String packagePath)
at Cognifide.PowerShell.Commandlets.UpdatePackages.InstallUpdatePackageCommand.<>c__DisplayClass16_0.<ProcessRecord>b__0()
at Cognifide.PowerShell.Commandlets.Packages.BasePackageCommand.PerformInstallAction(String siteContext, Action action)
at Cognifide.PowerShell.Commandlets.Packages.BasePackageCommand.PerformInstallAction(Action action)
at Cognifide.PowerShell.Commandlets.UpdatePackages.InstallUpdatePackageCommand.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()
Nested Exception
Exception: System.UnauthorizedAccessException
Message: Access to the path '\\in11wad550\http\01\com.wemshowcase_2\root\TDSPackages\KC.WEM.Foundation.All.Master.scitems.update' is denied.
Source: mscorlib
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Sitecore.Zip.ZipReader..ctor(String filename, Encoding encoding)
5316 20:42:00 INFO The script execution in ScriptSession '$scriptSession$|f0618bc1-c1e8-4c65-9187-e31f23d85b39' completed in 6 ms.
5316 20:42:00 INFO Executing a script in ScriptSession '$scriptSession$|f0618bc1-c1e8-4c65-9187-e31f23d85b39'.
5316 20:42:00 INFO The script execution in ScriptSession '$scriptSession$|f0618bc1-c1e8-4c65-9187-e31f23d85b39' completed in 143 ms.
15908 20:42:01 INFO User 'admin' calling the Remoting Automation service.
15908 20:42:01 INFO User 'sitecore\admin' successfully logged in to the Remoting Automation service.
15908 20:42:01 INFO Session 'f0618bc1-c1e8-4c65-9187-e31f23d85b39' disposed by user: 'sitecore\admin'

it seems the user doesn't have an access with the file even it is place inside of the root path of the site.

Is there any steps that i need to apply in the server side to make it work?

**Comment by michaellwest** [comment]
By the looks of the error this is beyond SPE. The issue appears to be environment specific and errors from the base .net framework layer and bubbling up through the Sitecore API. You may explore the permissions of the service account running the site or moving the package to beneath the web root.

**Comment by ramzam062086** [comment]
Hi Michaell, thank you so much for your quick response. I'm closing this now as the issue was already resolved. :)

**Comment by ramzam062086** [comment]
Hi Michaell, thank you so much for your quick response. I'm closing this now as the issue was already resolved. :)
