### ISSUE TITLE
Provide way to swap renderings and copy presentation rules

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1110]
The current commands for managing presentation do not include rules. The community could benefit from having the option to copy or remove rules from components stored on the shared or final layouts.

* [ ] Provide way to include rules when adding or updating a rendering
* [x] Provide way to replace a rendering

**Comment by michaellwest** [comment]
This was shared by a member of the community for copying the rules.

https://sitecore.stackexchange.com/questions/18846/how-can-i-copy-personalization-rules-to-a-rendering-in-sitecore-powershell/18958#18958

**Comment by michaellwest** [comment]
On the rendering definition, there a few properties currently not modified.

* ClearOnIndexUpdate
* Rules
* MultiVariateTest
* Conditions

**Comment by fluxdigital** [comment]
Having done something similar here: https://www.flux-digital.com/blog/swapping-deleting-renderings-sitecore-powershell-extensions/ 

These are the key things I think should be supported:

- Support for target rendering Id to swap and new rendering Id to replace it with
- Option for device layout
- Option for placeholder to target
- Support for swapping renderings on pages and templates standard values too
- Option for updating datasource Id as well when swapping out a rendering
- Support for Final Renderings field as well as Renderings field

**Comment by michaellwest** [comment]
Added a new command for switching from one rendering to another. `Switch-Rendering`

```powershell
$itemId = "{110D559F-DEA5-42EA-9C1C-8A5DF7E70EF9}"
$item = Get-Item -Path "master:" -ID $itemId
$defaultLayout = Get-LayoutDevice "Default"

$sourceRenderingId = "{37F58448-7460-4AD2-B0FB-67C85C2A49CB}"
$targetRenderingId = "{90A9C167-5714-481F-82E4-29E394D12614}"

$sourceRenderings = Get-Rendering -Item $item -Device $defaultLayout -FinalLayout |
    Where-Object { $_.ItemID -eq $sourceRenderingId }
$targetRendering = Get-Item -Path "master:" -ID $targetRenderingId | New-Rendering

# Replace all instances of the old rendering with the new rendering
foreach($sourceRendering in $sourceRenderings) {
    $item | Switch-Rendering -Id $itemId -Instance $sourceRendering -Device $defaultLayout -FinalLayout -NewRendering $targetRendering
}
```

**Comment by michaellwest** [comment]
Partially completed?

**Comment by michaellwest** [comment]
Leave it as-is. Can create a new issue in the future to cover anything missing.
