### ISSUE TITLE
Assigning null value to object results in error

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1117]
The following script results in an error. Please help me fix it.

```powershell
$homeItem = Get-Item -Path "master:\content\home"
$homeItem.Title = $null
```
![image](https://user-images.githubusercontent.com/933163/59785740-3e02ef80-928b-11e9-892c-ebc7255a4d8f.png)

**Comment by michaellwest** [comment]
Hopefully this helps @cassidydotdk overcome his problems. :-)

**Comment by michaellwest** [comment]
Now the field shows the reset value.

![image](https://user-images.githubusercontent.com/933163/59786216-5e7f7980-928c-11e9-9368-7688af6af138.png)

**Comment by mrwensveen** [comment]
Hi! Looking at your comment, is this still an issue? Otherwise, I can try to check it out.

**Comment by michaellwest** [comment]
Thanks @mrwensveen, I was being silly. I made the code change. Currently slated for the 6.0 release.

**Comment by mrwensveen** [comment]
Ah. Those null checks can definitely be tricky sometimes. 😄
