### ISSUE TITLE
Rules based report : language filter and more rendering options

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1118]
Images:

The default behavior renderings the image. Would like an option to convert to ItemPath.

![image](https://user-images.githubusercontent.com/933163/59891739-fae47180-939b-11e9-8738-b19db4939777.png)

Languages:

There is no option to filter languages.

![image](https://user-images.githubusercontent.com/933163/59891799-3121f100-939c-11e9-8bf5-6537225d1387.png)

**Comment by AdamNaj** [comment]
@michaellwest  Do we want to keep it still? If we're not planning to implement it, let's close it for now.

**Comment by AdamNaj** [comment]
Closing for now. Feel free if there is interest.
