### ISSUE TITLE
Sitemap using display name

### ISSUE THREAD

**Issue by adel8hub** [SitecorePowerShell/Console#1119]
### Expected Behavior

generate sitemap using display name, page url are using display name as configured

### Actual Behavior

sitemap is generated with item name

### Steps to Reproduce the Problem

` function Get-LongURL ($currentItem) {
   
    $urlOptions = [Sitecore.Links.UrlOptions]::DefaultOptions
    $urlOptions.Site = [Sitecore.Sites.SiteContext]::GetSite($currentSite)
	$urlOptions.UseDisplayName = $true
    $pageItemURL = [Sitecore.Links.LinkManager]::GetItemUrl($currentItem, $urlOptions)
    $pageItemURL.Replace('://','https://')
}

 $items = Get-ChildItem -Path "/sitecore/content/Italy/Home" -Language "it-IT" -Recurse 
 
  $items |
            Show-ListView @props -Property @{Label="Page Name"; Expression={$_.DisplayName} },
                @{Label="URL"; Expression={Get-LongURL($_)} }`
 
here some console output in debugging

PS master:\content\Home>Get-LongURL($currentItem)
https://prodcm-it.msccruises.com/editorial-search

PS master:\content\Home>$currentItem.DisplayName
Ricerca 

PS master:\content\Home>$currentItem.Language
 
CultureInfo : it-IT
Origin      : Sitecore.Globalization.LanguageOrigin
Name        : it-IT
Cacheable   : True
Immutable   : True

PS master:\content\Home> $urlOptions 
AddAspxExtension       : False
AlwaysIncludeServerUrl : False
EncodeNames            : True
SiteResolving          : True
Language               : it-IT
LanguageEmbedding      : Never
LanguageLocation       : FilePath
LowercaseUrls          : True
ShortenUrls            : True
Site                   : Sitecore.Sites.SiteContext
UseDisplayName         : False

**Comment by michaellwest** [comment]
I factored your script a little for my testing. I do however experience the issue your reported, although not a bug with SPE since you are calling the Sitecore API.

If I figure out the right combination to get what you want I'll let you know.

```powershell
function Get-LongURL {
    param(
        [item]$CurrentItem,
        $UrlOptions
    )
    $pageItemURL = [Sitecore.Links.LinkManager]::GetItemUrl($CurrentItem, $UrlOptions)
    $pageItemURL.Replace('://','https://')
}

$currentSite = "website"
$urlOptions = [Sitecore.Links.UrlOptions]::DefaultOptions
$urlOptions.Site = [Sitecore.Sites.SiteContext]::GetSite($currentSite)
$urlOptions.UseDisplayName = $true
$items = Get-ChildItem -Path "/sitecore/content/Home" -Recurse

$items | Show-ListView -Property @{Label="Page Name"; Expression={$_.DisplayName} }, @{Label="URL"; Expression={(Get-LongURL -CurrentItem $_ -UrlOptions $UrlOptions)}}
```

**Comment by michaellwest** [comment]
After further investigation, on my installation of Sitecore I do see the display name used. Did you override the Link Manager to have a different behavior? Perhaps you can provide screenshots of the results and also of the item to show what the name/display name are set to.

**Comment by michaellwest** [comment]
Please reopen the issue if you are able to provide more details in a vanilla instance of Sitecore using SPE 5.1+.
