### ISSUE TITLE
Publish-Item crashes

### ISSUE THREAD

**Issue by webbson** [SitecorePowerShell/Console#1129]
### Expected Behavior

Trying to run a simple script 
```
$theme = Get-Item -Path "master:/sitecore/media library/themes/PublicWebsites/Corporate Site/CorporateTheme"
$theme | Publish-Item -Recurse
```

This should publish the theme and all descendants.

### Actual Behavior

A crash with the following message:

```
Publish-Item : Could not load type 'Sitecore.Jobs.Job' from assembly 'Sitecore.Kernel, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null'.
At line:2 char:10
+ $theme | Publish-Item -Recurse
+          ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-Item], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Cognifide.PowerShell.Commandlets.Data.PublishItemCommand
```
### Steps to Reproduce the Problem

Clean install with: 

Sitecore 9.2
Sitecore PowerShell Extensions 5.1.0.19766
SXA 1.9.0 rev. 190528.

Just try to publish an item from PowerShell ISE with Publish-Item command.

**Comment by AlexKasaku** [comment]
@michaellwest - Was looking to see if this is related to the known compatability issue with 9.2, but I think this different as looks to be the latest 5.1 release? The publishing API calls made by PublishItemCommand may need to be abstracted into the versioned assemblies?

**Comment by AlexKasaku** [comment]
Can confirm I can reproduce this with a clean install of 9.2 and the latest 5.1 release.

**Comment by AlexKasaku** [comment]
Thanks for reporting this @webbson, have confirmed this is a bug and fixed for the next release.
