### ISSUE TITLE
Disable on content delivery

### ISSUE THREAD

**Issue by VGBenjamin** [SitecorePowerShell/Console#1130]
Hello,

Could you tell me what is the best way to disable module on the CD nodes and only stay active on CM. It is of course to avoid security issue.

Regards,
Benjamin

### Expected Behavior

Be able to disable the module on the content delivery nodes.

**Comment by michaellwest** [comment]
Hi @VGBenjamin , this is actually a pretty common setup. Some considerations to make:

* [ ] Only install the package on the CM instance
* [ ] Don't deploy any SPE files to the CD instance
* [ ] Follow the [SPE guide](https://doc.sitecorepowershell.com/security) to help keep things secure in the CM instance

**Comment by VGBenjamin** [comment]
Hello,

Due to the way the customer deploy the files it will be hard to not deploy some files on CD but I can change the config so I will try to disable eveything I can as described in the SFE guide then.

Thank you!
Benjamin
