### ISSUE TITLE
Remove-RoleMember not working for role-members

### ISSUE THREAD

**Issue by thomastherkildsen** [SitecorePowerShell/Console#1144]
Remove-RoleMember is not working for removing a role from a role.

I have verified that it works fine for removing a user from a role.
I have verified that Add-RoleMember works fine for adding a role to a role.
I have verified that it is not a caching issue.

My current work-a-around is to access the c# method RolesInRolesManager.RemoveRoleFromRole(role, targetRole); directly.

**Comment by AlexKasaku** [comment]
Confirmed and fixed `Remove-RoleMember` command. The code was incorrectly only proceeding with the role removal if the role _wasn't_ already a member of the role, rather than if it was.
