### ISSUE TITLE
Cannot add Item Language on Composite Components

### ISSUE THREAD

**Issue by sis-86** [SitecorePowerShell/Console#1145]
### Expected Behavior

It should be possible to Add Languages on Accordion Items

### Actual Behavior

Script Fails on "Accordion Item 1"

Add-ItemLanguage : Cannot complete operation.
At line:96 char:27
+ ... ch-Object { Add-ItemLanguage $_ -Language $originLanguage -TargetLang ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-ItemVersion], AggregateException
    + FullyQualifiedErrorId : InvalidOperation,Cognifide.PowerShell.Commandlets.Data.AddItemVersionCommand 

Sitecore Log:
ManagedPoolThread #13 17:07:26 ERROR One or more exceptions occurred while processing the subscribers to the 'item:saving' event.
Exception[1]: System.NullReferenceException 
Message[1]: Object reference not set to an instance of an object. 
Source[1]: Sitecore.XA.Feature.Composites 
   at Sitecore.XA.Feature.Composites.EventHandlers.SaveCompositeItems.GetNewLayoutFromRequest(String newlayout)
   at Sitecore.XA.Feature.Composites.EventHandlers.SaveCompositeItems.PropagateLayoutChanges(Item item)
   at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result) 

### Steps to Reproduce the Problem

Version 5.0 and 5.1

Create a new Page.
Place an Accordion Item on the Page.
Add a Rich Text or Promo into Accordion Content Area
Add Item Language (Include Subitem, Datasources, Overwrite latest)

![image](https://user-images.githubusercontent.com/56296668/66381694-18c0fb00-e9ba-11e9-93dc-506ebe3e597e.png)

**Comment by michaellwest** [comment]
Have you spoken with Sitecore support? This may be an issue with the script they deploy and not necessarily the SPE module.

**Comment by sis-86** [comment]
Hello michaellwest sorry I thought the script was a part of it, I will ask.

**Comment by sis-86** [comment]
So this was indeed a sitecore issue, if someone also has problems with that ask for hotfix 365329
