### ISSUE TITLE
ISE output disappears after a breakpoint is hit in debug mode or when long running operation runs

### ISSUE THREAD

**Issue by salvatore1930** [SitecorePowerShell/Console#1151]
### Actual Behavior

In SPE 6.0, Sitecore 8.2 and PowerShell 5.1 the messages printed to the ISE output, using the _Write-Host_ cmdlet, disappear from it when the code execution is paused (e.g. by hitting a breakpoint in debug mode or when there is a long-running operation ongoing). Once the script finishes messages printed before the "pause" are missing in the whole script output.

### Expected Behavior

Messages should persist in the ISE output until the script next run. This worked fine in the SPE 4.7.

### Steps to Reproduce the Problem

_Use Case 1:_
1. Create a simple script with two Write-Host lines:
2. Add breakpoint to the second line:
![image](https://user-images.githubusercontent.com/36243266/69069251-74a18980-0a26-11ea-8e5e-f2519145b7df.png)
3. Run the script in Debug mode.
4. The first message will disappear shortly after the breakpoint is hitted.
![image](https://user-images.githubusercontent.com/36243266/69069831-71f36400-0a27-11ea-8b1b-b46a858261e4.png)
5. The second message is displayed when the script is ran to the end.
![image](https://user-images.githubusercontent.com/36243266/69069858-7f105300-0a27-11ea-93a8-df88c91951b4.png)

_Use Case 2:_
Run a script with time-consuming command. At the moment the execution hits the long-running command the content in the output disappears.
```
Write-Host "Message 1";
$x = Get-ChildItem -Path master:\sitecore\content -Recurse;# <--- this command should take a while
Write-Host "Message 2";
```
PS: Before the SPE 6.0 installation all the 4.7 version files and System/Modules/PowerShell items were deleted from DB.

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 - [x] Asked questions on the Sitecore Slack Chat channel.
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
@salvatore1930 thank you for reporting the issue. I've seen this happen a number of times when I run scripts but never got around to identifying exactly the root cause. We'll have a look.

**Comment by michaellwest** [comment]
Issue may have been introduced with this commit 36d5a0c44f73cdef45e0654de91aad8252f0a43e.

**Comment by michaellwest** [comment]
I think I have this fixed. There is a line in which the output is cleared constantly. This requires a new build.
