### ISSUE TITLE
Write all output to log

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1155]
Provide a way to output every single line of data that would traditionally be written to the windows of the Console and ISE. 

Should include the standard data output, Write-Information, Write-Verbose, Write-Warning, and Write-Debug, and Write-Error.

**Comment by michaellwest** [comment]
![SNAG-0600](https://user-images.githubusercontent.com/933163/70658558-d9b25e80-1c23-11ea-8fb0-84b5e5f77f85.png)

![SNAG-0601](https://user-images.githubusercontent.com/933163/70658563-dcad4f00-1c23-11ea-9878-0eab5fc3e105.png)

**Comment by michaellwest** [comment]
```powershell
"abc"
1..3 | % { Write-Error "Ignore these errors"; STart-Sleep -Seconds 1 }
1..3 | % { Write-Output "Nothing to see here"; STart-Sleep -Seconds 1 }
1..3 | % { Write-Warning "You should be worried" -WarningAction Continue; STart-Sleep -Seconds 1 }
1..3 | % { Write-Verbose "Boring you to tears" -Verbose ; STart-Sleep -Seconds 1 }
1..3 | % { Write-Information "Typically a waste of space" -InformationAction Continue; STart-Sleep -Seconds 1 }
```

**Comment by AlexKasaku** [comment]
This is nice! Do you think it should be disabled by default though and require to optionally be turned on?

Does Write-Host skip this or does that map to something like Write-Output?

**Comment by michaellwest** [comment]
I do think it should be disabled by default and currently that is the case. 

All of the Write commands in the host are set up to log the output.

**Comment by michaellwest** [comment]
Fixed the issue with the default config value. It should be `false`.

Some other notes:
* "abc" executes using the `WriteLine` method in the provider
* `Write-Host` executes the `Write` method in the provider
* `Write-Output` executes the `WriteLine` method in the provider
