### ISSUE TITLE
How do you properly use delegated administration for users?

### ISSUE THREAD

**Issue by PremkumarDurai** [SitecorePowerShell/Console#1158]
### Expected Behavior
sitecore powershell script:
we have a requirement to read some of the sitecore items which current user is not having read permission ,
to do that we are using elevated privilege concept with admin  user id but still we are unable to read the items

we are using sitecore 8.1 update2.
 
### Actual Behavior

 its not returning the items which user is not having read permission though we have used elevated privilege concept

### Steps to Reproduce the Problem

```powershell
$elevatedUser= Get-User -Identity "sitecore\ElevatedUser"

New-UsingBlock (New-Object Sitecore.Security.Accounts.UserSwitcher $elevatedUser) {
    # Run commands that required the elevated access.
}
 #Display validation message only for WEB
$elevatedUser= Get-User -Identity "sitecore\ElevatedUser"

New-UsingBlock (New-Object Sitecore.Security.Accounts.UserSwitcher $elevatedUser) {
	if($($publishingTargetDatabase[$targetDatabaseFieldId]) -eq 'web' -and $DbName -eq 'web')
	{
		#Write-Host "Webonly"
        $linkedItem = Get-Item -Path master:\ -ID $item.ID -Language $LangToPublish	
        $customItem = [pscustomobject]@{
			"ID"=$linkedItem.ID
			"ItemPath"=$linkedItem.ItemPath
			"Language"=$LangToPublish
			"DisplayName"= $linkedItem.DisplayName
            "Database"= $($publishingTargetDatabase[$targetDatabaseFieldId])
			"Updated"=$linkedItem.__Updated
			"Updated by"=$linkedItem."__Updated by"
			"Created"=$linkedItem.__Created
			"Created by"=$linkedItem."__Created by"		
		}
	    Show-Alert "Invalid DataSource $customItem" 
	}
}
```

Provide  admin access to sitecore\ElevatedUser and try to get the item which current user is not having read permission 

SPE 5.0 and Sitecore 8.1 update 2
 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 yes
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 No
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
From your example, I do not see how you know which items have "deny read" for the users. Perhaps your query to do that is still incorrect.

**Comment by michaellwest** [comment]
Please reopen if you find that this is still an issue.
