### ISSUE TITLE
Read-Variable error in spe.Commands.Interactive.ReadVariableCommand

### ISSUE THREAD

**Issue by KurtBildeSDU** [SitecorePowerShell/Console#1159]
The build in Read-Variable can not be run more than one time in a session.

This section, part of a script, is streight forward:

$result = Read-Variable -Parameters `
    @{ Name = "originLanguage"; Value=$currentLanguage; Title=SetText orgLangStr; Options=$langOptions; },
    @{ Name = "destinationLanguages"; Title=SetText DestLangStr; Options=$langOptions; Editor="checklist"; },
    @{ Name = "includeSubitems"; Value=$false; Title=SetText InclSubItemsStr; Columns = 4; },
    @{ Name = "includeDatasources"; Value=$false; Title=SetText InclDataSourceStr; Columns = 4 },
    @{ Name = "includeSnippets"; Value=$false; Title=SetText InclSnippetDSStr; Columns = 4 },
    @{ Name = "ifExists"; Value="Skip"; Title=SetText IfExistsTitleStr; Options=$ifExists; Tooltip=SetText ToolTipStr; } `
    -Description $DescriptionStr `
    -Title $TitleStr -Width 650 -Height 660 -OkButtonName $OkButtonNameStr -CancelButtonName $CancelButtonNameStr -ShowHints

This runs the first time, but if you re-run it it throws an error:

Read-Variable : An error was encountered while executing the command 'Spe.Commands.Interactive.ReadVariableCommand'
At line:98 char:11
+ $result = Read-Variable -Parameters `
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Read-Variable], ArgumentException
    + FullyQualifiedErrorId : InvalidOperation,Spe.Commands.Interactive.ReadVariableCommand

And it seems like there is a kind of session caching as I have to wait or kill SPE to re-run it and it works again.

**Comment by AlexKasaku** [comment]
@KurtBildeSDU - Thanks for raising this. This looks to be a bug related to using a null default value in a parameter, which works the first time but fails after that. Is `$currentLanguage` ever null or not defined in your script? If it has a value I think this error shouldn't occur, from what I am currently seeing.

**Comment by AlexKasaku** [comment]
Pushed a fix for this - this was occurring if there was an existing variable for the parameter in the session (which would occur on multiple script runs) **and** the default value passed in was _null_.

The fix involves replacing the null check of the parameter with a `ContainsKey` check instead.

**Comment by KurtBildeSDU** [comment]
Perfect! And thanks for prompt action!
