### ISSUE TITLE
[Feature request]Show-ListView Report | Select/Un-select all option for listed items

### ISSUE THREAD

**Issue by vaishali4** [SitecorePowerShell/Console#1161]
### Problem Statement

Currently, in SPE ListView Report user has to perform multiple Ctrl+Click event for selecting multiple items (_consider huge list_) for performing any action.

### Solution 

It would be great if report window can be customized with an option to "select all" (like Ctrl+all) for listed items(reference screenshot below) and from there user can un-select few items (if required).

**This option will help in quickly reviewing and excluding items from a bigger list while performing an Edit Action.**

1. Select-all option:

![image](https://user-images.githubusercontent.com/13902575/71871613-b1911f00-313f-11ea-9737-8ef72b0073e7.png)

2. Un-select option:

![image](https://user-images.githubusercontent.com/13902575/71871694-05036d00-3140-11ea-9132-19a3a0f5f7a2.png)

- Verified on SPE 4.7 Sitecore 8.2

 - [Yes] Asked questions on the Sitecore Slack Chat channel. https://sitecorechat.slack.com/archives/C09THADMX/p1578373069004400

**Comment by AdamNaj** [comment]
This should have already worked when you clicked on the "Icon" column title.
But I made it more apparent and added the number of selected items to the status bar:
https://www.youtube.com/watch?v=YAglc7R5GGY
