### ISSUE TITLE
Add-ItemVersion doesnt work if item has existing versions

### ISSUE THREAD

**Issue by elivnjak** [SitecorePowerShell/Console#1162]
I understand the Add-ItemVersion creates a new version based on the existing version but is there a way I can create a new version when there is no existing version?

Sitecore has a lot of items which for some reason dont have a version at all. I'm trying to write a SPE script that can create a new version but for some reason I cant seem to add a version if there are 0 versions for that item. If I manually add a version through Sitecore content editor then run the script against the item, new versions are created.

My current script is:
`Add-ItemVersion -Path "master:\sitecore\templates\System\Email" -Language "en" -IfExist Append`

Sitecore: 9.2
SPE: 5.0

**Comment by AlexKasaku** [comment]
Confirmed that the behaviour described is occurring - the `Add-ItemVersion` command expects there to be an existing version to base the new version from.

In existing versions you can fallback on to the Sitecore API to do this rather easily in the context language:

```
$item = Get-Item "master:///sitecore/content/Home/Sample Item"
$item.Versions.AddVersion()
```

We can look at amending this to provide a means of adding a version to an item without existing versions, though the above is fortunately short.

**Comment by elivnjak** [comment]
That does the trick. Thanks!

**Comment by elivnjak** [comment]
Just for further information I wrote the following script to search for all items with missing versions and create a new version.

`$folder = "master:///sitecore/templates"
  
$items = Get-ChildItem -Path $folder -recurse | 
Where-Object { $_.Versions.GetVersions($true).Count -eq 0 } | 
ForEach-Object { $_.Versions.AddVersion() }
`

**Comment by AlexKasaku** [comment]
Added support for creating item versions without a source version via a new `-IfNoSourceVersion` paramter. Possible values:

`Skip`: No version is added _(Default behaviour)_
`Add`: Create a version in the target language

The default value of `Skip` matches existing behaviour, to avoid any breaking change in current behaviour.

**Comment by michaellwest** [comment]
Found an issue with Fallback enabled. Had to do this to get it working.

```powershell
$language = [Sitecore.Data.Managers.LanguageManager]::GetLanguage("en-150")
$items = Get-ChildItem "master:\content\sometreeofitems" -Language "en" -Recurse
foreach($sourceItem in $items) {
    $targetItem = $sourceItem.Versions.GetLatestVersion($language)
    if($targetItem.Versions.GetVersions($true).Count -eq 1 -and $targetItem.IsFallback) {
        $targetItem = $targetItem.Versions.AddVersion()
    }
    Add-ItemLanguage -Item $sourceItem -Language "en" -TargetLanguage "en-150" -IfExist Overwrite
} 
```

**Comment by michaellwest** [comment]
@AlexKasaku Does it make sense to add the version even if the targetItem is a fallback item by default?

I will commit the change that adds a version if the following conditions apply:

* Target version count = 0
* ActionIfExists = Append
* Target is fallback **(this is the new condition)**

**Comment by michaellwest** [comment]
Tested the language fallback by assigning "en" to the new languaged "en-GB". Enabled the language fallback on the standard values of my custom template. Then dropped this patch in:

```xml
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
    <sitecore>
        <sites>
            <site name="shell">
                <patch:attribute name="enableItemLanguageFallback">true</patch:attribute>
                <patch:attribute name="enableFieldLanguageFallback">true</patch:attribute>
            </site>
            <site name="website">
                <patch:attribute name="enableItemLanguageFallback">true</patch:attribute>
                <patch:attribute name="enableFieldLanguageFallback">true</patch:attribute>
            </site>
        </sites>
    </sitecore>
</configuration>
```
