### ISSUE TITLE
Feature Request: -PassThru for Add-Rendering

### ISSUE THREAD

**Issue by bic742** [SitecorePowerShell/Console#1163]
### Expected Behavior

`Add-Rendering` returns the `RenderingDefinition` object associated with the newly added rendering. This is helpful for cases where dynamic placeholders are in use, and the unique id of the Instance is leveraged to determine a generated placeholder value.

### Actual Behavior

`Add-Rendering` does not currently return a value. This makes it difficult to dynamically build pages via SPE. The specific use case I am processing is building pages during content migration.

### Current Work-around

If you leverage the `-Index` parameter for `Add-Rendering` and `Get-Rendering`, then you can get to the correct instance to grab the unique id:

```
Add-Rendering -Item $item -PlaceHolder $placeholderPath -Instance $accordionSectionRendering -DataSource $datasource.ID -FinalLayout -Index $renderingIndex
$accordionSectionInstance = Get-Rendering -Item $item -Placeholder $placeholderPath -FinalLayout -Index $renderingIndex
$renderingIndex++
```

### Proposed Feature

Add support for `-PassThru` switch on the `Add-Rendering` method. Switch will allow user to capture the `RenderingDefinition` instance of the newly added rendering in a variable and use it to calculate any dynamic placeholder that was generated by that rendering:

```
$rendering = Add-Rendering -Item $item -PlaceHolder $placeholderPath -Instance accordionSectionRendering -DataSource $datasource.ID -FinalLayout -PassThru
```

_Please include the version number of SPE and Sitecore._

* Sitecore 9.2
* SPE 6.0

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [x] Asked questions on the Sitecore Slack Chat channel.
 
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by AlexKasaku** [comment]
Agree that this is a good idea for a parameter on `Add-Rendering`, so I've added it.
