### ISSUE TITLE
Data Importer Importer Not populating template

### ISSUE THREAD

**Issue by kingjtiv** [SitecorePowerShell/Console#1165]
### Expected Behavior
When importing a csv with the fields from the template and going through proper mapping through the portal the information should populated in the item.

### Actual Behavior

When importing a csv with the fields from the template and going through proper mapping through the portal only the name field is populated no other fields are mapped. 

### Steps to Reproduce the Problem

Import a simple CSV for the Sample item from a clean install and map title and text content.

 - [X ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ X] Asked questions on the Sitecore Slack Chat channel.
 
 - [X ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Can you provide an example of the template structure and csv structure?

**Comment by kingjtiv** [comment]
`Name,Title,Text
"Sample Item 1","Everyday is a great day","<p>This is the day that the lord has made. I will rejoice and be glad in it.</p>"
"Sample Item 2","This is the second day.","<p>It is good.</p>"`

**Comment by AlexKasaku** [comment]
@kingjtiv - Can you provide the template structure? So show us the template you are using for the import and the fields you have created in it.

**Comment by kingjtiv** [comment]
@AlexKasaku i am using the sample item template that is default to sitecore. I was testing it on a clean install.

**Comment by AlexKasaku** [comment]
@kingjtiv - Thanks, I've confirmed the issue. There's a bug in the script where fields are not being populated on the first import, just on update only.

**Comment by AlexKasaku** [comment]
@kingjtiv - This will be included in the next release, but as it's just a script change you could grab the updated script and patch the relevant script item in your version of SPE to fix the issue:

Serialized file: https://github.com/SitecorePowerShell/Console/blob/b795ce42e62d752c8e85c675997b4d7a79c99bab/unicorn/SPE/Scripts/SPE/SPE/Tools/Data%20Management/Toolbox/Data%20Management/Data%20Importer.yml

Item path for script: `/sitecore/system/Modules/PowerShell/Script Library/SPE/Tools/Data Management/Toolbox/Data Management/Data Importer`
