### ISSUE TITLE
SXA Copy-Site is not working from remote session

### ISSUE THREAD

**Issue by HarikishoreReddy** [SitecorePowerShell/Console#1167]
### Expected Behavior

SXA site node should be cloned using Copy-Site function from the remote session.

### Actual Behavior

I have created script to clone SXA site node using Copy-Site function (/sitecore/system/Modules/PowerShell/Script Library/SXA/SXA - Multisite/Functions/Site cloning/Copy-Site). Site is cloned , but all references are failed to reset and they remain pointed to source site.  I have attached error log that I have received during execution of Copy-Site function from remote session. 

### Steps to Reproduce the Problem
The following is the script to reproduce the issue. 

```powershell
$session = New-ScriptSession -Username <User Id> -Password <Password> -ConnectionUri <Sitecore Url>
    $jobCloneSite = Invoke-RemoteScript -Session $session -ScriptBlock {
    try 
    {
        Import-Function Validate-PowerShell			
        Import-Function Copy-Site  
        $siteId = "TestSite"
        Set-Location -Path "master:"           
        $sourceSite = Get-Item -Path "<Source site path>"
        $targetSiteRootPath = "<Target site path>"           
        $targetSiteRootItem =  Get-Item -Path $targetSiteRootPath          
        $mapping = New-Object -TypeName "System.Collections.Hashtable"
        $mapping.Add("name", $siteId)      
        $destinationSite = Copy-Site $sourceSite $targetSiteRootItem $siteId $mapping            
                } 
    catch
    { $_ } 
} -AsJob -Verbose
Wait-RemoteScriptSession -Session $session -Id $jobCloneSite -Delay 5 -Verbose          
Stop-ScriptSession -Session $session
```

[Copy-site error log.txt](https://github.com/SitecorePowerShell/Console/files/4135443/Copy-site.error.log.txt)
                     
    
        
Sitecore version 8.2 Update 7
SPE 5.1
SXA 1.7

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
@HarikishoreReddy Since this is a script that comes with the SXA module and not with SPE, have you reached out to the #sxa channel on https://sitecore.chat?

**Comment by HarikishoreReddy** [comment]
@michaellwest - Thanks for replying. I have not reached out to Sitecore because the same script is working fine when it is being executed directly in sitecore instance. It is failing only when we try to execute from remote. Please confirm If you want me to reach out to Sitecore #sxa channel.
