### ISSUE TITLE
Console output is constantly getting cleared

### ISSUE THREAD

**Issue by borring** [SitecorePowerShell/Console#1168]
### Expected Behavior
A long running job finishes with console output intact.

### Actual Behavior
Any job that doesn't run instantaneously will have its output cleared.

### Steps to Reproduce the Problem
```
Write-Host "some output"
sleep 3
```

I think the issue may have been caused by this commit:
https://github.com/SitecorePowerShell/Console/commit/af94b8730711a734a1cddeb4eb940874408ce5a2

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
This is related to #1151 .

**Comment by borring** [comment]
@michaellwest Woops. I was looking at that issue as well, but didn't think it was a duplicate since the fix for that issue added the chunk of JS code that is clearing the console

https://github.com/SitecorePowerShell/Console/commit/36d5a0c44f73cdef45e0654de91aad8252f0a43e#diff-3459ef898b7bf880920f2acd089c0404R346

After checking out the 6.0 tag, it looks like that function `spe.clearOutput` was already present. and 36
