### ISSUE TITLE
GetItemReference fails with broken links

### ISSUE THREAD

**Issue by sgisbert** [SitecorePowerShell/Console#1169]
### Expected Behavior

GetReferenceItem should return all the referenced items in the links database, except those broken links that do not exists in the DB anymore.

### Actual Behavior

GetReferenceItem fails when at least one of the referenced items in the link database is not present on the db anymore (broken link), with the following exception:

Get-ItemReference : Object reference not set to an instance of an object.
At line:11 char:5
Get-ItemReference -Item $item

CategoryInfo          : NotSpecified: (:) [Get-ItemReference], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,Cognifide.PowerShell.Commandlets.Data.GetItemReferenceCommand

In this scope, $item has an actual value, and it is a valid item.
Checking the $item links in the navigation tab, we can see that this item has some broken links, not existing anymore in the DB.

A quick look at the command code:

linkDb.GetReferences(linkedItem)
.Select(link => link.GetTargetItem())
.Distinct(ItemEqualityComparer.Instance)
.ToList()
.ForEach(WriteItem);

it is likely that "link.GetTargetItem()" returns null when the target item does not exists anymore

Hopefully, rebuilding links database would fix the issue, but this is not something we can do on a regular basis due to the huge content the client has in the project.

### Steps to Reproduce the Problem

Need to get some broken links, and then execute the GetItemReference command on that item.

_Please include the version number of SPE and Sitecore._

Sitecore 8.2 u2 - PSE 5.0

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
I believe your issue is resolved by upgrading to SPE 5.1 or newer. #1083 should include your scenario.

**Comment by sgisbert** [comment]
Thanks. Do you foresee any risk in upgrading from 5.0 to 6.0? Any breaking change expected?

**Comment by michaellwest** [comment]
@sgisbert The primary change with 6.0 is that all the files with 'Cognifide' in the name have be changed to 'Spe'. You shouldn't have too much trouble getting to 6.0.
