### ISSUE TITLE
About Sitecore PowerShell Extensions Fails

### ISSUE THREAD

**Issue by kennethmauriks** [SitecorePowerShell/Console#1170]
### Expected Behavior

Click on the `About` button in the PowerShell ISE, details about this module are displayed in the window.

### Actual Behavior

The window opens with the error: `Requests to the server have been blocked by an extension.`

### Steps to Reproduce the Problem

Upon inspection of the DevTools console, the following error appears (also tested with a clean install of sitecore 9.3 & latest version of SPE):
`Refused to frame 'https://spe.najmanowicz.com/' because it violates the following Content Security Policy directive: "default-src 'self' https://apps.sitecore.net". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.`

Sitecore PowerShell Extensions 6.0
Sitecore 9.3
Windows PowerShell 5.1

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Thanks for reporting the issue @kennethmauriks . Thought I had the fix committed for the last release.
