### ISSUE TITLE
Memory leak when executing Powershell scripts in Sitecore Jobs 

### ISSUE THREAD

**Issue by MariiaHubenko** [SitecorePowerShell/Console#1171]
### Expected Behavior

Process memory usage doesn't grow after completing multiple PowerShell scripts in PowerShell ISE.

### Actual Behavior

Process memory usage grows to a certain point and doesn't get released after completing multiple PowerShell scripts in PowerShell ISE.

Running PowerShell scripts in PowerShell ISE populates a property `System.Management.Automation.Runspaces.Runspace.DefaultRunspace` with the `System.Management.Automation.Runspaces.LocalRunspace` object. This property internally assigns a `LocalRunspace` object to a _threadstatic_ field `ThreadSpecificDefaultRunspace`. This field has a lifetime of a thread. If the PowerShell script is executed inside a Sitecore Job it will run on the Sitecore Managed Thread. Since Sitecore Managed Threads are pooled, the `LocalRunspace` objects in _threadstatic_ fields remain in memory for the lifetime of a pool. Even disposed `LocalRunspace` objects continue living in the process memory. The problematic job has a name "ISE_Editing_Session - sitecore\admin" and it is started in `Cognifide.PowerShell.Client.Controls.SpeJobMonitor.Start(...)` method. The `LocalRunspace` objects are rather heavy (+500 MB). Also the "ISE_Editing_Session" job can be executed on any thread from Sitecore Managed Threadpool (which holds 20 threads by default). 

**Note:** the issue can be resolved by explicitly setting `System.Management.Automation.Runspaces.Runspace.DefaultRunspace` to `NULL` as soon as  the Script Session is disposed.

### Steps to Reproduce the Problem

- Install Sitecore Experience Platform 9.2 Initial Release, Sitecore PowerShell Extensions 5.0.
- Go to Sitecore Desktop and open "PowerShel ISE" application.
- Check Sitecore process memory usage.
- Execute the default script several times.
- Check process memory usage after last script completed.
- Check the number of disposed `System.Management.Automation.Runspaces.LocalRunspace` instances.
- Trigger Full Garbage Collection.
- Check if disposed objects were released from memory.

Sitecore Experience Platform 9.2 Initial Release, Sitecore PowerShell Extensions 5.0

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Hi @MariiaHubenko thank you for reporting the issue. I made a change and found no negative consequence in doing so. Please let me know if that was the kind of change you intended.

**Comment by MariiaHubenko** [comment]
Hi @michaellwest , yes this is indeed the change I've meant. After applying this change the `DefaultRunspace` object was released for all Sitecore Managed Threads which executed "ISE_Editing_Session" job with "Dispose session after script execution" mode. 

However if the PowerShell script is executed in "Keep ISE session between script executions" mode, the Managed Sitecore Thread still holds the `DefaultRunspace `object of the `ScriptSession`. It looks like same `ScriptSession` is reused in many Sitecore jobs and it doesn't get disposed when a job completes (since `AutoDispose` is disabled on `SessionScript`'s host). This `ScriptSession` will get disposed eventually, but not on a thread where "ISE_Editing_Session" job executed. So a `DefaultRunspace` of a different thread is set to `NULL` when such shared `ScriptSession` is disposed. It looks like the [DefaultRunspce shouldn't be shared between threads](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.runspace.defaultrunspace?view=pscore-6.2.0#remarks).

**Comment by MariiaHubenko** [comment]
Hi @michaellwest , do you think it will be OK to set `DefaultRunsace` to `NULL` once `ScriptRunner` completes a script? In this case every Sitecore Job will get its own `DefaultRunsace` and will release it on the correct thread.

**Comment by michaellwest** [comment]
@MariiaHubenko I made another change and it appears I am able to set the DefaultRunspace back to null after the script completes.

**Comment by MariiaHubenko** [comment]
@michaellwest With this change I can no longer replicate the memory leak.

**Comment by michaellwest** [comment]
This is wonderful news. Thank you very much for your support.
