### ISSUE TITLE
Remove-ItemVersion doesn't place removed version into the RecycleBin nor into the Archive

### ISSUE THREAD

**Issue by SoulOfUniverse** [SitecorePowerShell/Console#1177]
### Expected Behavior

When removing item version for instance:
Remove-ItemVersion -ID $item.ID -Language "en-us" 
If I call Remove-ItemVersion -ID $item.ID -Language "en-au" -Archive
System will throw:
Remove-ItemVersion : A parameter cannot be found that matches parameter name 'Archive'.
At line:1 char:49
+ Remove-ItemVersion -ID $item.ID -Language en-au -Archive
+                                                 ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-ItemVersion], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Cognifide.PowerShell.Commandlets.Data.RemoveItemVersionCommand
### Actual Behavior

It removes the versions, but you can't restore them anymore because the script doesn't place version into the recycle bin.

### Steps to Reproduce the Problem

Sitecore 9.0 Update 1
SPE 5.0

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Hi @SoulOfUniverse you just happen to be on the previous version. Upgrade to 5.1 to have access to that behavior. See #1085 for more details. If you can upgrade to 6.0 that would be even better.

**Comment by SoulOfUniverse** [comment]
Hi Michael,

Thank you I will try 6.0 and will let you know, I tried to find this in the releases but couldn't find the information regarding this -Archive feature.
