### ISSUE TITLE
Shifted from version 5.1 to 6.0 - problems regarding 404 on remoting

### ISSUE THREAD

**Issue by bohessner** [SitecorePowerShell/Console#1179]
### Expected Behavior

Remoting will contact sitecore and return a 200

### Actual Behavior

404 not found

### Steps to Reproduce the Problem

SPE version 6.0. Sitecore.NET 8.1 (rev. 151207).

`Import-Module -name SPE -Force

$session = New-ScriptSession -Username $user -Password $password -ConnectionUri $SitecoreInstanceUri 

Invoke-RemoteScript -Session $session -ScriptBlock { Get-User -Id RemoteSPEuser } `

"Invoke-RemoteScript" are calling this url: 
https://ai.local.alka-dk/-/script/script/?sessionId=e98a1f67-2ec6-4d67-880e-27772084a029&rawOutput=False&persistentSession=False

and return "404 not found"

I cant seem to figure out how and where the "/-/script/script/" part of the url are handled by sitecore?

**Comment by michaellwest** [comment]
This file handles the routing. https://github.com/SitecorePowerShell/Console/tree/master/src/Spe/Core/Processors/RewriteUrl.cs

Are all the Cognifide DLLs and configs deleted?

**Comment by bohessner** [comment]
Yes, all Cognifide DLLs and configs are delted.

I get this result:

Version             : 1.1
Content             : System.Net.Http.StreamContent
StatusCode          : NotFound
ReasonPhrase        : Not Found
Headers             : {[Pragma, System.String[]], [X-Frame-Options, System.String[]], [Cache-Control, System.String[]], [Set-Cookie, System.String[]]...}
RequestMessage      : Method: POST, RequestUri: 'https://ai.local.alka-dk/service/systemmeddelelser/404', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:
                      {
                        Authorization: Basic UmVtb3RlU1BFdXNlcjpycHUyMDE5
                        Content-Type: text/plain
                        Content-Encoding: gzip
                        Content-Length: 86
                      }
IsSuccessStatusCode : False

The RequestUri are the result of "ItemNotFoundUrl" override:

<setting name="ItemNotFoundUrl" value="/Service/SystemMeddelelser/404" patch:instead="setting[@name='ItemNotFoundUrl']"/>

**Comment by michaellwest** [comment]
Did you also update the SPE remoting module to 6.0?

**Comment by bohessner** [comment]
Yes I did.

**Comment by bohessner** [comment]
I am trying to figure out if SPE rewrite code are executed or something else are redirecting before it get to it. 

![image](https://user-images.githubusercontent.com/30377362/77245619-2395e200-6c20-11ea-9fb8-b5bf94679bc1.png)

Tried to remove our own code from above steps, but no change.

From my browser I can get the asmx file:

![image](https://user-images.githubusercontent.com/30377362/77245659-7c657a80-6c20-11ea-993b-bfc8a8ae0e9e.png)

When I, in browser, call RemoteScriptCall.ashx I get a 403.

**Comment by michaellwest** [comment]
Can you verify that you have patched to "enable" the services? There is an example here of a patch to apply which disables the SPE UAC feature. Please only use it for verification then create your own patch to align with what security settings are right for your installation.

https://alan-null.github.io/2017/01/spe-dev-config

**Comment by bohessner** [comment]
Hi

I have verified all settings in showconfig.aspx.

Now I tried the patch in your post, verified again - but I still got a 404.

I have removed all custom pipeline interference, still 404.

The files are there:
![image](https://user-images.githubusercontent.com/30377362/77259638-27a71b80-6c83-11ea-89a1-a5a55e8b7956.png)


I have downloaded your project to get the possibility of debugging - I want to verify that spe.Core.Processors.RewriteUrl are hit.

I am not sure how to wire up the debugging,- but I am trying...

**Comment by bohessner** [comment]
Finally found it.

In: Spe.Core.Processors.RewriteUrl.Process

Line: 52

` if (sourceArray.Length < 4)
                    {
                        return;
                    }` 

sourceArray.Length are 3 and therefore no rewrite are done.

Allowed in because of "/-/script/script" in line 48.

**Comment by michaellwest** [comment]
I think the issue you reported can be addressed by explicitly removing the empty entries and comparing against a lower array length. In the example I add the 4th element back in due to the way this code was written (been a while).

```csharp
var sourceArray = url.LocalPath.TrimStart('/').Split(new []{"/"}, StringSplitOptions.RemoveEmptyEntries);
if (sourceArray.Length < 3)
{
    return;
}
if (sourceArray.Length == 3)
{
    Array.Resize(ref sourceArray, 4);
    sourceArray[3] = "";
}
```

Would you be interested in a beta version of 6.0 to verify that it addresses your issue? I can give you just the dlls to test out.

**Comment by bohessner** [comment]
**I just inserted the code and compiled:**
![image](https://user-images.githubusercontent.com/30377362/77289900-36212180-6cdb-11ea-9aa9-9fa2f3e6e9ad.png)

**Copied the new Spe.dll to my bin and Executed:**
`Import-Module -name SPE -Force

$session = New-ScriptSession -Username $user -Password $password -ConnectionUri $SitecoreInstanceUri

Invoke-RemoteScript -Session $session -ScriptBlock { Get-User -Id RemoteSPEuser } `

**Result in log:**
10596 07:48:30 ERROR Attempt to call the 'remoting' service failed as user 'extranet\Anonymous' was not authorized.

**Comment by michaellwest** [comment]
Can you verify your SPE Remoting module version like this?

![image](https://user-images.githubusercontent.com/933163/77327909-d54d1580-6ce9-11ea-9afa-a4cfe1aab32b.png)

**Comment by bohessner** [comment]
![image](https://user-images.githubusercontent.com/30377362/77331024-7060e200-6d20-11ea-8c9a-3e36abb40f3f.png)

**Comment by bohessner** [comment]
As I stated earlier, it is an upgrade from 5.1 to 6.0 - I have no idea if some "old" items inside our Sitecore 8.1 can course any trouble. But the dll's, configs, files and SPE Remoting files are all verified to be 6.0. The core/master Items inside Sitecore are a "black-box" to me.

**Comment by michaellwest** [comment]
Really strange. In general what happens is the SPE Remoting module will create the Auth header where in previous versions the credentials were passed in the url. We've tested this with a vanilla instance on 8.2.7 and 9.3. I'm not certain what's unique about your solution that is conflicting with the default setup.

Perhaps there are other customizations in your solution that we haven't accounted for?

**Comment by bohessner** [comment]
Could you show an example of a complete url containing everything needed to contact Sitecore. Then I will compare it to what the remoting module on my machine is constructing.

I think my setup send a url like this: https://sitecoresite/-/script/script/ sessionId=337620dd-2474-4653-b551-8e3722e1cbee&rawOutput=False&persistentSession=False

Here I do not see any encrypted querystring parameter containing user/password, so it have to be in the sessionId - but who/where does sessionId get read/unpacked?

**Comment by bohessner** [comment]
Ok, I found the setup her:

$client.DefaultRequestHeaders.Authorization = New-Object System.Net.Http.Headers.AuthenticationHeaderValue("Basic", [System.Convert]::ToBase64String($authBytes))

I will try to trace it....

**Comment by michaellwest** [comment]
I managed to get my script to work with decrypting traffic through Fiddler.

```
POST https://spe.dev.local/-/script/script/?sessionId=68e0667e-03bb-417a-a3c7-5c80b4c31002&rawOutput=False&persistentSession=False HTTP/1.1
Authorization: Basic c2l0ZWNvcmVcYWRtaW46Yg==
Content-Type: text/plain
Host: spe.dev.local
Content-Length: 1070
Expect: 100-continue
Accept-Encoding: gzip, deflate


    if($PSVersionTable.PSVersion.Major -ge 5) {
        function Write-Information {
            param([string]$Message)
            $InformationPreference = "Continue"
            Microsoft.PowerShell.Utility\Write-Information -Message $Message 6>&1
        }
    }
    function Write-Debug {
        param([string]$Message)
        $DebugPreference = "Continue"
        Microsoft.PowerShell.Utility\Write-Debug -Message $Message 5>&1
    }
    function Write-Verbose {
        param([string]$Message)
        $VerbosePreference = "Continue"
        Microsoft.PowerShell.Utility\Write-Verbose -Message $Message 4>&1
    }
    function Write-Warning {
        param([string]$Message)
        $WarningPreference = "Continue"
        Microsoft.PowerShell.Utility\Write-Warning -Message $Message 3>&1
    }
    function Write-Error {
        param([string]$Message)
        $WarningPreference = "Continue"
        Microsoft.PowerShell.Utility\Write-Error -Message $Message 2>&1
    }

    Get-Location
<#68e0667e-03bb-417a-a3c7-5c80b4c31002#>
```

**Comment by bohessner** [comment]
Hi

I have tried to run your script and output but got the same output from the local compiled spe.dll:

25400 23:09:30 ERROR **Spe.Core.Processors.RewriteUrl.Process**: authHeader:  
25400 23:09:30 ERROR **Spe.sitecore_modules.PowerShell.Services.RemoteScriptCall.ProcessRequest**: username: , password: , authHeader:  
25400 23:09:30 ERROR Attempt to call the 'remoting' service failed as user 'extranet\Anonymous' was not authorized.

Our website are rather large and have around 10 developers working on it. I found out that some owin:AutomaticAppStartup are involved, and I have disabled it - but the authHeader remain blank as shown above.

It will soon be midnight at my end. I will continue tomorrow. Thx.

**Comment by bohessner** [comment]
**Changed**: Invoke-RemoteScript.ps1
```
# $client.DefaultRequestHeaders.Authorization = New-Object System.Net.Http.Headers.AuthenticationHeaderValue("Basic", [System.Convert]::ToBase64String($authBytes))

$client.DefaultRequestHeaders.Add("tester", [System.Convert]::ToBase64String($authBytes))
```

**Changed**: Spe.sitecore_modules.PowerShell.Services.RemoteScriptCall.ProcessRequest

`var authHeader = request.Headers["tester"];`

Rewrite:
```
if (string.IsNullOrEmpty(username) && string.IsNullOrEmpty(password) && !string.IsNullOrEmpty(authHeader))
            {
                    var encoding = Encoding.GetEncoding("iso-8859-1");
                    var usernamePassword = encoding.GetString(System.Convert.FromBase64String(authHeader));

                    var separatorIndex = usernamePassword.IndexOf(':');

                    username = usernamePassword.Substring(0, separatorIndex);
                    password = usernamePassword.Substring(separatorIndex + 1);

                PowerShellLog.Debug("username and password read from authHeader");

            }
```

Inserted some debug information.

**Result:**
```
27056 14:49:31 DEBUG Spe.sitecore_modules.PowerShell.Services.RemoteScriptCall.ProcessRequest: authHeader read from request.Headers['tester']: UmVtb3RlU1BFdXNlcjpycHUyMDE5 
27056 14:49:31 DEBUG username and password read from authHeader
27056 14:49:31 INFO  'GET/script' called by user: 'RemoteSPEuser'
27056 14:49:31 INFO  'https://ai.local.alka-dk/-/script/script?sessionId=8f065d71-54f2-465a-aef6-1ff9df1e32ff&rawOutput=False&persistentSession=False&script=/&sc_database&scriptDb&apiVersion=script'
27056 14:49:31 DEBUG ProcessScript called
27056 14:49:31 DEBUG cliXmlArgs': ''
27056 14:49:31 DEBUG The specified script is invalid
```

**Speculation**
Looks like Sitecore are removing: AuthenticationHeaderValue and leave it blank. Btw: we are using FormsAuthentication.

Now login are performed(with a twist and some jitterbug ), but the specified script turn out to be invalid?

**This code was executed**
```
Add-Type @"
    using System.Net;
    using System.Security.Cryptography.X509Certificates;
    public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(
            ServicePoint srvPoint, X509Certificate certificate,
            WebRequest request, int certificateProblem) {
            return true;
        }
    }
"@
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls, [Net.SecurityProtocolType]::Tls11, [Net.SecurityProtocolType]::Tls12

Import-Module -name SPE -Force

$session = New-ScriptSession -Username $user -Password $password -ConnectionUri $SitecoreInstanceUri 

Invoke-RemoteScript -Session $session -ScriptBlock { Get-User -Id boh } -Verbose
```

**Comment by michaellwest** [comment]
Does your server support gzip? I believe the current implementation sends compressed gzip.

Also, can you inspect what the entire message looks like when received by the service? Perhaps things look good coming from your local machine but once received by the server something has been altered.

**Comment by bohessner** [comment]
Hi

I am running on a local iis and it support gzip.

Have also tried to copy the site to a company server(iis) and got the same results.

I will revert to 5.1 and resume my work on the company solution.

Will get back to 6.0 when upgrading from Sitecore 8.1 -> 9.3

Thx for your support

**Comment by michaellwest** [comment]
Sorry we couldn't get it working quicker for you @bohessner . Hopefully a solution is identified before then.
