### ISSUE TITLE
Invoke-RemoteScript : A parameter cannot be found that matches parameter name 'Parent'.

### ISSUE THREAD

**Issue by bohessner** [SitecorePowerShell/Console#1182]
### Expected Behavior

Remoting use of Parent parameter will work.

### Actual Behavior

Thrown:  A parameter cannot be found that matches parameter name 'Parent'.

### Steps to Reproduce the Problem

SPE version 5.1.
Sitecore.NET 8.1 (rev. 151207)

This time the Sitecore Instance are identical :-)

In SPE ISE it succeed:

![image](https://user-images.githubusercontent.com/30377362/77962292-a92e2780-72db-11ea-8b70-180449b078ba.png)

Remote it will not:

![image](https://user-images.githubusercontent.com/30377362/77962372-c06d1500-72db-11ea-9695-3398fbae97f4.png)

**Comment by michaellwest** [comment]
Try calling Set-Location -Path "master:" at the top of your script.

**Comment by bohessner** [comment]
It worked - thank you.
