### ISSUE TITLE
Sitecore 9.3 support

### ISSUE THREAD

**Issue by khmurach** [SitecorePowerShell/Console#1183]
### Expected Behavior

Able to Install latest version on Sitecore 9.3

### Actual Behavior

Installation of version 5.2.1 failed

**Comment by khmurach** [comment]
This is probably due to renamed property Context to HttpContext in HttpRequestArgs

**Comment by cassidydotdk** [comment]
You need 6.0 for 9.3

**Comment by michaellwest** [comment]
https://doc.sitecorepowershell.com/appendix
