### ISSUE TITLE
[Feature request] Script run history

### ISSUE THREAD

**Issue by markgibbons25** [SitecorePowerShell/Console#1190]
It would be great to have some kind of history of scripts that have been run on the local machine.
I understand we can save scripts in the content tree - but maybe all executed scripts can be saved to a local file and then on the ISE we can have a place to view those scripts.

**Comment by AdamNaj** [comment]
This is very much achievable now... Consider the following script:

``` PowerShell
Set-HostProperty -HostWidth 2000

Get-ChildItem $SitecoreLogFolder -Recurse |
    ? { !$_.PSIsContainer -and $_.Name.StartsWith("SPE.") } | 
    Sort -Property LastWriteTime -Descending | 
    Select -first 1 |
    Get-Content | 
    ? {$_.Contains(" INFO  ") } | 
    ? {$_.Contains("Executing") -or $_.Contains("execution") } |
    %{ if($_.Contains("Arbitrary"))
        {
            Write-Host $_ -F Red
        } else {
            Write-Host $_
        }
    }


Show-Result -Text -Width 1500
```

The following endpoints are logged. 

![image](https://github.com/SitecorePowerShell/Console/assets/1209953/a4aef200-85d5-4d98-add3-fd4aff525a54)


If needed we can add more.

**Comment by AdamNaj** [comment]
@michaellwest - feel free to add your usual spit and polish and add this as one of our utility scripts if you consider it worthy.
