### ISSUE TITLE
Show-ListView - Data times out after a couple minutes

### ISSUE THREAD

**Issue by bic742** [SitecorePowerShell/Console#1197]
### Expected Behavior

Reports and data displayed via a `Show-ListView` command should persist and be usable until the user closes or dismisses the report.

### Actual Behavior

After not interacting with the component for a small time-frame, the report data appears to fall out of context. As a result, interacting with any buttons (export, paging, filters, actions, etc.) in the view pane throws a Null Reference Exception.

It appears that the data is stored in the cache, and the cache is timing out:

https://github.com/SitecorePowerShell/Console/blob/c569ef74232e7c15dcae3dca56eb9554a2713375/src/Spe/Client/Controls/PowerShellListView.cs#L67

### Steps to Reproduce the Problem

Sitecore 9.3.0
SPE 6.1.1

1. Make a report
1. Add an action to the report
1. Run the report
1. Wait 2 minutes
1. Try to execute action

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [x] Asked questions on the Sitecore Slack Chat channel.
 
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
![image](https://user-images.githubusercontent.com/933163/83956611-91b47300-a825-11ea-842e-84a14dc2c8b7.png)

**Comment by AlexKasaku** [comment]
@michaellwest  - Am I right in thinking this change doesn't change the underlying problem, but provides better feedback? This might explain an issue I saw recently where this happened with regularity, as it was also on a server with v. high memory usage and the cache was getting cleared up too quickly. I wonder if we can make this more durable.

**Comment by michaellwest** [comment]
@AlexKasaku Yes this was to both add better messaging and to improve it with a sliding expiration. It does not solve the issue, just less painful.
