### ISSUE TITLE
Show-ListView results do not display when executed from `Content Editor.aspx`

### ISSUE THREAD

**Issue by bic742** [SitecorePowerShell/Console#1200]
### Expected Behavior

Show-ListView should show results regardless of its execution location.

### Actual Behavior

When executing a script that leverages `Show-ListView` from the `Content Editor.aspx` page, the script runs but no results are displayed.

### Steps to Reproduce the Problem

- Sitecore 9.3
- SPE 6.1.1

1. Navigate to the Sitecore Launch Pad
2. Select the Content Editor button from the launch pad
3. Verify URL is ${hostname}/sitecore/shell/Applications/Content%20Editor.aspx
4. Find a context menu report and execute

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [x] Asked questions on the Sitecore Slack Chat channel.
 
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
This should open as a modal.

![image](https://user-images.githubusercontent.com/933163/87347529-03649880-c519-11ea-9de2-47b8386ef239.png)

I used this script:

```powershell
Get-ChildItem -Path "master:\content\" | Show-ListView
```

You are probably using `Close-Window` which doesn't appear to work as you expect when not in the Desktop mode.

**Comment by bic742** [comment]
You're quick...

That fixes my issue, but I was using `Close-Window` to dismiss the initial Running Script dialog when the view displays. Is there a way to accomplish that, or should I just live with it as-is?

**Comment by bic742** [comment]
I found this: https://sitecore.stackexchange.com/questions/14425/how-to-determine-whether-an-editor-is-using-the-desktop-content-editor-or-launch
