### ISSUE TITLE
Out-Download does not work when Basic authentication is enabled

### ISSUE THREAD

**Issue by ilchenkob** [SitecorePowerShell/Console#1203]
### Expected Behavior

The call to [Out-Download](https://doc.sitecorepowershell.com/appendix/common/out-download) should trigger file downloading on the client side.

### Actual Behavior

The browser shows authentication dialog asking about credentials for basic authentication because request to `/-/script/handle/<some_id>` returned `401` but correct authentication header has been sent (and was ignored for some reason?).

### Steps to Reproduce the Problem

Given:
* Sitecore 9.3
* SPE 6.0
* IIS configured to use "Basic authentication" for the access to Sitecore app
* Sitecore Identity is disabled using steps described in [official Sitecore documentation](https://doc.sitecore.com/developers/92/sitecore-experience-manager/en/understanding-sitecore-authentication-behavior-changes.html#UUID-47f9f57c-ca3b-bd39-fde8-98a167d37a24_section-idm45851236122672)

```powershell
# $results variable contains some objects
Import-Function -Name ConvertTo-Xlsx
[byte[]]$outobject = $results | Select-Object | ConvertTo-Xlsx 
Out-Download -Name "Report_$((Get-Date).ToString("yyyyMMdd_HHmmss")).xlsx" -InputObject $outobject 
```

As a result of `Out-Download` execution on the `spe.DownloadReport` function from `SpeShared.js` will be called on the client side. Which causes the request to `/-/script/handle/<some_id>` to be sent. But this request will fail to pass basic authentication and `401` will be returned in the response. All attempts to fill in credentials in browser's authentication dialog fail.

The same PowerShell script works fine when basic authentication is disabled.

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Any idea what the possible solution is?

**Comment by ilchenkob** [comment]
Didn't have enough time to digg deeper from what I described. So for now I have no idea why it happens. The interesting thing is that request to `/-/script/handle/<some_id>` is sent with correct authentication header.
If I manually enter the same URL in browser's address line but without ID at the end (like `https://mydomain/-/script/handle`), then there is no issues with basic authentication, server returns me `404` because there is no such resource in my app.

**Comment by ilchenkob** [comment]
I found a workaround.
1. Added the following section to `applicationHost.config` of IIS:
```XML
<location path="Default Web Site/-/script">
    <system.webServer>
        <security>
            <authentication>
                <basicAuthentication enabled="false" />
                <anonymousAuthentication enabled="true" />
            </authentication>
        </security>
    </system.webServer>
</location>
```

But this will cause `401` because the browser will add `Authentication` header when it's not needed for the request to `/-/script/handle/<some_id>`. So then applied changes from the next point.
2. Added following lines to `\sitecore modules\PowerShell\Scripts\SpeShared.js`:
```javascript
    function downloadFile(url, ) {
      var req = new XMLHttpRequest();
      req.open("GET", url, true);
      req.responseType = "blob";
      req.onload = function (event) {
        if (req.status === 401) {
          downloadFile(url);
        } else {
          var blob = req.response;

          var fileName = "Report";
          var contentDisposition = req.getResponseHeader("Content-Disposition");
          if (contentDisposition && contentDisposition.split('; ')[1] && contentDisposition.split('; ')[1].split('=')[1]) {
            fileName = contentDisposition.split('; ')[1].split('=')[1];
          }

          var link=document.createElement('a');
          link.href=window.URL.createObjectURL(blob);
          link.download=fileName;
          link.click();
        }
      };

      req.send();
    }

    spe.DownloadReport = function (handle) {
        downloadFile("/-/script/handle/" + handle);

        // original implementation:

        // var iframe = document.createElement("iframe");
        // iframe.src = "/-/script/handle/" + handle;
        // iframe.width = "1";
        // iframe.height = "1";
        // iframe.style.position = "absolute";
        // iframe.style.display = "none";
        // document.body.appendChild(iframe);
    }
```
Code listed above works fine in Chrome and Edge, but does not work in Firefox. Because Firefox keep sending `Authentication` header even after `401` returned from the server side because authentication is not needed.

This means that basic authentication is enabled for all URLs of my Sitecore app except any URLs under `/-/scripts`.

@michaellwest , as far as I understand, the problem is in [RewriteUrl processor](https://github.com/SitecorePowerShell/Console/blob/master/src/Spe/Core/Processors/RewriteUrl.cs). There is a URL rewrite on line 70 which rewrites URL but looses Authentication header. That's why if BA is enabled the original request to `/-/script/handle/<ID>` is authenticated but after the rewrite further request is not and it causes endless authentication dialog which is looped to `401` response.

**Comment by ilchenkob** [comment]
Our team found the solution for this issue. First of all, we reverted all changes described above and added the following section to Sitecore config:
```XML
    <powershell>
      <services>
        <handleDownload>
          <authorization>
            <add Permission="Allow" IdentityType="User" Identity="sitecore\myusername" desc="Basic authentication username."/>
          </authorization>
        </handleDownload>
      </services>
    </powershell>
```

**Comment by michaellwest** [comment]
That's great news @ilchenkob !
