### ISSUE TITLE
Show-ListView size params (Width, Height) only work when Modal switch is set

### ISSUE THREAD

**Issue by bmbruno** [SitecorePowerShell/Console#1205]
### Expected Behavior

`Show-ListView` cmdlet documents `Width` and `Height` parameters. Setting these values is expected to size the report window appropriately.

### Actual Behavior

The `Width` and `Height` parameter only work when the `Modal` switch is set on the cmdlet. This is made obvious by branching logic in `\src\Spe\Commands\Interactive\Messages\ShowListViewMessage.cs`, wherein the modal option passes the values of width/height through to the Sheer response dialog, but the non-modal path does not.

### Steps to Reproduce the Problem

Execute a `Show-ListView` cmdlet (with data) and the `Width` and `Height` parameters set to something obviously different than the default.

**Suggestion:** if these params are only intended to function with the `Modal` switch, then documentation should be updated accordingly. Please let me know if you want me to submit a PR for that :-)

Example of size not being set:

``` powershell
$items = Get-ChildItem -Path 'master:/sitecore/content' -Recurse
$items | Show-ListView -Width 400 -Height 300
```

Example of Modal flag respecting size params:

``` powershell
$items = Get-ChildItem -Path 'master:/sitecore/content' -Recurse
$items | Show-ListView -Width 400 -Height 300 -Modal
```

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
@bmbruno Any idea if it's possible to control the Sheer UI application window size in desktop mode? Curious if it would even be possible to make work.

I'd be happy to accept a PR for either a fix of the UI or to correct this in the docs. May be worth investigating the parameter sets to see if a warning would be necessary to alert the user of the issue.

**Comment by bmbruno** [comment]
Looking at `Sitecore.Shell.Framework.Windows.RunApplication()`, it appears that the width/height are pulled from the application definition item in the `core` database:

``` csharp
string width = StringUtil.GetString(application["Width"], "75%");
string height = StringUtil.GetString(application["Height"], "80%");
```

This means that the width/height values cannot be passed in via the `parameters` value (or any of the querystring options - I checked).

It's probably best to update the documentation to make it clear that the `Width` / `Height` params only function when using the `Modal` switch. I'll take a look into doing that as a start.

**Comment by bmbruno** [comment]
I updated the SPE documentation for `Show-ListView` to clarify the usage of `Width` and `Height`. I'd say this satisfies this issue and we can close. I'll let you decide. Thanks for the feedback!

https://github.com/SitecorePowerShell/Book/pull/25#issuecomment-671498458
