### ISSUE TITLE
Dialog buttons gets double encoding

### ISSUE THREAD

**Issue by mikaelnet** [SitecorePowerShell/Console#1207]
### Expected Behavior

When creating dialog boxes, buttons should have their labels as they are written in the script.

### Actual Behavior

When writing content that needs encoding, such characters gets double encoded resulting in incorrect content being displayed. I'm not sure if this is a problem with SPE or if it is in Sitecore itself.

### Steps to Reproduce the Problem

View the content of the buttons when firing this dialog from the console or the ISE:

`Show-ModalDialog -Control 'ConfirmChoice' -Parameters @{ btn_0='< Prev'; btn_1='Next >'; btn_2='<&">'; cp='Wizard'; te='Wizard step' }`

Tested on 6.0 and 6.1.1

 - [X] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [X] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Looks like the code encoded the text but never decoded it.

I made a change to correct the header text of the button. Have a glance at the commit and let me know if you think there are any other changes that should be made.

![image](https://user-images.githubusercontent.com/933163/90529466-601b2a80-e139-11ea-935a-36dee10225f1.png)

**Comment by mikaelnet** [comment]
Looks good! Thank you!
