### ISSUE TITLE
SPE 6.1.1 on Sitecore 10 xc0 docker setup -> Could not resolve type name: Spe.Integrations.Pipelines.AssemblyResolver, Spe (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

### ISSUE THREAD

**Issue by harko-aviva** [SitecorePowerShell/Console#1208]
### Expected Behavior

Expected behavior is for the SPE to install

### Actual Behavior

Error occurs when installing
Could not resolve type name: Spe.Integrations.Pipelines.AssemblyResolver, Spe (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

[Exception: Could not resolve type name: Spe.Integrations.Pipelines.AssemblyResolver, Spe (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).]    Sitecore.Diagnostics.Error.Raise(String error, String method) +133    Sitecore.Configuration.DefaultFactory.CreateType(XmlNode configNode, String[] parameters, Boolean assert) +1009    Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +69    Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +163    Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, Boolean assert) +68    Sitecore.Pipelines.CorePipelineFactory.GetObjectFromType(XmlNode processorNode) +91    Sitecore.Pipelines.CorePipelineFactory.GetProcessorObject(XmlNode processorNode) +138    Sitecore.Pipelines.CoreProcessor.GetMethod(Object[] parameters) +136    Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +476    Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +236    Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22    Sitecore.Nexus.Web.HttpModule.Application_Start() +215    Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +1221    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +584    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369  [HttpException (0x80004005): Could not resolve type name: Spe.Integrations.Pipelines.AssemblyResolver, Spe (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +724
--
### Steps to Reproduce the Problem

Run sitecore 10 xc0 docker setup.
After all containers are running healthy start package install wizard, upload the SPE 6.1.1. and press install.
After a few minutes the install crashes with error mentioned above and the container becomes unhealthy

 - [X] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [X] Asked questions on the Sitecore Slack Chat channel.
 
 - [X] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Does the image already have SPE installed? What else can you tell me about the contents of the running container?

**Comment by harko-aviva** [comment]
SPE is not yet installed, it is a clean install from the Sitecore 10 docker images.
This is done right after running docker-compose up.

What would you like to know about the contents of the container?

**Comment by AlexKasaku** [comment]
Is it possible to get the App_Config and bin contents list, perhaps as an attached file? The error suggests the configuration is in place but the assemblies aren't.

**Comment by harko-aviva** [comment]
> Is it possible to get the App_Config and bin contents list, perhaps as an attached file? The error suggests the configuration is in place but the assemblies aren't.

Sure, do you want the contents before or after the (partial) installation?

**Comment by AlexKasaku** [comment]
Both would be ideal, but especially before.

**Comment by harko-aviva** [comment]
Here you go, before and after

[sc10-xc0-before-spe-install.zip](https://github.com/SitecorePowerShell/Console/files/5200183/sc10-xc0-before-spe-install.zip)
[sc10-xc0-after-spe-install.zip](https://github.com/SitecorePowerShell/Console/files/5200184/sc10-xc0-after-spe-install.zip)

**Comment by harko-aviva** [comment]
hmm, there don't seem to be any differences

**Comment by harko-aviva** [comment]
Right, I made the C:\inetpub\wwwroot\sitecore\shell\version\Modules\ folder before doing the installation.
Still crashes but a different error-message now.

The Spe.config file does exist after the installation



ManagedPoolThread #15 13:30:27 ERROR Installation failed: System.Exception: Background process failed: Access to the path is denied. ---> System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Sitecore.Install.Files.FileInstaller.CommitWorker.ProcessOperation(FileOperationInfo info)
   at Sitecore.Install.Files.FileInstaller.CommitWorker.Run()
   --- End of inner exception stack trace ---
   at Sitecore.Shell.Applications.Install.Dialogs.InstallPackage.InstallPackageForm.AsyncHelper.<WatchForStatus>b__11_0()
   at Sitecore.Shell.Applications.Install.Dialogs.InstallPackage.InstallPackageForm.AsyncHelper.CatchExceptions(ThreadStart start)
2868 13:30:27 INFO  Config file modified: C:\inetpub\wwwroot\App_Config\Include\Spe\Spe.config
2868 13:30:27 INFO  ConfigChanged event was postponed.
2868 13:30:27 INFO  Config file modified: C:\inetpub\wwwroot\App_Config\Include\z.Spe\z.Spe.config
2868 13:30:27 INFO  ConfigChanged event was postponed.
ManagedPoolThread #11 13:30:27 INFO  Raising chaging file: C:\inetpub\wwwroot\App_Config\Include\Spe\Spe.config
ManagedPoolThread #11 13:30:27 INFO  Job ended: Install (units processed: )
2596 13:30:27 INFO  **************************************************
2596 13:30:27 WARN  Sitecore shutting down
2596 13:30:27 WARN  Shutdown message: HostingEnvironment initiated shutdown
3068 13:30:37 INFO  License file created: C:\inetpub\wwwroot\App_Data\license.xml
2216 13:30:57 WARN  The "SessionExpirationThreadCount" setting contains an invalid value. The default value is used instead. Invalid value: "". Default value: "2"

**Comment by michaellwest** [comment]
Out of curiosity, why are you not installing the scwdp.zip instead of installing through the client?

**Comment by harko-aviva** [comment]
I am using the package install wizard, as far as I know it's meant for installing packages :)
How would I go about installing it any other way?

Talked to my colleagues and we are beginning to expect the docker image is broken as it does show the powershell ise and powershell option but with a broken icon.
