### ISSUE TITLE
Set-Rendering function does not change older item versions

### ISSUE THREAD

**Issue by JohannesGoetz** [SitecorePowerShell/Console#1210]
### Expected Behavior

The **Set-Rendering** function sets the rendering in the Presentation details of the version the Item in the **-Item** Parameter.

### Actual Behavior

Only the latest version in the selected language can be changed.
A **-Version** Parameter is not available.

### Steps to Reproduce the Problem

Version 6.1.1

 - [ ] Use the **Set-Rendering** function and provide an Item in a Version, which is not the latest one in the provided language, in the **-Item** parameter. Also, set the **-FinalLayout** option
 - [ ] Run the script
 - [ ] The rendering will not be changed in the provided version

**Comment by michaellwest** [comment]
For this you will want to make sure that when you call get-item or get-childitem that you specify which versions.

**Comment by AlexKasaku** [comment]
@JohannesGoetz  - Can you provide a script where you're providing an older version to the command? The command just updates the relevant rendering field on the Item provided, so if given the right version it should update that one.

**Comment by AdamNaj** [comment]
Since there seems to be very little interest and there is a clear workaround, I'm closing this issue as it got stale. 
If you want this done re-open it in the future and provide a comment in support of it.
