### ISSUE TITLE
Documentation request - Upgrade guide

### ISSUE THREAD

**Issue by markgibbons25** [SitecorePowerShell/Console#1217]
Could we have a bit of documentation for upgrading for people not familiar with SPE's history / not familiar with updating modules?
Perhaps something simple like
## From 5.x
1. Remove old Cognifide config
2. Remove old Cognifide dll
3. Install the package and tick "Yes to all" for everything

## From 6.x
1. Remove old SPE config
2. Remove old SPE dll
3. Install the package and tick "Yes to all" for everything

**Comment by alexangas** [comment]
I would also like to know about any steps for moving to IAR.

**Comment by michaellwest** [comment]
Check out this page and let me know if you need anything else added. https://doc.sitecorepowershell.com/installation
