### ISSUE TITLE
Update icons for LaunchPad

### ISSUE THREAD

**Issue by PavloGlazunov** [SitecorePowerShell/Console#1219]
In the scope of LaunchPad redesign work the icons of all apps were changed. I would like to ask to update items of icons that appear on LaunchPad to align them with the new design.

Please, use the following icon paths:
_LaunchPadIcons/32x32/PowerShell ISE.png_
_LaunchPadIcons/32x32/PowerShell Reports.png_

**Note:** All icons are located at _Sitecore.Themes_ repository.

Please, reach me out if you need more details.

**Comment by michaellwest** [comment]
Are these icons included with Sitecore? What version of Sitecore do they come with?

**Comment by PavloGlazunov** [comment]
> Are these icons included with Sitecore? What version of Sitecore do they come with?

Yes, these icons are part of Sitecore. These changes are part of the 10.1 release.

**Comment by michaellwest** [comment]
Interesting. We use a single package from 8.x+. How do you propose I handle changing the icon when I need to support older versions?

**Comment by PavloGlazunov** [comment]
We did not remove the old icons set and we added a new icon set for such cases. So starting from 10.1 all apps will have the same style.

**Comment by michaellwest** [comment]
Now we just need a script to fix icons for those on older versions.

**Comment by michaellwest** [comment]
```
$iseButton = Get-Item -Path "core:{bfc79034-857c-4432-a5c2-2d93af784384}"
$iseButton.Editing.BeginEdit()
$iseButton.Fields["{D25B56D4-23B6-4462-BE25-B6A6D7F38E13}"].Value = "powershell/32x32/ise8.png"
$iseButton.Editing.EndEdit() > $null

$reportButton = Get-Item -Path "core:{74744022-353c-43f1-b8e4-5bc569ca9348}"
$reportButton.Editing.BeginEdit()
$reportButton.Fields["{D25B56D4-23B6-4462-BE25-B6A6D7F38E13}"].Value = "Office/32x32/chart_donut.png"
$reportButton.Editing.EndEdit() > $null
``

**Comment by michaellwest** [comment]
Trying to automate this step. 81ec97
