### ISSUE TITLE
Immediate Window Error

### ISSUE THREAD

**Issue by gerardorm** [SitecorePowerShell/Console#1225]
**Using**
Sitecore PowerShell Extensions 5.0.0.42513
Sitecore 9.1
Windows PowerShell 5.1

### Expected Behavior

Open the Immediate window without an error.

### Actual Behavior

I get this error when open the Immediate Window while debuging.
![image](https://user-images.githubusercontent.com/14027305/101699741-f781f180-3a38-11eb-8bed-1b505055f007.png)

### Steps to Reproduce the Problem

_Please include the version number of SPE and Sitecore._

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Can you reproduce the issue locally with 6.2?

**Comment by gerardorm** [comment]
> Can you reproduce the issue locally with 6.2?

I have not done it yet. I mean we prefer if we stay with 5.0, Is this something you think we should upgrade?

**Comment by michaellwest** [comment]
Did you remove any languages? What is unique about your client language?

**Comment by gerardorm** [comment]
No, we did not, we do have several languages but EN is the primary one. Seems like **Context.ContentLanguage** is null inside ExecuteCommand, which is weird.

**Comment by gerardorm** [comment]
Also I noticed 
![image](https://user-images.githubusercontent.com/14027305/101705884-2f8f3180-3a45-11eb-9cf0-471f85ab6d85.png) event this dropdowns don't work. And they got to do with the **Context**

**Comment by gerardorm** [comment]
Maybe using **LanguageManager.DefaultLanguage** instead of **Context.ContentLanguage** ?

**Comment by gerardorm** [comment]
Hi, @michaellwest I found out that the root issue first of all, the **IgnoreUrlPrefixes** setting value contains the path for **/sitecore modules/PowerShell** so this was causing some inconsistencies when calling the **ExecuteCommand** so basically every path that you ignore prevent Sitecore from processing specific requests, causing ASP.NET to process the request without Sitecore. But after removing that I get 401 for each call to **/sitecore%20modules/PowerShell/Services/PowerShellWebService.asmx**
![image](https://user-images.githubusercontent.com/14027305/101726957-cde4bc80-3a70-11eb-9e51-cf3cf022f28e.png)

**Comment by michaellwest** [comment]
I think what you need is the patch for identity server. Are you using IS?

**Comment by michaellwest** [comment]
`<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/" xmlns:role="http://www.sitecore.net/xmlconfig/role/" xmlns:security="http://www.sitecore.net/xmlconfig/security/">
  <sitecore role:require="Standalone or ContentManagement" security:require="Sitecore">
    <pipelines>
      <owin.cookieAuthentication.validateIdentity>
        <processor type="Sitecore.Owin.Authentication.Pipelines.CookieAuthentication.ValidateIdentity.ValidateSiteNeutralPaths, Sitecore.Owin.Authentication">
          <siteNeutralPaths hint="list">
            
            <path hint="spe">/sitecore%20modules/PowerShell</path>
          </siteNeutralPaths>
        </processor>
      </owin.cookieAuthentication.validateIdentity>
    </pipelines>
  </sitecore>
</configuration>`

**Comment by gerardorm** [comment]
Since I installed SPE I added the patch, no luck so far. Thanks for your time @michaellwest, sorry for bothering you.
![image](https://user-images.githubusercontent.com/14027305/101731387-cde8ba80-3a78-11eb-9c3d-3aa0f72343bd.png)

**Comment by michaellwest** [comment]
Hey @gerardorm , not a bother at all. If you _do_ update to 6.2 then it would be easier for me to provide you with dlls to debug the issue.

**Comment by gerardorm** [comment]
Hi @michaellwest, good news this morning I was able to get some luck, I added a patch for a site definition and added after 'modules_shell'. Patch: <site patch:after="*[@name='modules_shell']" name="modules_powershell" virtualFolder="/sitecore modules/PowerShell" physicalFolder="/sitecore modules/PowerShell" language="en" database="core" domain="sitecore" content="$(defaultContentDatabaseName)"/>.

Thanks for the help, if you want to remove the ticket or maybe leave it so someone can based on this if they are having the same issues.

Regards.

**Comment by michaellwest** [comment]
What an interesting solution. How did you figure out to try that?
