### ISSUE TITLE
Images are not visible on 'Recently uploaded images' section

### ISSUE THREAD

**Issue by Bharath7791** [SitecorePowerShell/Console#1229]
### Expected Behavior
When we go to content editor and click to upload image, images should come up
_Please describe the expected behavior._

### Actual Behavior
But we are getting below window. 
![imae_upload](https://user-images.githubusercontent.com/79588316/109017488-3bea6880-76dd-11eb-9ef7-e5ebf9c5b034.png)

_Please describe the actual behavior._

### Steps to Reproduce the Problem
go to content editor, select the item where we have image field. Click on browse button
_Please include the version number of SPE and Sitecore._
Sitecore PowerShell Extensions 6.1.1.38514
Sitecore 9.3

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 Yes
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 We had created a ticket to sitecore. When we had a discussion we got to know that, issue is only with respect to the role that we created using powershell. Hence they have asked us to create a ticket here
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Why did you open a ticket for SPE? Would this not be a support ticket that should go to Sitecore?

**Comment by Bharath7791** [comment]
We had created a ticket with Sitecore and we got below response.
<img width="589" alt="sc_response" src="https://user-images.githubusercontent.com/79588316/109022924-4fe49900-76e2-11eb-93e5-0c44940e0b67.PNG">

**Comment by michaellwest** [comment]
Can you provide details about how you are creating a role? What does your security setup look like?

**Comment by AlexKasaku** [comment]
@Bharath7791 - This doesn't really seem like it could be related to SPE, which uses the security API for changing roles. Could you recreate a similar role + user through the standard UI and see if it exhibits the same behaviour? If it does you could then take this to Sitecore Support.

**Comment by Bharath7791** [comment]
Hi @AlexKasaku ,

When we create a role manually or when we use the default roles and try this, we are able to see the images under 'Recently uploaded images' tab.

**Comment by Bharath7791** [comment]
Hi @michaellwest ,

Please find the attached script to create a role called 'Power user' which is equivalent to admin role.
[power_user_role_script.txt](https://github.com/SitecorePowerShell/Console/files/6041688/power_user_role_script.txt)

**Comment by AdamNaj** [comment]
Stale and a configuration issue rather than SPE issue.
