### ISSUE TITLE
Set-RenderingParameter not setting parameters on newly added rendering

### ISSUE THREAD

**Issue by bic742** [SitecorePowerShell/Console#1230]
### Expected Behavior

When using `Set-RenderingParameter` to update rendering parameters on a rendering, the updated values are reflected on a page.

### Actual Behavior

It appears that `Set-RenderingParameter` is not having any impact on the rendering

### Steps to Reproduce the Problem

```
$renderingParameters = [ordered]@{
    "ColumnWidth1" = "{9AD9D6FB-28FC-43C5-8DA4-4A6A63CE802F}";
    "ColumnWidth2" = "{9AD9D6FB-28FC-43C5-8DA4-4A6A63CE802F}";
}

$splitter = $splitterRendering | New-Rendering -Placeholder "main" 
$lastSplitter = $renderingCounter - 1

Add-Rendering -Item $destinationItem -Placeholder "main" -Instance $splitter -FinalLayout

$newRendering = Get-Rendering -Item $destinationItem -Instance $splitter -FinalLayout 

$newRendering |
    Set-RenderingParameter -Parameter $renderingParameters |
    Set-Rendering -Item $destinationItem -FinalLayout
```

The above code creates a new rendering instance and adds that instance to a page. Afterward, the instance is retrieved off of the page and it attempts to up the rendering parameters. 

Sitecore 9.3 w/ SXA - SPE 6.0

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [x] Asked questions on the Sitecore Slack Chat channel.
 
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
@bic742 How are you assigning the `$splitterRendering`?

**Comment by bic742** [comment]
`$splitterRendering = Get-Item -Path "master:{C25766C8-9AFD-4D28-87FE-147774F6806D}"`

That is the ItemId of the Split Columns rendering from SXA. It is successfully adding the page, and I can then add content to the placeholders. I am trying to update the column width rendering parameters so it will be a 50/50 split, and they won't stick. 

Note: It works if I pass the `-Parameter` parameter to `Add-Rendering`, but then that clobbers the `DynamicPlaceholderId` on the rendering.

**Comment by michaellwest** [comment]
Does this relate to the bug #1164?

**Comment by bic742** [comment]
Assuming this bug is resolved, then I should be able to pass the parameters in on `Add-Rendering`; I would consider this a viable workaround, but not the solution to the issue I have filed.

 I have already asked the client to upgrade from 6.0 to latest so I can get the `-PassThru` parameters on `Add-Rendering`. Once they complete the upgrade, I will give it a shot and update back.

**Comment by michaellwest** [comment]
If they go with 6.1.1 or 6.2 then that fix should be available.

**Comment by bic742** [comment]
Tried using `-Parameter` parameter on `Add-Rendering` using 6.2; it clobbered the `DynamicPlaceholderId` rendering parameter :(

Is it possible that this fix got lost in a regression somehow? I also need to confirm that 6.2 was correctly installed...

**Comment by bic742** [comment]
I'm closing this... A couple of final notes:

1. I was only able to get `Set-RenderingParameter` working by passing in paramters one at a time
2. It looks like the behavior I was seeing was based on dependencies with the given (SXA) component. There were other renderings parameters that had to be set for the splitter to display as necessary. 

Final code block:

```
# 50/50 split for each column
$splitter = $splitterRendering | New-Rendering -Placeholder "main" 
$lastSplitter = $renderingCounter - 1

$renderingParametersColumnOne = @{ "ColumnWidth1" = "{9AD9D6FB-28FC-43C5-8DA4-4A6A63CE802F}" }
$renderingParametersColumnTwo = @{ "ColumnWidth2" = "{9AD9D6FB-28FC-43C5-8DA4-4A6A63CE802F}" }
$renderingParametersSplitterSize = @{ "SplitterSize" = "2"; }
$renderingParametersEnabledPlaceholders = @{ "EnabledPlaceholders" = "1,2" }
$renderingParametersDynamicPlaceholderId = @{ "DynamicPlaceholderId" = "$lastSplitter" }

Add-Rendering -Item $destinationItem -Placeholder "main" -Instance $splitter -FinalLayout -PassThru | 
    Set-RenderingParameter -Parameter $renderingParametersColumnOne |
    Set-RenderingParameter -Parameter $renderingParametersColumnTwo |
    Set-RenderingParameter -Parameter $renderingParametersSplitterSize |
    Set-RenderingParameter -Parameter $renderingParametersEnabledPlaceholders |
    Set-RenderingParameter -Parameter $renderingParametersDynamicPlaceholderId |
    Set-Rendering -Item $destinationItem -FinalLayout
```

**Comment by michaellwest** [comment]
This seemed to work for me:

```powershell
$renderingItem = Get-Item -Path "master:{493B3A83-0FA7-4484-8FC9-4680991CF743}"
$destinationItem = Get-Item -Path "master:{110D559F-DEA5-42EA-9C1C-8A5DF7E70EF9}"

$renderingParameters = @{
    "ColumnWidth1" = "{9AD9D6FB-28FC-43C5-8DA4-4A6A63CE802F}";
    "ColumnWidth2" = "{9AD9D6FB-28FC-43C5-8DA4-4A6A63CE802F}";
    "ColumnWidth3" = ""
}

$rendering = $renderingItem | New-Rendering -Placeholder "main" 

$newRendering = Add-Rendering -Item $destinationItem -Placeholder "main" -Instance $rendering -FinalLayout -PassThru

$newRendering |
    Set-RenderingParameter -Parameter $renderingParameters |
    Set-Rendering -Item $destinationItem -FinalLayout
```
