### ISSUE TITLE
sitecore user profile email address reset

### ISSUE THREAD

**Issue by Manikandansankar90** [SitecorePowerShell/Console#1233]
we are  trying to update the details of custom properties fields in Sitecore users  through sitecore powershell script. 

```
if($isValid -eq "true") {
  set-User -Identity "domain\abc.com" -CustomProperties @{ "postalcode" = "xyz123" }
}
```
Above script executed successfully and  **Email address entry for user profile has been removed** if the fields in customproperties has been entered or modified/updated.

Expected Result:
Use rprofile email address should not be cleared out.

Configuration and versions:

SPE 5.1.0.19766
Sitecore 9.1
Windows PowerShell 5.1

**Comment by michaellwest** [comment]
You'll need to upgrade to 6.2 to get a fix. https://github.com/SitecorePowerShell/Console/issues/1216
