### ISSUE TITLE
Performance problems with Get-ChildItem -Recurse (bottleneck)

### ISSUE THREAD

**Issue by eMelgooG** [SitecorePowerShell/Console#1237]
I wrote my own BFS + DFS functions inside powershell to retrieve the items and both of my functions are outperforming the (Get-ChildItem -Recurse) by a lot. The DFS function is up to 5x faster than the Get-ChildItem -Recurse. 
Look at the tests I've done. I run the scripts in incognito mode and made sure the the items are not cached in the current session.

Default:  77s
![Default](https://user-images.githubusercontent.com/1024604/116884912-947f3a00-ac27-11eb-8531-e74ebcf85a4a.PNG)

BFS: 30s
![BFS](https://user-images.githubusercontent.com/1024604/116884923-9943ee00-ac27-11eb-9b19-c1d33c1b5f0c.PNG)

DFS: 22s
![DFS](https://user-images.githubusercontent.com/1024604/116884996-acef5480-ac27-11eb-9ff0-5829426f8974.PNG)

For the DFS I get between 15-22 seconds constantly. 

Is it ok if I play around with the C# source code and try to fix/ optimize this?

**Comment by michaellwest** [comment]
Hi @eMelgooG one you thing you may not have noticed is that calls to Get-Item and Get-ChildItem result in items that are "wrapped" with extra properties. If your item has a field on it called "Title", this would allow you to access the field using `$item.Title`. 

When accessing the "Children" property of the item, or making calls to `Axes`, as well as a few other places, your item is not decorated with these extra properties.

One thing you can try in your tests is to pipe the item to another command like this `$child | Initialize-Item`. You'll probably start to see similar results.

It's convenient to use `Get-ChildItem` and -Get-Item` with these extra parameters, but there's a cost.

**Comment by michaellwest** [comment]
Here is an example of what I mean.

![image](https://user-images.githubusercontent.com/933163/116895756-2459bf80-abf9-11eb-9258-320b77704eea.png)

![image](https://user-images.githubusercontent.com/933163/116895892-42272480-abf9-11eb-87e0-d68e88ec8b60.png)

**Comment by eMelgooG** [comment]
@michaellwest Thank you for your prompt and detailed answer, and yes I looked over the source code method GetChildItemHelper~ and found exactly what you were saying. There are lot's of method parameters and lot's of checks based on that params which is probably the reason why it's slowing it down. 
I don't really understand what exactly "Initialize-Item" does but from the tests I've done I see that I can't access the Item fields if I don't use it when I get the Item with GetItem(). 

In the company I work we have to run the scripts first on the Dev Env and then run it on Prod (which is pretty normal workflow). The problem is that the Dev server is helllllllllla slow.

**Comment by eMelgooG** [comment]
@michaellwest Ohhhhhhhhhh... I see now with the fields.

**Comment by eMelgooG** [comment]
In the script I made I was manually iterating over the the Item fields and that's why I didn't noticed this. This is a cool feature you guys made.

**Comment by michaellwest** [comment]
If you just want the items fast and don't need the use of the automatic properties consider calling more of the core Sitecore API.

I explain more about it [here](https://doc.sitecorepowershell.com/working-with-items#when-not-to-use-the-automated-properties).

For general usage the commands `Get-Item` and `Get-ChildItem` are fine. If you don't need to read all the fields on the item, use the automatic properties (which include the Editing calls) then the standard API is going to get what you need fast.

**Comment by eMelgooG** [comment]
Very interesting. By the way I know that the item data in sitecore db's is read by a query that unions these 4 tables: Items, SharedFields, UnversionedFields, VersionedFields. So the fields are already being pulled at the same time with the Item data. So I'm assuming that by populating the automated properties you guys have to iterate over all the fields of the item. Is that right? 
This might be overhead for some of the scripts I'm running as most of the time I don't need all the fields or I don't need them at all.

**Comment by eMelgooG** [comment]
I found the answer to my question here: 
![image](https://user-images.githubusercontent.com/1024604/116981267-8f71c780-acc7-11eb-9ec5-aa954f2111d2.png)

**Comment by michaellwest** [comment]
@eMelgooG Here is an experimental way to speed things up.

```powershell
$dpe = New-Object Spe.Core.Data.DisablePropertyExpander

$watch = [System.Diagnostics.Stopwatch]::StartNew()

$item = Get-Item -Path "master:\content\home"
$item.Title

$watch.Stop()
$watch.ElapsedTicks

$dpe.Dispose()
```

**Comment by eMelgooG** [comment]
@michaellwest  Thanks for the tip. I played with all these options and found out that the fastest way to pull all the items is to use the Axes.GetDescendants()

**Comment by michaellwest** [comment]
That will certainly be the fastest way to get the entire tree of content. You'll notice that many of the reports have used that approach too.

**Comment by eMelgooG** [comment]
@michaellwest  I have a question. It's not really related to this but you are more experienced than me in SiteCore and you might know: 
Do you have any idea how I can peek inside the code of the core sitecore api methods? Like Item.GetChildren() and Axes.GetDescendants? 

Also do you know what's this table used for or what it is? I was thinking it's used for the Axes.GetDescendants() method but I tried to run an SQL query and find the  rows with the ID of one of my websites homepage but it's not in there. 
![image](https://user-images.githubusercontent.com/1024604/117280835-4d7d8880-ae63-11eb-8473-fa8cf12b5377.png)
