### ISSUE TITLE
Cannot elevate session state using Okta login

### ISSUE THREAD

**Issue by gary1125** [SitecorePowerShell/Console#1240]
### Expected Behavior

I implemented Okta login. After I login and run a powershell script, I use the password. However, the password does not work.

![image](https://user-images.githubusercontent.com/1879390/119428611-8a48eb00-bd50-11eb-93ba-52cedfc5beab.png)

**Comment by gary1125** [comment]
Hi @michaellwest  thanks for the quick response. Could you let me know more details? I had a look at spe.config, and only found the following options:
`
          <token name="Default" expiration="00:00:00" elevationAction="Block"/>
          <token name="Console" expiration="00:05:00" elevationAction="Password"/>
          <token name="ISE" expiration="00:05:00" elevationAction="Password"/>
          <token name="ItemSave" expiration="00:05:00" elevationAction="Password"/>`

**Comment by michaellwest** [comment]
You can read more about it with issue #1196. This feature was released with SPE 6.2.
