### ISSUE TITLE
Restore-ArchiveItem with -ArchiveItem flag results in error

### ISSUE THREAD

**Issue by marcelgruber** [SitecorePowerShell/Console#1251]
### Expected Behavior

Archive item gets restored.

### Actual Behavior

Parameter set cannot be resolved using the specified named parameters.

<img width="981" alt="Screen Shot 2021-12-09 at 10 51 29" src="https://user-images.githubusercontent.com/4956028/145449400-a9e32616-2296-4a64-8b32-a63431b46be1.png">

### Steps to Reproduce the Problem

Sitecore version  9.0.1 (180604)
Sitecore PowerShell Extensions 6.2.0.34182
Windows PowerShell 5.1

```
$database = Get-Database -Name "master"
$archiveName = "recyclebin"
$archiveUser = "sitecore\admin" 
$maxItemsToFetch = 9999

$archive = Get-Archive -Database $database -Name $archiveName
$archivedItems = $archive.GetEntries(0, $maxItemsToFetch)

$archivedItems | ForEach-Object {
  Write-Host "Restoring" $_.ArchivalId "|" $_.OriginalLocation "| Archived by:" $_.ArchivedBy `r`n

  # ERROR IS HERE
  Restore-ArchiveItem -Archive $archive -ArchiveItem $_
}
```

I also tried wrapping the ArchiveEntry in `@($_)` and `[$_]` to ensure the specific item lives in an array, because that's what the -ArchiveItem expects:

`Restore-ArchiveItem -Archive <Archive> [-ArchiveItem <ArchiveEntry[]>]`

### Workaround

This appears to work:

`$archive.RestoreItem($_.ArchivalId)`

Which I got from:[https://github.com/SitecorePowerShell/Console/blob/fa730e2e0f8a8de55a15adc75e2c5ed2394c7b48/src/Spe/Commands/Data/RestoreArchiveItemCommand.cs#L60](https://github.com/SitecorePowerShell/Console/blob/fa730e2e0f8a8de55a15adc75e2c5ed2394c7b48/src/Spe/Commands/Data/RestoreArchiveItemCommand.cs#L60)

**Comment by michaellwest** [comment]
Looks like the book was a little out of date. You should see these options:

```powershell
Restore-ArchiveItem -Archive <Archive> [-WhatIf] [-Confirm]  [<CommonParameters>]
Restore-ArchiveItem -Archive <Archive> [-ItemId <ID>] [-WhatIf] [-Confirm]  [<CommonParameters>]
Restore-ArchiveItem -Archive <Archive> [-Identity <AccountIdentity>] [-WhatIf] [-Confirm]  [<CommonParameters>]
Restore-ArchiveItem -ArchiveItem <ArchiveEntry[]> [-WhatIf] [-Confirm]  [<CommonParameters>]
```

You should be able to drop the `-Archive` parameter in your example.
