### ISSUE TITLE
SPE 6.3 - IAR.zip not working after installation in 10.2 upgradation instance

### ISSUE THREAD

**Issue by sparida2022** [SitecorePowerShell/Console#1256]
Hi,

We are upgrading our application from Sitecore 9.1.1 to Sitecore 10.2.0 version. Post solution and database upgradation when we were trying to upgrade SXA in 10.2 instance as per Sitecore guide (SXA_10_2_0_upgrade_guide-en), it was mentioned in prerequisite section before upgrading SXA we have to install  Sitecore PowerShell Extensions 6.3 - IAR. We downloaded the same package from from both Sitecore and GitHub and installed the package. After installing this package PowerShell ISE didn't work in our upgraded Sitecore 10.2 instance. It was throwing exception "Layout not Found". Please find attached screenshot for your reference. We had raised ticket with Sitecore support for this, after seeing this issue they gave us below workaround solution for this.

- Sitecore support team told us to delete all the items which are available in SPE 5.0.zip package from our content tree (which was upgraded from Sitecore 9.1 to 10.2). 
- After deleting these items from our content tree PowerShell ISE started working.

Could you please confirm us above solution is reliable or not ? Can we proceed with above process to Production environment or not?

If the above solution is not reliable then please let us know what to do to resolve this issue. 

Waiting for your response.

Regards,
Santosh
<img width="938" alt="sitecore_ticket_info1" src="https://user-images.githubusercontent.com/99946435/154629623-9b049da2-4c69-41a2-bbe3-a1f3570bc7a4.png">
<img width="933" alt="sitecore_ticket_info" src="https://user-images.githubusercontent.com/99946435/154629629-7f3390ad-e765-4c24-9c4e-9035c8a06388.png">

**Comment by michaellwest** [comment]
Can you provide more details about which items you deleted that allowed it to work? Which database did you delete from?

**Comment by sparida2022** [comment]
Hi,

Thanks for your response.

Now in our case we have deleted old items from content tree manually and our PowerShell ISE is working.

Could you please confirm us above solution is reliable or not ? Can we proceed with above process to Production environment or not?

Regards,
Santosh

**Comment by jammykam** [comment]
Yes, as long as you deleted all the items in the original SPE package (from both Master and Core) then it is reliable.
