### ISSUE TITLE
Write-Progress indeterminate percent indicator

### ISSUE THREAD

**Issue by kningyi** [SitecorePowerShell/Console#1257]
### Expected Behavior

If I use WriteProgress without a PercentComplete argument, it should show an indeterminate progress bar just like when I do not use WriteProgress. Alternatively, it would be great if we can add a flag to specify that that the progress is uncertain like -PercentUnknown or something.

![image](https://user-images.githubusercontent.com/13121503/155916952-4673de82-8349-4315-92de-bfd64b2fab23.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/13121503/155916499-acde7266-0528-4756-8f61-e2780415cb1d.png)

### Steps to Reproduce the Problem

- Sitecore PowerShell Extensions 6.2.0.34182
- Sitecore 10.0.1
- Code: `Write-Progress -Status "Processing..." -Activity "testing"`

**Comment by michaellwest** [comment]
@kningyi Do you happen to have a script that produces the indeterminate indicator? I seemed to have lost my sample script from #1096

**Comment by kningyi** [comment]
Hm, I just run any script from the SPE module, like Find all Powershell commands:

![image](https://user-images.githubusercontent.com/13121503/157593425-7deefc54-f284-4db2-9858-03ed96b73ca3.png)

**Comment by AdamNaj** [comment]
Done
