### ISSUE TITLE
XSS - ListView

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#1264]
### Expected Behavior

No XSS

### Actual Behavior

XSS

### Steps to Reproduce the Problem

```powershell
$item = gi -path '/sitecore/content/Home'
$item.Title = '<script>alert(1)</script>'
$item | Show-ListView -Title "Test" -Property @{ Label = 'label'; Expression = { $_.Title } }
```

**Comment by michaellwest** [comment]
@alan-null Should it be replaced with anything?

![image](https://user-images.githubusercontent.com/933163/165670552-3f04a19f-849e-43c4-966c-c6db55be0a69.png)

**Comment by alan-null** [comment]
@michaellwest I think it's a good idea to indicate that someone is trying to do nasty things - I don't have any message/content preferences.
