### ISSUE TITLE
Sitecore 10: Access Powershell ISE using Identity Server

### ISSUE THREAD

**Issue by meethitesh28** [SitecorePowerShell/Console#1265]
Hello,

We are using Sitecore 10 using Sitecore Identity (ADFS) and trying to access Powershell ISE. It is asking for password. We've enabled Spe.IdentityServer.config file and after that we are entering our ADFS password. But still it throwing an invalid credentials error.
Can you please let us know what are the steps we need to follow to enable Poershell ISE using Sitecore Identity.

Thanks

**Comment by michaellwest** [comment]
Hi @meethitesh28 , there is currently no direct integration with Identity Server. You can patch the SPE configuration to change from **Password** to **Confirm**.

**Comment by meethitesh28** [comment]
> Hi @meethitesh28 , there is currently no direct integration with Identity Server. You can patch the SPE configuration to change from **Password** to **Confirm**.

Thank you @michaellwest, will change that.
