### ISSUE TITLE
Publish-Item does not support more than one Target

### ISSUE THREAD

**Issue by simoncroak** [SitecorePowerShell/Console#1267]
The Publish-Item SPE command does not support specifying more than one Target. Despite documentation and code appearing to suggest it should:

https://github.com/SitecorePowerShell/Console/blob/fa730e2e0f8a8de55a15adc75e2c5ed2394c7b48/src/Spe/Commands/Data/PublishItemCommand.cs#L62

`Publish-Item -Path "master:\sitecore\content\Global" -PublishMode Smart -Target web,prod2` 
results in no output or Job starting

`Publish-Item -Path "master:\sitecore\content\Global" -PublishMode Smart -Target web -Target prod2`
results in:

> Publish-Item : Cannot bind parameter because parameter 'Target' is specified more than once. To provide multiple values to parameters that can
accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
At line:1 char:85
... sitecore\content\Global" -PublishMode Smart -Target web -Target prod2
CategoryInfo          : InvalidArgument: (:) [Publish-Item], ParameterBindingException
FullyQualifiedErrorId : ParameterAlreadyBound,Spe.Commands.Data.PublishItemCommand

`[string]$targets = @('web','prod2')`
`Publish-Item -Path "master:\sitecore\content\Global" -PublishMode Smart -Target $targets`

results in:

> Publish-Item : Could not find configuration node: databases/database[@id='web prod2']
At line:3 char:1
Publish-Item -Path "master:\sitecore\content\Global" -PublishMode Sma ...
CategoryInfo          : NotSpecified: (:) [Publish-Item], InvalidOperationException
FullyQualifiedErrorId : System.InvalidOperationException,Spe.Commands.Data.PublishItemCommand

**Steps to Reproduce the Problem**
Sitecore v10.0.1
SPE v6.3.0

- [x] Tested issue with clean install of Sitecore and the latest available version of SPE.

- [ ] Asked questions on the Sitecore Slack Chat channel.

- [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by simoncroak** [comment]
`[string]$targets = [string[]]@('web','prod2')`
`Publish-Item -Path "master:\sitecore\content\Global" -PublishMode Smart -Target $targets`

Results in:

>Publish-Item : Could not find configuration node: databases/database[@id='web prod2']
At line:2 char:1
Publish-Item -Path "master:\sitecore\content\Global" -PublishMode Sma ...
CategoryInfo          : NotSpecified: (:) [Publish-Item], InvalidOperationException
FullyQualifiedErrorId : System.InvalidOperationException,Spe.Commands.Data.PublishItemCommand

**Comment by michaellwest** [comment]
You are casting target to a string which would be incorrect.

**Comment by simoncroak** [comment]
Hi @michaellwest I can confirm the following works:

```powershell
$targets = [string[]]@('web','prod2')
Publish-Item -Path "master:\sitecore\content\Global" -PublishMode Smart -Target $targets -Recurse -AsJob
```

Two publishing jobs are created, thank for all your help.
