### ISSUE TITLE
The request could not be completed because the restfulv2 service is disabled.

### ISSUE THREAD

**Issue by sparida2000** [SitecorePowerShell/Console#1273]
### Expected Behavior

PowerShell Console should open as expected after providing admin password.

### Actual Behavior

PowerShell Console is throwing exception as below :
5088 04:33:13 WARN Session state elevated for 'Console' by user: sitecore\Admin
8448 04:38:13 WARN Session state elevation expired for 'Console' for user: sitecore\Admin
5400 04:38:30 INFO A request to the restfulv2 service was made from IP 116.50.59.201:56473
5400 04:38:30 WARN The request could not be completed because the restfulv2 service is disabled.
7364 04:38:58 INFO Script item set to master:\system\Modules\PowerShell\Script Library\SXA\SXA - Site Manager\Toolbox\SXA Site Manager in ScriptSession $scriptSession$|vvrcwjy00wg4befqvlx2x2ln|b02c5c66-0e50-480b-b440-fe17a7eb744a.
8988 04:39:31 INFO Script item set to master:\system\Modules\PowerShell\Script Library\SPE\Tools\Security Management\Reports\Security Audit\Locked Items in ScriptSession $scriptSession$|vvrcwjy00wg4befqvlx2x2ln|c79d85f9-d361-4cc7-aad5-1fd7ce42f550.
1556 04:39:55 INFO Script item set to master:\system\Modules\PowerShell\Script Library\SPE\Reporting\Content Reports\Reports\Content Audit\Broken Links in ScriptSession $scriptSession$|vvrcwjy00wg4befqvlx2x2ln|b9cb50b5-c8c3-4f2d-8bec-ce54a092513a.
4996 04:40:26 WARN Session state elevated for 'Console' by user: sitecore\Admin

### Steps to Reproduce the Problem

We are using SPE version -
Sitecore.PowerShell.Extensions-6.3 - IAR.zip

Sitecore version -
10.2.0

Could you please look into this issue and let us know the solution for this ?

Waiting for your response.

Regards,
Santosh

**Comment by michaellwest** [comment]
Like many times before this could happen if the Identity Server config is not enabled. Are you using Identity Server with your installation?

**Comment by AdamNaj** [comment]
Stale support.
