### ISSUE TITLE
ServiceAuthorizationManager can be faster

### ISSUE THREAD

**Issue by mitikov** [SitecorePowerShell/Console#1277]
### Expected Behavior

#997 Fix was too strict in terms of multi-threading for ServiceAuthorizationManager.

There is no need in locks on top of concurrent dictionary: https://github.com/SitecorePowerShell/Console/blob/d614b8863e948c3e8f48f6a0e559439fa8440310/src/Spe/Core/Settings/Authorization/ServiceAuthorizationManager.cs#L123

The `.Keys.Count` call provokes collection copy, whereas plain call to `Count` does not:
https://github.com/SitecorePowerShell/Console/blob/d614b8863e948c3e8f48f6a0e559439fa8440310/src/Spe/Core/Settings/Authorization/ServiceAuthorizationManager.cs#L125

Double lookups could be replaced with TryGet(...) API: https://github.com/SitecorePowerShell/Console/blob/d614b8863e948c3e8f48f6a0e559439fa8440310/src/Spe/Core/Settings/Authorization/ServiceAuthorizationManager.cs#L129

### Actual Behavior

Can be faster.

### Steps to Reproduce the Problem

Can be observed via looking at the source code in the repo.

Regards,
Nik

**Comment by michaellwest** [comment]
Thank you for the feedback. I'll have a look and see what I can do.

**Comment by michaellwest** [comment]
@mitikov Please let me know if you see anything else.
