### ISSUE TITLE
Enhance "Media items by size and type" report 

### ISSUE THREAD

**Issue by suryagahlot** [SitecorePowerShell/Console#1279]
### Expected Behavior

I would like have size fiter field as an optional field or starts with 0KB and add additional filetypes example doc, docx, xls, xlsx etc

SSE question > https://sitecore.stackexchange.com/q/32647/1606

![image](https://user-images.githubusercontent.com/11260597/186795944-2f959a61-f585-40f8-9fe0-302e06493d46.png)

### Actual Behavior

Currently size filter is mandatory and it starts from 100KB. Also it allows only gif, jpg, jpeg, pdf, png, svg

### Steps to Reproduce the Problem

Navigate: Start > Reporting Tools > PowerShell Reports > Media Audit > Media items with size and type
Version: SPE 6.3

**Comment by michaellwest** [comment]
Added changes in c195ac4039a02eb58a9235fb4d060e19edb842ad
