### ISSUE TITLE
Unable to download file via ListView or Out-Download

### ISSUE THREAD

**Issue by kningyi** [SitecorePowerShell/Console#1291]
### Expected Behavior

File should be able to be downloaded when running the Out-Download command or clicking on the Export buttons in ListView

### Example Code

```
$items = Get-ChildItem -path "/sitecore/content" 
$items | Show-ListView
[string[]]$data = $items | ConvertTo-Csv -NoTypeInformation
Out-Download -Name "test report.csv" -InputObject $data
```

### Actual Behavior

Nothing gets downloaded when I run the Out-Download command.
Nothing gets downloaded when I click Export XLSX or CSV in ListView.
No error is shown in the blue powershell console.
Wrapping the code in a try-catch block, it did not reach the catch block.

When I open browser inspector, I notice a 404 in the Network tab for the following URL:

![image](https://user-images.githubusercontent.com/13121503/202642999-abaeaf64-462d-4b8f-bae1-a7a56bda7b43.png)

/login.aspx?ReturnUrl=%2Fsitecore%2520modules%2FPowerShell%2FServices%2FRemoteScriptCall.ashx%3Fscript%3D%2F%26sc_database%26scriptDb%3Dbb08ac525a734ec7b2ca95b5b88db8f4%26apiVersion%3Dhandle

When I checked spe logs, the closest error I see is:

```
ManagedPoolThread #11 07:01:04 WARN  The property cannot be processed because the property "Name" already exists.At line:1 char:26
+ $ScPsSlvPipelineObject | Select-Object -Property $ScPsSlvProperties
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exception: System.Management.Automation.PSArgumentException
Message: The property cannot be processed because the property "Name" already exists.
```

I have no issues running `Send-File -Path "robots.txt" -NoDialog`, so there's no problems in downloading files from the server.

Any ideas why I get this issue?

Error seems to only occur on one of my staging environments; I'm unable to replicate in my local or other environments.

The Spe.IdentityServer.config is already enabled.

_Please include the version number of SPE and Sitecore._
- Sitecore 10.0.1
- Sitecore PowerShell Extensions 6.2.0.34182

**Comment by michaellwest** [comment]
As seen in the documentation, most of the services are disabled by defaults. You can enable the handle endpoint if you want to be able to download from the UI provided by SPE.

The error message you pointed out from the log file is the key indicator that the service is disabled.

**Comment by michaellwest** [comment]
Read more about it here: https://doc.sitecorepowershell.com/security#configure-web-services

**Comment by kningyi** [comment]
Hmmm I'm running the code through the SPE ISE though?
Documentation link looks like it's for accessing outside of Sitecore..

Also, I'm able to trigger the Out-Download as long as I do not enter any basic auth creds in my site.
However, when I entered basic auth creds in the same window (hence resulting in the response header having a "www-authenticate:" for the domain), the Out-Download now fails.

**Comment by kningyi** [comment]
Yes, I already have that config in my local and same issue when I entered basic auth creds.

**Comment by kningyi** [comment]
Ok an update, apparently removing name="www-authenticate:" from web.config did not affect my headers. Had to implement the script workaround in https://github.com/SitecorePowerShell/Console/issues/1203#issuecomment-670036374 instead, no web.config changes needed.

**Comment by AdamNaj** [comment]
This seems like it was handled and, the issue also appears to be stale.
