### ISSUE TITLE
sitecore powershell console not loading

### ISSUE THREAD

**Issue by pmukherjee13** [SitecorePowerShell/Console#1293]
i installed sitecore powershell extension in my sitecore 10 initial realese version of instance, the installation was successful and post that when i try to open the powershell console or powershell ise, it only loads a blank screen, i have attached the screenshot.

I also checked the browser console and there are no errors.
![image](https://user-images.githubusercontent.com/95461731/203555247-d9fad4ec-ba36-45d7-a3df-ac32963a5dfb.png)

**Comment by michaellwest** [comment]
Are you using Identity Server? What errors exist in the Sitecore log and chrome devtools?

**Comment by pmukherjee13** [comment]
@michaellwest yes we are using identity server, and i checked in logs there are no errors in log and in chrome dev tools

**Comment by michaellwest** [comment]
During setup there is a step listed to enable the SPE config for Identity Server.

**Comment by pmukherjee13** [comment]
could you please share the location in identity server where i can check for the config

**Comment by michaellwest** [comment]
Have a look here:

App_Config/Include/Spe/Spe.IdentityServer.config.disabled

**Comment by pmukherjee13** [comment]
@michaellwest yes this is enabled already

**Comment by michaellwest** [comment]
I'm guessing there is something wrong with your installation. You may try again. Perhaps you used the wrong package or the installation is incomplete.

**Comment by AdamNaj** [comment]
This is pure stale support issue. Nothing to do. Not reproducible.
