### ISSUE TITLE
Feature Request - make Elevation Action case insensitive parsing.

### ISSUE THREAD

**Issue by iamandycohen** [SitecorePowerShell/Console#1297]
https://github.com/SitecorePowerShell/Console/blob/9defbf0e6adefb3ca47f2330f933e70879f92170/src/Spe/Core/Settings/Authorization/SessionElevationManager.cs#L39

**Comment by michaellwest** [comment]
Thank you.

**Comment by michaellwest** [comment]
Solved by #1298.

**Comment by alan-null** [comment]
Duplicate of: #1298
