### ISSUE TITLE
Active directory password is not working while using powershell console

### ISSUE THREAD

**Issue by anursriv** [SitecorePowerShell/Console#1301]
Hi Team,

We are working on a user story where we need to enable users to run the powershell scripts so that we can check if any item is modified that it will give correct info of user who has modified it.

We have installed powershell 6.4 version and using delegate access to achieve this. But when we have done this we found that when we are logging into powershell console , it is not taking AD password.
Need your help if we need any modification in settings to achieve it.

Regards,
Anurag

**Comment by michaellwest** [comment]
The most direct way to overcome this scenario is by switching from "Password" to "Confirm" as described [here](https://doc.sitecorepowershell.com/security#security-hardening).

> Confirm - Prompt the user for a confirmation before running the session elevated.

Confirm will present the user with an "OK" button but no password.
