### ISSUE TITLE
Get-ItemReferrer / Get-ItemReference to include links from standard values item with -Recurse parameter

### ISSUE THREAD

**Issue by kningyi** [SitecorePowerShell/Console#1302]
### Expected Behavior

Calling Get-ItemReferrer / Get-ItemReference should give the same number of links as the Links dialog under the Navigate tab.

### Actual Behavior

There were some links missing when I used the powershell code instead of the C# code:

```
Get-ItemReferrer -Id $item.Id -ItemLink | Show-ListView
```

```
$includeStandardValuesLinks = $true
[Sitecore.Globals]::LinkDatabase.GetItemReferrers($item, $includeStandardValuesLinks) | Show-ListView
```

When I set false for $includeStandardValuesLinks, the links returned are the same as the powershell code.

Is it possible to add a flag to allow the inclusion of links from standard values item?

_Please include the version number of SPE and Sitecore._

- Sitecore 10.0.1
- Sitecore PowerShell Extensions 6.2.0.34182

**Comment by AdamNaj** [comment]
Added through `-Recurse` parameter

- @michaellwest Needs documentation
- @michaellwest Removed the count before returning results as it can prevent the cmdlet from working if all referrers/references are from Standard values.
