### ISSUE TITLE
Powershell Script running is showing error

### ISSUE THREAD

**Issue by iprateeksunny** [SitecorePowerShell/Console#1305]
**Expected Behavior**
When we run Powershell script in Powershell ISE in Sitecore. Then it should generate the desired output/result.

**Actual Behavior**
In Sitecore 9.2 environment, when we are running Powershell script on PowerShell console. After some time, we are seeing one exception and script execution is failing.

**Steps to Reproduce the Problem**
We copy the script and open Powershell ISE and execute the script then after some time we see below error:

Exception of type: 'System.OutOfMemoryException' was thrown,
at Line: 60 Char: 21

And it is happening with every script.

![image](https://user-images.githubusercontent.com/132745621/236614972-5679a974-5897-4e5b-8675-2e18eb147ef5.png)

Sitecore Version: 9.2
Powershell Version: 5.1

**Comment by iprateeksunny** [comment]
The scope is global and we are expecting around 1000 items in the report generated from script.

**Comment by iprateeksunny** [comment]
Please let me know if any other information is required to investigate the issue

**Comment by michaellwest** [comment]
`Get-Contacts` and `Get-Value` appear to be custom functions. What do they do?

**Comment by michaellwest** [comment]
Can you provide a more complete example of your script? The screenshots do not provide much context into what is happening in the script.

**Comment by iprateeksunny** [comment]
Below is the screenshot of Get-Value and Get-Contacts functions:

![image](https://github.com/SitecorePowerShell/Console/assets/132745621/a4312fd3-a756-4185-b9fa-4163eb24f44f)

Please let us know if anything else is required.

**Comment by iprateeksunny** [comment]
Apologies.  the script is different. We are getting this error:

![image](https://github.com/SitecorePowerShell/Console/assets/132745621/214574f9-3899-426c-ab00-4f6b2269b657)
 
and the line(69) throwing the exception are as below:

![image](https://github.com/SitecorePowerShell/Console/assets/132745621/6905a1ac-98fa-4f51-abeb-af3f5cd5f289)

This issue is occurring only on production. If we run the same script on any lower environments then it works as expected.
Please let me know if anything else is required to investigate the issue.

**Comment by AdamNaj** [comment]
There are no clear reproduction steps that would allow us to fix this issue. 
Please provide script that will cause the issue on a clear Sitecore instance, otherwise we have to assume it's 3rd party code that is causing it.
