### ISSUE TITLE
Error when executing script. OkClick method through reflection is not allowed

### ISSUE THREAD

**Issue by Beatusvir** [SitecorePowerShell/Console#1308]
### Expected Behavior

Expecting script to run

### Actual Behavior

Error message shown when clicking Ok on the Elevate Session State modal.
```
Calling Cognifide.PowerShell.Client.Applications.PowerShellSessionElevation.OkClick method through reflection is not allowed
```

### Steps to Reproduce the Problem

Click Execute Button, type username and password (default user password)
Powershell Extensions 5.1
Sitecore 9.2

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [X] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
I don't recall seeing this error before. If you are able to upgrade to the latest version and then subsequently reproduce the issue then we may be able to identify a solution. The upgrade involves the `Cognifide` files being replaced with `Spe` files.

**Comment by Beatusvir** [comment]
@michaellwest thanks for you reply, I tried updating but it failed.
But afterwards digging into this it turned out to be this [hotfix](https://support.sitecore.com/kb?id=kb_article_view&sysparm_article=KB1003018) that broke executing scripts. No idea why yet. We reverted the hotfix

**Comment by michaellwest** [comment]
Do you think the change to the user dialog is going to break things in SPE?

**Comment by Beatusvir** [comment]
Honestly it looks like, because the error comes up as soon as you click the button after entering credentials, is like the OnClick event handler is just breaking things. I tried restarting IIS and then the server (thanks god it was just a test server), but same behavior. Hotfix reverted and it worked immediately.

**Comment by michaellwest** [comment]
Related article https://www.sitecoregabe.com/2023/06/security-bulletin-sc2023-003-587441-spe.html
