### ISSUE TITLE
AccessDeniedException Calling Spe.Client.Applications.UploadFile.PowerShellUploadFileForm.CancelClick or OKClick

### ISSUE THREAD

**Issue by Rhaguen** [SitecorePowerShell/Console#1309]
Using Sitecore Power Shell 6.4 on a Sitecore 9.1 instance.

### Expected Behavior

Expect script to upload a file trough Receive-File

### Actual Behavior
Get an exception:

`[AccessDeniedException: Calling Spe.Client.Applications.UploadFile.PowerShellUploadFileForm.CancelClick method through reflection is not allowed.]
   Sitecore.Reflection.MethodFilter.Filter(MethodInfo method) +1166
   Sitecore.Shell.Framework.Commands.CommandManager.GetMethodCommand(String command) +701
   Sitecore.Web.UI.Sheer.ClientPage.Dispatch(String command) +35
   Sitecore.Web.UI.Sheer.ClientPage.RaiseEvent() +124
   Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e) +806
   System.Web.UI.Control.PreRenderRecursiveInternal() +200
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

### Steps to Reproduce the Problem

- [Security Bulletin SC2023-003-587441](https://support.sitecore.com/kb?id=kb_article_view&sysparm_article=KB1003018) path must be installed.
- Click on either Ok or Cancel buttons from the Receive-File modal window throws the exception. Regardless of having or not a file selected.

### Potential fix tried
As highlighted by the Security Bulleting page, tried to path exceptions for the mentioned methods on Sitecore.Reflection.Filtering.config.  
I tried #1, then #2 and then #3. Finally all toguether, just to be sure.
Problem still persists.

![2023-07-13_10h02_48](https://github.com/SitecorePowerShell/Console/assets/3513230/bb81333d-ae88-4877-bda3-1b9d6062157c)

Could it be a know issue? Thanks in advance of any advice.

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
https://sitecore.stackexchange.com/a/35330/95 and #1308 outline steps to address.

**Comment by Rhaguen** [comment]
Thanks for the quick response, Michaell.
Unfortunately patching allowedMethods exceptions, as described on my original question, gave no positive feedback.

`<descriptor type="Spe.Client.Applications.UploadFile.PowerShellUploadFileForm" methodName="OKClick" assemblyName="Spe" hint="Ok"/>
<descriptor type="Spe.Client.Applications.UploadFile.PowerShellUploadFileForm" methodName="CancelClick " assemblyName="Spe" hint="Cancel"/>`

 Also, I'm already running the latest version of Sitecore Power Shell.

**Comment by michaellwest** [comment]
For clarification, the reflection filtering was something Sitecore added without directly involving the SPE. The inner workings of how it prevents methods from running is a bit of a mystery.

**Comment by AdamNaj** [comment]
This should be addressed in commit 545fd9afd872ca2ecb89cc1ac853fb5eaf63a7cc provided as part of #1241
