### ISSUE TITLE
Unlock-Item

### ISSUE THREAD

**Issue by Cbauwens** [SitecorePowerShell/Console#1313]
### Expected Behavior

_Please describe the expected behavior._

### Actual Behavior

_Please describe the actual behavior._

### Steps to Reproduce the Problem

_Please include the version number of SPE and Sitecore._

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by Cbauwens** [comment]
Hi,

I noticed that when running the 'Elevated Unlock' the actual 'Unlock-Item' command (/sitecore/system/Modules/PowerShell/Script Library/SPE/Tools/Security Management/Development/Unlock Item) is always executed in the "en" language and not in the content language of the item on that moment.

I was able to fix it by replacing "Get-Item -Path "." | Unlock-Item" with "Get-Item -Path "." -Language $SitecoreContextItem.Language.Name | Unlock-Item"

**Comment by michaellwest** [comment]
Does it work as expected if you did this?

`$SitecoreContextItem | Unlock-Item`

**Comment by Cbauwens** [comment]
yes, using "$SitecoreContextItem | Unlock-Item" also works fine. 
Might be even better because you don't need to retrieve the item again via the "Get-Item" command ?

**Comment by michaellwest** [comment]
Great. Thank you for confirming.

**Comment by AdamNaj** [comment]
Fixed as part of #1226
