### ISSUE TITLE
Executing Publish-Item against Experence Edge throws an error

### ISSUE THREAD

**Issue by RAhnemann** [SitecorePowerShell/Console#1314]
### Expected Behavior

Item is published to Experience Edge

### Actual Behavior

"Publish-Item : Object reference not set to an instance of an object" message is thrown.

### Steps to Reproduce the Problem

If your publishing db is named "experienceedge", run:

_Publish-Item -Path "Path_to_item" -Target "experienceedge"_

It will show the error. If you change your Target to "web" it will work as expected.

### Versions
Sitecore PowerShell Extensions 6.4.0.22430
Sitecore 10.3
Sitecore Edge Connector 21.x

*note, if you 

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [x] Asked questions on the Sitecore Slack Chat channel.
 
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by RAhnemann** [comment]
![image](https://github.com/SitecorePowerShell/Console/assets/36105511/8423665a-eaa5-4313-8089-def914c57b01)

**Comment by alan-null** [comment]
@RAhnemann It will be solved in **Edge Connector**, reported issue for them, id: `597269`

In case you have to hotfix your **onPrem** instance it could be fixed in SPE with these lines:
![image](https://github.com/SitecorePowerShell/Console/assets/6848691/36206624-7cc5-4ba6-9127-6c128edc4f5e)
 
CC: @michaellwest

**Comment by michaellwest** [comment]
Workaround blogged here https://rockpapersitecore.com/2023/09/using-powershell-to-publish-to-experience-edge/

```powershell
$pItem = Get-Item -Path "master:/sitecore/media library/Project/Tenant/Client/Sitemaps/sitemap"​
$db = Get-Database "experienceedge"​
$lang = [Sitecore.Globalization.Language]::Parse("en")​
[Sitecore.Publishing.PublishManager]::PublishItem($pItem, $db, $lang, $false, $false)
```
