### ISSUE TITLE
'System.Management.Automation.dll' reference

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#1320]
I think we should do something with this reference
https://github.com/SitecorePowerShell/Console/blob/bf1845085098e8c5977a6f19637155511a77c588/src/Spe/Spe.csproj#L142-L145

[nuget](https://www.nuget.org/packages/System.Management.Automation.dll/)

![image](https://github.com/SitecorePowerShell/Console/assets/6848691/ae617c3a-1f73-48ac-a513-9f54442adf53)

**Comment by AdamNaj** [comment]
Resolved.

**Comment by AdamNaj** [comment]
Useful: https://devblogs.microsoft.com/powershell/depending-on-the-right-powershell-nuget-package-in-your-net-project/
