### ISSUE TITLE
Reports - Find Audit Trail from logs

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#1321]
I think this line 
https://github.com/SitecorePowerShell/Console/blob/bf1845085098e8c5977a6f19637155511a77c588/unicorn/SPE/Scripts/SPE/SPE/Tools/Security%20Management/Reports/Security%20Audit/Find%20Audit%20Trail%20from%20logs.yml#L51

should use: `LastWriteTime` instead of `LastAccessTime` 

we use it for sorting but for unknown reason the other one is used to formating dates.

**UPDATE 2024-04:**
Logs are no longer stored on a disk, now, they're pushed to Azure Blob storage.
If we want to keep features depending on the disk-based logs relevant we have to update.

Haven't tied it yet but this might be good starting point
```powershell
$factory = [Sitecore.XmCloud.BlobStorageLogging.Factories.BlobContainerClientFactory]::new()
$client = $factory.CreateClient
```

**Comment by AdamNaj** [comment]
Unfortunately, We don't have access to the XM Cloud environment so we cannot implement this.
