### ISSUE TITLE
Package creation with -recurse childitems

### ISSUE THREAD

**Issue by PunjabSoftSolution** [SitecorePowerShell/Console#1323]
Expected Behavior
Package size should remain same with -recurse keyword.

Please describe the expected behavior.
When creating a package with Get-ChildItem -Path "master:/content/home", the package is created as expected. However, when using the -Recurse keyword, the package size doubles. Upon opening the package to investigate the difference, I observed that each folder item appears twice. Please investigate this issue. Thank you in advance.

Get-ChildItem -Path "master:/content/home" - This command works as expected.

Get-ChildItem -Path "master:/content/home" -Recurse - This command increases the package size to double. For example, if the package size is 1 MB with the top query, using this query results in a package size of 2 MB because it adds the same item twice in the folder.

Sitecore version 10.3 and SPE version 6.4.

**Comment by michaellwest** [comment]
Can you provide a functioning script to reproduce the issue that works with the default home item? Perhaps a package with the test content too.

**Comment by AdamNaj** [comment]
Those cmdlets are a thin coat over Sitecore APIs.
Closing as this seems like a problem with a clear workaround and a wrong usage of existing functionality rather than a bug + lack of reported response makes it unlikely that we will deal with it.
