### ISSUE TITLE
In Sitecore we could'nt able to unlock the item other than English version if we have global content manager role 

### ISSUE THREAD

**Issue by leenaa08** [SitecorePowerShell/Console#1325]
### Expected Behavior

we have created a new role (global content manager) which will have all access like the admin user, only condition is user need to lock and edit the item, it will create a new version and user needs to edit in that version which will come under his/her name, users should be able to unlock item which is locked by some other user.

### Actual Behavior
Expect English version user is unable to unlock and edit the other language versions, 
users are getting option to unlock and edit in English language but for other language versions unlock and edit option is disabled, instead it is showing the message "this item is locked by the other user."

### Steps to Reproduce the Problem

_Please include the version number of SPE and Sitecore._ 
  
 Version of Sitecore - 10 

Create a two user with the same role assigned (Global content manager)
1. unlock and edit an item through the login of user 1 
2.  try to login to the other user 
3.  then try to unlock and edit in the other version apart from English for the same item.
   Please check the screenshot attached for reference

<img width="886" alt="sitecore 2" src="https://github.com/SitecorePowerShell/Console/assets/90045446/60dad810-6871-4eee-ad39-51c4993cb206">
<img width="863" alt="sitecore 1" src="https://github.com/SitecorePowerShell/Console/assets/90045446/345f6fe9-0fb9-4374-bfb3-daf5480dddb0">

**Comment by mrvinaykj** [comment]
@leenaa08, This issue is not related to SPE.

**Comment by leenaa08** [comment]
@mrvinaykj  , we have checked with Sitecore team as well , they have mentioned the following commands , please check below

**Reply from Sitecore** : I have reviewed the behaviour of the unlocking process with the SPE tool called "Elevated Unlock" enabled. I was able to unlock the english item as you described, where as I was not able to before allowing that functionality.  

This behaviour comes from the  Sitecore PowerShell Extensions module (https://doc.sitecorepowershell.com/),and changes the expected locking/unlocking behaviour (https://doc.sitecore.com/xp/en/users/102/sitecore-experience-platform/lock-and-unlock-an-item.html).The Sitecore Powershell Extensions is not developed or supported by Sitecore. Our recommendation is to submit an issue to the SPE team: https://github.com/SitecorePowerShell/Console/issues, as bugs/issues like this would be addressed by the module community or contributors.

Please look into this issue

**Comment by AdamNaj** [comment]
This should be addressed by #1226.
