### ISSUE TITLE
It is not possible to search for scripts in the "Open" dropdown in ISE.

### ISSUE THREAD

**Issue by adam-najmanowicz-wttech** [SitecorePowerShell/Console#1326]
### Expected Behavior

When I search in the "Open" dropdown in ISE. I expect to find scripts in whichever Script library they are in the system.
![image](https://github.com/SitecorePowerShell/Console/assets/137067829/d744ca5b-47fa-4538-9f7a-2282a5400348)

### Actual Behavior

When entering search phrase the result list is always empty.

### Steps to Reproduce the Problem

Latest... and quite a few behind.

Will provide a PR fixing it in a moment.

**Comment by AdamNaj** [comment]
Oops... committed directly... will try to go through a feature branch next time.
