### ISSUE TITLE
NullReferenceException occurs when trying to accept VersionAddedNotification via PowerShell in Sitecore

### ISSUE THREAD

**Issue by mrvinaykj** [SitecorePowerShell/Console#1331]
### Expected Behavior

No exceptions should occur when accepting VersionAddedNotification via PowerShell in Sitecore.

### Actual Behavior

NullReferenceException occurs when trying to accept VersionAddedNotification via PowerShell in Sitecore.
It happens for cloned items after creating a new numbered version for its master item.

### Steps to Reproduce the Problem

Steps to reproduce:
1. Create a master item - /sitecore/content/Home/Sample Item
2. Clone master item - /sitecore/content/Home/Clones/Sample Item
3. Add a numbered version for the master item
4. Run the below PS script

```
$item = (Get-Item -Path "/sitecore/content/Home/Clones/Sample Item" -Language "en")
Write-Host $item.Uri
Write-Host "------------------------------"

$notifications = Get-ItemCloneNotification -Item $item

$notifications | % { Write-Host $_.Type $_.VersionUri}

foreach ($notification in $notifications)
{
if ($notification -ne $null)
{
if ($notification.Type -eq "VersionAddedNotification" `
-and $notification.Type -ne "FirstVersionAddedNotification")
{
Write-Host $notification.ItemUri

Receive-ItemCloneNotification -Notification $notification -Action Accept
}
}
}
```

Debugging the source code, we detected the exception occurs in VersionAddedNotification.Accept method
when trying to invoke this.SendMessage - see attached pictures
- 1_VersionAddedNotification.Accept.jpg
![1_VersionAddedNotification Accept](https://github.com/SitecorePowerShell/Console/assets/20638067/f1b91cf5-ac66-47a8-a8c0-139951d86953)
- 2_VersionAddedNotification.SendMessage.jpg
![2_VersionAddedNotification SendMessage](https://github.com/SitecorePowerShell/Console/assets/20638067/e7712156-0628-4632-bb86-9191efe99112)
- 3_ClientPage.jpg
![3_ClientPage](https://github.com/SitecorePowerShell/Console/assets/20638067/7fcb4d60-42e2-4aa2-ae3f-b9b535453f9d)

The reason for the issue is `HttpContext.Current` is null.

It is reproduced not steadily - after several attempts, it could be successfully accepted.
But, each failed attempt adds a new version for the cloned item.

**Comment by AdamNaj** [comment]
This one should be fixed but I have a feeling it's a lost cause... I don't think the notification for Field approval is going to be so easy to handle. unless we start taking over some of the "Accept" code. in some of the notifications.
