### ISSUE TITLE
Sitecore 10.4

### ISSUE THREAD

**Issue by justin-dx** [SitecorePowerShell/Console#1338]
Are there development efforts towards supporting the latest version (10.4) from Sitecore? If so, are you able to provide an **E**TA?
https://doc.sitecorepowershell.com/appendix

**Comment by AdamNaj** [comment]
The [recently released version 7.0](https://github.com/SitecorePowerShell/Console/releases/tag/7.0) supports 10.4.
It is also being [distributed by Sitecore together with SXA 10.4](https://developers.sitecore.com/downloads/Sitecore_Experience_Accelerator/10x/Sitecore_Experience_Accelerator_1040)

**Comment by justin-dx** [comment]
awesome, thanks for the fast reply

**Comment by michaellwest** [comment]
@AdamNaj The book builds automagically upon commits. I just checked and 10.4 is now included in the appendix.

**Comment by AdamNaj** [comment]
Sweet! That's great that it does that!
