### ISSUE TITLE
Sitecore Powershell Script Elevated Unlock button is unlocking only English pages, for non-English Pages just showing running script but not unlocking items

### ISSUE THREAD

**Issue by vikashmahala092** [SitecorePowerShell/Console#1339]
### Expected Behavior - When clicking on Elevated Unlock button it should unlock the item if item is non-english version

_Please describe the expected behavior._

### Actual Behavior - Showing message like running script but not unlocking non-english items, working fine for english pages.

_Please describe the actual behavior._

### Steps to Reproduce the Problem - One colleague can lock any item which is non-english version and other colleague can try to unlock it. 

_Please include the version number of SPE and Sitecore._ 

Sitecore PowerShell Extensions 6.4.0.16859
Sitecore 10.3
Windows PowerShell 5.1

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by AdamNaj** [comment]
Fixed in #1226,
Other duplicates or similar: #1313, #1325

Will be fully fixed in 8.0, until then, feel free to take the changes in the commit - should be in scripts only I think.
