### ISSUE TITLE
DoubleClick on item in ListView does not run default action as intended but instead throws an error.

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#1341]
### Expected Behavior

Doubleclick on an item in ListView should run default (first) action for that item.

### Actual Behavior

![image](https://github.com/SitecorePowerShell/Console/assets/1209953/976f28d2-d467-479c-a631-e93786859b38)

This is introduced by a Sitecore security measure introduced a few versions ago.

**Comment by michaellwest** [comment]
This issue is addressed through a Sitecore hotfix.

**Comment by AdamNaj** [comment]
Fixed.

**Comment by AdamNaj** [comment]
Right... but don't we want to fix it in SPE ootb?
