### ISSUE TITLE
New Show-ItemLister command

### ISSUE THREAD

**Issue by scjunkie** [SitecorePowerShell/Console#217]
Show-ItemLister

This would launch a Sitecore.Shell.Applications.Dialogs.ItemLister dialog. An example of this can be found at http://sitecorejunkie.com/2013/10/24/insert-a-new-item-after-a-sibling-item-in-sitecore/. Look for "ItemListerOptions itemListerOptions".

**Comment by AdamNaj** [comment]
While I think this can be useful in some scenarios I think the scope of it would be very narrow. I hope you don't mind that I close the issue for now (backlog cleanup). If you want to provide an implementation for it, feel free to re-open it.
