### ISSUE TITLE
Commands to manage Item Security

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#227]
Commands such as:
Get-ItemSecurity
Set-ItemSecurity

**Comment by michaellwest** [comment]
The idea here was to use the AccessRules on the item Security property. An example found here:
https://briancaos.wordpress.com/2009/10/02/assigning-security-to-items-in-sitecore-6-programatically/

**Comment by michaellwest** [comment]
@Adamnaj added commands similar to Get-Acl.

**Comment by AdamNaj** [comment]
Merged by implementing Issue #350
