### ISSUE TITLE
Add save settings button for ISE

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#250]
Using Ctrl-, you can modify the Ace settings for the session. Add a command to save those settings for the user and reload when a new ISE is opened.

![image](https://cloud.githubusercontent.com/assets/933163/4965112/56c58456-6743-11e4-81fb-4e783ba0f0a4.png)

**Comment by AdamNaj** [comment]
is it not needed any longer? Mikey - feel free to close if that's the case.

**Comment by michaellwest** [comment]
Implemented with Issue #252.

**Comment by AdamNaj** [comment]
Duplicate
