### ISSUE TITLE
Installation of Packages over HTTP Like Sitecore.Ship

### ISSUE THREAD

**Issue by scjunkie** [SitecorePowerShell/Console#265]
I'm wondering if it would be useful to install Sitecore packages over HTTP as is done in Sitecore.Ship: https://github.com/kevinobee/Sitecore.Ship

**Comment by AdamNaj** [comment]
You can already do this.
Using [Built in Remoting](http://blog.najmanowicz.com/2014/10/10/sitecore-powershell-extensions-remoting/) you can upload package to the server and then run a script to install it.

Please give the blog a read - If this solves the problem - feel free to close the issue or maybe blog about it? ;)

What couldn't be achieved? What Sitecore.Ship does better?

**Comment by AdamNaj** [comment]
After talking to @scjunkie - decided to close this. The functionality is achievable using current functionality.
