### ISSUE TITLE
GetBrokenLinks Method throw Error

### ISSUE THREAD

**Issue by NDurham12** [SitecorePowerShell/Console#271]
Running method GetBrokenLinks throws this error: 

$prodDB = [Sitecore.Data.Database]::GetDatabase("master")
$linkDB = [Sitecore.Globals]::LinkDatabase
$BrokenLinks = $linksDB.GetBrokenLinks($prodDB)

writeErrorStream      : True
Exception             : System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : InvokeMethodOnNull
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 4
PipelineIterationInfo : {}
PSMessageDetails      :

![image](https://cloud.githubusercontent.com/assets/5875789/5764650/75d2d8a2-9cb9-11e4-8966-73ae459569fe.png)

**Comment by AdamNaj** [comment]
$prodDB = [Sitecore.Data.Database]::GetDatabase("master")
$linkDB = [Sitecore.Globals]::LinkDatabase
$BrokenLinks = $link**s**DB.GetBrokenLinks($prodDB)

I think it's because of the typo in the variable name as highlighted above

**Comment by NDurham12** [comment]
D'oh. But very happy it's just a typo. Work around required too much logic.



<div>-------- Original message --------</div><div>From: Adam Najmanowicz <notifications@github.com> </div><div>Date:01/15/2015  5:12 PM  (GMT-06:00) </div><div>To: SitecorePowerShell/Console <Console@noreply.github.com> </div><div>Cc: Nona Durham <MrsNonaDurham@gmail.com> </div><div>Subject: Re: [Console] GetBrokenLinks Method throw Error (#271) </div><div>
</div>$prodDB = [Sitecore.Data.Database]::GetDatabase("master")
$linkDB = [Sitecore.Globals]::LinkDatabase
$BrokenLinks = $linksDB.GetBrokenLinks($prodDB)

I think it's because of the typo in the variable name as highlighted above

**Comment by AdamNaj** [comment]
I guess we can close it for now :)
