### ISSUE TITLE
Modules should rebuild integrations when enabled or disabled

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#277]
Can we make this an automatic feature?

**Comment by AdamNaj** [comment]
Integrations that need rebuilding require the user to press the rebuild button in ISE. I'm a bit weary of running those scripts automatically.

**Comment by michaellwest** [comment]
Some ideas for discussion:
1. Can we have a more convenient way to run it? Maybe context menu.
2. Can the integration builder analyze the module to make minimal changes?

**Comment by AdamNaj** [comment]
That makes sense but can easily explode into a much bigger task.
- What happens when I create a new script? Should it get added automatically?
- What about Name change? Instant rebuild as well?

**Comment by michaellwest** [comment]
Perhaps adding a Context Menu option to Enable/Disable the module and to
Rebuild Integrations would suffice.

**Comment by michaellwest** [comment]
It's not enough of a pain to be necessary.
