### ISSUE TITLE
Different icon for non-integration point script libraries

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#283]
@AdamNaj Can you create an icon for libraries that are not considered part of integration points? Might help with the differentiation of script libraries that have an affect on other parts of Sitecore.

**Comment by AdamNaj** [comment]
I think we'll pass on that. How would a different template be set? Integration point libraries are just the same as regular libraries we just differentiate those by name and I'm not convinced we should be doing it automatically using hooking to events.
