### ISSUE TITLE
Ability to find items using Sitecore Content Search API

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#284]
Find-Item commandlet with the following syntax:

```powershell
Find-Item [-Index] <string> [-Criteria <SearchCriteria[]>] [-Where <string>] [-WhereValues <Object[]>] [-OrderBy <string>] [-First <int>] [-Skip <int>]
```
Parameters:
```-Index``` - index name - ISE supports index name autocompletion
```-Where``` - Dynamic Linq syntax as specified in [this blog](http://weblogs.asp.net/scottgu/dynamic-linq-part-1-using-the-linq-dynamic-query-library)
```-WhereValues``` - array of objects for Dynamic Linq ```-Where``` parameter.
```-OrderBy``` - Dynamic Linq syntax ordering parameter
```-First``` - number of results to return
```-Skip``` - number of results to skip before returning the rest of results.
```-Criteria``` - simple search criteria in the following example form:
```powershell
@{
        Filter = "Equals"
        Field = "_templatename"
        Value = "PowerShell Script"
    }, 
@{
        Filter = "StartsWith"
        Field = "_fullpath"
        Value = "/sitecore/system/Modules/PowerShell/Script Library/System Maintenance"
    }
```
Where "Filter" is one of the following values:
- Equals
- StartsWith,
- Contains,
- EndsWith

Examples: https://gist.github.com/AdamNaj/273458beb3f2b179a0b6

**Comment by AdamNaj** [comment]
Implemented & documented.

**Comment by michaellwest** [comment]
Adam,
Very nice work. I look forward to trying this out.
