### ISSUE TITLE
Create a Rules Based Report Creator

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#293]
Question was sent to @AdamNaj related to writing reports without being able to see all of the Sitecore content. An idea I had was could we use rules and other query mechanisms to help generated reports without the user having to write any PowerShell, but all of this behavior is PowerShell driven?

**Comment by AdamNaj** [comment]
What a report creator would have to ask you for would be:

1) Root for the report.
2) Checkbox process immediate or recursive children?
3) Checkbox include root?
4) give you the ability to specify rules
5) provide with the list of all fields for every item template beneath and allow you to pick those that you want to display. 

What we would need to add is a ```Test-Rule``` Cmdlet that would accept the ```Sitecore-rules-xml``` and ```-Item``` to run the rules against.
This is very much doable but my concern is with the performance of such solution, The rules set would have to be run for every item in the pipeline - likely slower than ```gci . -Recurse | Where-Object { ... }``` but I might be wrong there

**Comment by michaellwest** [comment]
1-3 is pretty straightforward and we have an example of where this can be done.
4 rules is a new area for me.
5 sounds straightforward. scan all the items, show the fields, then select what you need.that could be slow.

would we create a new script library report item where the user configures all this and then when they choose and run a report we extract those settings from the sitecore item or instead request from the user each time?

**Comment by AdamNaj** [comment]
Implemented - verified to work on Sitecore 7. No report saving yet - that's postponed till 3.2
