### ISSUE TITLE
Improve the behaviour and look & feel of $Host.UI.PromptForChoice

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#295]
The dialog is shown when Script needs to ask user for choice when e.g. Debug event happens or when running e.g. ```Remove-Item``` with the ```-Confirm``` parameter.

The dialog should looks natively on Sitecore 8 and show the proper dialog title.

Sample script
```powershell
New-Item -Path master:\content\home -ItemType "Common/Folder" -Name Test | Remove-Item  -Confirm
```
![image](https://cloud.githubusercontent.com/assets/1209953/6314094/e3082b7a-b9ce-11e4-8567-ffb59ba1ce59.png)

**Comment by AdamNaj** [comment]
Improved

**Comment by michaellwest** [comment]
When test in the ISE using the following DialogHeader is null.

Write-Debug "Test message" -Debug

**Comment by michaellwest** [comment]
Also, when running in the console it just hangs.

**Comment by AdamNaj** [comment]
Have you copied the ConfirmChoice.xml from SPE\sitecore modules\Shell\Powershell the matching website folder? If not, that would explain the null, the other control is still unused - let's say it's ***reserved for future use***.

The dialog works for me identically as it does in Windows PowerShell ISE for the script you provided.

```powershell
Write-Debug "Test message" -Debug
```
produces the following in Sitecore PowerShell Extensions:
![image](https://cloud.githubusercontent.com/assets/1209953/6316312/8f918f78-ba22-11e4-9c7d-cf259ac25a0f.png)

And that's the product of running the same command in Windows PowerShell ISE:
![image](https://cloud.githubusercontent.com/assets/1209953/6316314/b51af8b0-ba22-11e4-8d86-027c27870523.png)

As to running it in Sitecore Commandline window... I agree it's lacking in interactions - any question asking or window showing commandlets will fail in it.

**Comment by michaellwest** [comment]
After a successful build I verified the new XML file was copied over. Next
week I'll take another look and Skype if we need to.

**Comment by AdamNaj** [comment]
The following is handled by issue #298 

> Also, when running in the console it just hangs.

Closing for now if needed please reopen

**Comment by michaellwest** [comment]
Works as expected. Thank you @AdamNaj .
