### ISSUE TITLE
Copy-Item should allow to copy items between databases

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#301]
The following should be possible:
```powershell
Copy-Item master:\content\Home\accelerators web:\content\
```

Additionally transfer should allow to specify the following ```-TransferOptions``` when item is being copied from one db to another::
- ```-AllowDefaultValues``` - default values should be database relative - only works on Sitecore 7.2+
- ```-AllowStandardValues``` default values should be database relative - only works on Sitecore 7.2+
- ```-ChangeId``` - when transfering the item the created item should have new ID. This means that copied item will not overwrite existing item if it was transfered before.

**Comment by michaellwest** [comment]
Sounds interesting.

**Comment by AdamNaj** [comment]
Done
