### ISSUE TITLE
Ability to configure Console folder name/path

### ISSUE THREAD

**Issue by akshaysura** [SitecorePowerShell/Console#304]
Ability to either configure foldername or path of the Sitecore Powershell console.

A quick solution is to change the folder name in the install itself to Powershell Console.

**Comment by AdamNaj** [comment]
Hi Akshay,

Not 100% sure what do you understand by "path of the Sitecore Powershell". You mean you want to customize where the scripts are located? If that is the case this is more complicated than changing the location of the items or files. There are dependencies on those locations inside the code. Could you elaborate on what you want to achieve by the change?

**Comment by akshaysura** [comment]
Location of the physical Console folder. Its conflicting with Insite
Console folder.

May be we could change it to be more specific like website\powershell
consol instead of website\console

On Mon, Feb 23, 2015 at 11:56 AM, Adam Najmanowicz <notifications@github.com

**Comment by AdamNaj** [comment]
This is changing in 3.0 which will be released soon.
Those files will be in ```/sitecore modules/PowerShell/Console/``` and ```/sitecore modules/Shell/PowerShell/```

**Comment by akshaysura** [comment]
oh thats great!

**Comment by AdamNaj** [comment]
Feel free to close the issue if this solves your problem :)
Was that the idea you were referring to on LinkedIn?

**Comment by akshaysura** [comment]
yes Sir!

**Comment by AdamNaj** [comment]
Thanks Akshay! And thanks for using the module :)
