### ISSUE TITLE
Space at the beginning of Invoke-SitecoreScript response

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#305]
Hello,

I've noticed that **Invoke-SitecoreScript** returns unexpected results.

**How to reproduce:**
-Invoke some script:
```
    $names = "sitecore_core_index"
	$JobHandle = Invoke-SitecoreScript {[Sitecore.ContentSearch.Maintenance.IndexCustodian]::RunIndexUpdateJobs($Params["Names"])} @{Names = $names}
```
-Display deserialized content as string

**Actual result:**
Returned string has space at the beginning. 

**Expected result:**
Invoke-SitecoreScript returns pristine object without additional spaces.

**Comment by AdamNaj** [comment]
Fixed. Thanks for the detailed report and for the pair programming to fix the issue @alan-null ;)

**Comment by alan-null** [comment]
Thanks Adam for your support ;)
