### ISSUE TITLE
Add -Confirm and -WhatIf parameters support to all our commandlets that modify any Sitecore data

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#308]
The idea is explained here: http://www.computerperformance.co.uk/powershell/powershell_whatif_confirm.htm

Sample script testing the platform commandlets:
https://gist.github.com/AdamNaj/f37bd5c714992b976cb9

So it should now be possible to perform dry runs on scripts.

**Comment by AdamNaj** [comment]
Implemented... what a chore!

**Comment by michaellwest** [comment]
Great job Adam!
