### ISSUE TITLE
Document minimal package & configuration needed

### ISSUE THREAD

**Issue by dufkaf** [SitecorePowerShell/Console#311]
While this extension is great it seem to be rather extensive and scary. There are lot of (example?) items in the tree, lot of events/pipelines hooked in config file. Is it possible to create minimal package with as few items as possible or at least describe what items/config lines can be safely deleted?

Current package is great for developer workstations to play but is is a bit scary to install it to production servers.

**Comment by AdamNaj** [comment]
Agreed, the hardening of the console is something that is very much on our minds.
In 3.0 you can already do much to achieve this like:
- Disable services you do not need to use (Issue #289)
- Breaking the library into functional modules and having the ability to disable modules you don't use/need (Issue #253)
- Ability to switch the work database to a different one to be able to use SPE on environments that don't have the ```master``` database (Issue #247)

Other than the Platform module (which is used by ISE and other sheer integrations like Show-ListView) I would say it's fairly safe to delete the other modules that you don't want to use.

I suspect a proper hardening guild would be useful. We've discussed writing a book about SPE - mostly out of our blogs - this sounds like a section that would be a very desirable should this book be put together. I'll see if I can transfer this into a mega blog-post of sorts.

**Comment by michaellwest** [comment]
So we finally started the book. No hardening section yet. 

http://michaellwest.gitbooks.io/sitecore-powershell-extensions/

**Comment by michaellwest** [comment]
Added a section for securing the services. Lists what is needed for a minimal service too.

**Comment by michaellwest** [comment]
Need to build package for the CD environment.

**Comment by AdamNaj** [comment]
@michaellwest provided a great write up on what needs to be done for a [minimal setup needed if you Need SPE for remote automation](http://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/content/security.html). 

Scroll to the bottom of the page for the "Minimal Web Service Configuration" section to learn how to configure SPE in a minimal configuration for production with remote automation.

Closing this issue as it delivers on the main requirement.
