### ISSUE TITLE
remote sitecore powershell console/ISE 

### ISSUE THREAD

**Issue by dufkaf** [SitecorePowerShell/Console#312]
Is it possible to run powershell console/ISE Sheer UI in my local sitecore installation but connect it to service (\sitecore modules\PowerShell\Services\PowerShellWebService.asmx) on remote sitecore?

This could be especially useful for content delivery instances where we don't have sitecore UI installed (our /sitecore folder is almost empty there).

**Comment by AdamNaj** [comment]
Wow! That is an absolutely fantastic idea!
I'm not sure about the viability of ISE (this doesn't go through a web service) but Console could definitely be fairly easily modified to deliver this functionality!

@michaellwest - I think this idea is definitely t-shirt worthy! :)

**Comment by michaellwest** [comment]
Fantastic. Maybe something like Invoke-Command and Enter-PSSession.

**Comment by dufkaf** [comment]
I am glad you like the idea and I hope it will be as easy as it looks :-)

I needed to troubleshoot some issue on content delivery without SPE or sitecore UI installed and I managed to get your RemoteAutomation web service running just by copying the 2.8 dll, the asmx file and adding minimal config file with database  set to web. Then I could run single line script blocks remotely which was great and solved my issue. However it was not very user friendly  and also the remote automation creates new session for each command which is not ideal too. Full console would be much easier for troubleshooting.

I was thinking about asking for server name first and opening the console directly to remote server but something like Enter-SPESession that would switch between different servers in existing console is great idea too and may be even easier to implement? 

Something line invoke-command (that would call existing RemoteAautomation.asmx service in single call?) would be good too.

**Comment by AdamNaj** [comment]
More good ideas, however some of it is already achievable... have you looked at my [Remoting blog](http://blog.najmanowicz.com/2014/10/10/sitecore-powershell-extensions-remoting/)?

**Comment by dufkaf** [comment]
Yes, I followed that blog post and that is what I did more or less, only in normal windows powershell console. However as explained the remote automation service does not keep session sou you cannot define variables on remote end and Invoke-SitecoreScript does data serialization back and forth with each call.  Also the full interactivity, tab completion and command history is something else than trying to type correct scriptblock into each "Invoke-SitecoreScript –Command { ... }    -Params @{ ... }" call :-)

**Comment by michaellwest** [comment]
@dufkaf Can you send me the files you used to get the minimal install of the service working? List of steps too? I'll put that in our book. Based on that I'll see if I can make it easier for future SPE deployments.

**Comment by michaellwest** [comment]
This is currently what I am able to achieve.

#### Example: Local SPE to Remote SPE
1. Install SPE on local SC instance.
2. Install SPE on remote SC instance.
3. Run the following from local to remote:

```powershell
# Import functions
Import-Function -Name New-ScriptSession
Import-Function -Name Invoke-RemoteScript

$session = New-ScriptSession -Username "admin" -Password "b" -ConnectionUri "http://remotespe/sitecore%20modules/PowerShell/Services/RemoteAutomation.asmx"

$script1 = {
    [Sitecore.Security.Accounts.User]$user = Get-User -Identity admin
}

$script2 = {
    $user
    $params.date.ToString()
}

$args = @{
    "date" = [datetime]::Now
}

Invoke-RemoteScript -ScriptBlock $script1 -Session $session -ArgumentList $args
Invoke-RemoteScript -ScriptBlock $script2 -Session $session

Name                     Domain       IsAdministrator IsAuthenticated
----                     ------       --------------- ---------------
sitecore\admin           sitecore     True            False
4/24/2015 12:08:29 PM
```

#### Example: Local Windows PowerShell ISE to Remote SPE
1. Install SPE on remote SC instance
2. Install SPE module into `C:\Users\Michael\Documents\WindowsPowerShell\Modules\SPE`
3. Run the following local Windows PowerShell ISE to remote:

```powershell
# Import module
Import-Module -Name SPE

$session = New-ScriptSession -Username "admin" -Password "b" -ConnectionUri "http://remotespe/sitecore%20modules/PowerShell/Services/RemoteAutomation.asmx"

$script1 = {
    [Sitecore.Security.Accounts.User]$user = Get-User -Identity admin
}

$script2 = {
    $user
    $params.date.ToString()
}

$args = @{
    "date" = [datetime]::Now
}

Invoke-RemoteScript -ScriptBlock $script1 -Session $session -ArgumentList $args
Invoke-RemoteScript -ScriptBlock $script2 -Session $session

Name                     Domain       IsAdministrator IsAuthenticated
----                     ------       --------------- ---------------
sitecore\admin           sitecore     True            False          
4/24/2015 12:17:58 PM
```

#### Minimal SPE setup
Files:
 * C:\inetpub\wwwroot\remotespe\Website\App_Config\Include\Cognifide.PowerShell.config
 * C:\inetpub\wwwroot\remotespe\Website\bin\Cognifide.PowerShell.dll
 * C:\inetpub\wwwroot\remotespe\Website\sitecore modules\PowerShell\Services\RemoteAutomation.asmx
 * C:\inetpub\wwwroot\remotespe\Website\sitecore modules\PowerShell\Services\web.config

**Comment by michaellwest** [comment]
Moved this documentation to the Gitbook. You can remotely execute commands from CM to CD if you copy over the files as described in the minimal setup.

http://michaellwest.gitbooks.io/sitecore-powershell-extensions/
