### ISSUE TITLE
Active Commerce Module ideas

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#313]
Nick: Look for hidden products, products missing certain attributes, etc
Nick: i.e. Product data quality stuff

**Comment by michaellwest** [comment]
Hit the order API, basic order reports ($ by day, $ by time of day, revenue by product)

**Comment by AdamNaj** [comment]
I think this should be moved outside of SPE. Even if you decide to implement it, this would be released as a separate module. Let's consider closing this issue.

**Comment by michaellwest** [comment]
Created a gist for @techphoria414 that covers this effort.
