### ISSUE TITLE
Set-Location C: not working as expected

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#314]
Using the path *C:* should change to the root of C but it instead changes to *C:\windows\system32\inetsrv*

Example:
```powershell
PS master:\> Set-Location -Path C:
PS C:\windows\system32\inetsrv\>
```

Verify the behavior with the path *HKLM:*

**Comment by AdamNaj** [comment]
As far as I can tell It's working as expected. Each ```PSDrive``` has a "current location" that is being maintained. For a drive from which the process was started it will be the location of the executable.

I suspect any other drive than ```C:``` it will land in the root. but ```C:``` in this case is special as ```C:\windows\system32\inetsrv\``` is where the ```w3wp.exe``` lives.

The following wil yield the result you expected:
```powershell
Set-Location -Path C:\
```

**Comment by michaellwest** [comment]
I can see how the worker process trumps my argument. Thanks for looking into it @AdamNaj . I'll make a mention of this behavior in the gitbook.
