### ISSUE TITLE
Command startmenuaction remembers last used integration point

### ISSUE THREAD

**Issue by pkocian** [SitecorePowerShell/Console#315]
Hi,

there is a problem when defining custom toolbox using command powershell:startmenuaction in core DB. 
We have this message in a Start menu action item in /sitecore/content/Documents and settings/All users/Start menu/Right/My Toolbox:
powershell:startmenuaction(scriptDB=master,scriptPath=/sitecore/system/Modules/PowerShell/Script Library/My Toolbox,menuItemId={4B48C604-FFD8-40C1-B98B-44452B82C9AF})

The problem is, that our menu is shown only before accessing any menu using powershell:startmenuaction with integrationPoint defined. When we click on any menu using integrationPoint this is remembered and it is then always shown on commands that are not using integrationPoint.
E.g. we click on our menu My Toolbox and it is shown. Then we click on Powershell Toolbox and the toolbox is used as integration point. Next time we click on our menu we see only Powershell Toolbox menu.

Maybe it would be enough to adjust method SetupIntegrationPoint() in class ScriptLibraryMenuItem to empty this.IntegrationPoint at first or when there is no integrationPoint in the context.

Regards,
Petr

**Comment by AdamNaj** [comment]
Interesting use case. I didn't suspect Sitecore would be re-using a previously created object like that, but this very much makes sense. The fix is already pushed to the ```master``` branch. If you need it for the sitecore7 branch it should be easy to copy there.

**Comment by pkocian** [comment]
Thank you for the quick fix, now it works as expected. Tested in Sitecore 7.

**Comment by AdamNaj** [comment]
Merged by implementing Issue #350
