### ISSUE TITLE
Integration with "Insert Item from template"

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#318]
Add integration with "Insert Item from template" so that script can be run when item is created in content editor - akin to how creation of language items raises a dialog.

**Comment by michaellwest** [comment]
Sounds like a nice feature.

**Comment by AdamNaj** [comment]
Implemented as a new integration point as described in [John's blog](http://www.sitecore.net/en-gb/learn/blogs/technical-blogs/john-west-sitecore-blog/posts/2013/01/add-context-menu-entries-to-manipulate-insert-options-in-the-sitecore-aspnet-cms.aspx)

**Comment by AdamNaj** [comment]
Implemented & verified to work on SC 7
