### ISSUE TITLE
Get-ScriptSession in ISE results in exception

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#321]
ScriptSession.cs:
PSInvalidOperationException

A pipeline is already running. Concurrent SessionStateProxy method calls are not allowed.

**Comment by AdamNaj** [comment]
Can you explain how to replicate it? 
I don't seem to be able to.

**Comment by michaellwest** [comment]
Attatch the debugger.
Open ISE.
Run command Get-ScriptSession

**Comment by michaellwest** [comment]
I believe @adamnaj implemented a workaround.

**Comment by AdamNaj** [comment]
Reopening as it needs merging to 7

**Comment by AdamNaj** [comment]
Merged by implementing Issue #350
