### ISSUE TITLE
Build SPE PowerShell module for use outside of Sitecore

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#324]
Built a Windows PowerShell module that simplifies the communication with the SPE Remote Automation service. The same scripts also reside in the function library found in the Platform SPE module. This can be used as an alternative to the Remoting script in the Platform module.

**Comment by michaellwest** [comment]
Need to package up the SPE module with instructions.

**Comment by JoeOffenberg** [comment]
Hi Michael, Is this Windows Powershell SPE module available in github?

**Comment by AdamNaj** [comment]
Hi Joe,

If you're in a hurry, you can use the current approach as described here:
http://blog.najmanowicz.com/2014/10/10/sitecore-powershell-extensions-remoting/

**Comment by michaellwest** [comment]
Joe, as soon as we release version 3.1 it will be available for use. Thank
you for your interest in it. If you have some use cases I can verify that
those will be supported.

Michael

**Comment by JoeOffenberg** [comment]
Thank you.  Our use case is with CA Release Automation.  We would like to
update sitcore packagaes and Hedgehog scitem.update files as part of a
release process that includes several technologies outside of Sitecore as
well, including Oracle, Tibco, IIS, .Net..  Sitecore is proving to be the
hardest part to automate.  Your Powershell Extensions look like the best
way in.

**Comment by michaellwest** [comment]
Implemented.
