### ISSUE TITLE
Publish problem

### ISSUE THREAD

**Issue by stefcoenen** [SitecorePowerShell/Console#325]
* Sitecore 7.2 rev 150407
* PSE 3.0

After trying some things out with PSE I discovered that when I publish my entire website I get an nullpointer reference inside one of the pipelines. There might be something wrong with an item that PSE can't handle I did try various things out. A screenshot is attached and the log has the following information:

    Server Error in '/' Application.
    Object reference not set to an instance of an object.
    Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
    Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

    Source Error:

    An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

    Stack Trace:

    [NullReferenceException: Object reference not set to an instance of an object.]
    Cognifide.PowerShell.Core.Modules.ModuleManager.get_Modules() +212
    Cognifide.PowerShell.Core.Modules.ModuleManager.GetFeatureRoots(String featureName) +153
    Cognifide.PowerShell.Integrations.Pipelines.PipelineProcessor`1.Process(TPipelineArgs args) +220

    [TargetInvocationException: Exception has been thrown by the target of an invocation.]
    System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig,       Boolean constructor) +0
    System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters,  Object[] arguments) +76
    System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +211
    System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
    Sitecore.Nexus.Pipelines.NexusPipelineApi.Resume(PipelineArgs args, Pipeline pipeline) +398
    Sitecore.Pipelines.Pipeline.Start(PipelineArgs args, Boolean atomic) +366
    Sitecore.Pipelines.Pipeline.Start(String pipelineName, PipelineArgs args, Boolean atomic) +197
    Sitecore.Web.Authentication.TicketManager.Login(Ticket ticket) +182
    Sitecore.Web.Authentication.TicketManager.Relogin(String ticketId, Boolean redirect) +308
    Sitecore.Pipelines.HttpRequest.UserResolver.Process(HttpRequestArgs args) +265
    (Object , Object[] ) +83
    Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +365
    Sitecore.Nexus.Web.HttpModule.(Object , EventArgs ) +457
    System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +92
    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +165
    Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET      Version:4.0.30319.34248

![publishing_powershell](https://cloud.githubusercontent.com/assets/12295021/7534355/206d7c72-f57a-11e4-9c28-41b0d43151ba.PNG)

**Comment by AdamNaj** [comment]
Hi @stefcoenen,

Thank you for using SPE in your developer toolbox. Looking at the stack tract I can see that this is related to Issue #310 which has been fixed and will be available when we release the 3.1 version of the module (hopefully later in May).

The secret is in our SPE module monitor that dynamically rebuilds (the in memory structures for) integration points based on changes in scripts. Should you avoid publishing the ```/sitecore/system/Modules/PowerShell/Script Library``` either making it unpublishable or otherwise by preventing it in your script, you should be able to publish everything else.

**Comment by stefcoenen** [comment]
Thanks @AdamNaj,

Did found that issue, but couldn't really figure out in what way it was related. Will be eagerly awaiting release 3.1. But perfect quick-fix in the meantime.

**Comment by AdamNaj** [comment]
Merged by implementing Issue #350
