### ISSUE TITLE
Rename Send/Receive functions to not collide with cmdlets

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#328]
There exist functions that interact with Sheer UI to Send-File (Download) and Receive-File (Upload) files or images. 

Need to rename the functions added for interacting with the web services to not collide with the pre-existing names.

**Comment by michaellwest** [comment]
Renamed commands to Send-MediaItem and Receive-MediaItem. Send from the client to the server and Receive from the server to the client.

**Comment by AdamNaj** [comment]
Was that not an intra-version problem that was not exposed in any public version?
I'm removing it from 3.1 milestone as it does not seem to provide any value as a change log item.

**Comment by michaellwest** [comment]
After our discussion it made sense that sending from the server meant
download where as sending from the local machine meant upload.
