### ISSUE TITLE
404 error when calling Web API script exposed in Master database

### ISSUE THREAD

**Issue by apucilowski** [SitecorePowerShell/Console#329]
Call a script located in Master database remotely through Web API, e.g.
$webClient = New-Object Net.WebClient
$request = "http://mysite/-/script/v2/master/MyExposedScript?user=sitecore\admin&password=b"
$webClient.DownloadString($request)

*Expected*
script output is returned

*Actual*
404 error code is returned

**Comment by michaellwest** [comment]
Does it work if the script is published to the web database?

**Comment by AdamNaj** [comment]
@michaellwest - I know the nature of the problem. and have already fixed it. Will commit the fix today.

**Comment by AdamNaj** [comment]
Merged by implementing Issue #350
