### ISSUE TITLE
Add feature to disable scripts from automatically running for integration points

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#330]
If a script is saved within one of the integration points it will automatically run if the module is enabled. Would like a way to disable individual scripts as well so I don't have to remove scripts to prevent from running.

#### Example:
I would like the _Random desktop background image_ script to run but not the _Automatically show quick info_.

![image](https://cloud.githubusercontent.com/assets/933163/7663723/773c6912-fb35-11e4-8a7a-f4eb72efd790.png)

**Comment by AdamNaj** [comment]
This would quickly become too complicated.

From my point of view this is what modules are for. Your module should deal with a single functionality, if you want that functionality gone - disable the module. The modules that are good examples of this are:
- Package Generator
- Media library Maintenance
- Task Management

In case of the "Media library Maintenance" you're dealing with a single script that is providing a single functionality and still can be easily disabled.

**Comment by michaellwest** [comment]
Opened #332 to address this concern.
