### ISSUE TITLE
Add context menu to scripts to create a task schedule

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#331]
There should be a context menu option for scripts to help generate a task schedule.

Add to the Task Management module.

**Comment by AdamNaj** [comment]
The script kind of already existed but was in a somewhat unexpected place. When clicking on an item under ```/sitecore/system/Tasks/Schedules``` you could select ```Scripts``` and then ```Create Task Schedule``` that would allow you to select a script.

This is now moved under the ```Content Editor Insert Menu``` integration point, so you can:
![image](https://cloud.githubusercontent.com/assets/1209953/8304160/078e7866-19a4-11e5-9663-8778f13a2b3c.png)
And then select a script for the task:
![image](https://cloud.githubusercontent.com/assets/1209953/8304167/21ad5b18-19a4-11e5-9c36-67b768a3ee6c.png)
Which would immediately pop up the schedule editing:

![image](https://cloud.githubusercontent.com/assets/1209953/8304203/55c8ca54-19a4-11e5-9a18-3a9174e3825d.png)

Don't think we need any more automation as it's now pretty straightforward.

**Comment by michaellwest** [comment]
Looks great Adam. Thanks for the update.
