### ISSUE TITLE
Add optimization scripts to the System Maintenance Module

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#334]
Added the following scripts to reproduce the features found in the Control Panel:

* Clean up databases
* Clean up link databases
* Rebuild content search indexes
* Rebuild search indexes

**Comment by michaellwest** [comment]
Completed.

**Comment by AdamNaj** [comment]
Reopening as it needs merging to 7

**Comment by AdamNaj** [comment]
All scripts now merged back to SC7
