### ISSUE TITLE
Add command to create anti-package

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#337]
Create anti-package from an existing package like in Sitecore Rocks.

**Comment by michaellwest** [comment]
@AdamNaj Is there a file selector dialog usable from within SPE? Thought about creating a Toolbox script that would open a file dialog and then generate the antipackage.

**Comment by michaellwest** [comment]
@AdamNaj Need your help updating the *Create Anit-Package* script to browse for a file rather than have a hard-coded path. Do we have a command for that?

**Comment by AdamNaj** [comment]
@michaellwest if it's not achievable with the durrent dialogs I'll create one for you over the weekend.

**Comment by michaellwest** [comment]
Perhaps a variation of the File Explorer would be sufficient. That includes an option to upload files.

**Comment by AdamNaj** [comment]
I hope this will do the trick for you:

```powershell
Show-ModalDialog -HandleParameters @{
    "h"="Header Text 2"; 
    "t" = "title"; 
    "ic"="People/16x16/box.png"; 
    "ok"="Pick";
    "ask"="";
    "path"= "packPath:$SitecorePackageFolder";
    "mask"="*.zip";
    "ht"="Header Text 1"
} -Control "Installer.Browse"
```

It will work when you update your code to the version that has Issue #374 resolved.

**Comment by AdamNaj** [comment]
Feel free to close this issue if ready for release.

**Comment by michaellwest** [comment]
Implemented.
