### ISSUE TITLE
Add NoClobber option to Export-Package command

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#338]
Support NoClobber like Export-Csv.

**Comment by michaellwest** [comment]
Implemented.

**Comment by michaellwest** [comment]
Just realized that NoClobber should just throw an error that the file already exists. Want to add the ability to autoincrement the names with numbers. Will correct the code and then come up with a new parameter name if appropriate.

**Comment by AdamNaj** [comment]
Merged by implementing Issue #350
