### ISSUE TITLE
Get-Package should support .xml and .zip packages

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#340]
The current version of Get-Package only supports reading the package xml. Should add support to read the project file inside package zip files.

**Comment by AdamNaj** [comment]
This doesn't seem to provide a lot of value. I don't think it's worth the effort which would be not super trivial.

**Comment by michaellwest** [comment]
I copied a few lines of code from the anti-package script. Pretty easy.

**Comment by michaellwest** [comment]
Implemented.
