### ISSUE TITLE
Deserialisation fails with "Some directories could not be loaded"

### ISSUE THREAD

**Issue by richardhauer** [SitecorePowerShell/Console#343]
I serialised a disparate set of nodes with security information that I wanted to port to a different environment.  I used the following commands:

$securedItems = gci -recurse | where-object { $\_["\_\_Security"] -ne "" }
$securedItems | ? { $\_."\_\_Security" -like "\*_Agency\*" } | serialize-item -recurse -target C:\Temp\Auth

This correctly output a structured set of folders and items.  I modified the item files to remove all fields except __Security, zipped the set and moved it to the other environment.

Unzipped on the other side and added a root "sitecore.item" node to pass as the path parameter as a sibling of the "sitecore" root folder.

Used the following command to import:
deserialize-item -path "E:\\\_deployments\\\_authentication\sitecore\sitecore" -root "E:\\\_deployments\\\_authentication\\sitecore\\" -recurse

I have tried many variations.  ProcessMonitor says that it found the sitecore.item file and was looking for a sitecore.link file (that was not found).

Everyone/Full permissions on the folder structure.

Folder/item structure is kinda like this:
E:\_deployments\_authentication
  - sitecore.item
  + sitecore
     + content
        - home.item
     + layout
     + templates
       + System

etc.

**Comment by AdamNaj** [comment]
Ho Richard,

The nature of the problem lies with the usage of ```-Recurse``` in conjunction with the ```-Path``` and is within the depths of the serialization API within sitecore I believe. As sitecore is trying to find the whole structure. I wonder though if you need the recurse and whether something like this wouldn't work:

```powershell
gci "E:\_deployments\_authentication\sitecore\sitecore" -recurse -File | 
   %{ Deserialize-Item -path $_ -root "E:\_deployments\_authentication\sitecore" }
```

**Comment by richardhauer** [comment]
Ran the below command – didn’t really think of that as an option.
No messages were recorded in the console or in the Sitecore log.
The field data in the files was not incorporated into Sitecore.

I modified the gci command (removing the last “/sitecore” so that it actually returned results first.
But no joy.

Sitecore log follows:
ManagedPoolThread #4 17:19:21 INFO  Job started: PowerShell-1b81b6a9-72b4-0771-a551-ed93f1a95d94-{E2611F89-B38E-49D8-9309-BA58269E3076}
ManagedPoolThread #4 17:19:21 INFO  Executing script:
gci "E:\_deployments\_authentication\sitecore" -recurse -File | %{ Deserialize-Item -path $_ -root "E:\_deployments\_authentication\sitecore" }
ManagedPoolThread #4 17:19:21 INFO  Timer script execution finished at 38ms
ManagedPoolThread #4 17:19:21 INFO  Job ended: PowerShell-1b81b6a9-72b4-0771-a551-ed93f1a95d94-{E2611F89-B38E-49D8-9309-BA58269E3076} (units processed: )

I am going to deserialise one of the files using the normal Sitecore process to check that my hand modification of the files hasn’t broken it, but there’s nothing at all coming from the console message-wise.


Thoughts?

Richard

**Comment by richardhauer** [comment]
I picked one file item for a bit more testing...
The item doesn't deserialize through the normal toolbar ribbon" because it is not an "update" per se.

I decided that I needed to use `-ForceUpdate` to make the update happen.

When I use the following command, I get no console messages and no error logs:
`Deserialize-item -path "E:\_deployments\_authentication\sitecore\content\toyota" -root "E:\_deployments\_authentication\sitecore\" -ForceUpdate`

When I add the -DisableEvents switch I get the following error:
`Deserialize-item : File path is not under dump root `
`At line:1 char:1 `
`+ Deserialize-item -path "E:\_deployments\_authentication\sitecore\cont ... `
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ `
`    + CategoryInfo          : NotSpecified: (:) [Import-Item], Exception `
`    + FullyQualifiedErrorId : ``System.Exception,Cognifide.PowerShell.Commandlets.Serialization.ImportItemCommand`

**Comment by richardhauer** [comment]
The fallback scenario is Get-Acl and these methods all seem to result in

`get-acl : Cannot perform the operation because it is not supported on the object found in path master:\sitecore\content`

**Comment by AdamNaj** [comment]
the following worked for me:
```PowerShell
gci "E:\_deployments\_authentication\sitecore\sitecore" -recurse -File |
   %{ Deserialize-Item -path $_.FullName -root "E:\_deployments\_authentication\sitecore" -ForceUpdate }
```

The key changes are:
- the additon of ```.FullName``` after the ```$_```
- the additon of ```-ForceUpdate``` parameter

**Comment by richardhauer** [comment]
Still no messages in the console, but that does seem to have imported the content.
Completely broke all the items unfortunately.

Sitecore complains that “The current item does not have a version in “English : English”.

I think I’m going to abandon this tactic and instead write a JSON file with the ID and Security info I want, then simply load the file and update the items.
Serialize/Deserialize clearly isn’t designed for this task.

Richard.

**Comment by AdamNaj** [comment]
Yeah I think sitecore expect the complete item information in the file.
You could think about exporting the item using ConvertTo-CSV and then ConvertFrom-CVS on import

**Comment by AdamNaj** [comment]
I guess this is closed for now

**Comment by hrishikeshtt** [comment]
Is there any way to revert what we deserailized using powershell extensions ?

**Comment by AdamNaj** [comment]
SPE uses the standard Sitecore APIs for serialization/deserialization. Unfortunately, Sitecore does not store the state from before deserialization - therefore unless you are in posession of a backup of the database from before - there is no way for you to revert it other than possibly going very deep and reverting it using database logs.

**Comment by hrishikeshtt** [comment]
We have multiple TDS projects to sync. We executed the below command

`Foreach($scproj in $scPROJS)
{
       $gcicommand = {gci $scproj -recurse -File |
                                    %{ Deserialize-Item -path $_.FullName -root $scproj -ForceUpdate }}  
}`

We have a collection of sitecore project paths in $scPROJS  and they contain many sitecore items.
While we run Invoke-RemoteScript command no projects synced.
It seems to be the $scproj variable is not updating the script.
Instead we hard coded the path the project synced correctly.
What may be the issue?

**Comment by michaellwest** [comment]
@hrishikeshtt In your script, `$scproj` would not be available in the scope of the `ForEach-Object` when deserializing the items.

**Comment by hrishikeshtt** [comment]
Is it mandatory that we should hard code the sitecore project path inside the deserializing script ?
In our scenario we can not hard code the paths because the same script will be used by multiple persons.
Is there any other way to tackle this issue ?

**Comment by michaellwest** [comment]
No it is not. There are multiple closures in your script, which is why I thought the variable was not working.

* First recommendation is to not use alias (gci, %) because it makes reading the script more difficult.
* You are creating a scriptblock and then assigning to a variable $gcicommand. Not sure why you are doing this in a foreach loop since you never invoke it.

```powershell
Foreach($scproj in $scPROJS) { 
    $gcicommand = {
        gci $scproj -recurse -File | 
            %{ Deserialize-Item -path $_.FullName -root $scproj -ForceUpdate 
        }
    }
}
```

Possible alternative (untested):
```powershell
foreach($scproj in $scprojs) {
    Get-ChildItem -Path $scproj -Recurse -File |
        ForEach-Object { Deserialize-Item -Path $_.FullName -Root $scproj -ForceUpdate }
}
```

**Comment by hrishikeshtt** [comment]
I tried that way.

This is my entire script

```powershell

param([string]$tfsmainpath)

 # Getting all project name from visual studio solution file
$projects = Invoke-Expression ".\GetProjects.ps1"

$scPROJS = @()

#Modifying the project name by removing the extension and concatinate the sitecore pathe
Foreach($project in $projects.split(';')){
	$extn = [IO.Path]::GetExtension($project)
	if ($extn -eq ".scproj" )
    {
		$project = $project.replace('..\..', $tfsmainpath)
		$project = $project.replace('..\', $tfsmainpath + '\Tenants\')
		$project = $project.substring(0, $project.LastIndexOf('\') + 1) + "sitecore"
		$project = "'" + $project + "'"
		$scPROJS += $project
		
    }
}

Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

Import-Module -Name SPE

# Creating new session for SPE remote scripting
$session = New-ScriptSession -Username admin -Password b -ConnectionUri http://sitecoregulp.local

Foreach($scproj in $scPROJS){

	$args = @{                     
		"Path" = $scproj
         }

	$script = {Get-ChildItem $params.Path -recurse -File |
						ForEach-Object { Deserialize-Item -path $_.FullName -root $params.Path -ForceUpdate }}

	$jobId = Invoke-RemoteScript -Session $session -ScriptBlock $script -ArgumentList $args -Asjob

	Wait-RemoteScriptSession -Session $session -Id $jobId -Delay 20 -Verbose
}
```

I have 20 TDS projects to sync. All of them are 100 KB in size and all are synced correctly except one which is around 1.4 MB in size.
But when I tried it by hard coded the path like below, it synced correctly.

```powershell
$script = {Get-ChildItem 'D:\TFS\*****\Dev\Features\Req_13010\*****\*****\*****\******\sitecore' -recurse -File |
						ForEach-Object { Deserialize-Item -path $_.FullName -root 'D:\TFS\*****\Dev\Features\Req_13010\*****\*****\*****\******\sitecore' -ForceUpdate }}

$jobId2 = Invoke-RemoteScript -Session $session -ScriptBlock $script -Asjob

Wait-RemoteScriptSession -Session $session -Id $jobId2 -Delay 20 -Verbose
```

I tried the script without specifying delay then I got time out exception
What may be the reason ?

**Comment by hrishikeshtt** [comment]
And after the successful syncing of sitecore items I deleted content, renderings, and templates from sitecore and tried running the script again but no item synced.
