### ISSUE TITLE
Null reference exceptions from the console

### ISSUE THREAD

**Issue by richardhauer** [SitecorePowerShell/Console#344]
MANY commands throw the following error after executing:

[NullReferenceException: Object reference not set to an instance of an object.]
   Cognifide.PowerShell.Client.Applications.PowerShellConsole.HandleMessage(Message message) +805
   Sitecore.Shell.Framework.Commands.MessageCommand.Execute(CommandContext context) +173
   Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e) +547
   System.Web.UI.Control.PreRenderRecursiveInternal() +180
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +4048

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Cognifide.PowerShell
   at Cognifide.PowerShell.Client.Applications.PowerShellConsole.HandleMessage(Message message)
   at Sitecore.Shell.Framework.Commands.MessageCommand.Execute(CommandContext context)
   at Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

but seem to complete their task anyway.  I know that's not very helpful, but that's all the telemetry I'm getting.

**Comment by AdamNaj** [comment]
Could you provide a sample (as reproducible as possible) command that would result in the error, please?

**Comment by richardhauer** [comment]
Unfortunately not easily.
There was a point where every command resulted in this error.

Of course now I can’t reproduce it at all.

*sigh*

**Comment by AdamNaj** [comment]
Might have been some session problem. I guess it's good that it functions ;)
If you can reproduce it in the future feel free to re-open this issue or create a new one.
