### ISSUE TITLE
Get-Item does not respect -ErrorAction or -ErrorVariable

### ISSUE THREAD

**Issue by richardhauer** [SitecorePowerShell/Console#345]
If I execute the following I get exceptions in the error window instead of silently having the error trapped in the variable.

`$item = gi -Path "master:\sitecore\content\foo" -ErrorVariable err -ErrorAction SilentlyContinue`

Note that $err does contain the error message.

**Comment by AdamNaj** [comment]
Implemented for Sitecore 8

**Comment by richardhauer** [comment]
I'm in Sitecore 8?
________________________________

**Comment by AdamNaj** [comment]
no no, we're implementing features first for Sitecore 8 branch and then porting to Sitecore 7 branch before release.

**Comment by AdamNaj** [comment]
Merged by implementing Issue #350
