### ISSUE TITLE
Install Fails  there's no template with the following ID 

### ISSUE THREAD

**Issue by JoeOffenberg** [SitecorePowerShell/Console#351]
During install of "Sitecore PowerShell Extensions-3.0 for Sitecore 7.zip" on Sitecore 7.0, install fails with the following error

System.Exception: Failed to add an item. Key: '/sitecore/system/Settings/Rules/Definitions/Elements/PowerShell'. Reason: there's no template with the following ID '{54DAE7CD-BFD8-4E69-9679-75F2AE9F9034}' at Sitecore.Install.Items.ItemInstaller.CreateLightweightItem(ItemReference item, XmlVersionParser parser) at Sitecore.Install.Items.ItemInstaller.InstallItem(BehaviourOptions installOptions, Item targetItem, ItemReference item, XmlVersionParser parser) at Sitecore.Install.Items.ItemInstaller.GetVersionInstallMode(PackageEntry entry, ItemReference reference, XmlVersionParser parser, ItemInstallerContext context) at Sitecore.Install.Items.ItemInstaller.InstallEntry(PackageEntry entry) at Sitecore.Install.Items.ItemInstaller.Flush() at Sitecore.Install.Framework.SinkDispatcher.Flush() at Sitecore.Install.Utils.EntrySorter.Flush() at Sitecore.Install.Framework.EntryBuilder.Flush() at Sitecore.Install.Zip.PackageReader.Populate(ISink`1 sink) at Sitecore.Install.Installer.InstallPackage(String path, Boolean registerInstallation, ISource`1 source, IProcessingContext context) at Sitecore.Install.Installer.InstallPackage(String path, ISource`1 source, IProcessingContext context) at Sitecore.Shell.Applications.Install.Dialogs.InstallPackage.InstallPackageForm.AsyncHelper.<INSTALL>b__4() at Sitecore.Shell.Applications.Install.Dialogs.InstallPackage.InstallPackageForm.AsyncHelper.CatchExceptions(ThreadStart start)

Any help would be appreciated.  Thanks !

**Comment by AdamNaj** [comment]
Hi Joe, this seems to be is due to the new templates that were introduced in Sitecore 7.1. Please find the missing template in the attached package. This should help you install the package.

[Rules Templates 7.1-1.zip | uploaded via ZenHub](https://files.zenhub.io/55680b2ebe7b0a672931416f)

**Comment by AdamNaj** [comment]
In 3.1 package I'll add those in a soft way - with install mode "Skip"

**Comment by JoeOffenberg** [comment]
Thanks!  I'll try it this morning and let you know!

**Comment by JoeOffenberg** [comment]
The install completes this time, but there are some problems.  1)  The
start menu items have icons but no labels see attached.  2)  Launching
either the ISE or the Powershell Console give the following error:
Server Error in '/' Application.
------------------------------
 *Input string was not in a correct format.* *Description: *An unhandled
exception occurred during the execution of the current web request. Please
review the stack trace for more information about the error and where it
originated in the code.

*Exception Details: *System.FormatException: Input string was not in a
correct format.

*Source Error:*

  An unhandled exception was generated during the execution of the current
web request. Information regarding the origin and location of the exception
can be identified using the exception stack trace below.
*Stack Trace:*

  [FormatException: Input string was not in a correct format.]
   System.Version.TryParseComponent(String component, String
componentName, VersionResult& result, Int32& parsedComponent)
+14468962
   System.Version.TryParseVersion(String version, VersionResult& result) +362
   System.Version.Parse(String input) +98
   Cognifide.PowerShell.Core.Settings.ApplicationSettings..cctor() +97

[TypeInitializationException: The type initializer for
'Cognifide.PowerShell.Core.Settings.ApplicationSettings' threw an
exception.]
   Cognifide.PowerShell.Core.Settings.ApplicationSettings.GetInstance(String
applicationName, Boolean personalizedSettings) +0
   Cognifide.PowerShell.Client.Applications.PowerShellConsole.OnLoad(EventArgs
e) +117

[TargetInvocationException: Exception has been thrown by the target of
an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[]
arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object
obj, Object[] parameters, Object[] arguments) +76
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
+193
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
   Sitecore.Web.UI.Sheer.ClientPage.OnLoad(EventArgs e) +337
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Page.ProcessRequestMain(Boolean
includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
+3178


------------------------------
*Version Information:* Microsoft .NET Framework Version:4.0.30319; ASP.NET
Version:4.0.30319.34237

**Comment by AdamNaj** [comment]
Is this the initial version of Sitecore 7.0 or a later build?
I'm a bit lost as to how your menu items are blank - if your UI language different from "en"?
Does it happen for you only on this instance or on a new instance as well?
Do you have the latest .Net (4.5.1) installed?

It behaves odd as in something was wrong with the environment...

**Comment by JoeOffenberg** [comment]
The revision is 130810.  Is there an uninstall procedure I can use to clean
up before reinstalling?


[image: Inline image 1]

On Fri, May 29, 2015 at 10:45 AM, Adam Najmanowicz <notifications@github.com

**Comment by AdamNaj** [comment]
The exception with version parsing have been addressed as part of the Issue #369 - you can apply the workaround from there for now and we will provide a proper fix in version 3.1.

**Comment by AdamNaj** [comment]
The fix for the original problem with missing templates is now fixed as part of the last commit:

Templates for rules engine taxonomy will be added to the 7.x package with Skip options for Sitecore 7.2-7.5. They will not be added to 8.0 as they are not needed there.
To achieve full functionality users will be required to run the following script after installation on 7.0:
```/sitecore/system/Modules/PowerShell/Script Library/Platform/Development/PowerShell Extensions Maintenance/Restore Rules on Sitecore 7dot0```
