### ISSUE TITLE
Example Event Handler module changed to Automatically serialize items

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#354]
The module should provide a better example to the power of SPE. Turn it into a module called "Automatically serialize items" and have it support item save, rename, remove, events.

**Comment by kamsar** [comment]
Beware: as I found with Unicorn, `EventDisabler` makes relying on Sitecore events unreliable for capturing changes (e.g. eventdisabler is used during parts of update package installs). A great demo, but not one I'd use in production.

**Comment by AdamNaj** [comment]
Thanks for the warning @kamsar. This would indeed not be used for anything bot a demo. I don't think using PowerShell for this purpose would be efficient anyway.

**Comment by AdamNaj** [comment]
High potential for slowing down Sitecore as PS is not fast enough for it I think.
