### ISSUE TITLE
Deprecate the unused commands

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#356]
Be sure to update the document help to indicate that it's a deprecated command.

* Get-Index
* Get-ItemByUri
* Get-SearchIndex

**Comment by AdamNaj** [comment]
- ```Get-Index``` - I could no longer find it in the code - removed the docs for it.
- ```Get-ItemByUri``` - this was already marked obsolete and not working for over a year - removed now.
- ```Get-SearchIndex``` this is now repurposed for the new Content Search API.
