### ISSUE TITLE
Remove-RoleMember command is not working

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#358]
**How to reproduce:**
1. Create new user (for example ***test***) in domain ***sitecore***
2. Execute following commands:
```powershell
Add-RoleMember -Identity sitecore\Author -Members test
Remove-RoleMember -Identity sitecore\Author -Members test
```
**Actual result:**
User test is assigned to Author group but second command (Remove-RoleMember) doesn't remove him.

**Expected result:**
Remove-RoleMember command work as expected (user is removed from role members)

**Comment by alan-null** [comment]
Fixed @bea0b8b46e4f25ebe09595ad72abfa94a56350f9

**Comment by michaellwest** [comment]
Great catch!

**Comment by AdamNaj** [comment]
Go Alan!
