### ISSUE TITLE
Invoke-Script command should support arguments

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#360]
Use case: Pass data to script for execution.
```powershell
$props = @{
    Path = "License Expiration\Tasks\License Expiration Notification"
    Arguments = $to,$from,$subject,$body
}
Invoke-Script @props
```

Content of the script:
```powershell
param(
    [string[]]$To,
    [string]$From,
    [string]$Subject,
    [string]$Body
)

Send-MailMessage @PSBoundParameters
```

**Comment by AdamNaj** [comment]
Implemented. Used ```-ArgumentList``` like you did in the new remoting module instead of ```-Arguments``` like suggested above for consistency.

Now if I save the script like:
```powershell
param(
    [string[]]$To,
    [string]$From,
    [string]$Subject,
    [string]$Body
)
Write-Host "Sending email from:$from to:$to"
```
to ```master:\system\Modules\PowerShell\Script Library\Test\Functions\Mail```
I can do the following:
```powershell
Invoke-Script -Path "master:\system\Modules\PowerShell\Script Library\Test\Functions\Mail" -ArgumentList "to", "from", "subject", "body"
```

And here's the result:
![image](https://cloud.githubusercontent.com/assets/1209953/9034916/955d1e46-39d3-11e5-98bf-b07e45b0f5c3.png)

**Comment by michaellwest** [comment]
Just to add to your reasoning, there are many more commands using ArgumentList than Arguments. Here's a sample.

**Arguments** with hashtable
* Set-WmiInstance

**ArgumentList** with Object[]
* New-Object
* Invoke-Command
* ForEach-Object
