### ISSUE TITLE
ApplicationSettings.SitecoreVersionCurrent throws exception if "revision" isn't an integer

### ISSUE THREAD

**Issue by uli-weltersbach** [SitecorePowerShell/Console#369]
We recently received a Sitecore hot fix which includes the following `sitecore.version.xml`.
When `ApplicationSettings.SitecoreVersionCurrent` tries to parse the revision number using `System.Version.Parse` an exception is thrown because the revision is not an integer.

I'm not sure whether this is actually a problem with Sitecore PowerShell or with Sitecore Support :)

```xml
<?xml version="1.0" encoding="utf-8"?>
<information>
  <version>
    <major>7</major>
    <minor>5</minor>
    <build>
    </build>
    <revision>141003 Hotfix 431794-1</revision>
  </version>
  <date>February 20, 2015</date>
  <title>Sitecore.NET</title>
  <company>Sitecore Corporation</company>
  <copyright>© Sitecore. All rights reserved.</copyright>
</information>
```

```csharp
public class ApplicationSettings
  {
    private static string rulesDb = (string) null;
    private static string settingsDb = (string) null;
    private static string scriptLibraryDb = (string) null;
    public static System.Version SitecoreVersionCurrent = System.Version.Parse(About.Version);
    [ ...]
```

**Comment by michaellwest** [comment]
@uli-weltersbach Thank you for reporting the issue. Looks like in our latest development version this is still an issue. I was able to reproduce the error by simply entering non-numeric characters in that file just as you have shown. I'm not certain of the affects on Sitecore, but you may be able to remove that text temporarily for testing. We'll work on a fix and get back with you.

**Comment by michaellwest** [comment]
@AdamNaj Please take a look at my changes and see if this correctly addresses the issue.

**Comment by AdamNaj** [comment]
Fixed. For now please remove the " Hotfix 431794-1" from the file 
```xml
<revision>141003 Hotfix 431794-1</revision>
```
for the current version to work properly.
