### ISSUE TITLE
"Version" field in templates

### ISSUE THREAD

**Issue by richardhauer** [SitecorePowerShell/Console#370]
The Version field that is used in various templates seems to contain a float or "dotted quad" value.  When using SOLR this field conflicts with Sitecore's internal Version field which is set in SOLR as an INT.

Under SOLR all fields are included in the index, to a config change is required either to exclude the PSE templates or to exclude the Version field in particular.  I've no idea whether PSE leans on the indexing features so am unaware what impact, if any, the above config changes will have on an existing implementation.

Might be nice (assuming a small config change is all that is required) to include the necessary exclusions in a config patch that ships with the package.

Could someone let me know what will happen if I simply remove all the PSE templates from the index?

Cheerio.

**Comment by AdamNaj** [comment]
Hi Richard. As I see only the ```Module``` template includes the ```Version``` field you mention. Most of Fields in there are for informational purpose only and are not used anywhere. I'm happy to change the field name if that would help.

I'm not really an expert in how Sitecore Content Search indexing works so you would have to provide some guidance for me here.

We're not using the Content Search anywhere in the module internals only the ```Find-Item``` cmdlet is aware of the new API.

**Comment by richardhauer** [comment]
Ok. That's a good start though. I'll send back a sample patch file.

Richard
________________________________

**Comment by AdamNaj** [comment]
Fixed. Fields renamed. Code augmented to reflect the change.

**Comment by richardhauer** [comment]
That's probably the easiest way to fix it. The other way is to add the Template ID to the exclusions list in the DefaultIndexConfiguration for Lucene and SOLR.

Rich
________________________________
