### ISSUE TITLE
Installation Issues trough Sitecore upgrade package

### ISSUE THREAD

**Issue by rootix** [SitecorePowerShell/Console#375]
Hi

As discussed during the SUGCON with Adam, here is the promised ticket.

I installed the module trough the item package. We work with Unicorn and Sitecore Courier in our solution. This resulted in an Sitecore upgrade package which threw an installation exception without any further information.

It turned out that the fact, that the same powershell templates with the same ID's are used both in core and master database are the root of the issue. 

Sitecore isn't capable of installing packages in which the same template (same id) is present in both databases together with at least one item which is based on one of those templates.

Adam told me that he will remove the templates from the core database. This would fix the problem for me.

Thanks!

**Comment by AdamNaj** [comment]
Fixed as part of Issues #371, #372, #373.
Predominantly #373 though :)
