### ISSUE TITLE
Add PowerShell ISE tile to LaunchPad

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#377]
Would be really sweet to start PowerShell ISE from LaunchPad.

![image](https://cloud.githubusercontent.com/assets/6848691/8253250/4e66a4a2-168e-11e5-8789-c41d1a02c0e5.png)

**Comment by alan-null** [comment]
Enjoy :smile:

**Comment by michaellwest** [comment]
Awesome news Alan. Thanks for the enhancement!
