### ISSUE TITLE
ISE throws NullReferenceException if item "/sitecore/content/home" is not found

### ISSUE THREAD

**Issue by pbering** [SitecorePowerShell/Console#378]
... due to shell site has contentStartItem="/Home" by default and that attribute is used in https://github.com/SitecorePowerShell/Console/blob/master/Cognifide.PowerShell/Client/Applications/PowerShellIse.cs without checking for null:

    ContextItemId = Context.ContentDatabase.GetItem(Context.Site.ContentStartPath).ID.ToString();

**Comment by alan-null** [comment]
Thanks for detailed report @pbering. Issue fixed.

**Comment by AdamNaj** [comment]
Brautifull! Thanks Alan for the quick reaction!

**Comment by pbering** [comment]
Wow quick :+1:
