### ISSUE TITLE
PowerShell ListViewer control does not properly display content wider than screen

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#380]
I ran a Find-Item query and output to Show-ListView. The output has so many columns that the scrollbar is the only way to see it all. The problem is that the overflow does not display properly.

Sample script:
```powershell
 Find-Item -Index sitecore_master_index -Criteria @{Filter = "StartsWith"; Field = "_fullpath"; Value = "/sitecore/content/home" } |
 Show-ListView -Property * -Title "Master Index"
        
Close-Window
```

**Comment by AdamNaj** [comment]
Fixed.

**Comment by asaikarthik** [comment]
Hi Adam, I am also facing the same issue, could you please let share the details to fix the issue

Thanks, Karthik
