### ISSUE TITLE
ISE Should support plugins integration point as 3rd strip in the ribbon

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#383]
For stuff like Prettifier or refactoring scripts. The ISE plugin script will get the selected text & whole script as an input and will be able to do anything with it. Upon completion the script will be pasted back into the editor

**Comment by michaellwest** [comment]
+1

**Comment by michaellwest** [comment]
Could create a plugin that removes all aliases from the script.

**Comment by AdamNaj** [comment]
Implemented with a number of rules that allow for conditional showing and enabling of buttons.

Plugin gets the whole strip in the ```$scriptText``` and the selected part of the script in ```$selectionText```. The plugin can send the script back to ISE using the following  command:

```powershell
Send-SheerMessage -Name "ise:pluginupdate" -Parameters @{ "script" = "$newScriptText" }
```

where the ```$newScriptText``` is the processed scriptText to replace the existing script in ISE.
