### ISSUE TITLE
Cannot save script using save as on existing script item

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#385]
**How to reproduce**
1. Open ISE
2. Create new script
3. Click *Save As...*
4. Find some existing script and try to override it

**Actual result**
Impossible to do it. Popup with error message appears.
![image](https://cloud.githubusercontent.com/assets/6848691/8340848/738ed2ae-1ac1-11e5-9788-92c5bd0407e5.png)

**Expected result**
No error message box, existing script item can be overridden by new one.

**Comment by alan-null** [comment]
Fixed. Now it is possible to use *save as* feature.

**Comment by AdamNaj** [comment]
Nice!

**Comment by michaellwest** [comment]
+1
