### ISSUE TITLE
SPE Module Enhancements

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#389]
Some enhancements being made:
* [x] Add examples to the script comments
* [x] Send and Receive commands should support pipeline input
* [x] Send and Receive commands should assume the media path is a directory unless a file extension is specified
* [x] Autodetect file extension of downloaded media items based on ImageFormat
* [x] Add proxy object to session to improve performance

**Comment by michaellwest** [comment]
@pbering This is why I've been behind on getting the update to you. You should be pleased with all the changes.

**Comment by michaellwest** [comment]
Implemented.

**Comment by AdamNaj** [comment]
Is this fully backward compatible? what i mean by that is - if someones used the [remoting from my original post](http://blog.najmanowicz.com/2014/10/10/sitecore-powershell-extensions-remoting/) will their script still work? If so, we can close this issue as we're moving towards the release.
