### ISSUE TITLE
Rules Based Report works with wrong path

### ISSUE THREAD

**Issue by rootix** [SitecorePowerShell/Console#393]
Hi

I think this is probably related to issue #378?

I had the same issue as the other ticket. I fixed this by changing the startItem from "/home" to "/" which results in a full start path of "/sitecore/content/". After this change, the ISE was working on the master database.

Now i saw that the Rules Based Report does not show a start path when i open it. On the playground i have a dropdown to select the root item.

After manually inserting a valid item path somewhere deep in the content tree, i get the following error message after running the report:

```
Get-Item : Cannot find path 'master:\content\home' because it does not exist.
At line:19 char:9
+ $root = Get-Item -Path master:\content\home\
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (master:\content\home:String) [Get-Item], IOException
    + FullyQualifiedErrorId : ItemDoesNotExist,Microsoft.PowerShell.Commands.GetItemCommand

Find-Item : maxClauseCount is set to 1024
At line:40 char:19
+ $templateFields = Find-Item -Index sitecore_master_index -Criteria @{Filter = "S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Find-Item], TooManyClauses
    + FullyQualifiedErrorId : Lucene.Net.Search.BooleanQuery+TooManyClauses,Cognifide.PowerShell.Commandlets.Data.Find
   ItemCommand
```

Can you guys investigate into this? I'm not sure what i should change to get everything work.

**Comment by michaellwest** [comment]
Hey @rootix, thank you for reporting the issue. Can you try the following workaround?

* Navigate to the following path:
/sitecore/system/Modules/PowerShell/Script Library/Authorable Reports/Toolbox/Rules based report

* Right click and **Edit with ISE**
* Change line 19 to the following:
```powershell
$root =  Get-Item -Path (@{$true="master:\content\home\"; $false="master:\content\"}[(Test-Path -Path master:\content\home)])
```
* Save the changes in the ISE

Now when you run the report if that path doesn't exist on master it will default to the Content item.

**Comment by rootix** [comment]
Hi @michaellwest 

The workaround resolves the issue for me, thanks!

Question about those fixes? Will you guys build a "hotfix" release with all the stuff which was fixed in the last few days? Or is the next version 3.2 in September?

**Comment by michaellwest** [comment]
That's a very good question. We may be able to squeeze out a 3.2 (or 3.1.1) sooner. I'll run it by @AdamNaj and see.

**Comment by AdamNaj** [comment]
3.2 will be released shortly with this and many more fixes :)
