### ISSUE TITLE
Powershell ISE throwing null reference exception

### ISSUE THREAD

**Issue by joosthollander** [SitecorePowerShell/Console#394]
Hi,

I Installed Sitecore PowerShell Extensions-3.1 for Sitecore 8 on our Sitecore 8 update 2 solution. When I start the powershell ISE I get a null reference exception (stack trace below).
I also installed the same package on a clean installation of Sitecore 8 update 2 and there it works just fine so I guess it must be related to some customizations we did on our solution. Can you provide guidance on how to debug this issue or is it something you have seen before?

Kind Regards,
Joost

15520 19:17:18 ERROR Application error.
Exception: System.Web.HttpUnhandledException
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Nested Exception

Exception: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Sitecore.Web.UI.Sheer.ClientPage.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Nested Exception

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Cognifide.PowerShell
   at Cognifide.PowerShell.Client.Applications.PowerShellIse.OnLoad(EventArgs e)

**Comment by michaellwest** [comment]
@joosthollander Do you encounter any issues in the Console?

**Comment by joosthollander** [comment]
Hi Michael,

The console seems to work just fine:

![image](https://cloud.githubusercontent.com/assets/4118001/8439396/358dfa52-1f6c-11e5-8558-2c517441ad44.png)

Regards,
Joost

**Comment by joosthollander** [comment]
Hi Michael / Adam,

I do not fully understand whats happening but I have been able to fix the issue. We compiled the code and found out that the null reference exception was causes by the fact that the following item was not present in the core database:
/sitecore/content/Applications/PowerShell/PowerShellIse/Menus/Sessions/ISE editing session

I created this item and used the binaries which we compiled and now ISE works.

regards,
Joost

**Comment by michaellwest** [comment]
Joost, I just confirmed that this item was introduced with issue #382. The item was added to source control but is missing from the package. I'll take a look and see if I can correct the deployed module on the marketplace.

**Comment by michaellwest** [comment]
@joosthollander In your original comment that you installed SPE 3.1 did a previous version exist in Sitecore you were simply upgrading? If so, what version?

I did confirm that in a clean install of both SC 8 up2 and SC 8 up3 the module works without error.

**Comment by alan-null** [comment]
Hi @joosthollander,

Your problem is probably related to #378.
From this [screen](https://cloud.githubusercontent.com/assets/4118001/8439396/358dfa52-1f6c-11e5-8558-2c517441ad44.png)
I can see that Home item is not present in your database.

Please install a package with default home item, or create the new one (path to the home item must be the same as on vanilla Sitecore instance).

This problem was already solved, but the current release doesn't contain those changes.

Hope it helps.

**Comment by joosthollander** [comment]
Hi, 

This may very well be the case. The home item is indead missing. And same package on same machine on a fresh install (with sitecore home item) did work.
@michaellwest There was no previous version and the issue also occurred on a different dev env with the same setup.

Thanks for your help!

Regards,
Joost

**Comment by AdamNaj** [comment]
Closing as solved. Fixed with Issue #378

**Comment by jayasimhas** [comment]
Hi Team

I do have Home item in my Tree, but i'm getting this error.
try to open any item in the path ex: /sitecore/system/Modules/PowerShell

is throwing null reference exception.

**Comment by jayasimhas** [comment]
Stake trace:
[NullReferenceException: Object reference not set to an instance of an object.]
   Sitecore.XA.Foundation.Editing.Commands.PreviewItem.RunPreview(ClientPipelineArgs args, Item item) +658
   Sitecore.XA.Foundation.SitecoreExtensions.VersionDecoupling.CurrentVersion.IsAtLeast(Version requiredVersion, Action actionIfAtLeast) +43
   Sitecore.XA.Foundation.Editing.Commands.PreviewItem.Run(ClientPipelineArgs args) +264

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +146
   Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj) +89
   Sitecore.Nexus.Pipelines.NexusPipelineApi.Resume(PipelineArgs args, Pipeline pipeline) +301
   Sitecore.Pipelines.Pipeline.Start(PipelineArgs args, Boolean atomic) +176
   Sitecore.Web.UI.Sheer.ClientPage.RunPipelines() +503
   Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e) +779
   Sitecore.Shell.Applications.ContentManager.ContentEditorPage.OnPreRender(EventArgs e) +24
   System.Web.UI.Control.PreRenderRecursiveInternal() +110
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2994

**Comment by alan-null** [comment]
Hey @jayasimhas 

It doesn't look like **SPE** bug but something in **SXA**.
Are you sure that you've installed everything properly? 

You can look for help on slack channel **#sxa** or raise a Sitecore support ticket.

**Comment by jayasimhas** [comment]
Ok , will do.
Thanks for the response.

**Comment by santoshyerramilli** [comment]
Hi ,
 With SPE 4.7 we are facing below issue

Invoke-RemoteScript : The script session with Id '83a20292-fa6f-430a-8dda-26de70ec5997' cannot be found.
At C:\Program Files\WindowsPowerShell\Modules\SPE\Wait-RemoteScriptSession.ps1:73 char:21
+         $response = Invoke-RemoteScript -Session $session -ScriptBlock $doneScri ...
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-RemoteScript
 
VERBOSE: Polling job . Status : .
VERBOSE: Finished polling job 83a20292-fa6f-430a-8dda-26de70ec5997.
VERBOSE: Checking the Runspace for the variable id.
Get-ScriptSession : The script session with Id '83a20292-fa6f-430a-8dda-26de70ec5997' cannot be found.
At line:2 char:36
+         $backgroundScriptSession = Get-ScriptSession -Id $params.__using_id
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (83a20292-fa6f-430a-8dda-26de70ec5997:String) [Get-ScriptSession], ObjectNotFoundException
    + FullyQualifiedErrorId : ScriptSessionNotFound,Cognifide.PowerShell.Commandlets.ScriptSessions.GetScriptSessionCommand

Thanks

**Comment by alan-null** [comment]
@santoshyerramilli 
This issue has been closed already.
Please create a new one with our issue template and provide steps to reproduce.
