### ISSUE TITLE
Bulk Role Tool

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#395]
Add a new toolbox item to set security on items en masse.

You should be able to have the following security settings:
* [ ] Read
* [ ] Write
* [ ] Create
* [ ] Delete
* [ ] Rename
* [ ] Administer
* [ ] Inheritance

You should be able to specify the role, select tree items in a specific database, then apply changes.

Simulate https://marketplace.sitecore.net/Modules/S/Sitecore_Bulk_Role_Permissions.aspx?sc_lang=en

**Comment by AdamNaj** [comment]
For the sake of early 3.2 release, I think we should postpone it till 3.3.

**Comment by AdamNaj** [comment]
This sounds more like of an idea of a broken out module

**Comment by AdamNaj** [comment]
Building this tool would require a fairly significant effort on the UI side that would not be reusable for other purposes + this functionality already being available as a separate module gives the community very little in terms of providing value other than an exercise.

I hope you don't mind Mike that I I'll close this for now for the sake of cleanliness of our backlog. If you want to implement it, feel free to re-open the issue.

**Comment by michaellwest** [comment]
Would require much effort to build this. Maybe one day when we have nothing else to do.
