### ISSUE TITLE
Role Commands - Test, New, Remove

### ISSUE THREAD

**Issue by jasonchester** [SitecorePowerShell/Console#396]
Commands for managing roles should be implemented:
* Test-Role - Returns true if the role exists and false if it does not
* New-Role - Create a Role 
* Remove-Role - Deletes a Role

This will eliminate the need to call into .net for managing roles 
```
$role = "testdomain\testrole1"

if([System.Web.Security.Roles]::RoleExists($role) -ne $true)
{
    Write-Host "Creating $role."
    [System.Web.Security.Roles]::CreateRole($role)
}
else
{
    Write-Host "$role exists."
}
```

**Comment by michaellwest** [comment]
Hey @jasonchester glad you are finding the security commands helpful. I think those will be pretty straightforward to add.

**Comment by michaellwest** [comment]
@jasonchester In case you haven't seen these yet, here are some commands related to user/role security.

![image](https://cloud.githubusercontent.com/assets/933163/8461078/76237afa-1fef-11e5-8b20-088856096c59.png)

**Comment by michaellwest** [comment]
Working on the following commands:
* [ ] Test-Account which will check for validating Roles and Users
* [ ] New-Role
* [ ] Remove-Role

**Comment by michaellwest** [comment]
Test-Account [-Identity] <AccountIdentity> [-AccountType <string> {Role | User | All}]  [<CommonParameters>]

**Comment by michaellwest** [comment]
```powershell
New-Role [-Identity] <AccountIdentity> [-PassThru]  [<CommonParameters>]
```

**Comment by michaellwest** [comment]
```powershell
Remove-Role [-Identity] <AccountIdentity> [<CommonParameters>]
```

**Comment by michaellwest** [comment]
Implemented.

**Comment by AdamNaj** [comment]
...aaaand closed.
