### ISSUE TITLE
Add support for working with Contacts in the xDB

### ISSUE THREAD

**Issue by jasonchester** [SitecorePowerShell/Console#397]
Supporting read,write,update of contacts in the xDB would allow users to script updates to xDB contacts using powershell.

At a minimum i would suggest the following commands
- Get-Contact
- New-Contact
- Remove-Contact
- Save-Contact

Optionally the following commands might be useful as well
- Merge-Contact
- Lock-Contact

**Comment by AdamNaj** [comment]
Interesting idea... I'll see into it as soon as I'm back from holiday

**Comment by michaellwest** [comment]
We briefly discussed and this could be a good add-on module built as a separate package. We're finding that the core module is getting pretty big.

**Comment by jasonchester** [comment]
Found an article related to Powershell & xDB

http://jockstothecore.com/xdb-reports-with-powershell/
