### ISSUE TITLE
Send-File produces cancelled return value after download

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#403]
```powershell
Get-Item -Path "master:\media library\Files\readme" | Send-File
```
Steps to reproduce:
* Run command
* Click download
* File downloads and completes and download dialog remains open
* Click X and return value is **downloaded**
* Click Close and return value is **cancelled**

**Comment by AdamNaj** [comment]
Fixed in commit 5b4c5660396deaa13f97e6e84b7691b41d083477
