### ISSUE TITLE
SiteCore Powershell Extension Installtion

### ISSUE THREAD

**Issue by alagaraja** [SitecorePowerShell/Console#404]
I am trying to install Sitecore PowerShell Extensions-3.0 for Sitecore 8 in my sitecore 8 instance (Windows 8.1 machine).

I used sitecore's Development Tools -> Installation Wizard and choosing the above mentioned package. It shows Install a Package sitecore dialog with Installing gif and stays there for over an hour and nothing happens. No error nothing it just spins.

First I tried to Powershell Extensions 3.1 version and it was the same, so I tried lowering to 3 and its the same.

Can somneone shed some lights on what I am missing?

Thanks

**Comment by michaellwest** [comment]
Are you using Mongo and is it running? I decided to not use it on my dev
machine so disabling it with this gist help for my package install problem.

https://gist.github.com/michaellwest/18e2707fca903a2ed382

In the script just update the $paths variable to whatever directory your
instance of sitecore is installed.

**Comment by alagaraja** [comment]
Yes. That did the trick. Thanks for your quick reply and I can't wait to take a deep dive into this.
