### ISSUE TITLE
Installing Update Package Remotely

### ISSUE THREAD

**Issue by intelligenSoft** [SitecorePowerShell/Console#405]
Hi,
I need to install an update package (contains sitecore items, that was packaged using TDS) from my build box (this is the box that builds the package at the time of building our sitecore visual solution studio solution that contains TDS project and our Web and other projects).

I need to install that updated package REMOTELY on a CMS box from the build box (Note: build box does not have sitecore or anything sitecore related installed). 

The CMS box has sitecore 8 installed and I just installed Sitecore PowerShell Extensions-3.1 for Sitecore 8. I can xcopy the .update package file to the CMS box's sitecore instance directory.

The question is how do I invoke "install-updatepackage" commandlet in the CMS box remotely from build box?

Any pointer to where to start will be of huge help. Also, am I in the right track as far as, able to deploy sitecore and other code (not Content) to other environments (such as QA, Staging and Production)?

Thanks in advance.

**Comment by AdamNaj** [comment]
The remoting method described on [my blog here](http://blog.najmanowicz.com/2014/10/10/sitecore-powershell-extensions-remoting/) should help you execute the ```Install-UpdatePackage```

**Comment by michaellwest** [comment]
In addition to Adam's blog we have also created a Windows PowerShell module
that you can use. Not yet blogged about it but you can find more details
here:
http://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/content/remoting.html

The module is here:
https://github.com/SitecorePowerShell/Console/blob/master/Data/packages/SPE%20Remoting-3.1.zip

**Comment by AdamNaj** [comment]
Closing as solution has been provided. Please re-open if additional info needed.
