### ISSUE TITLE
Useless (?) INFO logging

### ISSUE THREAD

**Issue by rootix** [SitecorePowerShell/Console#406]
Hi

I use version 3.1 of the Powershell Console. When i save an item on the authoring server, i get the following log statements:

![image](https://cloud.githubusercontent.com/assets/874015/8614241/072328da-26e8-11e5-935a-860822c8848b.png)

They seem to get logged by an anonymous function and the ScriptSession class on INFO level. Since i don't see which extension is executed, the message has not really a value in this context.

Why don't you change those messages to DEBUG-Level? I think they are only relevant when you need to check that. Otherwise it fills the log on the authoring system with information which are not relevant for daily use.

Regards,
Pascal

**Comment by michaellwest** [comment]
Hey @rootix, good call on that. In issue #333 we change the default behavior for Write-Log. It would be a good idea for us to continue down that path of reducing noise in the logger.

**Comment by michaellwest** [comment]
Implemented.
