### ISSUE TITLE
Sitecore.version.xml - powershell console fails load in case of unexpected value

### ISSUE THREAD

**Issue by petr-kasparek** [SitecorePowerShell/Console#407]
Hello,

I've reached an issue with running powershell console (and ISE too) when an unexpected value is found in Sitecore.version.xml. We got new file and some fix from sitecore and the file looks like this:

...
&lt;information&gt;
  &lt;version&gt;
    &lt;major&gt;7&lt;/major&gt;
    &lt;minor&gt;2&lt;/minor&gt;
    &lt;build&gt;0&lt;/build&gt;
    &lt;revision&gt; 7.2 rev. 140314 Hotfix 435527-1&lt;/revision&gt;
  &lt;/version&gt;
  ...
&lt;/information&gt;

When trying to run powershell it fails with an Server Error in '/' Application. 

The type initializer for 'Cognifide.PowerShell.Core.Settings.ApplicationSettings' threw an exception. ---> System.ArgumentException: Version string portion was too short or too long.

It is about revision number. But we want to keep the file like sitecore provide us, because of communication with sitecore, reporting issues and so on...

Thank you
Petr

**Comment by michaellwest** [comment]
This is related to issue #369. This behavior should be corrected with version 3.1 of SPE. Please let us know if the workaround described in issue #369 or an upgrade to 3.1 does not help.

**Comment by AdamNaj** [comment]
Closing as this issue is a duplicate and already solved. Showr term workaround provided in Issue #369
