### ISSUE TITLE
OuputBuffer.ToString() should output with a newline

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#409]
Found that the text returned in remoting was missing the new line.

![image](https://cloud.githubusercontent.com/assets/933163/8665487/1b6460a6-29aa-11e5-96ce-0d2c154e12d6.png)

**Comment by michaellwest** [comment]
Implemented.

**Comment by AdamNaj** [comment]
I guess that's closable now :)

**Comment by AdamNaj** [comment]
actually... I'm afraid it was slightly more complex - not every output line is terminated. Fix committed.
