### ISSUE TITLE
Add ability to Search for scripts in the the ISE Open button dropdown

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#411]
MRU behaviour - similar to what it looked before:
![image](https://cloud.githubusercontent.com/assets/1209953/8692760/7e708364-2ad1-11e5-8c2d-f5dab89592c2.png)

Type script name and press Enter to search for scripts:
![image](https://cloud.githubusercontent.com/assets/1209953/8692762/8878acce-2ad1-11e5-9b64-76112aa18908.png)

**Comment by AdamNaj** [comment]
Implemented

**Comment by michaellwest** [comment]
I'm getting an error in my browser after resyncing items and rebuilding the project.

```
http://console/sitecore/shell/default.aspx?xmlcontrol=Gallery.MruGallery& 500 (Internal Server Error)
```

**Comment by AdamNaj** [comment]
Can you send the stack trace from the error please?

**Comment by michaellwest** [comment]
Seems to be working on a different instance of Sitecore. When I get home
I'll try again.

**Comment by michaellwest** [comment]
0936cb to include controls.

**Comment by AdamNaj** [comment]
Not sure I know what to do with it :)

**Comment by michaellwest** [comment]
I no longer have a problem @AdamNaj .
