### ISSUE TITLE
Issue opening the PowerShell ISE

### ISSUE THREAD

**Issue by Asugusto** [SitecorePowerShell/Console#423]
Hi Guys, 

This is the exception that i found when i try to open the PowerShell ISE:

[Exception: CodeBeside class "Cognifide.PowerShell.SitecoreIntegrations.Applications.PowerShellIse,Cognifide.PowerShell" not found. (method: Sitecore.Web.UI.HtmlControls.CodeBeside.OnInit(EventArgs e)).]
   Sitecore.Diagnostics.Error.Raise(String error, String method) +129
   Sitecore.Web.UI.HtmlControls.CodeBeside.CreateCodeBeside(String type) +112
   Sitecore.Web.UI.HtmlControls.CodeBeside.OnInit(EventArgs e) +114
   System.Web.UI.Control.InitRecursive(Control namingContainer) +186
   System.Web.UI.Control.InitRecursive(Control namingContainer) +291
   System.Web.UI.Control.InitRecursive(Control namingContainer) +291
   System.Web.UI.Control.InitRecursive(Control namingContainer) +291
   System.Web.UI.Control.InitRecursive(Control namingContainer) +291
   System.Web.UI.Control.InitRecursive(Control namingContainer) +291
   System.Web.UI.Control.InitRecursive(Control namingContainer) +291
   System.Web.UI.Control.InitRecursive(Control namingContainer) +291
   System.Web.UI.Control.InitRecursive(Control namingContainer) +291
   System.Web.UI.Control.AddedControl(Control control, Int32 index) +189
   Sitecore.Shell.DefaultPage.OnInit(EventArgs e) +197
   System.Web.UI.Control.InitRecursive(Control namingContainer) +186
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2098

I already reinstall the package and I keep throwing this exception, any ideas?

**Comment by AdamNaj** [comment]
The error suggests that the dll was not found in the ```bin``` sub-directory of your Website folder. Can you verify that the package indeed installed correctly and the ```Cognifide.PowerShell.dll``` is found in your bin folder?

Other potential causes could be as described in issues: 
- #394 - Missing Home item (fixed in 3.2 - interim workaround found in the issue conversation)
- #404 - another potential cause is that the package didn't install in full as described in the issue because Mongo is not fully setup and analytics is enabled.

If those do not solve your problem please provide us with more details e.g.:
- your Sitecore version
- SPE version you're trying to run
- any other modules installed?
- Does Console work?
- Do "Start->Powershell Toolbox" script work?

Hope that helps.

**Comment by Asugusto** [comment]
I already checked for the dll and was there, also reinstall the package and nothing.... 
I'm not running mongo and the Home item is there.

I'm running:
Sitecore.NET 7.2 (rev. 140526)
SPE 3.1 for sitecore 7
There are no other modules installed
Yes, the console works fine and i can ran scripts
Yes, the Powershell Tolbox works fine

**Comment by AdamNaj** [comment]
Is it possible that this instance had an older version of SPE installed at some point?
Could you check this update guide to see if there is anything that needs to be migrated?
http://blog.najmanowicz.com/2015/02/27/upgrading-your-sitecore-powershell-extensions-from-2-x-to-3-x-what-you-need-to-know/

**Comment by Asugusto** [comment]
This was the first time that i installed SPE, and was directly the 3.1 version. I was working fine with the common console, until today i have this error:
Communication error: error; NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://xxx/sitecore%20modules/PowerShell/Services/PowerShellWebService.asmx/PollCommandOutput'.
I have a script that tries to order products in folders and for each product ordered i write a log in the console. In lower environments with a few products works fine. But in higher environments where there are more products this could be the problem? Also i want to know if i have to add something to avoid a timeout?

Regards

**Comment by AdamNaj** [comment]
There have been a number of issues improved and fixed about both Console and ISE in Milestone 3.2 - we are going to release it on Monday. Please verify if the new version still causes the problems for you.

Please make sure to clear your browser cache before using it as a number of scripts and assets have changed considerably.

**Comment by AdamNaj** [comment]
I hope this resolved the issue for you. Thanks for using SPE and letting us know about it and reporting the issue! We really appreciate your contribution!
