### ISSUE TITLE
I have written a powershell script for installing sitecore package in sitecore but it's giving below error

### ISSUE THREAD

**Issue by abhishekrnsit** [SitecorePowerShell/Console#425]
Hi,
Please help me out with this. I have written a powershell script for installing sitecore package in sitecore instance but it's throwing exception error. Please find the screenshot for this in attachments.

Below code I am assigning the value from xml file:
Invoke-SitecoreScript { 
 $PathFinderFile = "D:\Projects\DeployementProject\AmetekDeploymentScript\Build_Deploy_Scripts\Build_Scripts\FindPath.ps1"
   . $PathFinderFile
 $Target_folderSitecorePackage = FindPath "Target_folderToSitecoreZip"
   $SiteCorePackName = FindPath "SiteCorePackName"
   $SiteCorePackVersion = FindPath "Version"
   $PackageName = "SitecorePackage"+$SiteCorePackVersion+".zip"
   $PackagePath = $Target_folderSitecorePackage+"\"+$PackageName 
   Write-Host "$PackagePath"
   Import-Package -Verbose -Path "$PackagePath" -MergeMode "Merge" -InstallMode "Overwrite"} @{name = "value"}

I have hard coded the parameters for Invoke-SitecoreScript :

Invoke-SitecoreScript {Import-Package -Verbose -Path "D:\Spectro\AmetekPackageCreationFolder\SitecorePackage_21.0.0.0.zip" -MergeMode "Merge" -InstallMode "Overwrite"} @{name = "value"}

I am able to login in sitecore instance through powershell but the while installing a package its throwing exception, please find the screenshot for this in attachments. 

Please let me know if anything extra information I could provide on this. Thanks in advance!

![error](https://cloud.githubusercontent.com/assets/13437576/8805291/0f0ce3f6-2fee-11e5-86be-a588f3671997.jpg)

**Comment by michaellwest** [comment]
Can you install SPE 3.1 and follow this guide?

http://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/content/remoting.html

**Comment by abhishekrnsit** [comment]
Hi Michaell,

I have installed SPE 3.1, but when I opening sitecore powershell terminal it's throwing below error:

CodeBeside class "Cognifide.PowerShell.SitecoreIntegrations.Applications.PowerShellConsole,Cognifide.PowerShell" not found. (method: Sitecore.Web.UI.HtmlControls.CodeBeside.OnInit(EventArgs e)).

I have re-installed the SPE 3.0 and getting same error as above when opening sitecore powershell terminal. 

I think that is why remote automation service is not working :  "mysiteurl/Console/Services/RemoteAutomation.asmx"

I am not sure what I am missing out here. :(

Regards,
Abhishek

**Comment by AdamNaj** [comment]
Hi Abhishek,

is it possible that you've had an older version of SPE installed there before?
Can you try and follow this guide to see if there is anything there that is not migrated?
http://blog.najmanowicz.com/2015/02/27/upgrading-your-sitecore-powershell-extensions-from-2-x-to-3-x-what-you-need-to-know/

**Comment by abhishekrnsit** [comment]
Hi Adam,

I have followed the instruction, now the error which I were getting that has gone, but now when I am opening sitecore powershell terminal it's asking for login though I am already logged in sitecore.

**Comment by abhishekrnsit** [comment]
Please find the screenshot attached which I am getting now.
![image](https://cloud.githubusercontent.com/assets/13437576/8852370/74d41e40-3172-11e5-82eb-1b1742c4c9ce.png)

**Comment by abhishekrnsit** [comment]
Please find the screenshot attached the error which I am getting now.
![image](https://cloud.githubusercontent.com/assets/13437576/8852421/b0af358a-3172-11e5-9d4e-0e0f37f50774.png)

**Comment by AdamNaj** [comment]
Could you click on the Details button and paste the exception that will appear here?

Also - I wonder if logging out and back in won't help?

**Comment by abhishekrnsit** [comment]
Hi Adam, 

I have logged out and logged in but it didn't work. Please find the Exception screenshot attached which I am getting after hitting Details button. Thanks for helping.

![image](https://cloud.githubusercontent.com/assets/13437576/8868414/c608492a-31f5-11e5-9173-d569c3f9945e.png)

**Comment by AdamNaj** [comment]
I cannot reproduce it any longer - but I expect this to be fixed as part of the Issue #442. Please re-open it after SPE 3.2 is released if using it doesn't solve your issue.

**Comment by Hemantkeshri** [comment]
Hi Abhishek,
I am able to reproduce this issue. I think the issue might have been resolved by now, but may be this could help someone else in the forum,
Please make sure that .asmx are included in allowed extensions in web.config file as shown below.
<param desc="Allowed extensions (comma separated)">aspx, ashx,asmx</param>

Thanks
Hemant
