### ISSUE TITLE
Read-Variable dialog should support placeholder text and custom dropdown entry

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#427]
Now it's possible to do the following:

![image](https://cloud.githubusercontent.com/assets/933163/8850537/7595cc84-310e-11e5-8779-3781c228dd4b.png)

Combobox Placeholder:
```powershell
# The placeholder value will create a new option labeled *All* and have an empty string value.
@{Name="topCount"; Value="25"; Placeholder="All"; Title="Choose how much to return"; Options=$topOptions; Tooltip="Only the top results will be returned."; Columns=5;}
```

Textbox Placeholder:
```powershell
# The placeholder value will create background text for the textbox.
@{Name="searchText"; Value=""; Placeholder="Sample Item"; Title="Search Value"; Tooltip="Enter the text to search."; Columns="6";}
```

**Comment by michaellwest** [comment]
Implemented.

**Comment by AdamNaj** [comment]
This causes a problem with Sitecore 7 which does not have "Placeholder" property on Edit.

**Comment by AdamNaj** [comment]
for some reason the dialog looks like this on my machine:
![image](https://cloud.githubusercontent.com/assets/1209953/8889742/07c46a82-32e7-11e5-857e-64bcdd001b95.png)
:(

**Comment by michaellwest** [comment]
Fixed.
