### ISSUE TITLE
Add Report field renderer to easily render any item field.

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#433]
So Assuming you've added *Image* named - ```Image``` type field to Sample Item and set it on ```/sitecore/content/home``` item - the following script:
```powershell
Import-Function Render-ReportField
$items = Get-ChildItem master:\content | 
    Show-ListView -Property Name, Title, @{Name="Image"; Expression={Render-SitecoreField $_ "image" }}
```
might generate this report:

![image](https://cloud.githubusercontent.com/assets/1209953/8892343/2a4f758e-3354-11e5-9aaa-cbeb8d451efd.png)

The key here being the 
```powershell
Import-Function Render-ReportField
```
and then the use of the ```Render-SitecoreField``` function

**Comment by michaellwest** [comment]
Should the function be named Render-Field ?

**Comment by AdamNaj** [comment]
Implemented

**Comment by AdamNaj** [comment]
> Should the function be named Render-Field ?
Makes sense - or maybe ```Render-ItemField``` ?

**Comment by michaellwest** [comment]
Render-ItemField works too.
