### ISSUE TITLE
Add Report field renderer to easily render link to a script that will process a specific row..

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#434]
The following example script:
```powershell
Import-Function Render-ReportField
$script = Get-Item "master:\system\Modules\PowerShell\Script Library\Authorable Reports\Functions\Show-SearchResultDetails"
$index="sitecore_master_index"
$items = Get-ChildItem master:\ | Show-ListView -Property ProviderPath, 
    @{Label="Index Fields"; Expression={ Render-ScriptInvoker $script @{index=$index; itemId="$($_.Uri)"} "Show Index Fields" } } `
```
Will generate this report:
![image](https://cloud.githubusercontent.com/assets/1209953/8892452/4119948a-3358-11e5-8303-625e33a24074.png)
Clicking on the "Show Index Fields" link will run script for the row that was clicked.:
![image](https://cloud.githubusercontent.com/assets/1209953/8892459/7992622e-3358-11e5-9e8f-6497124c0424.png)

The key here being the 
```powershell
Import-Function Render-ReportField
```
and then the use of the ```Render-ScriptInvoker``` function

**Comment by AdamNaj** [comment]
Implemented.

**Comment by michaellwest** [comment]
What about calling it Render-Expression or Render-ItemFieldExpression?
