### ISSUE TITLE
Write Streams should output result to Console in real time.

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#438]
Akin to Issue #436 for Ise - this one is for Console.

Write-Progress is great but it would be better to be able to see progress in real time and not wait for all results. Can we have the other Write streams output to the blue pane incrementally rather than at the very end?

YES!

**Comment by michaellwest** [comment]
There is an issue I encounter when running commands. It doesn't complete until I click in the console and hit enter. Happens for something as simple as:

```powershell
1..10
```

**Comment by michaellwest** [comment]
![image](https://cloud.githubusercontent.com/assets/933163/8937558/09aa2b18-351f-11e5-8301-8f9f54c87040.png)

After click the text area and hitting enter.
![image](https://cloud.githubusercontent.com/assets/933163/8937563/17a0e112-351f-11e5-9d27-9fb1144e744e.png)

**Comment by AdamNaj** [comment]
Bah! You broke it!

**Comment by AdamNaj** [comment]
There... fixed it... be careful now, I'm not fixing it again!

**Comment by michaellwest** [comment]
Try this in the ISE.

```powershell
[Sitecore
```
