### ISSUE TITLE
Error Opening PowerShell ISE

### ISSUE THREAD

**Issue by HabDaddy** [SitecorePowerShell/Console#440]
Installed v3.1 on Sitecore 7.2 Update 2.  Already had SPE v3.0 installed.  Opening the console and the toolbox work fine but when selecting the ISE, get the following error:

Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 
[NullReferenceException: Object reference not set to an instance of an object.]
   Cognifide.PowerShell.Client.Applications.PowerShellIse.OnLoad(EventArgs e) +1396
[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +76
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +193
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
   Sitecore.Web.UI.Sheer.ClientPage.OnLoad(EventArgs e) +337
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3178

This occurs when in the Master database.  If I switch to the Core database, the ISE opens fine.

**Comment by michaellwest** [comment]
@HabDaddy Perhaps this is the issue

#394 - Missing Home item (fixed in 3.2 - interim workaround found in the issue conversation)

**Comment by HabDaddy** [comment]
That was it.  Thx.
