### ISSUE TITLE
Console doesn't retain job after application pool recycle caused by exception

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#442]
Reported the issue to @AdamNaj and shared the details on Skype.

**Comment by michaellwest** [comment]
Thoughts?

![image](https://cloud.githubusercontent.com/assets/933163/8990350/3b7161d6-36b7-11e5-822c-d5fcd6755cb7.png)

**Comment by AdamNaj** [comment]
Let's talk about it tonight. I think there might be a misunderstanding here.

**Comment by AdamNaj** [comment]
As commented on the commit - this is now considered fixed. Thanks for finding this Mikey!
