### ISSUE TITLE
Toolbox - Add Item Version Pruner

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#443]
Build something like this for SPE

https://github.com/sitecorepm/SitecoreVersionPruner

**Comment by AdamNaj** [comment]
This sounds more like something for a separate module. 
The logic part of it is achievable with a single-liner with implementation provided in #532 as demonstrated [in the Gist](https://gist.github.com/AdamNaj/b36ea095e3668c22c07e)
