### ISSUE TITLE
Get-ChildItem support for ID parameter

### ISSUE THREAD

**Issue by marrrcin** [SitecorePowerShell/Console#444]
Although Get-Item does support ID parameter, which translates ID to Sitecore Item ID, the Get-ChildItem commandlet does not support it. It will be a nice to have feature which will prevent us from writing:
```
Get-ChildItem (Get-Item . -ID "{GUID}").Paths.Path
#or
Get-ChildItem -Item (Get-Item . -ID "{GUID}")
```

**Comment by AdamNaj** [comment]
Implemnted
