### ISSUE TITLE
Add Type Accelerators for commonly used types

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#446]
Example:
```powershell
[psobject].Assembly.GetType("System.Management.Automation.TypeAccelerators")::Add('AccountIdentity',"Cognifide.PowerShell.Commandlets.Security.AccountIdentity")
```

* [x] Item
* [x] ContentSearchResult
*  [x] AccountIdentity

**Comment by AdamNaj** [comment]
Done for the following types:

Accelerator | Type 
 ----------- | ---- 
 Item | Sitecore.Data.Items.Item 
AccountIdentity | Cognifide.PowerShell.Commandlets.Security.AccountIdentity
SearchResultItem | Sitecore.ContentSearch.SearchTypes.SearchResultItem
Database | Sitecore.Data.Database
Account | Sitecore.Security.Accounts.Account
User | Sitecore.Security.Accounts.User
Role | Sitecore.Security.Accounts.Role
AccessRule | Sitecore.Security.AccessControl.AccessRule

**Comment by AdamNaj** [comment]
Closing it for now as it satisfies acceptance criteria. We might add more accelerators later.
