### ISSUE TITLE
Searching sitecore broken links in all versions 

### ISSUE THREAD

**Issue by Asugusto** [SitecorePowerShell/Console#448]
Hi everyone,

I notice that Reporting Tools > PowerShell reports > Content Audit > Broken links give me a report of broken links for all  last version items. My problem it's that i have a broken link in an older versions. Can i change they way to make this query?
I tried to delete this broken link at /sitecore/admin/removebrokenlinks.aspx. But it only shows the item that has the broken link, not the version.

Thanks

**Comment by michaellwest** [comment]
Hey @Asugusto I'm taking a look at that now. I think I'll have a solution to let you choose the latest or all versions, and include the version in the report.

**Comment by michaellwest** [comment]
Adding this:

![image](https://cloud.githubusercontent.com/assets/933163/9124307/73bdcba2-3c5b-11e5-9a0d-c18ef22bc36c.png)

**Comment by AdamNaj** [comment]
Mikey, if this is now handled, let's close it and release with 3.2.1

**Comment by michaellwest** [comment]
Implemented. @Asugusto we'll have this out in the next release. If you want the code early check out the serialized item in the repo. Let me know if you need help extracted the script text.
