### ISSUE TITLE
Console doesn't output first set of partial results

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#449]
Found a situation where *partial* results existed, the status was set to *working*, and the console only output the second+ results. The web service does return the initial set of data.

**Comment by michaellwest** [comment]
Before:

![image](https://cloud.githubusercontent.com/assets/933163/9148364/0121f200-3d3f-11e5-982b-4cab4093b7f8.png)


After:
![image](https://cloud.githubusercontent.com/assets/933163/9148368/1b8d6c5a-3d3f-11e5-85a3-e5979b401b3d.png)

**Comment by michaellwest** [comment]
@AdamNaj Should we include this as a 3.2.1?

**Comment by AdamNaj** [comment]
I wonder - since the console was not yet released on Marketplace we could just replace the binary and the .js files in the packages?

**Comment by AdamNaj** [comment]
Fixed
