### ISSUE TITLE
Ability to download any file or media item in a CI scenario

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#454]
As made clear by [this conversation](https://twitter.com/techphoria414/status/629391119143469057) we need an ability to download any file or media item created as a result of a remoting script operation.

**Comment by michaellwest** [comment]
With some more details I'll be able to write some module commands to help wrap the functionality.

**Comment by AdamNaj** [comment]
new functionality of the Restful API:

The type, origin and location now feature some new modes. first let me introduce the syntax
http://hostname/-/script/**type**/**origin**/**location**

Type | Origin | Location | Sample URL
--- | --- | --- | ---
media | database | root relative path | ```http://hostname/-/script/media/master/sitecore/media library/Default Website/cover```
media | database | media library relative path | ```http://hostname/-/script/media/master/Default Website/cover```
media | database | media item ID | ```http://hostname/-/script/media/master/{04DAD0FD-DB66-4070-881F-17264CA257E1}```
file | drive name (e.g. *c*) | drive relative path | ```http://hostname/-/script/file/c/?path=inetpub/wwwroot/sitecore8/Data/packages/package.zip```
file | package | package folder relative path | ```http://hostname/-/script/file/package/?path=package.zip```
file | data | data folder relative path | ```http://hostname/-/script/file/data/?path=packages\package.zip```
file | log | logs folder relative path | ```http://hostname/-/script/file/log/?path=log.20150807.txt```
file | media | media folder relative path | ```http://hostname/-/script/file/media/?path=image.png```
file | serialization | serialization folder relative path | ```http://hostname/-/script/file/serialization/?path=master\sitecore\templates\Modules.item```
file | apptemp | Sitecore temp folder relative path | ```http://hostname/-/script/file/apptemp/?path=tempfile.tmp```
file | debug | Sitecore debug folder relative path | ```http://hostname/-/script/file/debug/?path=somefile.ext```
file | index | Sitecore index folder relative path | ```http://hostname/-/script/file/index/?path=sitecore_master_index/segments.gen```
file | app | Sitecore website folder relative path | ```http://hostname/-/script/file/app/?path=web.config```
file | temp | system temp folder relative path | ```http://hostname/-/script/file/temp/?path=temp.tmp```
file | tmp | system tmp folder relative path | ```http://hostname/-/script/file/tmp/?path=temp.tmp```

**Comment by michaellwest** [comment]
Yay! Thank you for documenting all of these scenarios. Receive command is coming along nicely.

**Comment by michaellwest** [comment]
@AdamNaj I think the following should be considered for *file* usage.

Remove:
* temp
* tmp
* index
* file - using drive name. only a relative path to the folder should be allowed.

Rename:
* apptemp changed to temp

**Comment by michaellwest** [comment]
Making some progress on the *Receive-File* command used in SPE Remoting.

![image](https://cloud.githubusercontent.com/assets/933163/9266595/dc464dcc-4208-11e5-9739-386c464e5fee.png)

**Comment by michaellwest** [comment]
Works for both with and without a Session object. Sessions unnecessarily create a proxy object if you never run a remote script. I've remove that in the example but it will still work as expected.

![image](https://cloud.githubusercontent.com/assets/933163/9267256/7afa6c66-4211-11e5-9f9e-b35572f67e28.png)

**Comment by AdamNaj** [comment]
done & done
