### ISSUE TITLE
Get-ItemReference command returns SourceItem instead of TargetItem

### ISSUE THREAD

**Issue by Kasaku** [SitecorePowerShell/Console#455]
When used with the -Item parameter, the Get-ItemReference command returns a distinct list of all of the SourceItems provided by `GetReferences`. The result of this is the returned list will always just be of the item you are passing into the command.

If I have understood the use of the command correctly, I think the intention here should be to return the TargetItems instead, so that you get returned a list of items that the context item is referencing?

This is not a problem with the ItemLink implementation, since from that you can select either the SourceItem or the TargetItem.

It's a simple fix and I'll follow this with a pull-request of the suggested change.

**Comment by Kasaku** [comment]
As an additional note, the names `Get-ItemReferences` and `Get-ItemReferrers` might make this easier to see that these both return a collection of items? Or is this a deliberate style choice?

**Comment by michaellwest** [comment]
Regarding the naming convention, PowerShell has a standard of Verb-Noun with the noun in a singular form. The verbs also fall within an approved list.

**Comment by Kasaku** [comment]
Ah, ok, I thought it might come from a convention, and now that I look it up:

From https://technet.microsoft.com/en-us/library/dd878270(v=vs.85).aspx#SD01:
> To enhance the user experience, the noun that you choose for a cmdlet name should be singular. For example, use the name Get-Process instead of Get-Processes. It is best to follow this rule for all cmdlet names, even when a cmdlet is likely to act upon more than one item.

**Comment by AdamNaj** [comment]
Merged your Pull request #456. Thanks for taking the time to fix it!
