### ISSUE TITLE
Show that ISE script is modified and not yet saved

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#458]
The ISE should indicate that modifications were made a script and the changes have not yet been saved.

![image](https://cloud.githubusercontent.com/assets/933163/9266489/4aaae5ae-4207-11e5-931a-149af039a50f.png)

**Comment by AdamNaj** [comment]
![image](https://cloud.githubusercontent.com/assets/1209953/11334317/9516e7e2-91d4-11e5-9c96-77594c0283df.png)
