### ISSUE TITLE
Upgrade Console

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#469]
We're on version 0.6.3 of jQuery Terminal and the latest is 0.8.8.

http://terminal.jcubic.pl/

The upgrade should remove all custom code from within the old version of the plugin

The upgrade should enhance the console with syntax highlighting

**Comment by AdamNaj** [comment]
Not touching it, until it stops working :)

**Comment by michaellwest** [comment]
Upgraded the terminal to a new version 1.11.3 with commit 9d23413a04008115db1443a606b6d558c1265812.

**Comment by AlexKasaku** [comment]
Ooh, nice!

**Comment by michaellwest** [comment]
Added a707b42d34482baaeb4c993badc4130eaf086662 and fd7a2599fe88a8238d000d64b90bb183c072af28 but forgot to comment with the issue number.

**Comment by michaellwest** [comment]
Implemented.
