### ISSUE TITLE
Add "password" editor to enable asking for credentials in Read-Variable and Read-Host

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#473]
Try...
```powershell
Read-Host -AsSecureString
```

or
```powershell
Read-Variable -Parameters @{name="someString"; editor="password"}
```

Example dialog:
![image](https://cloud.githubusercontent.com/assets/1209953/9469590/3841cd20-4b48-11e5-8a06-d57489fe72cc.png)

**Comment by AdamNaj** [comment]
Implemented.

**Comment by michaellwest** [comment]
That is a great idea! Does it do any conversion with ConvertTo-SecureString?

**Comment by AdamNaj** [comment]
Not with the cmdlet, no. But it converts to Secure string where the PowerShell expects it (In the HostUI - ReadLineAsSecureString and in the Prompt method where SecureString is expected as output). Otherwise it just returns string, but obfuscate the letters on the screen.
