### ISSUE TITLE
Anti-package feature is not working

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#478]
Hi guys,

It seems that feature introduced here
**Add command to create anti-package #337**
is not working. Or I am using it in wrong way.

When I try to create anti-package using PS Toolbox following errors appears:
http://pastebin.com/gACUAHDN
As a package I selected PS 3.2 release package.

Below my host info
```
PS master:\>Get-Host
 
Name             : Sitecore PowerShell Extensions Host 3.2.0.20133 on Windows PowerShell 3.0 & Sitecore 8.0
Version          : 3.2.0.20133
InstanceId       : c61d7889-faca-4b54-8363-f761c26c7acd
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en
PrivateData      : Cognifide.PowerShell.Core.Host.ScriptingHostPrivateData
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Additional info:**
When I am trying to generate anti package using some package with package project, package is created, but I am still getting this error:
```
New-FileSource : Cannot bind argument to parameter 'Name' because it is an empty string.
At line:204 char:59
+             $package.Sources.Add(($files | New-FileSource @props))
+                                                           ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-FileSource], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Cognifide.PowerShell.Commandlets.P
   ackages.NewFileSourceCommand
```

Do I need package project/solution in order to generate AntiPackage? I would expect that I can generate anti package without project, basing only on info that is inside package.

**Comment by michaellwest** [comment]
Hey @alan-null, can you confirm that you followed the examples outlined here?

/sitecore/system/Modules/PowerShell/Script Library/Platform/Development/PowerShell Extensions Maintenance/Prepare Console Distribution

**Comment by alan-null** [comment]
what do you mean exactly?

I am little bit confused.
I just wanted to use this 
![image](https://cloud.githubusercontent.com/assets/6848691/9582538/3ad7a588-5006-11e5-905a-ce7b179caf02.png)

when I select any package I am getting random errors.

I expected empty anti package for Sitecore PowerShell release package because it is already installed on my instance.

**Comment by michaellwest** [comment]
Thanks for reporting the issue. Found some other issues to address.

**Comment by michaellwest** [comment]
@alan-null can you run this script here to see if it corrects the error you encountered?

https://gist.github.com/michaellwest/add2fff8744dfa62ab77

If so, you can save the contents of the script to this path:
/sitecore/system/Modules/PowerShell/Script Library/Package Generator/Toolbox/Create Anti-Package

The next release will include the fix.

**Comment by alan-null** [comment]
Hi @michaellwest,

Thanks. This solves the problem with PS Release package and some of my internal packages.
However I was able to find a new issue.

**Steps to reproduce**:
1. Create new package project with dynamic files as a source.
2. Save project
3. Generate package zip
4. Try to generate anti package.

**Result:**
Package was generated, I don't know if it is 100% correct, but I can see something like that on the script output.
```
New-FileSource : Cannot bind argument to parameter 'Name' because it is an empty string.
At line:219 char:59
+             $package.Sources.Add(($files | New-FileSource @props))
+                                                           ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-FileSource], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Cognifide.PowerShell.Commandlets.Packages.NewFileSourceCommand
```

**Resources:**
Please check if you can generate anti package for this one. I am getting error above.
[PSResources.zip](https://www.dropbox.com/s/nha6yzrrbvsy8dk/PSResources.zip)
[PSResources.xml](https://www.dropbox.com/s/r01ixtv3c8uthyp/PSResources.xml)

**Comment by michaellwest** [comment]
@alan-null can you please run the script from the gist again? I've updated it to account for that missing name. The *ItemSource and *FileSource commands depend on the name to be present. I added a check to generate a guid name if the package source is unnamed.

https://gist.github.com/michaellwest/add2fff8744dfa62ab77

**Comment by alan-null** [comment]
Hi @michaellwest,
No errors now. Thanks.

**Comment by michaellwest** [comment]
That's great to hear @alan-null . As you can see I've committed the changes and it will be included in the next release. Thank you for using SPE!

**Comment by AdamNaj** [comment]
Like he had a choice, his freaking boss is obsessed with it :D
