### ISSUE TITLE
Rebuilding integrations shouldn't throw errors for normal behaviour

### ISSUE THREAD

**Issue by Kasaku** [SitecorePowerShell/Console#480]
When integrations are rebuilt in the ISE, if a module is being added to a gutter or Content Editor ribbon an error is thrown. This is down to a Get-Item command being performed to check if this module already exists.

This doesn't actually cause a problem, as the script goes on to null-check the result of Get-Item and proceeds to add the new module. However, as the output shows the error it can be confusing to the user whether the script has executed successfully or not.

I think this could make use of the `-ErrorAction SilentlyContinue` option in Powershell so that this particular error isn't output to the result window.

**Comment by michaellwest** [comment]
Thank you for updating this. I saw it in the past but never got around to making a change.

**Comment by AdamNaj** [comment]
I guess we can close it as fixed :)
