### ISSUE TITLE
Check PowerShell version during installation 

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#482]
The current version of PowerShell should be validated  and a user must be informed about SPE prerequisites.
Some of the features included in PowerShell Console for Sitecore may not work without proper version of PS.

**Comment by michaellwest** [comment]
One additional thing we can do is include the following at the top of scripts

# Requires -version 3

This tells PowerShell the minimum requirement to run it.

**Comment by michaellwest** [comment]
I believe we may be beyond the need for this now, as it pertains to PS v2; Windows 10 and newer includes PS 5.

**Comment by michaellwest** [comment]
Please reopen if we should reconsider. Perhaps an option is to include a post install step to log dependency  issues.
