### ISSUE TITLE
Get-User throws an error when not found by Identity

### ISSUE THREAD

**Issue by pveller** [SitecorePowerShell/Console#483]
Hey Guys, 

why did you decide to `throw` in `Get-User` if not found by `Identity`:

```
Get-User : Cannot find an account with identity 'sitecore\bizzaro.md'.
At line:45 char:13
+     $user = Get-User -Identity $record.Login
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sitecore\bizzaro.md:AccountIdentity) [Get-User], ObjectNotFoundException
    + FullyQualifiedErrorId : Cannot find an account with identity 'sitecore\bizzaro.md'.,Cognifide.PowerShell.Commandlets.Security.GetUserCommand
```

Wouldn't it be more in Powershell spirit to just return an empty list? Like `Get-Item` would do, for example. Maybe I am missing something special about the users.

**Comment by michaellwest** [comment]
Hey @pveller, this behavior more closely aligns with the Active Directory commands. Get-ADUser -Id Michael.West would throw an error if the account didn't exist. 

You'll want to use the filter instead.

```powershell
Get-User -Filter "*.west"
```

**Comment by pveller** [comment]
Well, I see. I don't like the filter in my case as I want to be very precise with what I am getting back. Thanks anyway. I have another question but will submit a separate issue :)

**Comment by michaellwest** [comment]
Don't give up so quick! You can also do this:

```powershell
Get-User -Id 'sitecore\bizzaro.md' -ErrorAction SilentlyContinue
```

**Comment by Kasaku** [comment]
`Get-Item` does indeed throw an error if it can't find the item, which is how standard Powershell behaves with the file system. As @michaellwest has said though, you can add a parameter to suppress the error, and then perform a null check yourself. 

The ErrorAction is a standard parameter so should work across all commands.
