### ISSUE TITLE
Ability to peek variable value in a persisten ISE session.

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#495]
When a script is executed in an ISE persistent session - the value should be "peek-able" after the script execution.

![image](https://cloud.githubusercontent.com/assets/1209953/12071551/eb078958-b0b1-11e5-9c28-df48cc73f3af.png)

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/sMBLj87x51I/0.jpg)](http://www.youtube.com/watch?v=sMBLj87x51I)

**Comment by michaellwest** [comment]
I approve.

**Comment by AdamNaj** [comment]
Done.

**Comment by AdamNaj** [comment]
Test gist: https://gist.github.com/AdamNaj/2a878023d08ace2908ee
