### ISSUE TITLE
Remoting : Ability to work with $Using:variable in the scriptblock

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#499]
Currently you must use the $params variable. While this works and is effective, an alternative approach, which aligns with the usage of Invoke-Command through PowerShell Remoting, will work the same way.

![image](https://cloud.githubusercontent.com/assets/933163/9903540/c6a38f72-5c3c-11e5-9a85-ead336bdebe6.png)

**Comment by pbering** [comment]
+1

**Comment by AdamNaj** [comment]
Sounds like a great idea that would really help simplifying the usage of remoting!

**Comment by AdamNaj** [comment]
Is that implemented now?

**Comment by michaellwest** [comment]
This is implemented.
