### ISSUE TITLE
Set-Layout command seems not to work

### ISSUE THREAD

**Issue by AbsoluteSoftwareGmbh** [SitecorePowerShell/Console#503]
Hello together,

after many tries i suspect in versions 3.3 for Sitecore 8 (rev. 150121), the set-layout command seems not to work. The item shows "[No layout specified]".

Example:
```powershell
@(get-item . -language *) + (get-childitem . -r -language *) | foreach-object { resetFields($_) }
function resetFields($_item)
{
        $_CP = get-item master:/content/fischer-global-content/home/"fischer innovations"/"fastfix"
        $_LayoutDevice = Get-LayoutDevice -name "default"
        $_CPLayout = Get-Layout -item $_CP -device $_LayoutDevice
        
        if ($_execute -eq 1)
        {
            $_item | Reset-ItemField -IncludeStandardFields
            set-layout -item $_item -Device $_LayoutDevice -layout $_CPLayout
        }
}
```
Thanks in advance
AbsoluteSoftwareGmbh

**Comment by AdamNaj** [comment]
Hi,

Unfortunately the Layout cmdlets have not been brought up to the functionality of Sitecore 8 shared/final renderings and could be currently broken. I'll look into it and their general performance and "making sense" aspects in the next version. Thanks for bringing it up to our attention - there is so much functionality in SPE that we cannot explicitly focus on everything and rather focus on bits we know people actually use and want functional. Which you have just proven :)

Thank you for using SPE!

**Comment by AdamNaj** [comment]
Sitecore 8 support added - this now This can now be accomplished adding the `-FinalLayout` parameter when working with final layouts, which I expect to be your case.
