### ISSUE TITLE
cmdlets for managing clone notifications

### ISSUE THREAD

**Issue by mikaelnet** [SitecorePowerShell/Console#505]
Hi,

I’d like support for managing clone notifications, so that we can query/accept/reject the different types of notifications on item clones.

Best regards
// Mikael

**Comment by AdamNaj** [comment]
Implemented

**Comment by michaellwest** [comment]
Sweet. Never used it but I'm sure it's gonna be great!

**Comment by mikaelnet** [comment]
Nice! And thank you for the demo!

**Comment by AdamNaj** [comment]
The pleasure was mine! :)
