### ISSUE TITLE
3.3 upgrade error

### ISSUE THREAD

**Issue by reedyd** [SitecorePowerShell/Console#509]
I have multiple Sitecore web sites in development, all pointing to the same Sitecore databases. To prevent problems, I only run one dev web site at a time. This works, as far as Sitecore goes.

I got PSE working in my Dev2 by upgrading my Windows PS to v3.0 (thanks to advice from https://github.com/SitecorePowerShell/Console/issues/508#issuecomment-146388365). Then I tried to launch PSE in Dev1, but got the same problem. Very strange, since the solution in Dev2 was at the OS level, not the web site. In any case, I retried installing v3.0, but the runtime error persisted.

So then I tried to install v3.3. I keep getting this error now in both Dev1 & Dev2 with the 3.3 installation:

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 
[NullReferenceException: Object reference not set to an instance of an object.]
   Cognifide.PowerShell.Core.Modules.ModuleManager.get_Modules() +287
   Cognifide.PowerShell.Core.Modules.ModuleManager.GetFeatureRoots(String featureName) +153
   Cognifide.PowerShell.Integrations.Pipelines.PipelineProcessor`1.Process(TPipelineArgs args) +220

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +76
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +211
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
   Sitecore.Nexus.Pipelines.NexusPipelineApi.Resume(PipelineArgs args, Pipeline pipeline) +398
   Sitecore.Pipelines.Pipeline.Start(PipelineArgs args, Boolean atomic) +366
   Sitecore.Pipelines.Pipeline.Start(String pipelineName, PipelineArgs args, Boolean atomic) +197
   Sitecore.Web.Authentication.TicketManager.Login(Ticket ticket) +182
   Sitecore.Web.Authentication.TicketManager.Relogin(String ticketId, Boolean redirect) +308
   Sitecore.Pipelines.HttpRequest.UserResolver.Process(HttpRequestArgs args) +265
   (Object , Object[] ) +83
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +365
   Sitecore.Nexus.Web.HttpModule.(Object , EventArgs ) +457
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +92
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +165

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34249

**Comment by michaellwest** [comment]
So you have one instance of SQL running with the master core and web databases. Those 3 databases support three installations of Sitecore  websites. Then you installed SPE in one of those instances of Sitecore, which means that the assets are missing from the other two. What happens if you install the package in all three websites?

**Comment by AdamNaj** [comment]
OK this looks suspiciously like an issue #310 and #325 I think I might have confused you with my response to #508. This issue that you are experiencing right now seems to be related to SPE 3.0 and should be rectified by installing the latest verison of SPE (3.3)

Risking being wrong in thinking that you might have misunderstood my previous suggestion but I am going to explain it just in case. Windows PowerShell 3.0 or 4.0 that I suggested to install is part of the [Windows Management Framework](https://www.microsoft.com/en-us/download/details.aspx?id=40855). 
I suggest that you install WMF 4.0 on the OS level and SPE 3.3 on the Sitecore level (this one needs to be done on each of your Sitecore servers separately).

**Comment by AdamNaj** [comment]
One thing to do before reinstalling 3.3 - please remove the spe config file as otherwise you might have trouble installing SPE 3.3 over 3.0 (as I think I suggested in one of the previous issues.

**Comment by reedyd** [comment]
Installed WMF 4.0, and verified Windows PS is at v4.0 now.
Removed Cognifide.PowerShell.config & reinstalled PSE 3.3. It ran clean.
PSE Console runs fine. Verified PSE is at v3.3 now.
At startup, PSE ISE throws the other error again ( #508 )
Argh!

**Comment by AdamNaj** [comment]
ok. let's close this one and re-open #508 - I think I know the reason...
