### ISSUE TITLE
Remove compatibility fix for 2.x services location to fix incompatibility with Insite Commerce

### ISSUE THREAD

**Issue by kondapallysrknth** [SitecorePowerShell/Console#511]
Hello there,

I recently installed SPE 3.3 version on to our Sitecore instance and the tool is very nice and great work to all the team. 
We also use Insite Commerce in our application and it is usually accessed by [hostname]/console. Insite is no longer working after the installation of SPE module. So, I had to go through lot of debug scenarios and finally figured out that it was happening in the RewriteUrl.cs module located at Cognifide.PowerShell.Core.Processors at this particular condition.[Image attached]

![condition](https://cloud.githubusercontent.com/assets/15020413/10439108/658bbcd4-70fd-11e5-83b7-31afcd1f8912.png)

So, I decided to write our own custom rewritemodule.cs class and reference it in the config file. 

I wanted to confirm it with your team; by removing this line of code will not cause any issues with SPE functionality.

Thanks in advance.
Srikanth Kondapally

**Comment by michaellwest** [comment]
We added that I believe because a different application encountered issues
with the URL. If you can provide a code sample that fixes it we'll just
merge that into the next release.

**Comment by AdamNaj** [comment]
This was to support some possibly leftover obsolete code - this rewrite can now be removed. I'll do that before we release 4.0 as it should no longer be needed.

**Comment by kondapallysrknth** [comment]
Thank you. 

Removing that line of code was helpful and now both Insite and SPE module are working as expected.

**Comment by AdamNaj** [comment]
Fixed.
