### ISSUE TITLE
remove-item -Item displays path dialog

### ISSUE THREAD

**Issue by krzysztof-chmiel** [SitecorePowerShell/Console#515]
When running following script:
```powershell
$item = gi -path '/sitecore/content/Internal Group/mvc/mvc/Home/kris'
remove-item -Item $item -WhatIf
```
I get the popup "cmdlet Remove-Item at command pipeline position 1 Supply values for the following parameters: Path" asking for item path.

All is ok when I change a bit and run it as a pipeline:
```powershell
$item = gi -path '/sitecore/content/Internal Group/mvc/mvc/Home/kris'
$item | remove-item -WhatIf
```

**Comment by michaellwest** [comment]
It's likely due to the fact that PowerShell doesn't assume which provider you are using. At minimum master:\ should be set for the path. When using the pipeline PowerShell will map the path automatically.

**Comment by AdamNaj** [comment]
in your first scenario you can use the following syntax to avoid piping:
```powershell
$item = gi -path '/sitecore/content/Internal Group/mvc/mvc/Home/kris'
remove-item -Path $item.ProviderPath -WhatIf
```
As Michael highlighted PowerShell needs the drive qualifier to be able to tell to which provider send the item for handling. Specifying it using Item parameter is not sufficient as ```-Item``` is a dynamic parameter. that is used only when the provider can be established beforehand using the path qualifier.
