### ISSUE TITLE
A potentially dangerous Request.Path value was detected from the client (:)

### ISSUE THREAD

**Issue by kondapallysrknth** [SitecorePowerShell/Console#516]
Hello there,

I am trying to use Receive-RemoteItem function which is part of SPE Remoting module through Windows PowerShell Console and I get this error. Example: 
```powershell
Receive-RemoteItem -Session $session -Path "/sitecore/media library/18ComProduct/Desktop" -Database master -Destination "C:\Temp"
```
10944 14:52:24 ERROR Application error.
Exception: System.Web.HttpException
Message: A potentially dangerous Request.Path value was detected from the client (:).
Source: System.Web
   at System.Web.HttpRequest.ValidateInputIfRequiredByConfig()
   at System.Web.HttpApplication.PipelineStepManager.ValidateHelper(HttpContext context)

Am I doing anything wrong over here?

Thanks in advance
Srikanth Kondapally

**Comment by michaellwest** [comment]
One thing I see is that if using RootPath the Path argument should be relative.

Receive-RemoteItem -Session $session -Path "ReleasePackages\package.zip" -RootPath Package -Destination "C:\Temp"

I type this from my phone so not yet tested.

**Comment by kondapallysrknth** [comment]
Thanks for the response Michael.

I corrected the call to be as follows,

Receive-RemoteItem -Session $session -Path "ReleasePackages\SampleXMLPackage1.xml" -RootPath Package -Destination "C:\Temp"

I still see the exception as "ERROR Error during uploading file using PowerShell web service"

Note:I copied this Receive-RemoteItem function from the SPE remoting module 3.3 into Sitecore under and added it under "/sitecore/system/Modules/PowerShell/Script Library" and trying to execute it using PowerShell ISE in sitecore itslef.

**Comment by michaellwest** [comment]
Hey @kondapallysrknth Just want to be clear on the approach we recommend.

If your intent is to operate outside of Sitecore, using the Windows PowerShell ISE, you should use the SPE Remoting module and commands available within it.

If your intent is to operate inside of Sitecore, you should use Receive-File or Send-File.

**Comment by AdamNaj** [comment]
Closing as I understand it has been resolved
