### ISSUE TITLE
trying to get size value from media library items

### ISSUE THREAD

**Issue by fosscampbell** [SitecorePowerShell/Console#522]
I'm needing to get a report with the file sizes of the items in the media library. Editing the "Database Based Media Items" script to include this line:

    @{Label="Size"; Expression={$_.__Size} }

is not returning the size field value. I've also tried .Size to no avail. Is this possible to get and if so, what is the syntax that I am getting incorrect?

Thank you!
Drew

**Comment by alan-null** [comment]
hi @fosscampbell 

I was able to execute the following code
```powershell
$mediaItem = gi -path "/sitecore/media library/Default Website/sc_logo"

$mediaItem.Size
$mediaItem.Fields['Size'].Value
```
and it returned the following output
```
4081
4081
```
Try this code snippet.

Make sure your items are indeed media items.
Are you sure you didn't change the type before via some additional operation inside pipe?

**Comment by fosscampbell** [comment]
Thanks, @alan-null 

I was editing a script from the PSE. This is the full script:

    <#
        .SYNOPSIS
            Lists all media items that are database based.
        
        .NOTES
            Michael West
    #>
    function IsNotFileBased {
        param(
            $Item
        )
        
        !(New-Object Sitecore.Data.Items.MediaItem $item).FileBased
    }
    
    function Get-MediaItemNotFileBased {
        $items = Get-ChildItem -Path "master:\sitecore\media library\Images\Properties\id0\0\0\0\e28b6c394686b2b2401dfcdffd9b" -Recurse | Where-Object { $_.TemplateID -ne [Sitecore.TemplateIDs]::MediaFolder }
        
        foreach($item in $items) {
            if(IsNotFileBased($item)) {
                $item
            }
        }
    }
    
    $items = Get-MediaItemNotFileBased
    
    if($items.Count -eq 0){
        Show-Alert "There are no database based media items"
    } else {
        $props = @{
            InfoTitle = "Database based media items"
            InfoDescription = "Lists all media items that are database based."
            PageSize = 25
        }
        
        $items |
            Show-ListView @props -Property @{Label="Name"; Expression={$_.DisplayName} },
                @{Label="Updated"; Expression={$_.__Updated} },
                @{Label="Updated by"; Expression={$_."__Updated by"} },
                @{Label="Size"; Expression={$_.Size} },
                @{Label="Path"; Expression={$_.ItemPath} }
    }
    Close-Window

adding the .value doesn't seem to work in this way either. Maybe there is a better way to write this for the report I'm looking for?

Cheers!

**Comment by alan-null** [comment]
@fosscampbell 
I edited the script little bit. In the fist line put the root path for your report. 
See screenshot below code. Everything looks fine, I can see file Size
```powershell
$mediaFolderPath = "/sitecore/media library/Default Website"

function IsNotFileBased {
    param($Item)
    !(New-Object Sitecore.Data.Items.MediaItem $item).FileBased
}

function Get-MediaItemNotFileBased {
    $items = Get-ChildItem -Path $mediaFolderPath -Recurse | Where-Object { $_.TemplateID -ne [Sitecore.TemplateIDs]::MediaFolder }

    foreach($item in $items) {
        if(IsNotFileBased($item)) {
            $item
        }
    }
}

$items = Get-MediaItemNotFileBased

if($items.Count -eq 0){
    Show-Alert "There are no database based media items"
} else {
    $props = @{
        InfoTitle = "Database based media items"
        InfoDescription = "Lists all media items that are database based."
        PageSize = 25
    }

    $items |
        Show-ListView @props -Property @{Label="Name"; Expression={$_.DisplayName} },
            @{Label="Updated"; Expression={$_.__Updated} },
            @{Label="Updated by"; Expression={$_."__Updated by"} },
            @{Label="Size"; Expression={$_.Size} },
            @{Label="Path"; Expression={$_.ItemPath} }
}
```
![image](https://cloud.githubusercontent.com/assets/6848691/11008945/f6aff6c8-84d3-11e5-81e4-5cfef0456bc2.png)

 Hope it helps.

**Comment by fosscampbell** [comment]
I'm getting the same results with this. I'm thinking this may be an install issue or a Sitecore version issue.

![2015-11-06_1424](https://cloud.githubusercontent.com/assets/15695083/11010249/584e66cc-8492-11e5-8141-03d5b6875770.png)

I installed PSE into a clean version of Sitecore 7.5 and I am getting the data back as expected. I'll need to look into what was not installed correctly in our production version. Sorry for the bother - you have confirmed that my expectation of what I want to happen should - I'm not going crazy. Much appreciated!

![2015-11-06_1453](https://cloud.githubusercontent.com/assets/15695083/11010745/389a176e-8496-11e5-8b58-ac3da7162699.png)

**Comment by alan-null** [comment]
no problem. Have fun ;)
