### ISSUE TITLE
Harden security for Client Applications

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#527]
Issue reported by @jammykam on Slack. 

I have a User who belongs to the Client Authoring role. They do not access to SPE and it does not appear in the shortcuts/menus. But if they log in and type in the URL directly they can access SPE console.

The fix is to check if they have access....

By  calling `Assert.CanRunApplication("Files/path-to-application")`. This in turn checks if the user has read access to the item in `/sitecore/content/Applications/` in Core DB(edited)

**Comment by AdamNaj** [comment]
Implemented
