### ISSUE TITLE
UseDefaultCredentials for New-WebServiceProxy

### ISSUE THREAD

**Issue by rogiervanhetschip** [SitecorePowerShell/Console#531]
Hey!

Nice tool, saves us a lot of time!

We want to use SPE in our Continuous Delivery scripts, which run under Windows credentials we (developers) don't have access to. Would it be a good idea to extend several of the scripts (including Invoke-RemoteScript) with the UseDefaultCredentials parameter? This parameter is supported by New-WebServiceProxy, for creating a session with the current credentials. Also see https://technet.microsoft.com/en-us/library/hh849841.aspx

Kind regards,

Rogier

**Comment by michaellwest** [comment]
We certainly can add it. I had received the request some time back but looks like it's a good time to go ahead and implement.

**Comment by michaellwest** [comment]
Came up with something like this:

```powershell
New-ScriptSession -Username <String> -Password <String> -ConnectionUri <Uri[]> [<CommonParameters>]
    
New-ScriptSession -Username <String> -Password <String> -ConnectionUri <Uri[]> [-Credential <PSCredential>] [<CommonParameters>]
    
New-ScriptSession -Username <String> -Password <String> -ConnectionUri <Uri[]> [-UseDefaultCredential] [<CommonParameters>]
```

**Comment by michaellwest** [comment]
Implemented for New-ScriptSession.

**Comment by rogiervanhetschip** [comment]
Looks good, thanks for your help and quick response. That should help, now we can supply no Windows credentials, entered Windows credentials or the current Windows credentials. This last option will allow our Continuous Delivery script engine to run Powershell scripts against Sitecore, for example post-installation.

Thanks again!
