### ISSUE TITLE
Add/Remove-ItemLanguage - changed to general Add/Remove-ItemVersion - version management commands 

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#532]
Edity by @AdamNaj

Commands renamed. Aliasses added for compatibility.
Tests showing it in operations [in the Gist](https://gist.github.com/AdamNaj/b36ea095e3668c22c07e)

**Comment by michaellwest** [comment]
https://gist.github.com/AdamNaj/1bd3980a9a5dc5014c66

**Comment by AdamNaj** [comment]
I need to look at the implementation but I think we might want to rename the `Add-ItemLanguage` and `Remove-ItemLanguage` to as effectively those would do the same thing to a degree. Max Version pruning is really the thing to add.

**Comment by michaellwest** [comment]
I would think that adding separate commands will help keep the command from becoming bloated or complicated.

**Comment by AdamNaj** [comment]
The thing is that other than trimming to max number they are pretty much doing the same :)

**Comment by AdamNaj** [comment]
Implemented
