### ISSUE TITLE
Automatic properties do not support newly added template property until restart

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#534]
Here is a use case:

Assume the item template has properties _Title_ and _Text_.
$item = Get-Item -Path "master:\content\home"
$item.Title = "Kitchen"
$item.Text = "Warm and comfy"

Next I add the property _Color_ to the template.
$item = Get-Item -Path "master:\content\home"
**This will fail because the item does not contain the property _Color_.**
$item.Color = "Red"

After using `Restart-Application` the property is found.

**Comment by AdamNaj** [comment]
Those are cached per template. I can invalidate the templates caches whenever I detect any change in templates branch though.

**Comment by michaellwest** [comment]
Do it.

**Comment by AdamNaj** [comment]
Invalidation implemented
