### ISSUE TITLE
Console timeout causes loss of PSDrive context

### ISSUE THREAD

**Issue by richardhauer** [SitecorePowerShell/Console#537]
If one opens a PowerShell Console in desktop mode, Sitecore 8.0U3 + SPE 3.0.0.22668, and one populates some variable with data you may notice that after a while of leaving the console alone, the variables have become reset and the context is lost.  The first command issued to "PS master:\" (assuming it includes a reference to a previously populated variable) when returning to the console is met with an error and the console is returned to "PS C:\windows\system32".

Might be good to synchronise the console timeout with the Sitecore Shell timeout, if that's even possible.

R

**Comment by michaellwest** [comment]
Maybe this article will help 

http://getfishtank.ca/blog/setting-session-timeouts-in-sitecore-7

**Comment by richardhauer** [comment]
Is it possible that the PowerShell console has an independently set timeout value?  My other settings are already synchronised, but it appears that the console times out faster than the shell.

**Comment by AdamNaj** [comment]
Other than Console (which does keep-alive) on its SPE Session - SPE Sessions are timed out and that's very much an intended outcome. The problem with ISE session staying in memory is that those can take quite a bit of memory (especially accumulated in variables) and we want to be very aggressive in removing them from memory.

**Comment by richardhauer** [comment]
My timeout issue was happening in the console FWIW.

R

**Comment by AdamNaj** [comment]
I've tested this today leaving the console idle for over an hour (I've even shortened the session/cache expiration time to 2 minutes) and didn't experience the behaviour. The KeepAlive ping was keeping the session in memory for as long as the console window in the desktop was opened.

Could you provide further details on how to reproduce it with SPE 3.3 or later on a clean sitecore server?

Could this is occurring in a specific situation when server is under memory pressure with the HTTPCache is aggressively cleared?

**Comment by AdamNaj** [comment]
Closing this for the lack of activity. Assuming it's working as designed.
