### ISSUE TITLE
Support more publishing options like PublishRelatedItems, RepublishAll, CompareRevisions and FromDate as well as publish Synchronously

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#539]
- `-PublishRelatedItems` - Turns publishing of related items on. Works only on Sitecore 7.2 or newer
- `-RepublishAll` - Republishes all items provided to the publishing job.
- `-CompareRevisions` - Turns revision comparison on.
- `-FromDate` - Publishes items newer than the date provided only.
- `-Synchronous` - Performs the publishing action synchronously making the script wait for the publishing opration to end.

**Comment by AdamNaj** [comment]
Implemented

**Comment by michaellwest** [comment]
I'd like to adjust it so the default behavior is Synchronous and we use an *AsJob* parameter to indicate that the job will be return and run Asynchronously.

**Comment by AdamNaj** [comment]
Added note to the original issue description and closing.
