### ISSUE TITLE
Enable Type name auto-complete

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#540]
Ability to type partial type name and make ISE provide relevant suggestions.

Based on type name only (one word no dots):
![image](https://cloud.githubusercontent.com/assets/1209953/11867998/1a6e2c00-a4b5-11e5-9117-f55bfe0dfa62.png)

Provide Namespace prefix and everything in that namespace and nested namespaces will be found too:
![image](https://cloud.githubusercontent.com/assets/1209953/11868089/b617b9a0-a4b5-11e5-9d58-10f6317dba8d.png)

If your type contains a word but is not necessarily at the beginning of the class you can use a type wildcard:
![image](https://cloud.githubusercontent.com/assets/1209953/11869876/50b64d7a-a4c3-11e5-9f61-cd2772835a53.png)

**Comment by michaellwest** [comment]
Sweet!

**Comment by AdamNaj** [comment]
Implemented on PowerShell 3+
