### ISSUE TITLE
Enable method signature hint on Ctrl+Space

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#541]
This should work on static types:
![image](https://cloud.githubusercontent.com/assets/1209953/11895949/dd68fa8c-a582-11e5-86a2-997d4e449368.png)

Static members of static types:
![image](https://cloud.githubusercontent.com/assets/1209953/11895985/113f0374-a583-11e5-88c9-ece75093a2d5.png)

As well as instantiated variables:
![image](https://cloud.githubusercontent.com/assets/1209953/11896008/3d17e4fc-a583-11e5-9577-ebbe298ee241.png)

If a variable is not instantiated a message should be given:
![image](https://cloud.githubusercontent.com/assets/1209953/11896198/be1c9628-a584-11e5-9fe1-ae8ab97a6895.png)

**Comment by AdamNaj** [comment]
Implemented for PowerShell 3.0+

**Comment by michaellwest** [comment]
@AdamNaj You have just added a feature I've needed in PowerShell ISE for years. Thank you.

**Comment by AdamNaj** [comment]
You're welcome.Same here. Less and less reasons to fall back to Visual Studio for anything :)
