### ISSUE TITLE
Add Experience buttons Integration Point

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#546]
Add a new integration point for the getChromeData pipeline.

**Comment by michaellwest** [comment]
Implemented. @AdamNaj please review.

**Comment by AdamNaj** [comment]
Looks interesting. Need some additional work. Personally I'd name it "Experience Buttons" as I thin that's how those are called from the user's point of view. Also a script for creating the integration point script library would be required.

**Comment by AdamNaj** [comment]
Ok, this item has now been re-implemented to work like the other integration points. Enabled conditionally with rules.

**Comment by michaellwest** [comment]
This will need to be moved to the Cognifide.PowerShell.Sitecore8 library.

**Comment by AdamNaj** [comment]
Already done that yesterday, during the old SC version tests :)
Actually only the first class need to be version specific, as far as I could see. 
Why do you think the second one needs to be moved?

**Comment by michaellwest** [comment]
I could be wrong. The first gave me an error. Wasn't sure if the second one needed to move too. Just making sure.

**Comment by AdamNaj** [comment]
Fixed with commit 69b45e3ae0d7c302242e67244ca1dba352bdb5d3
