### ISSUE TITLE
Rebuild-SearchIndex should return existing job

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#558]
If an index is already in the process of being rebuilt, then the command should return the existing job rather than nothing.

**Example:** Running this command when the job is already rebuilding will return the current job.
```powershell
Rebuild-SearchIndex -Name sitecore_master_index -AsJob
```

**Comment by michaellwest** [comment]
Implemented.

**Comment by RajasekharVM** [comment]
Hi Michaellwest,
Can you please provide complete code for Rebuild index through powershell (Import module spe)
