### ISSUE TITLE
Security for Context Menu

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#567]
Discovered today that an author/designer can see the *Scripts* link. Should this be hidden?

![image](https://cloud.githubusercontent.com/assets/933163/12491353/4ab42238-c040-11e5-82c9-cce17b2d1ae8.png)

**Comment by michaellwest** [comment]
I think what I'm looking for is how to secure the *ScriptLibraryMenuItem* command. The default state is always **enabled**.

**Comment by AdamNaj** [comment]
To hide it you can change the security settings for the `/sitecore/content/Applications/Content Editor/Context Menues/Default/Context PowerShell Scripts` item in the core database for the roles that should not see the menu. In case of each implementation it can be different depending on which users you want to show it to.

One other thing we can do as well is to hide it if no scripts are available to the particular user.

**Comment by michaellwest** [comment]
Thank you.
