### ISSUE TITLE
Hide full path for download dialog

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#568]
The full path should be changed to only show the file name and perhaps the parent name.

![image](https://cloud.githubusercontent.com/assets/933163/12503980/2be32822-c09f-11e5-9230-3d594594f56a.png)

**Comment by AdamNaj** [comment]
Can do.

**Comment by AdamNaj** [comment]
By default the dialog will show only the file name. Use `-ShowFullPath` to show the full path to the file or item.
