### ISSUE TITLE
New-Item cmdlet does not respect language parameter while creating a branch

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#577]
**How to reproduce:**
1. Add additional language to your Sitecore (in my case PL)
2. Execute the following code
```powershell
New-Item -Path "/sitecore/content/Home" -Name "Branch" -ItemType "Branches/System/Analytics/Profile" -Language "pl-pl"
```

**Actual result:**
Only root item is created in desired language.
Children are created in english.

**Expected result:**
Branch is created in the same way as Sitecore creates it (whole branch is created in context language).

**Comment by AdamNaj** [comment]
Fixed

**Comment by alan-null** [comment]
Woow, fast.
Great!
