### ISSUE TITLE
Add-ItemLanguage should return the newly created version

### ISSUE THREAD

**Issue by pierresapinault-ef** [SitecorePowerShell/Console#578]
Hi,
As discussed in [the comments of this page](http://blog.najmanowicz.com/2014/10/12/working-with-sitecore-items-in-powershell-extensions/) I would like to raise this issue.

Copy/paste:
I'm often doing some content migration and have to populate fields from some other items. I parse all languages of the source item and want to get the values there and copy them to the newly created item.

This is how I would like to go about it :
```powershell
$SourceItems = Get-Item -Path $path -Language *
foreach ($sourceItem in $SourceItems)
{
  $newItem = Get-Item -Path $newPath -Language $sourceItem.Language.Name
  $newItem."Title" = $sourceItem."Menu Title"
  $newItem."Text" = $sourceItem."Page Text"
}
```
This throws an error is the language version doesn't exist because you cannot edit on a null-valued object (the item).
To go around this i make sure i have an English version "en" and then run it like this:

```powershell
$SourceItems = Get-Item -Path $path -Language *
foreach ($sourceItem in $SourceItems)
{
  $newItemEN = Get-Item -Path $newPath -Language en
  $newItemEN | 
    Add-ItemLanguage -TargetLanguage $sourceItem.Language.Name -IfExist Skip | 
    Out-Null
  $newItem = Get-Item -Path $newPath -Language $sourceItem.Language.Name
  $newItem."Title" = $sourceItem."Menu Title"
  $newItem."Text" = $sourceItem."Page Text"
}
```

I see two possibilities:
1) automatically invoke the `Add-ItemLanguage` in the background if the language version doesn't exist when using syntax like `$newItem."Title" = $sourceItem."Menu Title"`

2) the `Add-ItemLanguage` should return the new item so that we don't need to use `Get-Item` afterwards to get the new item.

Hope this makes sense.
Thanks for this great tool!
best,
Pierre

**Comment by AdamNaj** [comment]
Implemented in commit 470bba7ef43b386db3ac3fc6b7dfc56383b42f50.
```powershell 
Add-ItemLanguage -Path $newPath -TargetLanguage $sourceItem.Language.Name -IfExist Skip
```
will now return the existing version if it exists
