### ISSUE TITLE
Set-Layout cdlt not working

### ISSUE THREAD

**Issue by pierresapinault-ef** [SitecorePowerShell/Console#579]
Hi,
Not sure if i'm doing something wrong but i try to run the following and nothing happens:
```powershell
$item = Get-Item -Path master:/sitecore/content/sites/views/locations/warsaw

$device = Get-LayoutDevice -Default
$layout = Get-Item -Path master:/sitecore/layout/Layouts/Sites/Layout

Set-Layout -Item $item -Device $device -Layout $layout
Get-Layout $item
```
Any idea?
best,
Pierre

**Comment by AdamNaj** [comment]
Depending on which version of Sitecore you're using... it works with the old shared layouts exclusively so not really working in Sitecore 8 yet, this will be fixed in SPE 4.0 as part of Issue #503

At which point you will be able to provide the `-FinalLayout` on the layout cmdlets to switch them to work on `__Final Renderings` rather than `__Renderings`

**Comment by pierresapinault-ef** [comment]
We use Sitecore 7.2, old school shared layout. For now i am setting the layout on the standard values then and adding the renderings with Powershell

**Comment by AdamNaj** [comment]
I've just verified it (although on the latest code and on Sitecore 8) but it should not make any difference in this case and it seems to be working for me. 
```powershell
# where my test page will go
$path = 'master:\content\Sample'

# wipe and re-create it if exists
if(Test-Path $path){
    Remove-Item $path
}
$item = New-Item -Path $path -ItemType "Sample/Sample Item"

# wipe renderings just to make sure
$item."__Renderings" = ""

# select default layout
$device = Get-LayoutDevice -Default

# and a layout we will change to
$layout = Get-Item -Path 'master:\layout\Layouts\System\Simulated Device Layout'

# change the layout from what is in Standard values to the new one.
Set-Layout -Item $item -Device $device -Layout $layout | Out-Null

# verify
Get-Layout $item 
``` 
what I'm seeing is:
![image](https://cloud.githubusercontent.com/assets/1209953/12944078/4f186578-cfe5-11e5-95c0-1fc8e45d649f.png)
And in the rendering details:
![image](https://cloud.githubusercontent.com/assets/1209953/12944314/8db1c6e8-cfe6-11e5-96a1-8c13f1644b53.png)

**Comment by pierresapinault-ef** [comment]
hmm then i have no clue, maybe something custom in our instance that i don't know about. Thanks for checking though :)

**Comment by AdamNaj** [comment]
OK, I've just verified it on 7 and it does not work for me either... investigating...

**Comment by AdamNaj** [comment]
ok... again... this seems to be working for me as expected on 7 too... sorry :)
the thing I thought was a problem was me clearing out the `__Renderings` field which behaves differently on Sitecore 7 and 8. On 7 it breaks link with Standard values, whereas on 8 it creates a fallback to standard values.

So the script in this form:
```powershell
# where my test page will go
$path = 'master:\content\Sample'

# wipe and re-create it if exists
if(Test-Path $path){
    Remove-Item $path
}
$item = New-Item -Path $path -ItemType "Sample/Sample Item"

# select default layout
$device = Get-LayoutDevice -Default

# and a layout we will change to
$layout = Get-Item -Path 'master:\layout\Layouts\System\Simulated Device Layout'

# change the layout from what is in Standard values to the new one.
Set-Layout -Item $item -Device $device -Layout $layout | Out-Null

# verify
Get-Layout $item 
```
... produces the following result for me:

![image](https://cloud.githubusercontent.com/assets/1209953/12945753/d128b48c-cfef-11e5-8e3a-f3db4d603c76.png)
Which is what is expected.

**Comment by AdamNaj** [comment]
Am I having a stroke?
This only started working after I've fixed another bit that was just committed!

**Comment by AdamNaj** [comment]
Fixed. Will be available in version 4.

**Comment by pierresapinault-ef** [comment]
Thanks a lot, and take it easy ;-)
