### ISSUE TITLE
Create anti update package

### ISSUE THREAD

**Issue by AnweshaGD** [SitecorePowerShell/Console#586]
How do I create an anti .update package using the PS toolbox? Currently it accepts only .zip files. I tried converting the .update to .zip and run the package in the PS toolbox but the items are missing in the anti package.

**Comment by michaellwest** [comment]
Right now SPE has the native capabilities to create modules only. Since the update packages are essentially zip files, you could unwrap it to see what's inside.

**Comment by AdamNaj** [comment]
As Michael stated... (just making sure it's understood properly) the "Anti package" functionality only works with the standard Sitecore packages (like the ones available on Sitecore marketplace) not the `.update` packages at this point.

**Comment by AdamNaj** [comment]
Closing as it's answered
