### ISSUE TITLE
Bug in Add-ItemLanguage

### ISSUE THREAD

**Issue by geoffreysmith** [SitecorePowerShell/Console#587]
This works:

```
cd 'master:/sitecore/layout/Placeholder Settings'
Get-ChildItem . -Recurse | Add-ItemLanguage -TargetLanguage "de-de" -IfExist Skip

```
This does not
```
Add-ItemLanguage -Path "master:\content\home" -Language "en" `
    -TargetLanguage "en-gb" `
    -IfExist Skip `
    -IgnoredFields "Title"
```

It produces the following error:
```

Add-ItemLanguage : Value cannot be null.
Parameter name: name
At line:1 char:1
+ Add-ItemLanguage -Path "master:\content\home" -Language "en" `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by geoffreysmith** [comment]
Using the following package: Sitecore PowerShell Extensions-3.3 for Sitecore 8.zip and with Sitecore 8.0. Happens in multiple environments.

**Comment by AdamNaj** [comment]
This cmdlet has seen a major re-structure as part of the 4.0 release and the problem no longer seem to occur for me. Please verify it when 4.0 is released.

**Comment by AdamNaj** [comment]
Could you verify that this is now working for you and possibly close the issue if fixed? 
Thank you for using SPE!

**Comment by AdamNaj** [comment]
Closing as not reproducible any longer.
