### ISSUE TITLE
Security and account managing cmdlets should support System roles and Creator-Owner role.

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#596]
As requested in issue #595 "Everyone" as well as dynamic & special roles were hard to work with using the built in cmdlets.

It should be possible to work with them in the following manner:
```powershell
#get "Everyone" role from "default" domain
Get-role -Identity "default\Everyone"
#get "Creator-Owner" dynamic role
Get-role -Identity "Creator-Owner"
#get "Everyone" dynamic role
Get-role -Identity "\Everyone"

#Create ItemAcl with the above roles.
New-ItemAcl -Identity "default\Everyone" -PropagationType Any `
    -SecurityPermission DenyInheritance -AccessRight *
New-ItemAcl -Identity "Creator-Owner" -PropagationType Any `
    -SecurityPermission DenyInheritance -AccessRight *
New-ItemAcl -Identity "\Everyone" -PropagationType Any `
    -SecurityPermission DenyInheritance -AccessRight *
```

Since this is fixed on platform level - other cmdlets dealing with roles should also accept it now.

**Comment by AdamNaj** [comment]
Implemented

**Comment by michaellwest** [comment]
Can we use Get-Role -Filter "*\Everyone" instead to be consistent with the
other commands?

**Comment by AdamNaj** [comment]
For the benefit of users that come here... we discussed it on the call - it is consistent with how we do it in other cases.

Having it specified as `"Everyone"` implies the `"sitecore"` domain as it does in case of all other users/uses. Using a slash in `"\Everyone"` indicates that you want the generic `Everyone` without the `"sitecore"` domain.
