### ISSUE TITLE
SPE Remoting : Support uploading zip files and unpacking

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#600]
Support uploading of zip files and unpacking.

This behavior should be similar to the Receive-File command.

**Comment by michaellwest** [comment]
Now you can do something like
```powershell
Get-Item -Path C:\temp\Kittens.zip | Send-RemoteItem @props -RootPath Media -Destination "Images/"
```

**Comment by AdamNaj** [comment]
Implemented for now. We'll introduce choice whether to unzip on not in 4.1
