### ISSUE TITLE
What is the console url

### ISSUE THREAD

**Issue by hsingh23** [SitecorePowerShell/Console#605]
I can get to the console via the desktop, but I don't know how to get to the console outside the desktop. 

For ISE I use /sitecore/shell/Applications/PowerShell/PowerShellIse?sc_bw=1
but  /sitecore/shell/Applications/PowerShell/PowerShellConsole?sc_bw=1 is not a valid url.

What is the console url?

**Comment by michaellwest** [comment]
Hey @hsingh23 looks like the path is the following:

```
 /sitecore/shell/Applications/PowerShell/PowerShell Console?sc_bw=1
```

**Comment by hsingh23** [comment]
Thanks a lot
