### ISSUE TITLE
Console / ISE should warn user before closing browser tab when the script is running

### ISSUE THREAD

**Issue by marrrcin** [SitecorePowerShell/Console#613]
It's a UX suggestion - when the script is running (either in Console or in ISE), there should be a warning before closing a browser tab / window. It could be usefull in the situation when the user runs time consuming task and then accidently closes tab - of course the script will continue execution, however the user loses the track of the script output.

**Comment by AdamNaj** [comment]
Great feature! Thanks Marcin!
