### ISSUE TITLE
Publish-Site command needed or Publish-Item needs tuning for publishing

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#620]
The combinations required to publish a site or an item just has too many combinations. I think we need one command for site and one for item.

`Publish-Site Smart -AsJob`

`Publish-Item -Recurse -Related -AsJob`

**Comment by AdamNaj** [comment]
I might not be understanding the concept of "Publish Site", but isn't it just publication of the whole Sitecore tree? If that is the case I do see much point as it can be achieved simply by:

```powershell
Publish-Item -Path master:\ -Recurse 
```
Other than it always working on root and being recursive by default wouldn't it share 99% of the code (which is already pretty complex) with `Publish-Item`?

**Comment by michaellwest** [comment]
Can't make up my mind for the title. Trying to produce some better examples for publishing.

**Comment by michaellwest** [comment]
// Publish Site - Smart
Publish-Item -Path "master:\" -PublishMode Smart

Item = null
Mode = Full
Deep = true
Compare = true

// Publish Site - Republish
Publish-Item -Path "master:\" -PublishMode Full -RepublishAll
Publish-Item -Path "master:\" -PublishMode SingleItem -Recurse -PublishRelatedItems

Item = null
Mode = Full
Deep = true
Compare = false
RebuildAll = true (for RebuildDatabase)

// Publish Site - Incremental
Publish-Item -Path "master:\" -PublishMode Incremental

Item = null
Mode = Incremental
Deep = false
Compare = false

// Publish Item
Publish-Item -Path "master:\content\home" -PublishMode SingleItem
Publish-Item -Path "master:\content\home" -PublishMode Full -Recurse -PublishRelatedItems

Item = "master:\content\home"
Mode = Full
Deep = true
Compare = true

**Comment by michaellwest** [comment]
Updated so now only these options are used through remoting:

```powershell
# Republish Site
$jobId = Invoke-RemoteScript -Session $session -ScriptBlock {
        (Publish-Item -Path "master:\" -PublishMode Full -Recurse -RepublishAll -AsJob).Handle.ToString()
}
Wait-RemoteSitecoreJob -Session $session -Id $jobId -Delay 2 -Verbose

# Smart Publish Site
$jobId = Invoke-RemoteScript -Session $session -ScriptBlock {
        (Publish-Item -Path "master:\" -PublishMode Smart -Recurse -AsJob).Handle.ToString()
}
Wait-RemoteSitecoreJob -Session $session -Id $jobId -Delay 2 -Verbose

# Smart Publish item with children and related items
$jobId = Invoke-RemoteScript -Session $session -ScriptBlock {
        (Publish-Item -Path "master:\content\home" -PublishMode SingleItem -Recurse -PublishRelatedItems -AsJob).Handle.ToString()
}
Wait-RemoteSitecoreJob -Session $session -Id $jobId -Delay 2 -Verbose

# Incremental Publish Site
$jobId = Invoke-RemoteScript -Session $session -ScriptBlock {
        (Publish-Item -Path "master:\" -PublishMode Incremental -FromDate "03/17/2016" -AsJob).Handle.ToString()
}
Wait-RemoteSitecoreJob -Session $session -Id $jobId -Delay 2 -Verbose
```

**Comment by AdamNaj** [comment]
Do you think this is now working as you expected? Feel free to close the issue if so.

**Comment by michaellwest** [comment]
Yes. Implemented.
