### ISSUE TITLE
Suggested changes to package generator

### ISSUE THREAD

**Issue by AlexKasaku** [SitecorePowerShell/Console#623]
I have a couple of suggested changes for the package generator scripts, but thought I'd sound out what the feeling is on them before implementing.

1. Change the script names to use "Tree" instead of "Branch", i.e. "Quick download tree as package" and "Add tree to package".

 Branch makes sense to me, but as Sitecore already uses tree elsewhere (e.g. in the serialization and index commands) and Branch also has a special meaning in Sitecore, it might be more consistent.

2. I think it'd be useful to prefix the Quick Download package with a time-of-generation timestamp so it results in a sortable file, e.g. "_20160414.092023.ItemName-1.zip_"

**Comment by AdamNaj** [comment]
1. "Tree" sounds sensible especially since it's also used in this vein for serialization.
2. I would not force it during download but rather seed the dialog with the date prefix.

**Comment by AlexKasaku** [comment]
Read my mind! When I took a look at how it could work I saw it could go in as the default value in the textbox, so they'd be free to delete if they wish.

Will implement and push up later this evening.

**Comment by AlexKasaku** [comment]
Implemented:

- Branch renamed to Tree in 2 package generator scripts
- Timestamp added to quick download
- Help text for Download Package updated
