### ISSUE TITLE
Question about possible configuration error for Sitecore PowerShell regarding fonts and Globalization

### ISSUE THREAD

**Issue by hannahcclark** [SitecorePowerShell/Console#626]
I am working on a Sitecore implementation that uses Sitecore PowerShell. I've been seeing the following error in the Sitecore server logs quite often:

The error’s source is “Sitecore.Globalization.ItemEventHandler” with the message “Cannot find dictionary domain for the dictionaty entry '/sitecore/system/Modules/PowerShell/Fonts/some_font_here’ ('{font’s-item-id-here}')” where some_font_here is replaced with the name of any one of the fonts in the Sitecore powershell module. Whenever it occurs, it happens in a group of five times per font for each of the seven fonts.

When I look in the content editor on a server that is experiencing those errors, under /sitecore/system/Modules/PowerShell/Fonts/, I can see each of the fonts. Upon inspecting each item, I have verified that the id in the error message matches the item id. Because this is the case, I suspect that something has not been configured or set correctly regarding how the fonts are being accessed. However, given that any configuration regarding it is the standard configuration, as far as I am aware, I am not sure where to start. Do you have any insight into where I might be able to find the cause of this so that I may correct it?

**Comment by michaellwest** [comment]
Hi @hannahcclark, can you tell me which version of Sitecore you are running and SPE?

Try running `Get-Host` in the console to see version information; a screenshot will work.

**Comment by michaellwest** [comment]
I'm going to guess that PowerShell 2.0 is running on the machine.

**Comment by hannahcclark** [comment]
The Sitecore version is 8.1. The SPE version is shown in the following screenshot.
<img width="602" alt="screen shot 2016-04-13 at 8 56 17 pm" src="https://cloud.githubusercontent.com/assets/7838955/14514020/d42dd7d2-01ba-11e6-8ebc-589219335858.png">
The server itself is running powershell 4.0. 
<img width="639" alt="screen shot 2016-04-13 at 8 58 00 pm" src="https://cloud.githubusercontent.com/assets/7838955/14514029/e6bd12dc-01ba-11e6-8fdb-dd127c6359b1.png">

Please let me know if I can provide additional information that would be helpful.

**Comment by michaellwest** [comment]
Hmm. Does this happen in your local instance?

If you can send me your email address I can add you to the slack chat; we
have a channel for SPE.

**Comment by michaellwest** [comment]
@hannahcclark I'm also on twitter @michaelwest101

**Comment by hannahcclark** [comment]
I have not seen it in the logs for my local instance, only the dev, test, and production environments. I am fairly new to the team working on Sitecore at my company, so it is possible that this is due to a difference in how the logs are being viewed rather or even differences in what is being logged that I am unaware of, although that seems somewhat unlikely.

Regarding the slack chat, my email is hclark@vistaprint.com. I am not currently on twitter. However, I will not be available much longer tonight to work on this so any further responses on my part about this issue will probably be delayed until morning.

**Comment by michaellwest** [comment]
Thank you @hannahcclark. I sent you an invite. Once you create your account go ahead and find the module-spe channel. @AdamNaj myself and others will be able to take a look at it for you tomorrow. I suspect that upgrading to 4.0 will resolve the issue.

**Comment by AdamNaj** [comment]
[Fix for Fonts - Issue 626-1.zip](https://github.com/SitecorePowerShell/Console/files/219321/Fix.for.Fonts.-.Issue.626-1.zip)

Can you please verify if the attached package fixes the issue for you?

**Comment by hannahcclark** [comment]
The above fix has not completely solved the issue. It is possible that it has reduced the amount of times the error occurs by eliminating an occurrence that tends to happen shortly after a sitecore instance is set up on a server, but I can't say that for sure. It still occurs at the random points throughout the day.

**Comment by AdamNaj** [comment]
As discussed on Slack channel, please confirm that the old items are deleted in the "web" databases. It's somewhat possible that Sitecore is processing them every time publish happens.

**Comment by hannahcclark** [comment]
They were indeed published to web in the database which all other web databases are populated from, and after speaking with some other team members who are more knowledgeable about it, it seems that for the most part occurrences of the error seem to be shortly after known times of publishes to that database. I will ensure that they are deleted and let you know if doing so fully resolves this issue.

**Comment by hannahcclark** [comment]
The fix did work. The issue was on my end with database backpopulation overwriting some changes and maintaining copies of the old fonts in web without my realizing, but that should be corrected when the changes are applied in the appropriate environment. Thanks for your help. I really appreciate it.

**Comment by michaellwest** [comment]
Thanks for the update @hannahcclark .We appreciate you reporting the issue and working with us to resolve it.

**Comment by AdamNaj** [comment]
Brilliant! Glad to see it fixed!
