### ISSUE TITLE
Show-ListView properties don't support closure expressions

### ISSUE THREAD

**Issue by jomiham** [SitecorePowerShell/Console#631]
Hi,

I found a problem when trying to use a closure as a Show-ListView property expression.

Simple example:
```powershell
function GreetingColumn([string]$phrase) {
    return @{ Name=$phrase; Expression={ "{0} {1}!" -f $phrase, $_.Name }.GetNewClosure() }
}

$columns = @("Name") + (GreetingColumn "Hi") + (GreetingColumn "Hello")

$items = Get-ChildItem "master:/sitecore"

# This works:
$items | Format-Table -Property $columns

# This does not work:
$items | Show-ListView -Property $columns
```

It works with Format-Table, but not with Show-ListView and the problem seems to be that a Property can either be a Hashmap or a string, and for a Hashmap, the Expression scriptblock is serialized and then recreated which means that closure context are lost:
https://github.com/SitecorePowerShell/Console/blob/master/Cognifide.PowerShell/Commandlets/Interactive/BaseListViewCommand.cs#L43

From previous experience of your work, this looks like a simple enough fix to reuse the incoming Expression if it is a scriptblock. But if you are swamped, let me know and I can take a stab at a pull request.

By the way, the reason for this is that I wanted to create a report matrix with all placeholders and their allowed controls, so If you know of a way to get this working without closures, a hint would be appreciated... :-)

Jonas Hamnered

PS. Thanks for all your great work! Really enjoying the debug functionality in v4!

**Comment by AlexKasaku** [comment]
I think this just needed what you suggested, to reuse the existing ScriptBlock provided by the Hashtable rather than serializing to a string first. I've implemented that and it looks like it should work, using your example provided.

Do you want to pull the latest from master and see how it fares for you?

**Comment by AdamNaj** [comment]
It's working for me, great job Alex!
Feel free to close the issue when you have a moment.

**Comment by AdamNaj** [comment]
For the sake of counting it against this release, I'm considering it implemented.

**Comment by AlexKasaku** [comment]
Apologies, I've been away! Thanks for updating the issue :)
