### ISSUE TITLE
Error installing powershell package

### ISSUE THREAD

**Issue by timlaughlin** [SitecorePowerShell/Console#633]
In Sitecore 8.0 Update-7 we have item name rules that prevent hypens in item name and it is preventing installation of the package.

ERROR Error installing items/core/sitecore/content/Applications/PowerShell/PowerShellIse/Menus/Sessions/One-time session/{BA5B0AF4-AAA1-46D6-9CB6-C53A77F05EAA}/en/1/xml

ERROR Installation failed: Sitecore.Exceptions.InvalidItemNameException: An item name cannot contain any of the following characters: \/:?"<>|[]- (controlled by the setting InvalidItemNameChars)

**Comment by AdamNaj** [comment]
While we can get the dash removed from the name n the future release. At the moment I think the only solution for you is to lift the limitation on dashes while installing SPE. Thanks for reporting the problem!

**Comment by AdamNaj** [comment]
Fixed
