### ISSUE TITLE
Variable peek should throttle large arrays

### ISSUE THREAD

**Issue by marrrcin** [SitecorePowerShell/Console#635]
Recently I've been working on a script which processed large ammount of items and I had issues with the variable peek feature. Due to the fact that one of my script's variables contained more than 1000 items, hovering above it (often accidentaly) after first script execution was freezing ISE and also was causing high CPU usage of w3wp process for about 10-20 seconds. 

I think that there should be an option in settings to disable variable peek _or_ maybe the feature should be redesigned so it will not expand whole contents of variable and just show a line with [+] button to expand it on demand (like in Visual Studio).

A **workaround to this issue** is to switch ISE to use **"one-time-session"**, so the variables will not be left in memory between script executions.

**Comment by michaellwest** [comment]
+1

**Comment by AdamNaj** [comment]
OK. Implemented it as a setting where you can specify the maximum of objects that are parsed within an `IEnumerable`. The setting is stored within the web.config include as:

```xml
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
  <sitecore>
    <settings>
      <setting name="Cognifide.PowerShell.VariableDetails.MaxArrayParseSize" value="20" />
    </settings>
  </sitecore>
</configuration>
```

The code defaults to 20 if the setting does not specify otherwise.

**Comment by AdamNaj** [comment]
Implemented

**Comment by marrrcin** [comment]
That's a great news!
