### ISSUE TITLE
Show-ListView should have version dependant buttons

### ISSUE THREAD

**Issue by marrrcin** [SitecorePowerShell/Console#636]
When running Show-ListView commandlet, the result dialog shows many buttons where one of them is **Page Editor**. As Sitecore 8.X replaced this feature with Experience Editor, this dialog should show different caption in Sitecore 7.X and 8.X.

**Comment by AdamNaj** [comment]
Hey Marcin,

This script you've mentioned is part of Zen Garden, not SPE :)
