### ISSUE TITLE
Arguments Not Supported With AsJob

### ISSUE THREAD

**Issue by ncipollina** [SitecorePowerShell/Console#639]
I am attempting to execute a remote script to apply an update package to my Sitecore instance and I've discovered what appears to be a bug.  When trying Invoke-RemoteScript with Arguments and the -AsJob flag, the $params variable in the ScriptBlock is empty.  Is this intended to work this way?

**Comment by michaellwest** [comment]
Hey @ncipollina I've been going to move away from the $params pattern by replacing it with `$using:variablename`.

Try this:
```powershell
Import-Module -Name SPE -Force

$session = New-ScriptSession -Username "admin" -Password "b" -ConnectionUri "http://console"
$message = "This is the message."
Test-RemoteConnection -Session $session -Quiet
Invoke-RemoteScript -Session $session -ScriptBlock {
    Write-Output $using:message
} -AsJob
Stop-ScriptSession -Session $session
```

**Comment by michaellwest** [comment]
@ncipollina Did the example i provide help?

**Comment by ncipollina** [comment]
Yes and no.  It worked when I tried it locally, but when I tried to execute the script with a $using variable from Visual Studio Team Services Release it did not.  It complained about not being able to find the variable called in the $using statement.

**Comment by michaellwest** [comment]
That's interesting. I seemed to have experienced a similar issue with Visual Studio Code.

**Comment by AdamNaj** [comment]
Hi @ncipollina,

Did you manage to solve your issue? It would be great if we could add your solution to the remoting docs :)

**Comment by AdamNaj** [comment]
Closing the issue for lack of activity.
