### ISSUE TITLE
Publish-Item Not Working

### ISSUE THREAD

**Issue by ncipollina** [SitecorePowerShell/Console#643]
For some reason the Publish-Item command is not working.  If I issue the following command:

`Publish-Item -Path "master:\" -PublishMode Smart`

I get the following error message:

Publish-Item : Value cannot be null.
Parameter name: first
At line:1 char:1
+ Publish-Item -Path "master:\" -PublishMode Smart
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-Item], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Cognifide.PowerShell.Commandlets.Data.PublishItemCommand

Any idea what I might be doing wrong?

**Comment by michaellwest** [comment]
That's funny. Last night I was having the same problem. I believe in 4.0
the issue exists. My workaround until 4.1 was to use -AsJob on the command.
See if that helps you too.

**Comment by ncipollina** [comment]
Does -AsJob actually work though or is it just swallowing the error?

**Comment by michaellwest** [comment]
Last night when I tested it actually worked. My script was not publishing
our careers data until I added the switch.

**Comment by michaellwest** [comment]
@ncipollina We're planning to have the 4.1 released here soon.
