### ISSUE TITLE
Schedule task not executed on Content Delivery Server

### ISSUE THREAD

**Issue by hiralshah19** [SitecorePowerShell/Console#647]
Hi,

I have 2 tasks which creates a sitemapxml file seperately for both my Content Management and Content delivery environments. 

For instance, task1: SitemapXml CM runs / generates sitemap xml file for Content Management environment. 

Task2: SitemapXML CD runs/generates Sitemap xml file for Content Delivery environment,

The issue here is: Whenever i execute Task2 it always updates SitemapXML file for Content Management environment and runs for the Master database. It never updates this for content Delivery intance not it logs any activities of schedule tasks for sitecore logs of Content Delivery server's log files. 

Please suggest here if i need to seperately configure them with powershell. I am fairly new to this.

Thanks in advance!

Hiral

**Comment by michaellwest** [comment]
Sounds like the issue is due to SPE not being installed or running on the CD instance. You may want to try that, then use the publish:end:remote event to trigger executing the script.

**Comment by michaellwest** [comment]
@hiralshah19 I was able to extend the `ScriptedItemEventHandler` to listen for remote publish events. Then with a configuration change and scripts added to the script library I created a sitemap generator.

**Comment by AdamNaj** [comment]
Closing the issue for lack of activity in a long time. Assuming the problem is resolved, re-open otherwise.
