### ISSUE TITLE
Timeout on package install - SPE Remoting 

### ISSUE THREAD

**Issue by glenmcinnis** [SitecorePowerShell/Console#652]
Using SPE v 4 and Sitecore 8.1 Update 3. 

A simple function to install an update package results in a dead session shown on the console. Package does seem to install. Anyway to catch this? Function and output below.

function Invoke-RemoteUpdatePackageInstall
{
	param (
		$session,
		$path
	)
	$jobId = Invoke-RemoteScript -Session $session -ScriptBlock {
			Install-UpdatePackage -Path $packagePath -UpgradeAction Upgrade -InstallMode Install
		}  -AsJob -ArgumentList @{"packagePath" = $path }
	Wait-RemoteScriptSession -Session $session -Id $jobId -Delay 5 -Verbose
}

VERBOSE: Polling job d913222a-fd6a-465b-b081-f5de0d1f4bcb. Status : Busy.
VERBOSE: Polling job d913222a-fd6a-465b-b081-f5de0d1f4bcb. Status : Busy.
VERBOSE: Polling job  . Status :  .
VERBOSE: Finished polling job d913222a-fd6a-465b-b081-f5de0d1f4bcb.
Get-ScriptSession : The script session with Id 'd913222a-fd6a-465b-b081-f5de0d1f4bcb' cannot be found.
At line:3 char:36
+         $backgroundScriptSession = Get-ScriptSession -Id $__using_id
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (d913222a-fd6a-465b-b081-f5de0d1f4bcb:String) [Get-ScriptSession],
   ObjectNotFoundException
    + FullyQualifiedErrorId : ScriptSessionNotFound,Cognifide.PowerShell.Commandlets.ScriptSessions.GetScriptSessionCo
   mmand

**Comment by michaellwest** [comment]
Hi @glenmcinnis , thank you for reporting the issue. As part of commit e4f390484aa48aeed33e1e5a66e23ba09da819b4 in issue #617 i was able to address the issue. The job did in fact complete. The issue at hand is the job handle was never returned properly. We should have it out as part of 4.1 here soon.

// @AdamNaj

**Comment by AdamNaj** [comment]
Any action needed on my part or is this a closed issue now?

**Comment by AdamNaj** [comment]
Confirmed with @michaellwest that we're OK to close it.
