### ISSUE TITLE
Same script, different outputs

### ISSUE THREAD

**Issue by afortaleza** [SitecorePowerShell/Console#655]
Hello there, I'm running a very simple script from the Sitecore Powershell ISE and from the Windows Powershell ISE (using Invoke-RemoteScript) but I get different results and I don't know why.

Here's the script I run from Sitecore Powershell ISE:
```posh
try {
    $item = Get-Item -Path "/sitecore/system/Modules/PowerShell" -ErrorAction Stop
    return $true
}
catch {
    return $false
}
```
When I run this I get a ```True``` value as the return (expected) because I have that path in my sitecore.

Here's the script I run from Windows Powershell ISE:
```posh
$session = New-ScriptSession -Username admin -Password b -ConnectionUri "http://sitecore.instance1"
Invoke-RemoteScript -Session $session -ScriptBlock {
    try {
        $item = Get-Item -Path "/sitecore/system/Modules/PowerShell" -ErrorAction Stop
        return $true
    }
    catch {
        return $false
    }
}
```
When I run this I get a ```False``` as return (not expected). I was expecting to have the same result from the script run on Sitecore Powershel ISE, why am I'm getting different results?

If I change the path from ```"/sitecore/system/Modules/PowerShell"``` to ```"/sitecore"``` I get ```True``` on both scripts. Weird!

**Comment by afortaleza** [comment]
Forcing the database was the solution
```"master:/sitecore/system/Modules/PowerShell"```

**Comment by michaellwest** [comment]
Hey @afortaleza , if you use the `$_` in the catch block you would see the error message. Apparently the assumed provider through remoting is the filesystem where as in the console and ise it's the master database.
