### ISSUE TITLE
Packaging Generator : Defaults to overwrite/ merge with no options to change 

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#659]
The module should provide some way to influence the behavior.

**Comment by AlexKasaku** [comment]
@michaellwest - I've worked in a fairly simple way to do this. Want to try out this package and see what you think? It will overwrite the items at `/sitecore/system/Modules/PowerShell/Script Library/Package Generator/Content Editor/Context Menu/Packaging`

https://www.dropbox.com/s/25riennimfuuh9h/20161020.2233.Packaging-1.zip

It would be nice if the Merge Mode could disable/enable according to the selection of the other field, but we don't have that functionality (yet!)

**Comment by AdamNaj** [comment]
@AlexKasaku just saw your package - I like the changes but would like the Advanced to simply take over the existing ones. It's easier this way.

Also I think the steps should Close-Window immediately. When I originally implemented the packager we didn't have this functionality.

**Comment by AdamNaj** [comment]
Maybe the Branch one could also have checkboxes on whether to include the root or children only. I find that I often need to include the children but don't want to overwrite the root or I want different merge settings for root and the children.

**Comment by AlexKasaku** [comment]
That's a good idea. I split the scripts into an Advanced version because I thought the dialog took away from the "quick" nature of the regular ones and could annoy users if they're happy with the default.

**Comment by AdamNaj** [comment]
let's include your version instead and call it a wrap :)

**Comment by AlexKasaku** [comment]
No problem, will update and commit it at nearest available opportunity.

**Comment by AdamNaj** [comment]
Sounds awesome!

**Comment by AlexKasaku** [comment]
Implemented, also includes bonus option now for deciding whether to include the root as well as adding either children or descendants.

**Comment by michaellwest** [comment]
Uh oh. @AdamNaj is going to beat you up @AlexKasaku for allowing the *Z* in the date to show up in the serialized files.

**Comment by AlexKasaku** [comment]
Uh oh, no serializing from 8.2 then? Does it cause an issue deserializing into earlier environments, or a different issue? Should be easy enough to reserialize without either way...

**Comment by michaellwest** [comment]
There is a script under platform that does it for you.

**Comment by AlexKasaku** [comment]
Thanks @michaellwest, I wasn't aware of that requirement and script. I've reserialized the files and commited again.
