### ISSUE TITLE
UI : Add Check All dialog when using Read-Variable

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#666]
Could be useful for long lists like this.

![image](https://cloud.githubusercontent.com/assets/933163/16606357/fc6e1ee0-42fc-11e6-8a06-17f46e16c8ef.png)

**Comment by AdamNaj** [comment]
![checklistactions](https://cloud.githubusercontent.com/assets/1209953/17159518/24fdeef6-539e-11e6-89de-2c3e5c7c0de7.gif)

Done.
