### ISSUE TITLE
Add ability for nesting modules inside module folders

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#668]
As a SPE user I want to be able to nest a set of my modules inside _**modules folder**_ so I can organise my script library even better.

Currently there is an insert option for **Script Library** but when I use it there is no effect
![image](https://cloud.githubusercontent.com/assets/6848691/16619267/b7f18fcc-438d-11e6-8fe7-203a4f1e85c7.png)

Then when I try to import one of the functions form my nested module I am not able to do it.
![image](https://cloud.githubusercontent.com/assets/6848691/16619258/b263636e-438d-11e6-94a6-54a757480df2.png)

**Comment by AdamNaj** [comment]
Implemented
