### ISSUE TITLE
Ribbon : Support for small buttons, menus, and tooltip

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#670]
Something like this:
[Someone's blog](http://reyrahadian.com/2015/12/17/how-to-create-a-custom-ribbon-in-sitecore-content-editor/)

**Comment by AdamNaj** [comment]
Specifying button size is not the hard part really, it's the decision on whether the button should be small or large that is problematic. I'm torn on how to store this without bloating the script items with the otherwise unnecessary fields.

**Comment by michaellwest** [comment]
We also need to store a tooltip for the button.

**Comment by michaellwest** [comment]
Heck, let's throw in the menu too!

![image](https://cloud.githubusercontent.com/assets/933163/21583747/ac5089f4-d053-11e6-83bb-bb7ea8152cd1.png)

**Comment by AdamNaj** [comment]
Implemented.

For small button prefix the name of the script with `Small$`
To have a menu, just create scripts under the script that is a button

No field for tooltip though. Couldn't find a reasonable one to reuse, and it's too situational to add one.
