### ISSUE TITLE
Variables inspector can hang IIS worker process trying to inspect a large byte array

### ISSUE THREAD

**Issue by pveller** [SitecorePowerShell/Console#677]
Hey Guys,

Took me a while to figure out what was going on. I haven't debugged it to be certain but I am fairly sure I know what it is. I was basically reading the media item's content into a byte array and then, after I would run the script and get back to the PSE, it would hang the IIS worker process. Through experimentation I realized that it would happen as my mouse pointer gets closer to the `$bytes` in the script below. Try it out for yourself. Maybe my theory is not right. Once I figured out what was causing the hang I switched to the `one-time session`.

```powershell
$images = Get-ChildItem -Path '/sitecore/media library/Habitat/Images/Square'

$media_url = New-Object 'Sitecore.Resources.Media.MediaUri' $images[1]
$media = [Sitecore.Resources.Media.MediaManager]::GetMedia($media_url)

$stream = $media.GetStream().Stream
$memory = New-Object 'System.IO.MemoryStream'
$stream.CopyTo($memory)

$bytes = $memory.ToArray()

$memory.Dispose()
$stream.Dispose()
```

Run this and try to inspect the `$bytes`. Or maybe it's the attempt to inspect a stream that's been disposed off but I believe it's the byte array. Everything was fine with that line commented out. Now with a throw away session my process keeps spinning just fine.

**Comment by AdamNaj** [comment]
Hi Pavel,
Thanks for reporting the issue.
This should be mitigated by the fix to issue #635.

![image](https://cloud.githubusercontent.com/assets/1209953/17692993/1502c4f4-639d-11e6-8991-240ad77b30f8.png)
