### ISSUE TITLE
publish-item command works differently in 4.0

### ISSUE THREAD

**Issue by reedyd** [SitecorePowerShell/Console#678]
I just upgraded to Sitecore 8.1 & SPE 4.0 from Sitecore 7.5 & 3.n. I found that some commands that work on our legacy platform do not work on the new one. For instance:
```

Sitecore PowerShell Extensions
Copyright © 2010-2015 Adam Najmanowicz - Cognifide, Michael West. All rights Reserved.
 PS master:\>gi master:/sitecore/layout | publish-item -recurse:$false -verbose:$true -publishmode Full -targets web
VERBOSE: Performing the operation "Publishing language 'en', version '1' to target 'web'." on target "master:\layout".
VERBOSE: Publishing item 'layout' in language 'en', version '1' to target 'web'.  (Recurse=False).
publish-item : Value cannot be null.
Parameter name: first
At line:1 char:30
+ gi master:/sitecore/layout | publish-item -recurse:$false -verbose:$true -publis ...
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-Item], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Cognifide.PowerShell.Commandlets.Data.PublishItemCommand
```

I've combed the documentation, and tried lot's of different things, but still cannot figure out what's wrong.

**Comment by AdamNaj** [comment]
Hi @reedyd,

There have indeed been some changes to how the ```Publish-Item``` works as reflected in issue #539. Those might have triggered the different behaviour you are noticing. Unfortunately the cmdlet has some serious issues in 4.0 and those will be rectified as part of the issues #643 & #617 as well as some additional tuning has been added as part of the issue #620.

This means that you might need to tune your publishing script again after you upgrade to 4.1. I cincerely hope this is the final change as we are fairly happy with how the Cmdlet operates now.

Now to address your issue - I suspect the best course of action is to run the same version of SPE on both environments if you want to keep your scripts unchanged between the environments. (We always release matching version of SPE for both SC 7.x and 8.x)

**Comment by reedyd** [comment]
Thank you Adam. The -AsJob parameter got past the error, so I'm good to go.

I could not find 4.1 on Sitecore Marketplace, so I'll check for it another time.

**Comment by AdamNaj** [comment]
4.1 is not yet released, hopefully next week :)
