### ISSUE TITLE
UI Resources - japanese

### ISSUE THREAD

**Issue by haramizu** [SitecorePowerShell/Console#682]
[powershell-core.zip](https://github.com/SitecorePowerShell/Console/files/431803/powershell-core.zip)

I made Japanese UI resource file for this module.
Please import attached xml file to Sitecore CoreDB.

I tested on Sitecore 8.1 update 3 and Sitecore PowerShell Extensions 4.0.

**Comment by AdamNaj** [comment]
@haramizu - this is awesome! I've imported the libraries and checking the general compatibility of running SPE in Japanese language now. It seems that that the project was somewhat broken when running in Japanese but working through the issues at the moment.

I see the translations appearing in ISE but I also see that there is a number of items still missing in the UI. I wonder if you would be willing to deliver the translation for the remaining items if I provided you with the translation xml?

**Comment by haramizu** [comment]
@AdamNaj  - Thank you for good comment.

I find some missing data using previous xml file. I will create additional resource and post to here. Please wait next comment.

**Comment by AdamNaj** [comment]
@haramizu I have compiled the translation file of what I think should be fairly complete list of items. You can see that a fair share of those is already translated through the file you have so kindly provided. The rest of those is marked with `**` around them.

[spe-translation.zip](https://github.com/SitecorePowerShell/Console/files/434966/spe-translation.zip)

The files are generated through my own script. I tried to keep the format that you have provided but cannot be 100% sure that the format is fully OK.

**Comment by AdamNaj** [comment]
Ok... made some fixes and added some that needs to be translated. - please use this one instead:
[spe-translation.zip](https://github.com/SitecorePowerShell/Console/files/435277/spe-translation.zip)

**Comment by haramizu** [comment]
[spe-translation-ja-jp.zip](https://github.com/SitecorePowerShell/Console/files/436575/spe-translation-ja-jp.zip)

@AdamNaj  I translated term to Japanese. Please use attached file. Thank you.

**Comment by AdamNaj** [comment]
Imported and working.
