### ISSUE TITLE
Add -Device parameter to Set-Rendering Cmdlt

### ISSUE THREAD

**Issue by pierresapinault-ef** [SitecorePowerShell/Console#685]
Hi guys,

Following up on an issue I opened recently about the `Set-Rendering` cmdlet, I still experience issues with it. The `Get-Rendering` gives me the correct renderings from the correct devices, but then the `Set-Rendering` saves them on the Default device no matter what I try.

Here's the code:
```powershell
$item = Get-Item .
$device = Get-LayoutDevice "Sites2017"
$rendering = $item | Get-Rendering -DataSource "*rootname*" -Device $device | %{
			$datasource = $_.Datasource.Replace([string]"rootname",$Root.Name);
			Write-Host $datasource
			Set-Rendering -Item $item -Instance $_ -DataSource $datasource		
 		}
```
The datasources print correctly in the console, then when i look at the presentation details, the Sites2017 device still has the wrong ones, and the default device has been overwritten partly.
Feel free to add me on skype for live demo ;)
pierre.sapinault.ef

Thank you again for your support!
best,
Pierre

Edit: using SPE 4.0 and sitecore 7.2 rev. 141226

**Comment by AdamNaj** [comment]
Looking at the code of the Cmdlet it seems to me that you might be running into the following scenario: 
- The Cmdlet seeks for your rendering by its `UniqueID` by browsing through all the devices and looking for the first one containing the `UniqueID`.
- What I suspect is happening is that you have the rendering with the same Uniqe ID in both Default and your "Sites2017" device and the Cmdlet stops the seek process at the first instance found.

I suspect those renderings to be added to your new device some other way than SPE as the cmdlets should bnever manipulate the `UniqueID` property of the `RenderingDefinition` class but rather let the class handle it on its own.

**Comment by AlexKasaku** [comment]
Good catch @AdamNaj, would explain the issue. It wouldn't have been something triggered by my testing as the Unique ID would be expected to be unique.

**Comment by pierresapinault-ef** [comment]
Hey Adam, 
Those renderings are completely different, there is not one rendering in common between those 2 devices. Some have the same name but they are two different renderings in reality.
What SPE does is that it finds the renderings in the Sites2017 device and replaces the token. Then instead of saving it back in that save device, it saves it in the Default device. It also replaced some the tokens in the renderings in Default device.
See before http://screencast.com/t/ihzV74PsEMlr
and after http://screencast.com/t/Vx6fWtxxBy
It's really weird.
For now we are not using those cmdlets anymore and are changing the tokens by treating the renderings field as a string.
Best,
Pierre

**Comment by AdamNaj** [comment]
Hi Pierre,

I wonder if if was possible to upload the xmls for the renderings before and after treating them with the cmdlet so we can diagnose and pinpoint what's really happening?

**Comment by pierresapinault-ef** [comment]
Yes of course:

BEFORE:
<r>
  <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{E5988516-5B20-44A6-B4AC-1BE956F1BC66}">
    <r ds="/sitecore/content/efcom/rootname/Shared Content/Home Page/Stage" id="{F1CEDCF6-271E-4DDD-B617-BD0835435430}" ph="page-content" uid="{E7CFA2B0-F47C-458E-A775-3ED5EA38011C}" />
    <r ds="/sitecore/content/efcom/rootname/Shared Content/Modules/Language Picker" id="{BC9928AD-F83C-4406-BA20-55D4CA8103D1}" ph="stage-module" uid="{F28FECC5-86F4-41C1-953A-212B4C69A13F}" />
    <r ds="/sitecore/content/efcom/rootname/Shared Content/Modules/Product Highlights" id="{B130F899-9592-4EC5-83E1-A80B4AE9D40D}" ph="page-content" uid="{07900519-3E5D-40B9-94B9-5B6914FD4B32}" />
    <r ds="/sitecore/content/efcom/rootname/Shared Content/Home Page/Pillars" id="{F4F877DC-06CF-499E-AA84-F84A9F619F7F}" ph="page-content" uid="{1FC1353D-3555-4A17-90AE-9B8B8D5299FA}" />
    <r ds="/sitecore/content/efcom/rootname/Shared Content/Home Page/Mosaic" id="{14160722-43F2-4F7E-8DB6-C2CA22871A1F}" ph="page-content" uid="{3A7803F1-DA1E-47D3-B774-DE412BFC18D1}" />
    <r id="{8F455394-FBEB-4EA3-9437-304D714D795A}" ph="page-content" uid="{F5EF2E98-DE8C-4B6A-B9E5-4D0F4F17CCBE}" />
    <r ds="/sitecore/content/efcom/rootname/Shared Content/Modules/Infomeetings" id="{90E288FF-A6F2-49BC-884B-52AE5BC29B3B}" ph="page-content" uid="{2D536F9C-231F-45B8-93F9-FE45614611A7}" />
    <r ds="/sitecore/content/efcom/rootname/Shared Content/Modules/Price Quotation" id="{9C903F0C-8A16-4496-9F1C-90696F74AD14}" ph="page-content" uid="{9A96832F-823A-447C-BA36-E5A12BD3CC87}" />
    <r ds="/sitecore/content/efcom/rootname/Shared Content/Home Page/Accreditations" id="{6B524676-EFDD-4162-B811-356D0B16D7FF}" ph="page-content" uid="{525F2779-F62E-4854-9B5B-3B8FF8F093CD}" />
    <r ds="/sitecore/content/efcom/rootname/Shared Content/Modules/Footer" id="{58E1988D-F7D8-494C-8E44-D9890F46E651}" ph="page-footer" uid="{EBCE499C-E401-4DF9-8843-56643929D465}" />
    <r id="{38D51FE9-2F21-40CC-8592-791E5D0F4C02}" ph="seo-footer-links" uid="{153E5A4B-150F-4C19-A969-50D59303704C}" />
  </d>
  <d id="{15404A50-DD1C-49BF-A78C-CD8444DEDA8C}" l="{8817B671-106D-43F9-BA5B-96760B040E5C}">
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Home Page/Stage" id="{7530255F-D52A-407C-AFAF-E85205EAA774}" ph="stage-section" uid="{E7CFA2B0-F47C-458E-A775-3ED5EA38011C}" />
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Modules/Language Picker" id="{D1E75065-4D19-43D7-B808-8192E18A93A9}" ph="stage-module" uid="{F28FECC5-86F4-41C1-953A-212B4C69A13F}" />
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Home Page/Pillars" id="{D911D90B-FD3D-41F2-AFFC-D15DA5991BF5}" ph="page-content" uid="{1FC1353D-3555-4A17-90AE-9B8B8D5299FA}" />
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Home Page/Mosaic" id="{2757881E-2DF1-41B4-A8FA-F9642111F7AB}" ph="page-content" uid="{3A7803F1-DA1E-47D3-B774-DE412BFC18D1}" />
    <r id="{001226C6-1628-447F-AC00-CC97D0885E21}" ph="page-content" uid="{F5EF2E98-DE8C-4B6A-B9E5-4D0F4F17CCBE}" />
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Home Page/Language Learning" id="{42E40923-A71A-4390-8FD0-0DEFD039C38D}" ph="page-content" uid="{4A96287B-BCC7-4590-8D17-D0F0AEF47AF3}" />
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Modules/Infomeetings" id="{951599E8-BE82-4FB2-8CBE-C3DD88F7D948}" ph="page-content" uid="{2D536F9C-231F-45B8-93F9-FE45614611A7}" />
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Modules/Language Footer" id="{6F860D54-71D8-483A-823D-4B4ADA8D7FA4}" ph="page-content" uid="{EBCE499C-E401-4DF9-8843-56643929D465}" />
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Modules/Mobile Image CTAs" id="{5B4B3F4B-BB7E-4FE1-AFF8-2EF37FF7F2D2}" ph="mobile-content" uid="{33E5DE2C-52FE-484C-AC47-9AF3EFBCCF0B}" />
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Home Page/Pillars" id="{F20AFD9C-A742-44FB-8284-118957103937}" ph="mobile-content" uid="{EC7041DF-E605-424F-ABFF-9BC0D4B8B033}" />
    <r id="{3F382B7F-0765-4F1F-A13F-964E1A22190C}" ph="mobile-content" uid="{C1F6D9E7-08DF-47B1-AAB9-2C92EFA5EACC}" />
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Home Page/Infomeetings" id="{6C810F55-DB07-4790-BBE0-C5EA5748A9E2}" ph="mobile-content" uid="{2FA68151-D6C4-480F-B7BE-083688023903}" />
    <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Modules/Price Quotation" id="{07A2E65C-5D25-4DB9-8FC4-47A60A63DA32}" ph="mobile-content" uid="{22176278-612D-4F9D-AE59-37F265E85D13}" />
  </d>
</r>

AFTER:
<r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{E5988516-5B20-44A6-B4AC-1BE956F1BC66}">
        <r ds="{6DCFA49C-23D8-40FB-A20A-B628A5E6F03E}" id="{7530255F-D52A-407C-AFAF-E85205EAA774}" ph="stage-section" uid="{E7CFA2B0-F47C-458E-A775-3ED5EA38011C}" />
        <r ds="{371F5776-432A-4F54-97F0-FD4A7C782C53}" id="{D1E75065-4D19-43D7-B808-8192E18A93A9}" ph="stage-module" uid="{F28FECC5-86F4-41C1-953A-212B4C69A13F}" />
        <r ds="/sitecore/content/efcom/rootname/Shared Content/Modules/Product Highlights" id="{B130F899-9592-4EC5-83E1-A80B4AE9D40D}" ph="page-content" uid="{07900519-3E5D-40B9-94B9-5B6914FD4B32}" />
        <r ds="{9A9F466C-8CDF-4D98-8B05-5D065A193981}" id="{D911D90B-FD3D-41F2-AFFC-D15DA5991BF5}" ph="page-content" uid="{1FC1353D-3555-4A17-90AE-9B8B8D5299FA}" />
        <r ds="{555EFE5F-7F40-42C4-A504-4D9B9B37AD79}" id="{2757881E-2DF1-41B4-A8FA-F9642111F7AB}" ph="page-content" uid="{3A7803F1-DA1E-47D3-B774-DE412BFC18D1}" />
        <r id="{8F455394-FBEB-4EA3-9437-304D714D795A}" ph="page-content" uid="{F5EF2E98-DE8C-4B6A-B9E5-4D0F4F17CCBE}" />
        <r ds="{8C733C3C-CC18-4235-92D5-405A6F7890B5}" id="{951599E8-BE82-4FB2-8CBE-C3DD88F7D948}" ph="page-content" uid="{2D536F9C-231F-45B8-93F9-FE45614611A7}" />
        <r ds="/sitecore/content/efcom/rootname/Shared Content/Modules/Price Quotation" id="{9C903F0C-8A16-4496-9F1C-90696F74AD14}" ph="page-content" uid="{9A96832F-823A-447C-BA36-E5A12BD3CC87}" />
        <r ds="/sitecore/content/efcom/rootname/Shared Content/Home  Page/Accreditations" id="{6B524676-EFDD-4162-B811-356D0B16D7FF}" ph="page-content" uid="{525F2779-F62E-4854-9B5B-3B8FF8F093CD}" />
        <r ds="{D56983C1-6DDD-4AD5-8EC4-20A3EFDFD122}" id="{6F860D54-71D8-483A-823D-4B4ADA8D7FA4}" ph="page-content" uid="{EBCE499C-E401-4DF9-8843-56643929D465}" />
        <r id="{38D51FE9-2F21-40CC-8592-791E5D0F4C02}" ph="seo-footer-links" uid="{153E5A4B-150F-4C19-A969-50D59303704C}" />
    </d>
    <d id="{15404A50-DD1C-49BF-A78C-CD8444DEDA8C}" l="{8817B671-106D-43F9-BA5B-96760B040E5C}">
        <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Home Page/Stage" id="{7530255F-D52A-407C-AFAF-E85205EAA774}" ph="stage-section" uid="{E7CFA2B0-F47C-458E-A775-3ED5EA38011C}" />
        <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Modules/Language Picker" id="{D1E75065-4D19-43D7-B808-8192E18A93A9}" ph="stage-module" uid="{F28FECC5-86F4-41C1-953A-212B4C69A13F}" />
        <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Home Page/Pillars" id="{D911D90B-FD3D-41F2-AFFC-D15DA5991BF5}" ph="page-content" uid="{1FC1353D-3555-4A17-90AE-9B8B8D5299FA}" />
        <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Home Page/Mosaic" id="{2757881E-2DF1-41B4-A8FA-F9642111F7AB}" ph="page-content" uid="{3A7803F1-DA1E-47D3-B774-DE412BFC18D1}" />
        <r id="{001226C6-1628-447F-AC00-CC97D0885E21}" ph="page-content" uid="{F5EF2E98-DE8C-4B6A-B9E5-4D0F4F17CCBE}" />
        <r ds="{B26A6F13-5BA4-4BE7-8291-AB1E704812F6}" id="{42E40923-A71A-4390-8FD0-0DEFD039C38D}" ph="page-content" uid="{4A96287B-BCC7-4590-8D17-D0F0AEF47AF3}" />
        <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Modules/Infomeetings" id="{951599E8-BE82-4FB2-8CBE-C3DD88F7D948}" ph="page-content" uid="{2D536F9C-231F-45B8-93F9-FE45614611A7}" />
        <r ds="/sitecore/content/efcom/rootname/2017 Datasources/Modules/Language  Footer" id="{6F860D54-71D8-483A-823D-4B4ADA8D7FA4}" ph="page-content" uid="{EBCE499C-E401-4DF9-8843-56643929D465}" />
        <r ds="{837771F9-7563-4891-8F06-94CB314E32B9}" id="{5B4B3F4B-BB7E-4FE1-AFF8-2EF37FF7F2D2}" ph="mobile-content" uid="{33E5DE2C-52FE-484C-AC47-9AF3EFBCCF0B}" />
        <r ds="{9A9F466C-8CDF-4D98-8B05-5D065A193981}" id="{F20AFD9C-A742-44FB-8284-118957103937}" ph="mobile-content" uid="{EC7041DF-E605-424F-ABFF-9BC0D4B8B033}" />
        <r id="{3F382B7F-0765-4F1F-A13F-964E1A22190C}" ph="mobile-content" uid="{C1F6D9E7-08DF-47B1-AAB9-2C92EFA5EACC}" />
        <r ds="{4FBAB3BB-9E24-44E4-85DA-6A393E82A611}" id="{6C810F55-DB07-4790-BBE0-C5EA5748A9E2}" ph="mobile-content" uid="{2FA68151-D6C4-480F-B7BE-083688023903}" />
        <r ds="{8A21F5CD-E041-463C-9866-37CEE5D673DA}" id="{07A2E65C-5D25-4DB9-8FC4-47A60A63DA32}" ph="mobile-content" uid="{22176278-612D-4F9D-AE59-37F265E85D13}" />
    </d>
</r>

best,
Pierre

**Comment by AdamNaj** [comment]
Hi Pierre,

Unfortunately this confirms my suspicions from the previous comments... :( If you look at the XMLs in BEFORE - you will find the same UID for renderings in both devices. e.g. If you Search for `{F28FECC5-86F4-41C1-953A-212B4C69A13F}` a rendering with this UID is in both devices. I will have a think about how to handle this. We might need to add a `-DeviceHint` switch so that the device you specify is a preferred device in the seeking process, but as it stands now you unfortunately cannot process your layout with the existing cmdlets.

**Comment by pierresapinault-ef** [comment]
Yes I had just seen that, you were right. Probably the developer copied the renderings from last year and updated the path in it. So that means when an item is duplicated, Sitecore changes the ID but not the UniqueID?? Is that a bug or on purpose?
Same for helping out with this, it's more informative since we are handling it in a different way now but good to know!
best,
Pierre

**Comment by AdamNaj** [comment]
Closing as answered.
