### ISSUE TITLE
Incorrect context language in script session

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#694]
### Steps to Reproduce the Problem
  1.  Add new language to the system
  1.  Switch from `en` to `new_lang` (use query string `sc_lang` on desktop)
  1.  Open ISE
  1.  Execute script
``` powershell
[Sitecore.Context]::ContentLanguage
[Sitecore.Context]::Language
gi .
```
  
### Expected Behavior 
I am able to get proper context language 

### Actual Behavior
I always get item in **en** language.
Context properties from Sitecore also return english language.

**Comment by AdamNaj** [comment]
The following now works:
```powershell
[Sitecore.Context]::Language
```
While the following is not settable because it comes from the current site which is usually `shell` in PowerShell scripts:
```powershell
[Sitecore.Context]::Job,Language
```

**Comment by AdamNaj** [comment]
Implemented
