### ISSUE TITLE
Packages should support the addition of post-install xdt transforms

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#695]
Today there is no native way to apply post-install xdt transforms.

**Comment by michaellwest** [comment]
This feature could also add easier support for post install steps as PowerShell scripts.

**Comment by AdamNaj** [comment]
I am not 100% sure it's the job for this module...

**Comment by michaellwest** [comment]
Perhaps an addon module?

**Comment by AdamNaj** [comment]
While I can see value in having a functionality like this in Sitecore, I do not necessarily see how post install XML transformations are related to this module.

Post install scripts might be an interesting idea though.

**Comment by michaellwest** [comment]
JammyKam has a nice article on how one can accomplish this:
