### ISSUE TITLE
Type initializer exception when executing script via WebAPI

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#696]
### Steps to Reproduce the Problem
1. Add new Module with `Web API` integration point
2. Add new script under Web API folder (let's say name will be: Foo)
3. Insert following content 
```powershell
$pck = New-Package -Name "PckgName"
Export-Package $pck
```
**Now, kill your instance**
After that call following URL:
`http://domain/-/script/v2/master/Foo?user=admin&password=b`

### Expected Behavior 
Script executed, without any errors

### Actual Behavior
You will get following error as an API response:
```
Export-Package : The type initializer for 'Sitecore.Install.Serialization.IOUtils' threw an exception.
At line:3 char:1
+ Export-Package $pck
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-Package], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Cognifide.PowerShell.Commandlets.Packages.ExportPackageCommand
``` 

After these steps you will not be able to execute `Export-Package` anywhere

### Additional notes:
Very important here is fact that first thing you do after restart is Web API call.
If you turn instance off and on again and before calling script via Web API execute the script body from ISE, then everything will work fine.

**Comment by AlexKasaku** [comment]
This is due to the constructor of the `Sitecore.Install.Configuration.InstallerObjectFactory` type, which appears to be expecting to be instantiated when the current Database context is `core`, rather than `master`.

**Comment by AlexKasaku** [comment]
Implemented a fix.
