### ISSUE TITLE
Script is not executed remotely with no errors

### ISSUE THREAD

**Issue by jinek** [SitecorePowerShell/Console#698]
PS C:\Users\testUser> Invoke-RemoteScript -Session $session -ScriptBlock {Write-Host "test"}
PS C:\Users\testUser>
So no output, no errors.

If I call saved script via url it returns ok and no output:
http://sitecore/testpsscript/

If I call http://sitecore/sitecore%20modules/PowerShell/Services/RemoteScriptCall.ashx
it says 403 - forbidden

**Comment by AlexKasaku** [comment]
What parameters are you passing to your request to RemoteScriptCall? And what version of SPE are you running?

**Comment by Temaska** [comment]
I use 4.1 and **Write-Host** doesn't work remotely for me.
Try to just use "test" to display message
-ScriptBlock {"test"}

**Comment by AdamNaj** [comment]
Values written to host are not retrieved back. You need to pipe your result to `Out-Default` to get your results. Host text is discarded with remoting.
