### ISSUE TITLE
Incompatible scripts with Sitecore 8.2

### ISSUE THREAD

**Issue by rootix** [SitecorePowerShell/Console#701]
Hi

Sitecore removed the support for the old Search API starting with Sitecore 8.2

At least the following script isn't working anymore in this version:
```
/sitecore/system/Modules/PowerShell/Script Library/System Maintenance/Tasks/Rebuild search indexes
```

Probably there are more affected scripts (Cache API, Search API, usage of IsPageEditor and so on).

**Comment by AlexKasaku** [comment]
Thanks for raising this, there are quite likely others that may be affected. For that particular script, you can use the included `Rebuild content search indexes` task which uses `Sitecore.ContentSearch.ContentSearchManager`

**Comment by AdamNaj** [comment]
Mentioned script removed. It's obsolete since 7.0 - I think it's safe to not support the old API now.
Also while at it I did a review of some other Search scripts and removed them slightly... like the Rebuild on Index Viewer report. Now shows update progress.
