### ISSUE TITLE
In documentation, link commands to their manual page.

### ISSUE THREAD

**Issue by AlexKasaku** [SitecorePowerShell/Console#702]
I think it would be more helpful if the command links in the Documentation went directly to their command page, rather than the Glossary. Currently unsure how the documentation is built but happy to take a look at this.

e.g. Clicking Get-ItemReferrer would link to:

https://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/content/appendix/commands/Get-ItemReferrer.html

Rather than:

https://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/content/GLOSSARY.html#get-itemreferrer

**Comment by michaellwest** [comment]
Looks like this is a behavior in the Gitbook generator. Will need to investigate more.

**Comment by AlexKasaku** [comment]
Is it possible to get access to the gitbook repo, I'd be happy to have a look?

**Comment by AlexKasaku** [comment]
I can see how this needs to be implemented, it's mainly an update to the documentation generation script in SPE. Hoping to implement this week.

**Comment by AlexKasaku** [comment]
Implemented and all documentation regenerated.
