### ISSUE TITLE
Help shortcut cannot be closed if no matching command exists

### ISSUE THREAD

**Issue by kamsar** [SitecorePowerShell/Console#704]
To reproduce:

* Open ISE
* Enter, say, `throw 'hello'` - something that is not a command with help
* Hit ctrl-enter
* Result:

![image](https://cloud.githubusercontent.com/assets/103677/18521212/11d4f8fe-7a60-11e6-8f9a-2c74268dc4fc.png)

Note the lack of a close box. Clicking in the background also does not seem to dismiss the help modal.

**Comment by AlexKasaku** [comment]
A close button certainly would help. You can also use ESC to close the dialog.

**Comment by michaellwest** [comment]
Looks like the div containing the close button is returned in the command help results rather than coded on the client side.

**Comment by AlexKasaku** [comment]
I've made a few changes to improve the help dialog:

- Close button is now added client-side, and appears when there's no help text to show.
- Even when showing, ocassionally the close button wasn't working.
- Navigating links around the help would open more dialogs on top of each other, now they reuse the same dialog.
- Clicking outside of the dialog also now closes it.

**Comment by kamsar** [comment]
Awesome 😀
