### ISSUE TITLE
Import-Role commandlet does not work as documented

### ISSUE THREAD

**Issue by rootix** [SitecorePowerShell/Console#707]
I tried to Serialize some Roles with the command

    > Export-Role -Filter "sitecore\prefix*"

Which worked as expected.

When i tried to import the Roles on another instance, i tried the following command as seen in the Gitbook:

    > Import-Role -Filter "sitecore\prefix*"

It gives me the following exception:

    Import-Role : The name 'sitecore\prefix*' is improperly formatted.

    The name can only contain the following characters: a-z, 0-9, periods, dashes, underscores, backslashes, and spaces.
    Parameter name: name
    At line:1 char:1
    + Import-Role -Filter "sitecore\prefix*"
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Import-Role], ArgumentException
        + FullyQualifiedErrorId :     System.ArgumentException,Cognifide.PowerShell.Commandlets.Serialization.ImportRoleCommand

Isn't the filter method supported by Import-Role?

**Comment by AlexKasaku** [comment]
This looks like a bug to me, the Import-Role command is throwing an error due to trying to create an `AccountIdentity` with the given filter, which I don't think is applicable.

**Comment by michaellwest** [comment]
@AlexKasaku Please peer review.

**Comment by AlexKasaku** [comment]
Reviewed and discussed with @michaellwest to produce combined update!
