### ISSUE TITLE
Item Name Validation Error

### ISSUE THREAD

**Issue by ncipollina** [SitecorePowerShell/Console#711]
We are currently getting the following error message when either opening a script or executing a powershell command in the ISE window.

An item name must satisfy the pattern: ^[\w\*\$][\w\s\-\'\$]*(\(\d{1,}\)){0,1}$ (controlled by the setting ItemNameValidation)

This only happens in our production environment and does not occur in any other.  Does anyone have any idea of what might be causing this issue?

Thanks in advance,
Nick

**Comment by michaellwest** [comment]
Hi @ncipollina, what version of SPE do you have installed in production? I believe we encountered this issue some time back. Perhaps 4.1 will resolve the issue?

**Comment by ncipollina** [comment]
I just upgraded to 4.1 and I'm still seeing this issue.

**Comment by AlexKasaku** [comment]
Hi @ncipollina, are you able to pull out the full exception with stack trace from the logs?

**Comment by ncipollina** [comment]
@AlexKasaku part of the problem is that it isn't generating any errors in the log files.

**Comment by AlexKasaku** [comment]
Just a thought, do you know the account name (e.g. sitecore/something) of the user that is attempting to open the script in ISE in production?

**Comment by ncipollina** [comment]
@AlexKasaku I was using my own domain account.  When I switched to the admin account it works now.  My domain account is marked as an admin.  Is there some sort of verification that goes on concerning user account name?  If so, how do we overcome this?

Thanks,
Nick

**Comment by AlexKasaku** [comment]
That's why I asked for the name, are you able to share it? I suspect it contains invalid characters that don't match the above regex. When you execute an ISE script an item is created to store the last script you executed, using the account name.

**Comment by ncipollina** [comment]
I can't provide the specific name but the format is domain\email@address.com

**Comment by AlexKasaku** [comment]
Yep so that will fail the name validation. I think this could be classified as a bug as it's a valid Sitecore username so it should be handled. There is some logic to clean up the name of invalid characters, but it doesn't currently handle the @.

Unfortunately this logic will always run so for now you won't be able to use an account with that name format to run scripts.

**Comment by AlexKasaku** [comment]
The item name selection is now much more restrictive about what characters it allows, and any that aren't valid are stripped out, so this shouldn't prove a problem with email address usernames in the future.
