### ISSUE TITLE
Add possibility to choose context item for remote scripts

### ISSUE THREAD

**Issue by Temaska** [SitecorePowerShell/Console#712]
**Add possibility to choose context item for remote scripts**

Some cmdlets can't be executed without setting the context item
Example: Get-LayoutDevice
with context: 
![image](https://cloud.githubusercontent.com/assets/2772345/19228848/abbd3f96-8ed1-11e6-850e-4a127d7d9ea0.png)
without: 
![image](https://cloud.githubusercontent.com/assets/2772345/19228857/bf61e51a-8ed1-11e6-99c9-0f911e80293f.png)

Through remote execution I didn't find way to set up context item. So all my scripts which use this simple sample code are failed.
It would be nice to add functionality to set what context item should be used during script execution or connection.

**Comment by AdamNaj** [comment]
You can set the context to any item with

``` powershell
cd master:\
```

or the longer version:
``` powershell
Set-Location master:\
```

**Comment by Temaska** [comment]
It works! Thank you!
