### ISSUE TITLE
Package Generator : Should support options for autopopulating the fields with presets

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#714]
Would be nice if you can autopopulate the Author, version, readme, etc.

![image](https://cloud.githubusercontent.com/assets/933163/19323738/ca504c24-9083-11e6-89e2-4515e89e9f5d.png)

**Comment by AdamNaj** [comment]
The script is already doing that, no?
Except for readme - I don't really see how that would work :)

**Comment by michaellwest** [comment]
I guess what I was thinking holds true for many of the scripts we package. How does someone create configuration settings so they don't have to change the script?

**Comment by michaellwest** [comment]
Seems unnecessary to implement something for this.
