### ISSUE TITLE
Documentation : Add examples to book for re-linking items

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#718]
Based off of issue #717 and https://gist.github.com/AdamNaj/354660183bea96a4ceb06cf1a9a92f30#file-Relink-Test-ps1

**Comment by AdamNaj** [comment]
I've committed documentation with the examples in a bit more classic PS - potentially you could use those. They will also make it into the book when we regenerate the pages for the gitbook.

**Comment by michaellwest** [comment]
Excellent. Thank you @AdamNaj

**Comment by AdamNaj** [comment]
Maybe we should create those in the gitbook repo instead now that we have them hosted on Github?

**Comment by michaellwest** [comment]
Created new issue in the book.

https://github.com/SitecorePowerShell/Book/issues/3
