### ISSUE TITLE
Publish-Item seems not to work with different language than en

### ISSUE THREAD

**Issue by RajasekharVM** [SitecorePowerShell/Console#724]
Publish item is not working for all the languages which are specified.
my example code is like below;

``` powershell
publish-item -path "master:\home" -target web -publishmode Smart -Recurse -language "en", "en-GB", "Ar-SA"
```

**Comment by AdamNaj** [comment]
Hi @RajasekharVM,
I wonder if you are running SPE 4.1 or an older version by a chance. The `Publish-Item` Cmdlet was pretty seriously broken in previous versions.

**Comment by RajasekharVM** [comment]
i tried with providing the languages like "en-en" ,"Ar" then also it is not working

**Comment by AdamNaj** [comment]
What error do you see when you try to run the cmdlet?
First thing I can see is the path to the `Home` Item.

Did my test in 4.1 and it seems the following worked for me no problem:

```powershell
Publish-Item -Path "master:\content\home" -Target web -PublishMode Smart -Recurse -Language "da", "ja-JP", "de-DE", "en" -Verbose
```
Notice I've added the `-Verbose` parameter that might help you diagnose the problem.
Again - I'll need to know which version of SPE you are on. This Cmdlet was seriously broken in SPE 4.0.

**Comment by RajasekharVM** [comment]
hi Adam, thanks for responding.
I tried with SPE 4.1 only, I am trying to publish my complete site like ""master:\Sitecore" is the root.
SPE is downloaded from the below and version is "REMOTING SPE 4.1" https://marketplace.sitecore.net/en/Modules/Sitecore_PowerShell_console.aspx"

Still it is publishing (in web) in only en only even after providing the multiple languages which are already having languages in master.

I am running the commands in job like as shown below.

 $job = Invoke-RemoteScript -Session $session -ScriptBlock {Start-ScriptSession -ScriptBlock {Publish-Item -Path "master:\sitecore" -Target web -PublishMode Smart -Recurse -Language "en", "en-GB", "Ar-SA" -Verbose
      }        
    }

**Comment by RajasekharVM** [comment]
I am seeing any error , content is publishing but language versions are not publishing in web(other than en)

**Comment by RajasekharVM** [comment]
sorry i am not seeing errors.

**Comment by michaellwest** [comment]
The Start-scriptsession should not be there for remoting since it's already a background job.

**Comment by RajasekharVM** [comment]
I tried with out Strat-scriptession, Still it is not publishing all the specified languages...

**Comment by RajasekharVM** [comment]
Hi Michaellwest it is working for singlet item wise  like "$job = Invoke-RemoteScript -Session $session -ScriptBlock {Publish-Item -Path "master:\sitecore\content\Global Network\Global Site" -Target web -PublishMode Smart -Recurse -Language * -Verbose" ,
But in my case i want publish whole site in all specified languages (my root site is : master:\sitecore).. 

Please let us know if any other commands to publishing all the specified languages ..

**Comment by AdamNaj** [comment]
What do you see if you execute the script in ISE?
```powershell
Publish-Item -Path "master:\sitecore\content\Global Network\Global Site" -Target web -PublishMode Smart -Recurse -Language * -Verbose
```

**Comment by RajasekharVM** [comment]
Hi AdamNaj,
the above command is working to publish item wise  for specified  Languages , in case of if i am publishing complete site "master:\sitecore", the specified languages are not working.

**Comment by RajasekharVM** [comment]
If i specify languages Item wise (master:\sitecore\content\Global Network\Global Site) will work as expected. 
But if i specify language at root level like "master:\sitecore" , then in this condition languages are not working as expected for items also.

**Comment by AlexKasaku** [comment]
@RajasekharVM - It's really helpful if you can paste in the commands you ran and the output you received from SPE after each.

**Comment by RajasekharVM** [comment]
Hi ,
Please find the below commands. I am not getting errors. 

Item wise :  (Working as expected- publishing specified languages)
$job = Invoke-RemoteScript -Session $session -ScriptBlock {Publish-Item -Path "master:\sitecore\content\Global Network\Global Site" -Target web -PublishMode Smart -Recurse -Language * -Verbose

Complete site: (  whileOther publishing than en -Specified languages are not publishing ) ( I tried even by providing the language as * and specified langauage mentioned in 2.)

1: $job = Invoke-RemoteScript -Session $session -ScriptBlock {Publish-Item -Path "master:\sitecore" -Target web -PublishMode Smart -Recurse -Language * -Verbose

2: $job = Invoke-RemoteScript -Session $session -ScriptBlock {Publish-Item -Path "master:\sitecore" -Target web -PublishMode Smart -Recurse -Language "en*", "en-GB", "Ar-SA" -Verbose

**Comment by AdamNaj** [comment]
OK, have a suspicion what the issue might be... 
Can you check if the item that you're specifying as the root of publishing has the language you're asking to be published? If not, can you try to add one and try the publishing again?

Also... before we go deep into remote debugging - can you confirm whether or not the publishing operation works locally in ISE?

**Comment by alexmwillis** [comment]
I have the same issue. @AdamNaj you are correct, the command only publishes in language versions on the root item. Would it be possible to publish in all requested languages?

**Comment by AdamNaj** [comment]
Implemented. 
- Specifying languages without a wildcard will bypass the language version existence check on the root item now. 
- Wildcards still require the existence so e.g. `Language en-*` will not publish en-GB if it's not present on the publishing root.

**Comment by venkatashivakatta** [comment]
what is the solution here?

**Comment by venkatashivakatta** [comment]
root item has only en language. if i add required languages, will it publish from the root level if is use ($job = Invoke-RemoteScript -Session $session -ScriptBlock {Publish-Item -Path "master:\sitecore" -Target web -PublishMode Smart -Recurse -Language "en*", "en-GB", "Ar-SA" -Verbose) 

**PS master:\>Get-Item -Path master:/sitecore -Language * | Format-Table -Property DisplayName,Language,Id,Version,TemplateName
 
DisplayName Language ID                                     Version TemplateName
----------- -------- --                                     ------- ------------
sitecore    en       {11111111-1111-1111-1111-111111111111} 1       Root**
