### ISSUE TITLE
Developers should be able to set script execution in context of any user or language

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#726]

**Comment by AdamNaj** [comment]
@michaellwest , @AlexKasaku Did you guys have a chance to play with it?
If you don't see any problems with its operation, I'll close the issue as implemented.

**Comment by AlexKasaku** [comment]
I haven't yet, I can't *imagine* there's going to not going to be anything I don't like about it though :)

**Comment by michaellwest** [comment]
Received this error after choosing more languages. Clean install of SC with no languages other than en.

![image](https://cloud.githubusercontent.com/assets/933163/19708927/e30a9274-9ae7-11e6-8f58-99621c04c49b.png)

**Comment by AdamNaj** [comment]
Great catch! Fixed.
