### ISSUE TITLE
Dialog Commands: New commands for building UIs

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#727]
A few years ago when I first started learning PowerShell I learned of a [module](https://showui.codeplex.com/) that generated commands for building UI.

Here's an example of what I was thinking.
- `Show-UI` : The primary command for rendering a wizard or modal dialog.

Controls:
- `New-Label`
- `New-RuleEditor`
- `New-Treelist`
- `New-Droplist`

To build and show a dialog you would do this:

``` powershell
$tabs = @()

$firstTabControls = @(
    New-Checkbox -Title "Proceed Silently" -Value $true -Tooltip "Check this if you don't want to be interrupted",
    New-Textbox -Title "Text" -Value "Some text" -Placeholder "You see this when text box is empty" -Tooltip "Just a single line of Text" -ValidationExpression "[a-zA-Z]*"
)

$tabs += New-Tab -Name "FirstTab" -Title "Start" -Controls $firstTabControls

Show-UI -Title "Welcome to your first Wizard!" -Tabs $tabs
```

**Comment by AdamNaj** [comment]
I highly doubt we'll get to ever implement this. Should we close it for now?

**Comment by michaellwest** [comment]
Might be good for a 5.0 release.

**Comment by AdamNaj** [comment]
Cleaning up backlog. If you decide to implement it, feel free to re-open.
