### ISSUE TITLE
Introduce validation to Read-Variable properties and the form as a whole

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#728]
As documented in https://gist.github.com/AdamNaj/37ad58e1a9350604e4815ca586acf39e

**Comment by michaellwest** [comment]
I noticed that if there is an error in the validation scriptblock you have no way of viewing the output from the session.

**Comment by michaellwest** [comment]
Here is an approach that I got working. The Validator appears to use a different session so any functions defined in the script won't load; therefore I created reusable functions. Any chance we can get the functions to auto-load?

```powershell
$result = Read-Variable -Parameters `
    @{ Name = "username"; Value=""; Title="UserName"; Placeholder="User name goes here"; Mandatory=$true;
        Validator = { 
            Import-Function -Name Assert-UsernameRequirement
            $variable.Error = Assert-UsernameRequirement -Id $variable.Value
        }
    },
    @{ Name = "password"; Value=""; Title="Password"; Editor="password"; Placeholder="Password goes here"; 
        Validator = {
            Import-Function -Name Assert-PasswordRequirement
            $variable.Error = Assert-PasswordRequirement -Password $variable.Value
        }
    },
    @{ Name = "description"; Value=""; Title="Description"; Lines=3; Placeholder="User description";
        Validator = {
            Import-Function -Name Assert-NotNullOrEmpty
            $variable.Error = Assert-NotNullOrEmpty -Value $variable.Value
        }
    } `
    -Description "This Dialog shows how to provide a validator for values" `
    -Title "Password entry" -Width 450 -Height 450 -OkButtonName "Proceed" -CancelButtonName "Abort" -ShowHints
```

**Comment by AdamNaj** [comment]
You are right in the fact the session is a one-off throw away session that does not collect input.
It's still possible to Write-Log if needed, but I think I'll need to add error logging so it's easier to debug those little scripts.

For diagnostics purposes you can always append your message to the $variable.Error until you're happy with the results.

I think it's OK to ask people to import their own functions explicitly. In most cases the code is simple enough that it doesn't need a function and since section initialization happens every time a field is validated it could take a considerable time if we added all functions every time.

**Comment by michaellwest** [comment]
You raise some good points @AdamNaj . Thanks for the clarification.

**Comment by AdamNaj** [comment]
Implemented
