### ISSUE TITLE
ISE Results close button and Progress Overlay should not scroll with results.

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#730]
With the change introduced with #710  the Progress indicator and close button started scrolling when the script output overflown a single width of the results container div.
Those should always stay visible.

![image](https://cloud.githubusercontent.com/assets/1209953/19665683/7ab4367c-9a46-11e6-86ed-df95adf41ad1.png)

**Comment by AlexKasaku** [comment]
Good spot!

**Comment by AdamNaj** [comment]
Fixed.
