### ISSUE TITLE
Cannot add a User to a Role where the User name contains the “@” sign using PSE

### ISSUE THREAD

**Issue by EmanueleCiriachi** [SitecorePowerShell/Console#731]
I have to bulk-add a large number of users to a role, to this extent I am using the Add-RoleMember cmdlet.

If I run

`Add-RoleMember -Identity  "<role name>" -Members "name.lastname"`

it works fine, however in our instance the users come from an Okta Membership Provider, where they are identified by their domain\email - such as

`domain\name.lastname@maildomain.com`

When I try to run

`Add-RoleMember -Identity  "<role name>" -Members "domain\name.lastname@maildomain.com"`

I am greeted with a:
"Error: The name is improperly formatted. The name can only contain the following characters: a-z, 0-9, periods, dashes, underscores, backslashes, and spaces."

Can we add the "@" sign to the list of allowed characters?

**Comment by AlexKasaku** [comment]
This is indeed a bug in the `AccountIdentity` class, where the regex it uses to validate the name is too restrictive. This needs to be updated there.

**Comment by AdamNaj** [comment]
Implemented
