### ISSUE TITLE
QUESTION: Workflow Dialog Box

### ISSUE THREAD

**Issue by SHaberm** [SitecorePowerShell/Console#739]
I have created a workflow action using Powershell.  When the task is run, is there a way to prevent the dialog box "Running scipt" from appearing to the user?  I have looked and cannot find anything specific to keeping the dialog from displaying.

Thanks

**Comment by AdamNaj** [comment]
Unfortunately not at the moment. We need this dialog to attach user interface action monitor control to. e.g. any dialogs that you might want to launch. I was thinking however about adding a cmdlet that would let you close the dialog, although it would still blink for a while.

**Comment by AdamNaj** [comment]
What you can do however is Give the dialog some meaningful temt/messages by using the `Show-Progress` cmdlet and then closing it with `Close-Window` cmdlet once the script ends executing.

e.g Like the following script will produce the dialog below, do your actions and then close the dialog.
```powershell
Write-Progress -Activity "Now I'm doing something..." `
    -Status "Should take me about 3 seconds but I'm not quite sure...";
# your script actions
Close-Window
```

![image](https://cloud.githubusercontent.com/assets/1209953/20218634/d4d325fe-a825-11e6-9369-0cedf2128a40.png)

**Comment by SHaberm** [comment]
Thanks for the reply.  The issue I was having related to Workflow.  I created a script that checks if the item being published has any associated aliases.  If so, publish those as well.  We were noticing that the dialog box that pops up was staying on the screen (hanging).  I figure I would check to see if we could just get rid of it but understand why we cannot.

Thanks

Scot Haberman
HR & Corp App Delivery
(980) 373-2627
