### ISSUE TITLE
RemoteAutomation.asmx not working after installing Sitecore Powershell Extension 4.0 in Sitecore 8.1

### ISSUE THREAD

**Issue by abkeshri** [SitecorePowerShell/Console#740]
Hi, 

I have installed Sitecore Powershell Extension 4.0 in Sitecore 8.1 instance, but RemoteAutomation.asmx service is not working. As it was works fine with Sitecore 7.2.

My local sitecore 8.1 instance name : mySitecore8local/
I have browsed below url to access RemoteAutomation.asmx Service

mySitecore8local/Console/Services/RemoateAutomation.asmx

Is there any instructions to follow to get it resolved or I am installing the wrong version of Sitecore Powershell Extension for Sitecore 8.1. Please help. Thanks!

Regards,
Abhishek

**Comment by AdamNaj** [comment]
Is remote automation enabled in the Cognifide.PowerShell.config?

You can try following the advices from this document: https://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/content/remoting.html

**Comment by AdamNaj** [comment]
Closing, since there was no update for over 3 weeks. Assuming it's resolved.
