### ISSUE TITLE
SPE 4.2 : Package incorrectly contains events config

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#741]
The package contains the `Cognifide.PowerShell.Events.config` in both the enabled and disable state.

![image](https://cloud.githubusercontent.com/assets/933163/20290951/f2cdd6f0-aaa8-11e6-9b35-784220824387.png)

**Comment by AdamNaj** [comment]
New packages are uploaded and published (bottom of the list). Pieter is still working on removing links to the old ones that are throwing YSODs at the moment.
