### ISSUE TITLE
Add TimeOut parameter to remote script session

### ISSUE THREAD

**Issue by Temaska** [SitecorePowerShell/Console#742]
By my project needs I need to setup timeout parameter for remote script session.
So I had to modify New-ScriptSession.ps1
It would be great if you add this functionality to the SPE 

/Modules/SPE/New-ScriptSession.ps1

expand parameters list with a new one:
```
[Parameter(Mandatory = $false, ParameterSetName = "Timeout")]
[long]$TimeOut,
```

and then setup the timeout to a proxy object:
(line 100)
```
if($TimeOut) {
      $proxy.TimeOut = $TimeOut
}
```

Usage (set timeout up to 10 min):
`$session = New-ScriptSession -Username admin -Password b -ConnectionUri http://remotesitecore -Timeout 600000 `

Thank you

**Comment by michaellwest** [comment]
@Temaska Great idea. I added the parameter but changed the units to **seconds**.

```powershell
$timeout = 600 # seconds
$session = New-ScriptSession -Username admin -Password b -ConnectionUri http://remotesitecore -Timeout $timeout
```

**Comment by Temaska** [comment]
@michaellwest Thank you so much!

**Comment by michaellwest** [comment]
Implemented.
