### ISSUE TITLE
Cannot GetItem with asterisk in the name

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#749]
**How to reproduce:**
- Create the following script and save it as a Context Menu integration script
![image](https://cloud.githubusercontent.com/assets/6848691/20598697/a5079722-b24a-11e6-9264-6ccbb5003b51.png)

**body:**
```powershell
gi .
get-host
```

- Invoke it in a Content Editor from Context Menu (or simply run script in ISE - for some reason I've got different results in ISE for different instances)
![image](https://cloud.githubusercontent.com/assets/6848691/20598708/b670fc24-b24a-11e6-92e8-9f23ec9fed9f.png)

**Actual:**
`Get-Item` returns incorrect item

**Expected:**
I am able to use `Get-Item` when my context item contains asterisk in the name

**Comment by AdamNaj** [comment]
Fixed
