### ISSUE TITLE
Security : Improve Elevated Session State messages and style

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#761]
I'm proposing a few changes to improve the messages for **Elevated Session State**.

**Comment by michaellwest** [comment]
Changed the message and color.
![image](https://cloud.githubusercontent.com/assets/933163/20870989/3ddc3c10-ba56-11e6-85f3-e5d47b596d05.png)

Changed the window title text and color. Changed the password message.
![image](https://cloud.githubusercontent.com/assets/933163/20870991/4748fb8a-ba56-11e6-9e0a-6fbb025fa3a3.png)

Reduced the padding.
![image](https://cloud.githubusercontent.com/assets/933163/20870997/51519222-ba56-11e6-9a3c-8f5cfe23cc1f.png)

**Comment by michaellwest** [comment]
I like this better. The red is a little more subtle.

![image](https://cloud.githubusercontent.com/assets/933163/20871420/5108addc-ba5b-11e6-8cc2-af797c785ee4.png)

![image](https://cloud.githubusercontent.com/assets/933163/20871423/59d030de-ba5b-11e6-82f0-c9d60ba79f30.png)

![image](https://cloud.githubusercontent.com/assets/933163/20871430/68a248ae-ba5b-11e6-84f7-acfe62dbe328.png)

**Comment by michaellwest** [comment]
Not sure how to change this though.

![image](https://cloud.githubusercontent.com/assets/933163/20871488/0929eb24-ba5c-11e6-84cf-a230ae797d6d.png)

**Comment by michaellwest** [comment]
Updated message.

![image](https://cloud.githubusercontent.com/assets/933163/20872385/a4f22362-ba63-11e6-8a3a-5d9b7d07d0b1.png)

**Comment by AdamNaj** [comment]
Agree with the change of wording, but not with the choice of colors.
In my opinion (and that seems to be consistent with other Sitecore styling) red is used for errors and what we're facing here is a warning where both Sitecore and Windows are using yellow.

**Comment by michaellwest** [comment]
Ok.
