### ISSUE TITLE
Read-Variable with duplicate field names results in unhelpful error when closing dialog

### ISSUE THREAD

**Issue by techphoria414** [SitecorePowerShell/Console#768]
`Read-Variable -Parameters @{ Name="Test"; Title="Test 1";  }, @{ Name="Test"; Title="Test 2"; }`

Running the above on 4.3 results in a dialog that opens fine, but when clicking "OK" or "Cancel" the following error is presented:

> Multiple controls with the same ID 'var_Test_validator' were found. FindControl requires that controls have unique IDs.

**Comment by michaellwest** [comment]
@techphoria414 Should the user see this?

![image](https://cloud.githubusercontent.com/assets/933163/21442953/e9e04b50-c866-11e6-96e0-3ad171def7eb.png)

**Comment by techphoria414** [comment]
@michaellwest Looks much better!
