### ISSUE TITLE
Command : Get-ChildItem now supports -Depth parameter

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#769]
PowerShell now supports a new parameter for `Get-ChildItem` called depth.

![image](https://cloud.githubusercontent.com/assets/933163/21448158/09bc6ace-c8a5-11e6-941e-db15826c581e.png)

**Example:** The following recursively searches from child items and stops after two levels deep.
```powershell
Get-ChildItem -Path "master:\media library\" -Recurse -Depth 2
```

The following error message is received in SPE 4.3 on a machine which supports the new parameter.

![image](https://cloud.githubusercontent.com/assets/933163/21448192/5536b40a-c8a5-11e6-8be3-966c67315b74.png)

**Comment by michaellwest** [comment]
Looks like in PowerShell 3 the parameter was already there, just not implemented by the FileSystem provider.

**Comment by AdamNaj** [comment]
Good job and great find! it's going to be really helpful :)
