### ISSUE TITLE
New modules are always created under Script Library root

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#770]
### Steps to Reproduce the Problem
  1. Open CE
  1.  Navigate to Script Library
  1. Create `PowerShell Script Module Folder`
  1. Try to create new Module under folder
  
### Expected Behavior 
New module created under folder

### Actual Behavior
New module created under Script Library root

**Comment by AdamNaj** [comment]
Appears to be working now. Great Job!
