### ISSUE TITLE
Default services configuration for Sitecore Client Users role is incorrect

### ISSUE THREAD

**Issue by techphoria414** [SitecorePowerShell/Console#773]
The default service config for _handleDownload_ and _execution_ is supposed to include the _sitecore\Sitecore Client Users_ built-in role, but is missing the "s" on the end of the role name. The attached configuration patch resolves the issue.

[zClientFix.SitecorePowerShell.config.txt](https://github.com/SitecorePowerShell/Console/files/674711/zClientFix.SitecorePowerShell.config.txt)

**Comment by michaellwest** [comment]
Duplicate of issue #765. Code checked in addresses typo.

**Comment by michaellwest** [comment]
Fixed.
