### ISSUE TITLE
Ribbon integration does not properly render Tooltip

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#776]
I started looking into saving the tooltip in the "__Short description" field on the script item. Whenever you run the integration sync it would pull from this value and stuff into the Tooltip field on the Large button item.

Why is the item convention different than all of the other sitecore ribbon buttons?

To get it working I needed to create a chunk item with the child button, and then a separate reference item.

![image](https://cloud.githubusercontent.com/assets/933163/21583713/829d85d6-d052-11e6-96a9-f7da07833211.png)

With this setup, the tooltip appears.

![image](https://cloud.githubusercontent.com/assets/933163/21583716/9aa25eea-d052-11e6-9bed-5a055b12303b.png)

Using the panel and the orientation of items generated by SPE, the tooltip doesn't work.

![image](https://cloud.githubusercontent.com/assets/933163/21583724/f323c3f6-d052-11e6-9a55-6ed36b9310a6.png)

**Comment by AdamNaj** [comment]
This does not really take the tooltip from the script does it? It only displays the tooltip if you added it to core database but will wipe it out if you move the script, right?

**Comment by michaellwest** [comment]
Yes @AdamNaj , that is correct.
