### ISSUE TITLE
PowerShell issue

### ISSUE THREAD

**Issue by gdhcl** [SitecorePowerShell/Console#779]
Hi 
We have installed the updated Power shell Extension(Full 4.3 release for Sitecore 7) from market place.
https://marketplace.sitecore.net/en/Modules/Sitecore_PowerShell_console.aspx

We earlier had PowerShell Extension 3.3 on Sitecore version 7.2 Update 6.

After installing we are facing the following issue only in chrome where as in IE its showing its expected behavior ie it displays the security Dialogue pop up.

![powershellissue](https://cloud.githubusercontent.com/assets/10414145/21714017/e6bb17bc-d422-11e6-9a45-b2362210bceb.png)

We need  help in this regard.

Thanks
Debi

**Comment by michaellwest** [comment]
@gdhcl Have you cleared your browser cache?

**Comment by gdhcl** [comment]
Thanks @michaellwest After clearing the cache it worked..

**Comment by michaellwest** [comment]
Great. Don't hesitate to post another issue or contact us with more questions.
