### ISSUE TITLE
Copy-Item should support a recursive flag for child items

### ISSUE THREAD

**Issue by MichaelBosch** [SitecorePowerShell/Console#780]
It should be possible to execute something like this:
copy-item "master_legacy:\media library\MySite" "master:\media library" -TransferOptions 0 -Recursive 1

This would create the MySite folder in the destination and then loop through all the children of MySite and create those items as well including subfolders and other child items.

Currently, this will just create an empty folder named MySite on the target.

**Comment by michaellwest** [comment]
@MichaelBosch 
With the following script, I was able to make this happen:

```powershell
# I manually created Social2 in this example
Copy-Item -Path "master:\media library\Images\Social\Connector" -Destination "master:\media library\Images\Social2" -Recurse
```

![image](https://cloud.githubusercontent.com/assets/933163/21746805/c6f85c46-d517-11e6-8873-0d060bd50707.png)

Is this what you are trying to achieve?

**Comment by michaellwest** [comment]
Do note that `-TransferOptions` is a dynamic parameter only on the *CmsItemProvider* while the `-Recurse` switch is available by default.

**Comment by MichaelBosch** [comment]
Yep.  Got it working.  Thanks!
