### ISSUE TITLE
Dialog : Read-Variable doesn't recognize value of type Item

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#781]
When using `Read-Variable` and providing a Value of type `Item`, the field is blank.

Code:
```powershell
$defaultRootItem = Get-Item -Path "master:\content\home"

$props = @{
    Title = "Sample"
    Description = "Sample sample."
    Parameters = @(
        @{Name="rootItem"; Value=$defaultRootItem; Title = "This should be a content item"; root="/sitecore/content/"; Editor="Droptree"}
    )
}

$result = Read-Variable @props
```

Dialog:
![image](https://cloud.githubusercontent.com/assets/933163/21739296/453104c0-d45d-11e6-8b06-af4ecd093da4.png)

**Comment by michaellwest** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/933163/21739322/e60b9b44-d45d-11e6-940d-3fc31a7dd85c.png)

**Comment by michaellwest** [comment]
Fixed.

**Comment by AdamNaj** [comment]
Not quite sure why have you limited the check to Item. 
Removing the PSObject wrapper on all values by default instead.
