### ISSUE TITLE
SPE Scripts cannot be installed via Update Packages in 4.3.1

### ISSUE THREAD

**Issue by mikeedwards83** [SitecorePowerShell/Console#783]
If you add an script to an update package it cannot be installed to a Sitecore instance using the UpdateInstallationWizard.

An item is created in Sitecore but it has no versions.

Commenting out the following event handler fixes the problem:

    <handler type="Cognifide.PowerShell.Core.Settings.Authorization.ScriptItemSecurityEventHandler, Cognifide.PowerShell" method="OnEvent" />

There is also a duplicate entry of this handler:
https://github.com/SitecorePowerShell/Console/blob/master/Cognifide.PowerShell/App_Config/Include/Cognifide.PowerShell.config#L56
https://github.com/SitecorePowerShell/Console/blob/master/Cognifide.PowerShell/App_Config/Include/Cognifide.PowerShell.config#L342

**Comment by AdamNaj** [comment]
You can disable ItemSave protection by placing this patch in your Include folder:
```xml
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
  <sitecore>
    <powershell>
      <userAccountControl>
        <gates>
          <gate name="ItemSave">
            <patch:attribute name="token">Permissive</patch:attribute>
          </gate>
        </gates>
        <tokens>
          <token patch:before="*[@name='Default']" name="Permissive" expiration="00:00:00" elevationAction="Allow"/>
        </tokens>
      </userAccountControl>
    </powershell>
  </sitecore>
</configuration>
```

Would you be so kind to provide an update package with one random script so I can test it and devise a solution for the problem that will respect the update process, please?

**Comment by AdamNaj** [comment]
Fixed.

**Comment by mikeedwards83** [comment]
@AdamNaj  The scripts now automatically display, I don't get the link to elevate my permissions. Is this expected?

**Comment by AdamNaj** [comment]
The patch include file disables script save  security to pre 4.3 level and is a temporary fix to the problem you're experiencing.  However the fix in code I've committed solves this problem without having the include config file deployed.  With 4.4 you won't have to use it and update packages will still work.
