### ISSUE TITLE
Update-ListView command does not update ListView items

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#786]
### Steps to Reproduce the Problem
* Create following scripts:
![image](https://cloud.githubusercontent.com/assets/6848691/21851589/06708600-d810-11e6-97c9-cd6608edf635.png)

**Update**
```powershell
Get-ChildItem master:\ | update-listview
```
**ListView**
```powershell
Get-ChildItem master:\content | Show-ListView -Property DisplayName, __Updated , "__Updated by"
```
 
* Open `ListView` script and execute it.
* Click **Update** button
![image](https://cloud.githubusercontent.com/assets/6848691/21851705/8139511e-d810-11e6-9bc4-19d014c5b342.png)

  
### Expected Behaviour 
List is populated with updated datasource

### Actual Behavior
List not updated
![image](https://cloud.githubusercontent.com/assets/6848691/21851709/8904608c-d810-11e6-803f-fc8c1b9ecbb2.png)

**Comment by AdamNaj** [comment]
Fixed
