### ISSUE TITLE
Show-Result -Text overlapped with another modal dialog

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#790]
### Steps to Reproduce the Problem
  1. Open ISE
  1. Run the following code

  ```powershell
"Log message 1"
"Log message 2"
"Log message 3"
"Log message 4"

Show-Result -Text 

Start-Sleep -Milliseconds 1000

$params= New-Object Hashtable
$params += @{ Name = "Description"; Title = ""; Value = "Something"; editor = "info"; }
$result = Read-Variable -Parameters $params `
-Description " " `
-Title "Title"  -Width 500 -Height 500 `
-OkButtonName "Proceed" -CancelButtonName "Abort"
```
### Expected Behaviuor 
**Read-Variable** dialog should appear after I close **Show-Results** modal dialog windows.

### Actual Behaviuor
**Read-Variable** dialog appears immediately, thus it overlaps **Show-Results** modal dialog.

![image](https://cloud.githubusercontent.com/assets/6848691/21929089/eb21df90-d98e-11e6-99b1-ea730dc3d1de.png)

**Comment by AdamNaj** [comment]
Implemented

**Comment by alan-null** [comment]
It works!
Thanks!

**Comment by michaellwest** [comment]
This appears to have caused `Show-Result -Text` to stop working when running from the context menu.

When I run the context menu "Run Unit Test" the job dialog just sits there.

![image](https://cloud.githubusercontent.com/assets/933163/21964695/af6ebd7c-db16-11e6-96a8-213d7072f359.png)

**Comment by AdamNaj** [comment]
This is caused by another issue:  Inability to use `Write-Progress` with indeterminate -Percent - reporting and fixed separately.
