### ISSUE TITLE
Wev API documentation improvement

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#792]
docs url: https://doc.sitecorepowershell.com/web-api.html

Following example URL
`http://remotesitecore/-/script/v2/master/homeanddescendants?user=admin&password=b`
is no longer valid. 

I know this is an example but someone might get stuck like I did.

value `admin` is no longer valid for pattern in [`WildcardMatch` method](https://github.com/SitecorePowerShell/Console/blob/master/Cognifide.PowerShell/Core/Settings/Authorization/AuthorizationEntry.cs#L65)

I had to provide following user via query string: `sitecore\admin` and this should be default one right now.

**Comment by michaellwest** [comment]
Thanks for reporting it @alan-null . Also created a new repo for the book in case you didn't know.
