### ISSUE TITLE
ISE does not execute with 4.3 security upgrade

### ISSUE THREAD

**Issue by plfields** [SitecorePowerShell/Console#793]
We are running sitecore 8 and have upgraded to PowerShell 4.3. After being prompted to elevate security, scripts do not run/execute; neither can I open alternate scripts. However scripts will run fine in the powershell console. Here is my gate configuration.

    <userAccountControl>
        <gates>
          
          <gate name="Console" token="Console"/>
          <gate name="ISE" token="ISE"/>
          <gate name="ItemSave" token="ItemSave"/>
        </gates>
        <tokens>
          
          <token name="Default" expiration="00:00:00" elevationAction="Block"/>
          <token name="Console" expiration="00:30:00" elevationAction="Password"/>
          <token name="ISE" expiration="00:30:00" elevationAction="Password"/>
          <token name="ItemSave" expiration="00:30:00" elevationAction="Password"/>          
        </tokens>
      </userAccountControl>

**Comment by AdamNaj** [comment]
A very common problem after SPE upgrades is that the Java scripts (that make ISE tick) get cached in the browser and you need to purge the browser cache to make things work again. Can you make sure that this is not the problem before we go deeper?

**Comment by plfields** [comment]
AdamNaj,

thank you kindly. That resolved my issue. Very much appreciated sir!

**Comment by AdamNaj** [comment]
Great news! I hope you'll enjoy the improvements we've put into the project since the version you've used before :)

**Comment by michaellwest** [comment]
Any way for SPE to use versioned or timestamped query strings with the JavaScript resources?
