### ISSUE TITLE
Unable to use @ sign in the Identity parameter for Get-User cmdlet

### ISSUE THREAD

**Issue by EmanueleCiriachi** [SitecorePowerShell/Console#797]
Due to Active Directory integration, our fully qualified names all contain emails; while trying to batch process a bunch of them, I realized that I cannot Get-User anything - I get

`"The name 'Emanuele.Ciriachi@email.com' is improperly formatted.`
`The name can only contain the following characters: a-z, 0-9, periods, dashes, underscores, backslashes, and spaces.`

This is similar to [issue 731](https://github.com/SitecorePowerShell/Console/issues/731), and I will try my hand at fixing it myself.

**Comment by EmanueleCiriachi** [comment]
This was actually fixed in 4.3.

**Comment by AdamNaj** [comment]
Awesome!
