### ISSUE TITLE
Close-Window command closes ListView window when not in Desktop mode

### ISSUE THREAD

**Issue by jomiham** [SitecorePowerShell/Console#798]
We have a few reports that are run from the Content Editor (ribbon or context menu) and would like to show a ListView report without the users having to manually close the progress dialog.

However, the `Close-Window` command behaves differently depending on if the script is started from Desktop mode or from Content Editor mode.

Consider this simple script:
```powershell
Get-ChildItem . | Show-ListView -Property ItemPath, Language, Version
Close-Window
```

When running from Content Editor context menu in Desktop mode, it works as expected.
However, when doing the same from the Content Editor mode (i.e. click on Content Editor in the Dashboard), it behaves differently:

**Expected result:** 
The progress dialog should be closed, but the ListView window should remain open. (same as in Desktop mode)

**Actual result:** 
The progress dialog is closed, but the ListView window never shows up.

Steps to reproduce:
1. Install attached package (includes a module called "Issue - Close-Window closes ListView window" with two small sample scripts)
1. In Desktop Mode: Open the Content Editor
1. Right click on /sitecore and run the **"Without Close-Window"** script - Note that both Report and Progress dialog window remains open
1. Now run the **"With Close-Window"** script (same way) - Note that Progress dialog closes, while Report window remains open.
1. Exit Desktop mode and open Content Editor directly from Dashboard
1. Run the **"Without Close-Window"** script - Note that both windows remain open
1. Finally, run the **"With Close-Window"** script - Note that the Progress dialog closes but no Report window is shown!

Not sure if it is relevant, but I noticed that without the Close-Window command, the Progress dialog ends up:
- _in front of_ the Report in Desktop mode
- _behind_ the Report in the Content Editor mode.

[Sample scripts - Close-Window closes ListView window.zip](https://github.com/SitecorePowerShell/Console/files/714514/Sample.scripts.-.Close-Window.closes.ListView.window.zip)

**Comment by AdamNaj** [comment]
I will most definitely investigate if I can work around it, but Sitecore apps act significantly different when they are run in "full screen" mode than when they are one-of-many on desktop. It's currently not possible to have 2+ "non-modal windows" on one tab in this mode as it is.

What I can suggest is to run `Show-ListView` with `-Modal` parameter. This way the list  view should be available to your user and the "script runner" dialog should close the moment you close the List View.

**Comment by jomiham** [comment]
Thanks Adam! I tried the `-Modal` workaround and it does get rid of the "script runner" dialog. 

However, we use the Open (item) action for mosts reports and it seems that in Desktop mode the new Content Editor opens in the background (behind the report window) which of course is confusing for the users...

I haven't had time to test yet, but maybe that could be solved if the Open action uses `-Modal` for the `Show-Application` command as well? Or is there any way of finding out if a script is run in full screen or desktop mode?

**Comment by AdamNaj** [comment]
You're right, you should try to modify those calls to be modal too, which will make them behave like in full screen mode.

**Comment by AdamNaj** [comment]
Looking at the examples provided adding -Modal works and it seems achieves your original and updated goal. Closing the issue for now. Feel free to re-open it if there are other issues with it.
