### ISSUE TITLE
Show-ListView filter should support searching for multiple keywords rather than exact match

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#801]
As pointed out by the question [here](http://sitecore.stackexchange.com/questions/3884/how-to-use-multiple-words-in-quick-filter-box-in-sitecore-powershell-show-listvi), the filter on `Show-ListView` doesn't appear to acknowledge multiple keywords spread across multiple columns.

Here is an example:
![image](https://cloud.githubusercontent.com/assets/933163/22093140/de3acb6e-ddc8-11e6-9528-b026f1022225.png)

I expect using the words *finish* **and** *corrupted* to return two different records, but instead all records are hidden. Searching for *finish* **or** *corrupted* will return a single record.

![image](https://cloud.githubusercontent.com/assets/933163/22093184/3ad8a33c-ddc9-11e6-9ee8-d321bf4877d8.png)

**Comment by AdamNaj** [comment]
This is not a bug. The search was performed on a literal phrase as designed.
That said it's a worthy improvement to have.

**Comment by AdamNaj** [comment]
I've implemented the improvement but it's not working 100% as you requested. it still requires for all words to be present in one item, just not in one field. I don't want us to implement boolean logic here, it's not really a search component.

**Comment by jomiham** [comment]
Would it be possible to allow quoted strings to support literal phrases as well?

**Comment by AdamNaj** [comment]
Literal phrases with quotes implemented on top of the new behaviour.

**Comment by jomiham** [comment]
Fantastic! Thank you Adam!
