### ISSUE TITLE
Failed - Network Error when exporting CSV, Excel, etc from Show-ListView

### ISSUE THREAD

**Issue by SHaberm** [SitecorePowerShell/Console#804]
Having a strange problem and am stuck where to look next.  We have 3 CM servers.  All have SPE installed on each.  For some reason, one of the servers is giving us an error when we try to export entries from List View.

Our report displays without any issues on all 3 servers.  2 of the 3 servers export to the selected file type without issue.  1 server always gives us a problem.  The configuration between the servers are identical except the 1 server is the publishing server as well.

When I click the CSV button in the list view, i do get a message in the log:
5256 2017:01:23 13:18:49 ERROR The term 'Full' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.At line:1 char:1
+ Full Alias Name,Links to?
+ ~~~~

Again, works on other two servers without an issue but not on this one.  I do beleive it is something specific on this server but hit a wall as to where to look next.  Any help would be appreciated.

**Comment by michaellwest** [comment]
What version of Windows PowerShell is on each server?
What version of SPE is on each server?

**Comment by SHaberm** [comment]
SPE 3.2
PowerShell 3.0

**Comment by michaellwest** [comment]
Hi @SHaberm , any chance you can upgrade to version 4.3? There has been quite a number of improvements/fixes since 3.2.

**Comment by SHaberm** [comment]
Let me try that first and see what happens.  If the error persists, will update this thread.

**Comment by AdamNaj** [comment]
Assuming things worked (for lack of activity). Feel free to reopen the issue otherwise.
