### ISSUE TITLE
Allow POST to RestfulService v2

### ISSUE THREAD

**Issue by dsolovay** [SitecorePowerShell/Console#805]
Currently, only GET is allowed to RestfulService. It would be useful to have the option to POST, as this would avoid recording passwords to IIS logs, and would be more appropriate for scripts that make changes.

This can probably be accomplished by adding a `POST/2` entry to `apiVersoinsToServiceMapping` dictionary in [RemoteScriptCall.ashx.cs](../blob/master/Cognifide.PowerShell/sitecore%20modules/PowerShell/Services/RemoteScriptCall.ashx.cs#L42)

**Comment by dsolovay** [comment]
If you agree, I can submit a PR.

**Comment by AdamNaj** [comment]
Sounds like a worthy and useful addition. Since you seem to b in context already, you're probably in best position to test it  Dan. Go ahead!

**Comment by michaellwest** [comment]
@dsolovay I've been writing unit tests in Pester for PowerShell. What might be a good way to test this behavior?

**Comment by AdamNaj** [comment]
@dsolovay we will be wrapping the 4.4 soon. Do you think you'll have the time to include your code or would you prefer that I provide an implementation for it?

**Comment by dsolovay** [comment]
It looks like the current Pester tests should work, as long as you provide a `-method post` parameter.

**Comment by dsolovay** [comment]
Why don't you go for it, Adam. I probably won't be able to get to it this
week.

**Comment by AdamNaj** [comment]
Implemented
