### ISSUE TITLE
Add ability to access CustomField implementations based on field types used.

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#810]
Add `._` and `.PSFields` properties that will dynamically expand fields such as:

![image](https://cloud.githubusercontent.com/assets/1209953/22393086/8bb6c5ec-e501-11e6-97ca-016b1211767f.png)

**Comment by AdamNaj** [comment]
Implemented

**Comment by michaellwest** [comment]
Great idea!

**Comment by michaellwest** [comment]
Added example to the *Working with items* page.

**Comment by AdamNaj** [comment]
Implemented.
