### ISSUE TITLE
Calling Write() with no output throws an exception

### ISSUE THREAD

**Issue by kamsar** [SitecorePowerShell/Console#814]
To reproduce:

* Implement a basic cmdlet (or hack one that already exists)
* As the first statement in its implementation call `Host.UI.Write("anything")`
* Call the cmdlet

An out of range exception is thrown, due to the array count check [here](https://github.com/SitecorePowerShell/Console/blob/master/Cognifide.PowerShell/Core/Host/ScriptingHostUserInterface.cs#L95) becoming index `-1` if the `Output` has nothing in it yet.

Edge case? Yes. And it was because I was using it wrong anyway ;)

**Comment by AdamNaj** [comment]
Still, worth fixing, some people make this call from their scripts.
Fixed.
