### ISSUE TITLE
Console elevation with F12 open seems to crash the page

### ISSUE THREAD

**Issue by kamsar** [SitecorePowerShell/Console#815]
Not sure if this is only me or what, but...

SPE 4.3, Sitecore 8.2 (RTM), Chrome 56

* Startup Sitecore Desktop
* Open F12 dev tools
* Open PS console
* Enter password in elevate prompt
* "Aw snap, something went wrong with this webpage"

Seems to only occur when an elevate prompt was entered. Refreshing the page makes the console work, and the elevation succeeded.

**Comment by AdamNaj** [comment]
Unfortunately cannot reproduce it here :(

**Comment by kamsar** [comment]
I think my browser was acting weird. Good on Chrome. Closing.
