### ISSUE TITLE
Download report throws 401 in 4.2

### ISSUE THREAD

**Issue by SNiels** [SitecorePowerShell/Console#816]
Locally I can generate and download reports, but on a remote server the following error populates my logs.
`11004 12:31:13 ERROR Attempt to call the 'handle' service failed as user '' was not authorized.`

This log comes from [this code](https://github.com/SitecorePowerShell/Console/blob/a787538c04ba1d1305c893c878ba88c5358363c4/Cognifide.PowerShell/sitecore%20modules/PowerShell/Services/RemoteScriptCall.ashx.cs#L77) that checks auth.

SPSE version: 4.2
User: sitecore\admin
IIS Identity: NetworkService 

Any idea why this is happening?

**Comment by AdamNaj** [comment]
I would check what the final integrated value of the "handleDownload" on your production service is.
This was introduced as part of security measures intended to harden SPE as part of issue #715 . Consult the issue and [our security hardening guide](https://doc.sitecorepowershell.com/security.html#restrict-users-and-roles) for further instructions.

**Comment by AdamNaj** [comment]
Looking at your log entry though - it feels like something might be blocking your authentication cookie, the log should never state that `''` was the user name.

**Comment by SNiels** [comment]
This started working on two environments all the sudden, though one still doesn't allow downloads.
When inspecting the cookies, I do see the auth cookies being sent.

**Comment by AdamNaj** [comment]
Sounds like an environment issue. Hope you'll get to solve it, not sure I can help much more than this :(

**Comment by AdamNaj** [comment]
I'll close the issue for now. If you can provide additional details, that can track it to SPE, feel free to re-open the issue.
