### ISSUE TITLE
Stuck "Installing.." SPE for 1st time. No error message, nothing happens, no clues..

### ISSUE THREAD

**Issue by JRG-MKE** [SitecorePowerShell/Console#823]
Hello, 

I'm on "**Chapter 10 - SITECORE POWERSHELL EXTENSIONS**" of Phil's book. 

After a good 20 minutes of "Installing..." the SPE, nothing is happening other than the "Installing..." looping icon.. 

Is there a trace somewhere to consult? If the case, can the information be accessible, seeable to users on the "Installing.." screen itself?  Usually installations are a bit more verbose. 

Thank you,

**Comment by michaellwest** [comment]
@JRG-MKE Do you have Xdb setup completely or completely disabled? Oftentimes Sitecore installation hangs for that.

**Comment by JRG-MKE** [comment]
I'm not sure where to look at to know, it seems it's pretty involved and I don't remember having been exposed to this installation. I'm also reading from others that MongoDB would need to be installed.
At this point I need neither of them, but I can install either or both if necessary. xDB relating to experience and marketing features I read. There are unused at this point and that should be for a while. I feel like having to install the North Korean dictionary and some encyclopedia to print "Hello World!" ;)

**Comment by michaellwest** [comment]
@JRG-MKE Disabling xdb is relatively straight forward. [Disable xDB](http://sitecore.stackexchange.com/questions/342/how-can-i-disable-xdb) 

If you open up your latest log file, you should see at the top details about whether or not xDB is disabled.

I've seen this installation issue happen for packages that are not for SPE.

**Comment by JRG-MKE** [comment]
BINGO! Thank you so much, installed! 

Ideally the same messages found in the logs would pop-up in the Installation screen.

In the documentation it wouldn't harm specifying where files live like this "Sitecore.Xdb.config".  I found it in 
\Website\App_Config\Include and would know now, but until you do.. One could be seasoned with scripting in general, but relatively new to Sitecore and wanting to limit the bush beating. 

Thanks again!

**Comment by AdamNaj** [comment]
Great to hear that.  Thanks for handling it skilfully @michaellwest. 

@JRG-MKE this is an underlying platform (Sitecore) rather than SPE issue hence we did not document it in the module.
