### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by a3codeDA** [SitecorePowerShell/Console#826]
Hi, 
I have installed PowerShell Extensions 2.7.5 first and 4.4 for Sitecore 8 (Full 4.4 release for Sitecore 8)
on sitecore 8.1.

I can't execute any app becourse  I see an error^

> Server Error in '/' Application.

> CodeBeside class "Cognifide.PowerShell.SitecoreIntegrations.Applications.PowerShellConsole,Cognifide.PowerShell" not found. (method: Sitecore.Web.UI.HtmlControls.CodeBeside.OnInit(EventArgs e)).
> 
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
> 
> Exception Details: System.Exception: CodeBeside class "Cognifide.PowerShell.SitecoreIntegrations.Applications.PowerShellConsole,Cognifide.PowerShell" not found. (method: Sitecore.Web.UI.HtmlControls.CodeBeside.OnInit(EventArgs e)).
> Exception: CodeBeside class "Cognifide.PowerShell.SitecoreIntegrations.Applications.PowerShellConsole,Cognifide.PowerShell" not found. (method: Sitecore.Web.UI.HtmlControls.CodeBeside.OnInit(EventArgs e)).]
>    Sitecore.Diagnostics.Error.Raise(String error, String method) +137
>    Sitecore.Web.UI.HtmlControls.CodeBeside.CreateCodeBeside(String type) +103
>    Sitecore.Web.UI.HtmlControls.CodeBeside.OnInit(EventArgs e) +254
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +166
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +379
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +379
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +379
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +379
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +379
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +379
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +379
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +379
>    System.Web.UI.Control.AddedControl(Control control, Int32 index) +215
>    Sitecore.Shell.DefaultPage.OnInit(EventArgs e) +188
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +166
>    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1839
> 

How to fix it ?
What I did in a wrong  way ?

**Comment by AdamNaj** [comment]
You might want to go over the steps described in the blog post: http://blog.najmanowicz.com/2015/02/27/upgrading-your-sitecore-powershell-extensions-from-2-x-to-3-x-what-you-need-to-know/

**Comment by a3codeDA** [comment]
thanks it is works now.

**Comment by AdamNaj** [comment]
Glad to hear that!
