### ISSUE TITLE
New-Item command should report non-existent path

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#828]
The current implementation reports an unhelpful error message when the `-Path` parameter provides a path that does not actually exist.

**Example:**
```powershell
New-Item -Path "master:\content\home\PATH_DOES_NOT_EXIST" -Name "RandomName" -ItemType ...
```

**Comment by AdamNaj** [comment]
Implemented

**Comment by michaellwest** [comment]
Thanks @AdamNaj !
