### ISSUE TITLE
New-Item error message typo for long names

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#829]
Saw this message today:

> New-Item : An item name lenght should be less or equal to 100.

**Comment by AlexKasaku** [comment]
That's one of the error messages from Sitecore itself, the spelling mistake is in the `Sitecore.Data.Items.ItemUtil.AssertItemName` method. It's been like that for a few versions now and looks like it's still incorrect in 8.2 Update 2.

**Comment by AdamNaj** [comment]
I'm not even seeing even this. Instead ,I see:
```
New-Item : String or binary data would be truncated.
The statement has been terminated.
At line:1 char:1
+ New-Item -Path "master:\content\home" -ItemType "Sample/Sample Item"  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Item], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.PowerShell.Commands.NewItemCommand
```

**Comment by AdamNaj** [comment]
I am not sure we can do much about it. Passing the API error seems like the best solution as item creation can fail for various OOTB and customization reason.

**Comment by AdamNaj** [comment]
Should we close it?

**Comment by AlexKasaku** [comment]
I agree that it 's just passing back the Sitecore API error message, which is what it should do - Sitecore should indeed fix this spelling typo there, it's been there a while!

**Comment by AdamNaj** [comment]
This is not fixable by us and there are many more vectors that we would hide if we did.

**Comment by michaellwest** [comment]
Thank you for looking into it.
