### ISSUE TITLE
SPE Minimal for Sitecore 8 v4.2 to 4.4.1 not working with Sitecore 8.2 rev161221

### ISSUE THREAD

**Issue by afortaleza** [SitecorePowerShell/Console#833]
How to reproduce the error: 
* Install Sitecore 8.2 rev161221 (my case running at http://sitecore82rev161221)
* Install SPE Remoting-4.4.1
* SPE Minimal-4.4.1 for Sitecore 8 on sitecore
* Run the following [sample ](https://doc.sitecorepowershell.com/v/v4.4.0/remoting.html) script on Windows Powershell ISE
```powershell
Import-Module -Name SPE
$session = New-ScriptSession -Username admin -Password b -ConnectionUri http://sitecore82rev161221
$jobId = Invoke-RemoteScript -Session $session -ScriptBlock {
        "master", "web" | Get-Database | 
            ForEach-Object { 
                [Sitecore.Globals]::LinkDatabase.Rebuild($_)
            }
} -AsJob
Wait-RemoteScriptSession -Session $session -Id $jobId -Delay 5 -Verbose
Stop-ScriptSession -Session $session
```

When doing that I get the following error
```
Wait-RemoteScriptSession : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an argument that is not null or empty, and then try the 
command again.
At line:9 char:48
+ Wait-RemoteScriptSession -Session $session -Id $jobId -Delay 5 -Verbo ...
+                                                ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Wait-RemoteScriptSession], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Wait-RemoteScriptSession
```

Looks like the Invoke-RemoteScript call is not running properly. Here's a table with the results for the versions I have tested

Remoting Version|Minimal Version | Result
-|-|-
4.1.1|4.1|OK
4.1.1|4.2|Fail
4.1.1|4.3|Fail
4.1.1|4.4|Fail
4.1.1|4.4.1|Fail

**Comment by AdamNaj** [comment]
Could this be because of #716? Since 4.2 remoting is disabled by default for security reasons.  You need to enable it explicitly as explained here : https://doc.sitecorepowershell.com/security.html

**Comment by afortaleza** [comment]
That was it @AdamNaj , sorry for missing that point and wasting your time. Thx!

**Comment by AdamNaj** [comment]
No time wasted.  It felt pretty apparent from where I sit!  :) Glad to hear it's working for you now.  
Happy scripting!
