### ISSUE TITLE
Package name format - redundant dash

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#834]
When I create a package `123` using standard package designer in Sitecore and click `Generate Zip` my packages name will be:

| Version   |      Package name      |
|----------|:-------------:|
| Specified |  123-VERSION.zip |
| Unspecified | 123.zip   | 

When using SPE context menu  to generate package names I will get

| Version   |      Package name      |
|----------|:-------------:|
| Specified |  123-VERSION.zip |
| Unspecified | 123-.zip (redundant dash) |

**Comment by michaellwest** [comment]
Thanks for reporting it @alan-null . This has bugged me too.

**Comment by AdamNaj** [comment]
Change implemented.
