### ISSUE TITLE
Incorrect PowerShell messages - SXA Layout ,Packaging items of Scripts context menu

### ISSUE THREAD

**Issue by Strelkovna** [SitecorePowerShell/Console#836]
Please find attached docx file that describes issues, steps to reproduce and some screenshots as well.
[PSE_Issues_documented.docx](https://github.com/SitecorePowerShell/Console/files/786918/PSE_Issues_documented.docx)

**Comment by AdamNaj** [comment]
Implemented.

Rendering copy/paste messages moved from text results to the dialog itself.
Package creation start will pop up an alert with message about the operation.
Add item/branch option selection dialogs have a new message added about operation that will be performed.
