### ISSUE TITLE
SPE RemoteAutomation Webservice not found when starting a new session

### ISSUE THREAD

**Issue by Firgeis** [SitecorePowerShell/Console#838]
Running this command from the Sitecore ISE:

`$session = New-ScriptSession -Username admin -Password b -ConnectionUri http://mysitecore`

Returns:

`New-WebServiceProxy : The request failed with HTTP status 404: Not Found.`

I have followed the guide in the book and tried it in 4.3 as well as 4.4.1. Remoting is enabled in configuration file  and admin is also a member of powershell group. Also checked that there is not a custom pipeline interfering with routing and that the files exists physically on the Website.

**Comment by michaellwest** [comment]
Hi @Firgeis , you'll want to check out the book for steps to enable the service. The services are all disabled by default with version 4.3+.

https://doc.sitecorepowershell.com/security.html

**Comment by Firgeis** [comment]
Hi @michaellwest , thanks for your response. As far as i know remoting is enabled, here is a snippet from my showconfig:
`<remoting enabled="true" requireSecureConnection="false">
<authorization>
<add Permission="Allow" IdentityType="Role" Identity="sitecore\PowerShell Extensions Remoting"/></authorization>
</remoting>`

**Comment by michaellwest** [comment]
Thank you @Firgeis . Just to confirm, is the account added to the group shown in the config?

**Comment by Firgeis** [comment]
Yes, I can confirm the user is a member of that group

**Comment by AdamNaj** [comment]
Assuming this is no longer a problem for the lack of activity. Closing to clean up our backlog. Feel free to re-open if still happening.
