### ISSUE TITLE
Read-Variable validation messages cause unexpected column wrapping

### ISSUE THREAD

**Issue by techphoria414** [SitecorePowerShell/Console#840]
When using validation on a field with `Read-Variable` along with a column width, validation messages can cause columns to wrap in unexpected ways.

```
Read-Variable -Parameters `
    @{Name="Lorem"; Title="Lorem"; Mandatory=$true; Columns=6},
    @{Name="Ipsum"; Title="Ipsum"; Columns=6},
    @{Name="Dolor"; Title="Dolor"; Mandatory=$true; Columns=6},
    @{Name="Sit"; Title="Sit"; Mandatory=$true; Columns=6}
```

![screen shot 2017-02-26 at 3 37 43 pm](https://cloud.githubusercontent.com/assets/1562106/23343451/c8f46802-fc39-11e6-97f8-3d60a5e917c7.png)

Workaround seems to be to add "first" to the first column fields to force a `clearfix` css class.

```
Read-Variable -Parameters `
    @{Name="Lorem"; Title="Lorem"; Mandatory=$true; Columns="6 first"},
    @{Name="Ipsum"; Title="Ipsum"; Columns=6},
    @{Name="Dolor"; Title="Dolor"; Mandatory=$true; Columns="6 first"},
    @{Name="Sit"; Title="Sit"; Mandatory=$true; Columns=6}
```

![screen shot 2017-02-26 at 3 40 33 pm](https://cloud.githubusercontent.com/assets/1562106/23343466/f087b946-fc39-11e6-96bb-45a234ece57d.png)

**Comment by michaellwest** [comment]
Adding the `Mandatory` setting to the second column doesn't encounter the issue.

![image](https://cloud.githubusercontent.com/assets/933163/23348720/5f5a477a-fc72-11e6-8a1c-b1e146a26622.png)

```powershell
Read-Variable -Parameters `
    @{Name="Lorem"; Title="Lorem"; Mandatory=$true; Columns=6},
    @{Name="Ipsum"; Title="Ipsum"; Mandatory=$true; Columns=6},
    @{Name="Dolor"; Title="Dolor"; Mandatory=$true; Columns=6},
    @{Name="Sit"; Title="Sit"; Mandatory=$true; Columns=6}
```

**Comment by michaellwest** [comment]
@techphoria414 Looks like the `first` was added as part of issue #429 to adjust this problem. Not sure if @AdamNaj could not find an alternative approach at the time or what.

**Comment by techphoria414** [comment]
@michaellwest You are correct that if both columns are showing an error message, the wrapping does not occur, I assume because they stay the same height.

**Comment by AdamNaj** [comment]
This is very much on purpose, and how grids like bootstrap solve the issue. Should we not have the `"first"` modifier specified explicitly I would have to count the columns and add the the `clearfix` manually.

Also the following would not be possible as I would wrap the row after the "User Name"
![image](https://cloud.githubusercontent.com/assets/1209953/23374089/0f4e2402-fd23-11e6-8548-0d97186cc5bc.png)

Unfortunately the reverse layout (when the large field would be on the right is not currently possible as I would have to add something like "last" support).

**Comment by AdamNaj** [comment]
Added #843 (a.k.a "Columns=last") to add the ability to align to the right and further compensate for some additional scenarios. We're dealing with grid here, not tables. Some creative laying out is bound to be required ;)
