### ISSUE TITLE
Read-Variable validators can't access local functions

### ISSUE THREAD

**Issue by techphoria414** [SitecorePowerShell/Console#841]
It appears that local functions aren't available to validators, which lead me to create a `Cmdlet` instead to avoid repeating validation logic.

```
Function ValidateMe($variable) {
    $variable.Error = "Error"
}
    
Read-Variable -Parameters `
    @{Name="Lorem"; Title="Lorem"; Mandatory=$true; Validator={
        ValidateMe -variable $variable #doesn't work
        #$variable.Error = "Error" #works
    }}
```

Any way this would be possible or is a `Cmdlet` my best bet?

**Comment by AdamNaj** [comment]
Unless convinced otherwise, I'd prefer to keep it as it is. Feel free to re-open to provide additional motivation :)
