### ISSUE TITLE
Security : Add MemberOf property for User and Role objects

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#842]
As can be seen [here](https://gist.github.com/RobsonAutomator/a65ddd70e3482ac76fb4524b0e593fc5) there is a need to return the membership for users and roles.

![image](https://cloud.githubusercontent.com/assets/933163/23345333/1dab46a0-fc52-11e6-9749-9ed3e3099111.png)

**Comment by michaellwest** [comment]
Implemented.

**Comment by AdamNaj** [comment]
The `User` already contains property `Roles` that was added in the last release. Can you please align the implementation with the existing one? I would rather not have duplicated properties and breaking changes if we can avoid them.

**Comment by michaellwest** [comment]
@AdamNaj I changed the `MemberOf` property to an Alias and added a `Roles` property to the Role object.

**Comment by AdamNaj** [comment]
Looks good now.

![Seal of approval](http://media.treehugger.com/assets/images/2013/10/seal-of-approval-meme.jpg)

**Comment by michaellwest** [comment]
Good recommendation.
