### ISSUE TITLE
Sitecore database drives need to be added in a more defensive manner

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#846]
A report on non-existent "master" drive has been reported on Slack a couple of times.
The code needs to be hardened so that failing to add one drive will have no effect on others.

**Comment by AdamNaj** [comment]
Implemented. As a consequence `filesystem` is no longer available. There was really never a good use for it.

**Comment by michaellwest** [comment]
When you say `filesystem` is no longer available, what do you mean?

**Comment by AdamNaj** [comment]
there is a `filesystem` readonly database in Sitecore that exposes files from under the `/sitecore/` website subfolder.

**Comment by michaellwest** [comment]
Oh yeah. We don't need that.

**Comment by AdamNaj** [comment]
That's why I removed it :)
