### ISSUE TITLE
Set-ItemTemplate should support fields copying to aid with templates that do not have matching fields

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#847]
This is a scenario that I've seen being a problem multiple times, e.g. [here](http://blogs.perficient.com/microsoft/2016/06/sitecore-powershell-change-item-template-and-retain-field-value/) or [here](http://sitecore.stackexchange.com/questions/1008/how-to-change-item-templates-and-retain-existing-data).

We have 2 templates:
- `User Defined/Source` - with fields: `Field1`, `Field2`, `Field3`
- `User Defined/Target` - with fields: `Field4`, `Field5`, `Field6`

and Item at path `master:\content\home\TemplateChangeTest` that is of template `User Defined/Source`.
I want to change the item template to `User Defined/Target` and make the following transformation:
- `Field1` -> `Field4`
- `Field2` -> `Field5`
- `Field3` -> `Field6`

All other fields have counterparts with a matching name in the `User Defined/Target` template.

The following script should do the trick:
```powershell
Set-ItemTemplate -Path master:\content\home\TemplateChangeTest `
    -Template "User Defined/Target" `
    -FieldsToCopy @{Field1="Field4"; Field2="Field5"; Field3="Field6"}
```

**Comment by AdamNaj** [comment]
Implemented

**Comment by michaellwest** [comment]
You're a hero to many @AdamNaj !
