### ISSUE TITLE
Ability to close/hide 'Progress Window'

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#848]
As a user, I want to be able to close/hide progress window 

### Steps to Reproduce the Problem
- Create a module with insert item integration point.
Use following code as an insert item code
`Get-ChildItem master:\ | Show-ListView -Property DisplayName, __Updated , "__Updated by"`
- Open CE and invoke new **Insert Option**

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/6848691/23508906/0071624a-ff54-11e6-947c-3bb9add8a32f.png)

### Expected Behavior 
I would like to control which windows are shown. 

My scenario would be: show list view window without any other windows. Once I open List View and close it I have to close underlying popup as well. I want to skip this last redundant step.

**Comment by AdamNaj** [comment]
Can't really be done. This is happening because you're running content editor in Full screen mode rather than on desktop which forces all windows to pop up as modal. At the moment I am not quite sure on how to accommodate this request.

Some additional discussion on Issue #798
