### ISSUE TITLE
Cancelled SXA upgrade keeps presenting user with Done! message

### ISSUE THREAD

**Issue by Strelkovna** [SitecorePowerShell/Console#852]
1. Create new tenant and site that uses any grid
2. Navigate to Settings->Foundation->Upgrade->Required and update Required version to current+1
3. Save changes - following message appears:
Experience Accelerator Content Upgrade Required
Your Sitecore instance has been updated with a more recent version of Experience Accelerator. However your content has not yet been upgraded. Your site might not be functional before you upgrade your content.
Upgrade

4. Click upgrade and  then close 'PowerShell Scrip Results' window

ER:
Windows closed, user can navigate to any item in CE

AR:

Done! message is presented

**Comment by michaellwest** [comment]
This is likely an issue within the SXA scripts, assuming it is still an issue.
