### ISSUE TITLE
Add Sitecore NuGet references

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#858]
Time to start using the NuGet feed.

**Comment by michaellwest** [comment]
@AdamNaj Need your input on how to properly handle the version 7 project. The feed only goes back to 7.2.

**Comment by AdamNaj** [comment]
Not sure we need it any longer, if it's not supported by Sitecore.

I wonder, is it possible to switch nuget packages to older versions en-masse (in the whole solution)?

**Comment by michaellwest** [comment]
You can change the NuGet packages at a global level, but not sure this would be practical for an on-going basis. In addition, there is a single project that requires Sitecore 7.0 which is not in the feed.

**Comment by AdamNaj** [comment]
We need to have a robust solution for changing version we're building against, to see quickly what does and does not compile in each version. I have that on my machine right now in form of folders I can quickly switch. Maybe Nuget is not the answer if it does not support this.

I don't have a problem with not being able to develop against unsupported versions, though.

**Comment by michaellwest** [comment]
Are you referring to these support dates?
https://kb.sitecore.net/articles/641167

**Comment by AdamNaj** [comment]
yes

**Comment by AdamNaj** [comment]
It's good enough for now.
