### ISSUE TITLE
New-Item should work for -ItemType (Template) provided as GUID string

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#861]

**Comment by michaellwest** [comment]
Sweet. I was hoping this would finally be supported.

**Comment by AdamNaj** [comment]
It was working before, but as a side effect :) Update 3 broke this :)

**Comment by michaellwest** [comment]
Seriously? When was this added? I  should read the release notes.

**Comment by AdamNaj** [comment]
Might be in there, when it's released ;)

**Comment by AdamNaj** [comment]
Implemented.

**Comment by michaellwest** [comment]
Yay!
