### ISSUE TITLE
CSV from Show-ListView gets truncated on some environments.

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#863]
As originally reported on Slack:

> *Jason Booth:* I created a content report - it reports on some fields from parts of our content tree. When I run it via the ISE or the Reporting Tools menu, all is good. However, when I download to csv, the last item in the report is always missing from the csv. No matter how I sort or filter in Sitecore, the csv is always missing whatever the last item is. When I query items, I use the `-Language *` flag, so, depending on how I sort or filter, the csv may be missing multiple rows if the last rows are different language versions of one item. I nearly submitted this as a bug but, of course, it works fine on my dev environment - we only see this issue on our qa environment. Both environments are currently using the same data in question. Both were recently upgraded to SPE 4.5. I'm at a loss...

Later:
![image](https://cloud.githubusercontent.com/assets/1209953/24237355/3c8a60c6-0fa6-11e7-9deb-a71267327fbd.png)
> *Jason Booth:*CSV results are 2 short (taking the header row into account). The last two from PSE in Sitecore are the same item, two language versions. If I sort or filter differently, some other item is left off of the CSV.
> *Jason Booth:*so, something else I just noticed, I don't think it is just leaving off a row or two, after filtering the data down to get a smaller dataset, the last line in the CSV cuts off
![image](https://cloud.githubusercontent.com/assets/1209953/24237390/5da89372-0fa6-11e7-8bc4-45d1ae57904a.png)

> *Jason Booth:* It seems environmental - I don't have this issue on my local workstation but both our prod and QA (Win 2012 R2 Data Center) on Azure have the issue.

Adam Najmanowicz: I see we're sending `Content-Length` header based on string length, but I wonder if this isn't actually a problem. Hypothetical but... If I'm writing the string and the server expands EOL characters to 2 LN/CR while Length counts EOL as one because... something in the server settings.... guessing to a degree, but that would be consistent with the fact that the longer the result is the more it's truncated. I'll stop sending Content-Length in this case, IIS will add it anyway.

**Comment by AdamNaj** [comment]
Changed.

**Comment by jason-booth** [comment]
Tested and confirmed the fix. CSV's are now exported with the correct number of rows/amount of content as expected.
