### ISSUE TITLE
Is it possible to create items with a specific ID using New-Item?

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#865]
I'm able to get this to work.

```powershell
$parentItem = Get-Item -Path "master:" -ID "{E0633AA5-8423-4D7B-9BFC-B3F882D2019E}"
$itemId = "{789E2DCD-001B-4B3A-87AA-D6ADB9DEDFAD}" ## I want to use this ID
$itemName = "Contact Us"
$templateId = "{E24E0789-A058-48BF-ABB6-C69C0E60B6B7}"

$item = [Sitecore.Data.Managers.ItemManager]::CreateItem($itemName, $parentItem, $templateId, $itemId, [Sitecore.SecurityModel.SecurityCheck]::Enable)
```

**Comment by AdamNaj** [comment]
I just got goose bumps... Somehow guids started to feel much less "globally unique"

**Comment by michaellwest** [comment]
Thought about a data migration where i compare id rather than maintain a mapping table.

**Comment by mikaelnet** [comment]
Yes, this makes perfect sense. I've been in situations where I've done exactly this.

**Comment by michaellwest** [comment]
Thanks for validating my comment @mikaelnet . @AdamNaj usually thinks my ideas are crazy.

**Comment by AdamNaj** [comment]
To be fair... they usually are :)

**Comment by AdamNaj** [comment]
🙄 Fine... it's done. `-ForceId` :)

**Comment by michaellwest** [comment]
Yay!
