### ISSUE TITLE
Script post step for Sitecore packages

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#866]
As a Sitecore developer I want to be able to define a post step for Sitecore package which will invoke PowerShell script.

# Demo
### Package configuration
![image](https://cloud.githubusercontent.com/assets/6848691/24673742/9b9a3906-1979-11e7-8c9d-177c30471cec.png)

### Package installation
![demo](https://cloud.githubusercontent.com/assets/6848691/24673781/c2d792e8-1979-11e7-9dc5-8debbe7b6e84.gif)

**Comment by michaellwest** [comment]
I like it!

**Comment by AdamNaj** [comment]
Closing as implemented. Not verified, but I trust you Alan :)
