### ISSUE TITLE
ISE - add ability to move results container

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#868]
As an SPE developer, I want to be able to move results row on the right side, so I can better use available space.

Something like this
![image](https://cloud.githubusercontent.com/assets/6848691/24680251/69012f60-1990-11e7-8515-c4f0de02c4e5.png)

**Comment by michaellwest** [comment]
Want.

**Comment by michaellwest** [comment]
This is a tricky one. I started by moving the results panel next to the editor border. Then changed the GridPanels to Borders so they wouldn't generate a table. Finally, assigned a display of Flex to the parent div. This is going to take some time to get it working right.

**Comment by AdamNaj** [comment]
I tried this one and had to back out of it, this code is a bit too spaghetti to change... 
I think the autohiding of the results should roughly achieve the same.

If you still want it after the other linked issue, feel free to reopen this one.
