### ISSUE TITLE
Changing job name

### ISSUE THREAD

**Issue by hishaamn** [SitecorePowerShell/Console#869]
Is it possible to change the name `ScriptExecution` which is present on the `job.aspx` to something meaningful? For example, I have a script which triggers the creation of item. So, instead of having `ScriptExecution` as name, it will be preferable to have something like this "Content Creation" which is defined by the user

**Comment by AdamNaj** [comment]
Not at the moment... Will get on it for next version.

**Comment by AdamNaj** [comment]
The way it was implemented is 2 fold. If you spin up a new Session through `Start-ScriptSession` you can provide a `-JobName` parameter as it should have always worked. If you're running it through the UI relying on Sitecore commands - the Job name will automatically include the Item name of the script executed as implemented in Issue #898.

Implemented this way as I think that changing this from inside Job is really not something that should be done.
