### ISSUE TITLE
WFFM Package installation.

### ISSUE THREAD

**Issue by RajasekharVM** [SitecorePowerShell/Console#870]
Hi All,
Can you please provide me the  commands to install WFFM package by using SPE.
Thanks,
Rajasekhar.VM

**Comment by RajasekharVM** [comment]
I tried with the below commands and got an error as shown below.
Commands:
Invoke-RemoteScript -Session $session -ScriptBlock{
Install-Package -Path "C:\test\WebForm forMarketers8.1 rev.160304" -InstallMode Overwrite -MergeMode Merge
}

Error:
Install-Package : Error while opening file 'C:\test\WebForm forMarketers8.1 rev.160304'
At line:2 char:1
+ Install-Package -Path "C:\test\WebForm forMarketers8.1 rev.160304" -I ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : System.Exception,Cognifide.PowerShell.Commandlets.Packages.InstallPackageCommand

**Comment by AdamNaj** [comment]
This would be better served by asking a question on [Sitecore Stack Exchange](https://sitecore.stackexchange.com/)

**Comment by AdamNaj** [comment]
Assuming this was solved otherwise.
