### ISSUE TITLE
AddFromTemplate error for user in developer role

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#871]
Created a new user `sitecore\devdan` and added to the `sitecore\Developer` role. 
Opened a script in the ISE and it errors.

![image](https://cloud.githubusercontent.com/assets/933163/24833459/acd7ac4a-1c8e-11e7-9489-00ed197eedc4.png)

**Comment by AdamNaj** [comment]
Proper write and create security settings were needed on descendants for per-user Settings item.
