### ISSUE TITLE
Toolbox & Reports should be visible for users in role "Sitecore Client Maintaining"

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#872]
![image](https://cloud.githubusercontent.com/assets/933163/24833461/c506600e-1c8e-11e7-9da6-98d535fb52f6.png)

**Comment by AdamNaj** [comment]
Added read rights for "Sitecore Client Maintaining" - as this is the group that Sitecore allows to show other reports to. Developer is a member of this group.
