### ISSUE TITLE
Opening a list view from the ribbon of another list view results in incorrect column headers

### ISSUE THREAD

**Issue by techphoria414** [SitecorePowerShell/Console#876]
The second list view appears to utilize the same headers (`-Property` argument) as the first list view. To reproduce:

1. Create a script that displays a list view, e.g.

```
$data = @(
    @{ Lorem = "Ipsum"; Hello = "World"; Animal = "Dog" },
    @{ Lorem = "Dolor"; Hello = "Galaxy"; Animal = "Cat" }
)

$data | Show-ListView -Property @{Label="Lorem"; Expression={$_.Lorem}}, @{Label="Hello"; Expression={$_.Hello}}, @{Label="Animal"; Expression={$_.Animal}}
```

2. Create a ribbon script that also displays a list view, with different columns, e.g.

```
$data = @(
    @{ Color = "Green"; Size = "Large"; },
    @{ Color = "Blue"; Size = "Small"; }
)

$data | Show-ListView -Property @{Label="Color"; Expression={$_.Color}}, @{Label="Size"; Expression={$_.Size}}
```

Executed on its own, the second script displays correctly (Color and Size). Invoked from the ribbon of the first list view, it still displays Lorem, Hello, and Animal.

This issue seems to have been introduced since 4.3 (where this scenario seemed to work fine). Started experiencing it when I installed 4.5.

Sitecore package of the example above:
[20170419.1755.Inner List View Columns-1.zip](https://github.com/SitecorePowerShell/Console/files/938583/20170419.1755.Inner.List.View.Columns-1.zip)

**Comment by AdamNaj** [comment]
Fixed.
