### ISSUE TITLE
Remoting service media GET service call fails if extension is specified.

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#877]

**Comment by michaellwest** [comment]
Looks like a missing Pester test!

**Comment by AdamNaj** [comment]
That's just a simple URL call like:
http://sxa/sitecore%20modules/PowerShell/Services/RemoteScriptCall.ashx?script=/Project/Showcase/Themes/Showcase/Sass/component-search.scss&sc_database=master&scriptDb=master&apiVersion=media

Where before it would fail as I was not trimming the extension and thus item would not be found.

**Comment by AdamNaj** [comment]
Fixed
