### ISSUE TITLE
Get-Rendering unable to resolve Languages

### ISSUE THREAD

**Issue by jdylanmc** [SitecorePowerShell/Console#881]
Documentation here: https://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/appendix/commands/Get-Rendering.html

When using Get-Rendering, there are not many options to specify which language you want the final layout in.  Additionally, the only options that allow you to specify the Language do not allow you to specify an item.

For example, this call fails:

`Get-Rendering -Item $page -Device (Get-LayoutDevice -Default) -Language $page.Language -FinalLayout`

This was tested in Sitecore 8.1 update 3, with Sitecore Powershell Extensions 4.3

**Comment by AdamNaj** [comment]
Done
