### ISSUE TITLE
Package Generator - Save XML project for later use

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#884]
The package generator saves so much time. In the spirit of automation, why have to recreate the module item-by-item more than once? 

Add the ability to save to XML for later use either by SPE or the Package Manager. 

How about a preview dialog of items-to-be-added too?

**Comment by AlexKasaku** [comment]
Implemented a checkbox for downloading the package as XML.

**Comment by michaellwest** [comment]
Changed icons.

![image](https://user-images.githubusercontent.com/933163/29099448-09e1d35c-7c6b-11e7-9fd8-602ead78eed1.png)

**Comment by michaellwest** [comment]
Preview Package also includes a report.

![image](https://user-images.githubusercontent.com/933163/29099667-6f992ac8-7c6c-11e7-9f6b-574babbe0c86.png)

**Comment by michaellwest** [comment]
@AlexKasaku Should the report actually show the different languages?

**Comment by AlexKasaku** [comment]
I wondered about this, what do you think? It's possible to add only certain language variants of an item into a package.

The `Get-PackageItem` command currently returns each language as a different item in the pipeline, similar to if you do `Get-Item -Language *`. Perhaps that should stay the same and the report should group items together by ID and then the `Language` column will be a comma-separated list?

**Comment by michaellwest** [comment]
We need to make the report and package match in content. I think now we
only add a single language and latest version, correct?

**Comment by AlexKasaku** [comment]
They are matching - in so much as the package has those versions and languages in it. All the items there have been read out of the package.

**Comment by michaellwest** [comment]
Looks like this is done.
