### ISSUE TITLE
Request - Implement the whatif flags

### ISSUE THREAD

**Issue by VGBenjamin** [SitecorePowerShell/Console#885]
Hello,

It could be really usefull to implement the wathif flags as it is in most powershell commands.: https://www.pluralsight.com/blog/software-development/test-powershell-with-whatif

Thank you for this great product.

Benjamin V.

**Comment by AdamNaj** [comment]
Which cmdlets do you find missing those? I always try to implement the functionality on our built-in cmdlets, but maybe you've found some that are missing?

**Comment by VGBenjamin** [comment]
I didn't found some missing one but it isn't present into the documentation. 
For example:
- https://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/appendix/commands/Set-ItemTemplate.html
- https://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/appendix/commands/Remove-ItemVersion.html
If it is just a documentation issue that is already really great. Thanks a lot for your product.

Benjamin

**Comment by AdamNaj** [comment]
This needs to be moved to the Gitbook repo.
