### ISSUE TITLE
Dictionary Key Problem

### ISSUE THREAD

**Issue by RobsonAutomator** [SitecorePowerShell/Console#886]
![sitecore-dictionary-key](https://cloud.githubusercontent.com/assets/831971/25840971/656061ea-349e-11e7-8dc9-583f0c743948.jpg)

**Comment by AlexKasaku** [comment]
Key is a property in the Sitecore Item class that gives the same value as the Name property, but in lowercase. What you are seeing in the Key column is the value of that property.

SPE allows you to conveniently access field values as if they were properties on the Item class, but if there are field names with the same value as an existing property, such as Key, then then this convenient method won't work. The same would happen if you had a field called "Name" on a template.

**Comment by AdamNaj** [comment]
Great catch @AlexKasaku! One comment on my side... you can still access such field in the convenient way you mentioned, In case of such conflict SPE will pre-pend the field value with a `_` so you can access this field under `_Key`

**Comment by AlexKasaku** [comment]
Ah, yes! This is why I didn't close the issue as I thought there might be some extra insight for this :)

**Comment by AdamNaj** [comment]
No issue found - so closing. Thanks again for the great hint Alex!
