### ISSUE TITLE
Send-File issue

### ISSUE THREAD

**Issue by RobsonAutomator** [SitecorePowerShell/Console#887]
There is some additional contend at the end of file.
Script for test:
$path = Join-Path $AppPath "App_Config\Include\Cognifide.PowerShell.config"
Send-File -Path $path 

Resut:
![send-file-issue](https://cloud.githubusercontent.com/assets/831971/25841342/007d589e-34a0-11e7-9690-88084e86514c.jpg)

**Comment by alan-null** [comment]
Hey @RobsonAutomator 

Could check whether you can download some media item (js/css) from media library and see whether it behaves the same way?
I reported such issue some time ago (November 2016) and it was an issue of Sitecore
Unfortunately, the support page with this fix is no longer available.
[Cached version](https://webcache.googleusercontent.com/search?q=cache:Utf8d8yiBMwJ:https://github.com/sitecoresupport/Sitecore.Support.95901/releases+&cd=1&hl=en&ct=clnk&gl=pl)

I used: **8.2 rev. 160729 (Initial Release)** back then.

**Comment by AdamNaj** [comment]
Closing as I can no longer reproduce it. Platform problem.
