### ISSUE TITLE
Add ability to customize ListView empty results view

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#888]
As a developer, I want to be able to customise results page of ListView when there are no results.

Right now I am unable to change the `EmptyIcon` value. It has hardcoded value
```xml
<Image ID="EmptyIcon" Src="/sitecore modules/PowerShell/Assets/error.png" Width="64" Height="64"
```
![image](https://cloud.githubusercontent.com/assets/6848691/25849587/5f218d88-34bf-11e7-8ad5-23684bfdf683.png)

**Comment by techphoria414** [comment]
Would be great to be able to add a link as well. I've created CRUD applications using `Show-ListView` and there's not a great way to allow the user to create the first item, since there are no actions available when the list is empty.

**Comment by AdamNaj** [comment]
@techphoria414 - sounds like a good idea for a whole new Issue :)

**Comment by AdamNaj** [comment]
Implemented as a new `-MissingDataIcon` parameter
