### ISSUE TITLE
Hi I am not able to rebuild the link db in sitecore using spe 4.3 

### ISSUE THREAD

**Issue by RajasekharVM** [SitecorePowerShell/Console#893]
When i use commnads ( [Sitecore.Globals]::LinkDatabase.Rebuild($database))to rebuild, i am getting as "Unable to find type [Sitecore.Globals]."
 
Can you please guide me how to proceed

**Comment by AdamNaj** [comment]
Based on your example - I've just tried this in SPE ISE and it worked fine for me.
```powershell
$database = Get-Database -Name "master"
[Sitecore.Globals]::LinkDatabase.Rebuild($database)
```
Can you tell more about how/where are you running it?

**Comment by RajasekharVM** [comment]
Hi Adam,
We are trying by using Powershell ISE by importing SPE module.
We are getting issue.
Or rebuild functionality will work only on SPE ISE ?

**Comment by RajasekharVM** [comment]
i tried with SPE 4.5

**Comment by RajasekharVM** [comment]
suggest me how to install latest SPE on my local server.

**Comment by RajasekharVM** [comment]
We are facing some issue while rebuild the link databes, by using the blow code.
https://michaellwest.blogspot.in/2015/05/sitecore-powershell-extensions-system-maintenance.html

While using the below code we are getting the error. And we are running the code by using Powershell ISE(Down loaded SPE 4.5 from market place and placed the spe modules and appconfig, bin and respective folders)

Error :

Unable to find type [Sitecore.Globals].

**Comment by RajasekharVM** [comment]
Hi Adam,
I am using above script which have mentioned. But while running the script i am getting the below message(it  is not giving any error) and rebuild  is not happening.. Can you please guide us to resolve the issue.

Messages 
**VERBOSE: Checking the Runspace for the variable id.
VERBOSE: Polling job 4d3b0808-534d-479e-a625-4b0712f80d4d. Status : Busy**

**Comment by AdamNaj** [comment]
That means the operation is in progress and after a few messages like this, when the rebuild is finished it should give you the completion message.

**Comment by RajasekharVM** [comment]
After few messages it is saying that pulling job is available and finished pulling job.

Please find the below full messages while running the script:

VERBOSE: Checking the Runspace for the variable id.
VERBOSE: Polling job 4d3b0808-534d-479e-a625-4b0712f80d4d. Status : Busy.
VERBOSE: Checking the Runspace for the variable id.
VERBOSE: Polling job 4d3b0808-534d-479e-a625-4b0712f80d4d. Status : Busy.
VERBOSE: Checking the Runspace for the variable id.
VERBOSE: Polling job 4d3b0808-534d-479e-a625-4b0712f80d4d. Status : Busy.
VERBOSE: Checking the Runspace for the variable id.
VERBOSE: Polling job 4d3b0808-534d-479e-a625-4b0712f80d4d. Status : Busy.
VERBOSE: Checking the Runspace for the variable id.
VERBOSE: Polling job 4d3b0808-534d-479e-a625-4b0712f80d4d. Status : Busy.
VERBOSE: Checking the Runspace for the variable id.
**VERBOSE: Polling job 4d3b0808-534d-479e-a625-4b0712f80d4d. Status : Available.
VERBOSE: Finished polling job 4d3b0808-534d-479e-a625-4b0712f80d4d.
VERBOSE: Checking the Runspace for the variable id.**

**Comment by RajasekharVM** [comment]
and script execution is stopped after getting the messages.

**Comment by RajasekharVM** [comment]
after the script execution when i checked the logs, it is showing as unitprocessed is blank.

**Comment by AdamNaj** [comment]
As far as I can see, from what you gave me, the processing has performed and the rebuilding should be successful.
