### ISSUE TITLE
Not able to pass argument to job

### ISSUE THREAD

**Issue by RajasekharVM** [SitecorePowerShell/Console#894]
Hi I am trying to rebuild the link db by using Powershell ISE, installed SPE(4.3)and required file in app-config,bin and powershell modules.

Not able to pass the arguments to Job while running the rebuild commands. can you please suggest any solution for this ... 

$dbName= Read-Host "Please enter Database name to rebuild"
$jobId=Invoke-RemoteScript -Session $session -ScriptBlock {
       Write-Output "Hi db is  $($params.name)" 
        Get-Database $($params.name) |
            ForEach-Object { 
                [Sitecore.Globals]::LinkDatabase.Rebuild($_)
                 Write-Log "Rebuild database in SPE $($params.name)"
               }                    
               
}-AsJob -Arguments @{"name"=$dbName}

Wait-RemoteScriptSession -Session $session -Id $jobId -Delay 5 -Verbose
$EndDate=(GET-DATE)

--------
Out put 👍 (in the above i am hard coded Db value as "core" )
Hi db is 
00:02:18.9276861 - Total Time taken to Rebuild in mins

**Comment by RajasekharVM** [comment]
Got the way to pass argument to job in powershell SPE , : use this format like -- $using:dbName


$jobId=Invoke-RemoteScript -Session $session -ScriptBlock {
       Write-Output "Selected database name is $using:dbName"
       Get-Database $using:dbName | 
            ForEach-Object { 
                [Sitecore.Globals]::LinkDatabase.Rebuild($_)
                 Write-Log "Rebuild database in SPE $using:dbName"
                 }              
              
}-AsJob

**Comment by AdamNaj** [comment]
Assuming this is a solved problem now.
