### ISSUE TITLE
Cannot pass an argument to a script session running as a job

### ISSUE THREAD

**Issue by romanfirsov** [SitecorePowerShell/Console#902]
Hello Everyone,

I'm trying to pass an argument to a script session running as a job on the server. I pass an argument with the help of ArgumentList parameter. Here is the code:

```powershell
$script = { 
   [Sitecore.Security.Accounts.User]$user = Get-User -Identity admin 
   $user 
   $params.date.ToString() 
} 
      
$args = @{ 
   "date" = [datetime]::Now 
} 
      
Invoke-RemoteScript -ConnectionUri "http://remotesitecore" `
    -Username "admin" -Password "b" -ScriptBlock $script `
    -ArgumentList $args -AsJob
```
It seems that the $params.date variable is empty and I cannot get current date inside the script block. The argument actually gets passed when I run the script without -AsJob parameter. I cannot use $Using variable to pass arguments.

Thank you.

**Comment by AdamNaj** [comment]
Sounds like a task you would jump on @michaellwest :)

**Comment by michaellwest** [comment]
@romanfirsov Can you try the following? I prefer no longer using the `$params` notation.

```
$date = [datetime]::Now
$script = { 
   [Sitecore.Security.Accounts.User]$user = Get-User -Identity admin 
   $user
   $localDateVariable = $using:date
   $localDateVariable.ToString() # This also may work $using:date.ToString() 
} 
      
Invoke-RemoteScript -ConnectionUri "http://remotesitecore" -Username "admin" -Password "b" -ScriptBlock $script -AsJob
```

**Comment by romanfirsov** [comment]
Hello @michaellwest ,
            
This is working example. But I'm running this code inside DSC resource. It replaces the $using:date with the value of the $data variable. A cannot use the $using notation.

Thank you.

**Comment by michaellwest** [comment]
@romanfirsov Did you ever get past this issue? Been a while since we last looked at it. Please post your solution if you have one. Closing for now.
