### ISSUE TITLE
Feature request: Enable rule editor to edit conditions and actions

### ISSUE THREAD

**Issue by damcbc** [SitecorePowerShell/Console#905]
Currently when using the Read-Variable  command and using the rule editor it will not allow you to selection actions. It allows only for conditions. 
Spoke to mr. Michael West and he confirmed that currently SPE hides by default the actions on that editor.

For example:
`$result = Read-Variable -Parameters `
        @{ Name = "psRule"; Editor="rule"; title="My Editor"; Tooltip="Select the condition"; }`
`

when you run the script with this command the rule editor will not enable you to select which actions to take when editing the rule only the conditions.

**Comment by michaellwest** [comment]
Script using **rule** and **action**:
```powershell
$result = Read-Variable -Parameters @{ 
    Name = "psRule"; Editor="rule action"; title="My Editor"; Tooltip="Select the condition";
}
```
Produces the following:
![image](https://user-images.githubusercontent.com/933163/27008687-6801805a-4e3e-11e7-9980-037045c8b79b.png)

@AdamNaj Would we want the rule path configurable too?
Current hard-coded to `"/sitecore/system/Settings/Rules/PowerShell"`

**Comment by michaellwest** [comment]
Implemented.

**Comment by AdamNaj** [comment]
Added a dialog size increase when actions are showing on top of rules. The rest checks out great!
