### ISSUE TITLE
ISE UX/UI improvements

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#907]
While working with ISE I'v noticed few things:
* When using "Full Size" mode (`http://sc/sitecore/shell/Applications/PowerShell/PowerShellIse`), navigation buttons from the ribbon are not visible
![image](https://user-images.githubusercontent.com/6848691/26994886-1a6d1860-4d6a-11e7-9be1-f2e856aea3ff.png)
* When clicking any dropdown button quickly after changing selection in ISE, **Gallery Window** will pop up and then (context item selector, recent scripts selector, context user/language selector and so on) suddenly disappear 
* After I opened any **Gallery Window** and then focus on ISE, recently opened **Gallery Window** remains in place for ~2s, while it should disappear immediately
* When I switch ribbon tab, the next tab will refresh its state after ~2s, while it should refresh it immediately.

**Comment by AdamNaj** [comment]
Awesome job!

**Comment by AdamNaj** [comment]
Verified. Working great!
