### ISSUE TITLE
Export CSV

### ISSUE THREAD

**Issue by nikkipunjabi** [SitecorePowerShell/Console#909]
Dear SPE Team,

Thanks for great module.

I'm facing issue with exporting Arabic Text in Export CSV in Show-ListView Dialog
I think we need to include the -encoding unicode to the Export-CSV

Can you please check it?

Thank You,
Nikki

**Comment by michaellwest** [comment]
Hi @nikkipunjabi , the `Export-Csv` command available in SPE is in fact the one provided by Windows PowerShell. If the version of Windows PowerShell installed on your PC/server supports the parameter, then so would SPE.

**Comment by nikkipunjabi** [comment]
It works fine! Thank You!

**Comment by michaellwest** [comment]
Great to hear.
