### ISSUE TITLE
Permissions required for content authors to view reports under Powershell Reports

### ISSUE THREAD

**Issue by grayjr** [SitecorePowerShell/Console#913]
I have installed Powershell for Sitecore version 4.2 for Sitecore 8
When logged on as an admin I can access powershell reports under Reporting Tools >> PowerShell Reports.  When logged on as a content author who has the Sitecore Client Authoring role I cannot see the reports. I have given the Sitecore Client Authoring role read permissions to core: sitecore/content/Documents and settings/All users/Start menu/Right/Reporting Tools/PowerShell Reports
as instructed in the GitBook.
What am I missing?
Thanks

**Comment by michaellwest** [comment]
Hi @grayjr, does this link provide the solution you need?

https://sitecore.stackexchange.com/questions/4095/sitecore-powershell-extensions-reports-authorization

**Comment by grayjr** [comment]
Hello,
I had found this article and it did not help me solve my issue.
Thanks,
John

**Comment by michaellwest** [comment]
Bummer. How of chance, can you work with version 4.5? We've made some improvements to the security features and we highly recommend you move to it.

**Comment by grayjr** [comment]
We should be able to move to this version.
I’ll do so and let you know if I still have issues.
Thanks,
John

**Comment by michaellwest** [comment]
Great. Let's start with your development environment first to be sure it solves the issue for you, as well as help you learn how to enable the appropriate services.

See about half way down on this page.

https://doc.sitecorepowershell.com/security.html

**Comment by grayjr** [comment]
Will do.
Thank you for your prompt response.

**Comment by AdamNaj** [comment]
This was tackled in the issue #872- using Sitecore security settings. You can either use SPE 4.6 (should be released tomorrow or follow the changes that were introduced in the commit for this feature.

**Comment by grayjr** [comment]
Just want to confirm that version 4.5 is compatible with Sitecore version Sitecore.NET 8.1 (rev. 160519)
This is the version we are on.
Thanks,
John

**Comment by grayjr** [comment]
Hello,
I have installed version 4.5 in both our dev and stage environments a that solved my security issue.

I have a related question:
Can you point me to documentation regarding security implications of installing the module on a
production CMS server?
We would like to install the module in our prod CMS Sitecore instance but want to be sure we are
not opening ourselves up to security risks.

Thanks for all of your help.

-John

**Comment by michaellwest** [comment]
Hi @grayjr , the release of version of 4.5 was to address the vectors of attack discovered while working in the CM role. We do not recommend configuring SPE in a CD role. Installing in DEV, INT, TST CM, and PRD CM should be fine. Do note that the services should be disabled by default, and if you choose, you can enable services based on your need.

**Comment by AdamNaj** [comment]
Hi @grayjr, as Michael already stated installing SPE on CD is not recommended. You can find the information on how to secure your environment and what the knobs are here: https://doc.sitecorepowershell.com/security.html

The version 4.6 available on Marketplace now has all the security fixes and also allows authors in "Client Maintaining" role to see the reports as long as the package is installed on the server.
