### ISSUE TITLE
Cursor does not go to the new line when we press enter for Read-Variable

### ISSUE THREAD

**Issue by nikkipunjabi** [SitecorePowerShell/Console#916]
Team, 

When we press "Enter" with Read-Variable having 20 lines then it triggers OK and the cursor doesn't go to a new line.

For example:

$props = @{
    Parameters = @(
        @{Name="ItemPath"; Title="Enter Sitecore Item Path"; lines=20; Tooltip="Enter Sitecore Item Path";}
    )
    Title = "Publish Items"
    Description = "Publish Items"
    Width = 650
    Height = 400
    ShowHints = $true
}

$result = Read-Variable @props

Is there any way I can allow the user to move the cursor in between lines and add a new line in Read-Variable as in above example?

Thank You

**Comment by michaellwest** [comment]
I don't think using a textbox to store item paths would be the right use for it. Is there another field that would work for you?

I do however see that the return key is tied to the "OK" button.

**Comment by nikkipunjabi** [comment]
Basically, I want to take the input from the user for the list of items path or id to publish. 
Other option would be to take the input in a text file and then read the values.

**Comment by michaellwest** [comment]
@nikkipunjabi If you have the user create a CSV, you could use `Import-Csv`.

**Comment by nikkipunjabi** [comment]
Perfect! I've used the similar approach and will continue with it. Thank You!
