### ISSUE TITLE
Packaging : Overhaul Package Manager with more features!

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#923]
Would be nice if the `Quick download tree as package` command supported referenced media items.

**Comment by michaellwest** [comment]
Current progress:
- Add Item and Tree include linked media and custom templates
- Arrays with lookup added to prevent duplicate items being added to a package.

**Comment by michaellwest** [comment]
Sent to Kamruz for QA.

**Comment by michaellwest** [comment]
TODO : Add linking to the Quick Download.

**Comment by michaellwest** [comment]
![image](https://user-images.githubusercontent.com/933163/29102907-feed929e-7c81-11e7-8b61-fe114e50fb42.png)

**Comment by AdamNaj** [comment]
I see you even remembered to update the `Recover Version Specific Icons` script. Great!
It's a MUCH better tool now! 

Shall we close the issue? Do you want to rename it before release? It seems to be doing so much more than what the title hints at.

**Comment by michaellwest** [comment]
I think this baby can be closed.
