### ISSUE TITLE
Change Settings Item creation to use the Folder ID rather than path

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#932]
### Expected Behavior

When opening and running the console and ISE, the settings item created for the logged in user should based generated by template item ID rather than path.

### Actual Behavior

In a scenario where the Common/Folder item is moved, the settings item creation fails.

### Steps to Reproduce the Problem

Move the `Common/Folder` template to a different path. Launch the ISE and watch it fail.

![image](https://user-images.githubusercontent.com/933163/29624539-f33220fa-87ee-11e7-9c38-26849a08d08d.png)

![image](https://user-images.githubusercontent.com/933163/29624544-f7bd1a58-87ee-11e7-9578-d783440c813b.png)

**Comment by AlexKasaku** [comment]
Could be worth having a quick look around the solution for other instances of "/sitecore/content/..." for hints at reliances on other common item paths.

**Comment by michaellwest** [comment]
Yeah, there are a number of places we can improve this. Better as a separate issue.

**Comment by AlexKasaku** [comment]
Whilst I was there I moved a use of /sitecore/templates into a constant, similar to how the others behaved.
