### ISSUE TITLE
New-UsingBlock: Dispose called twice

### ISSUE THREAD

**Issue by yannisgu** [SitecorePowerShell/Console#933]
### Expected Behavior

When using New-UsingBlock Dispose should only be called once.

### Actual Behavior

The Dispose method of the IDisposable object will be called twice. 
Once because of the using block and once because of the manual call to Dispose in the finally block. 
They are both doing exactly the same, so one of them can safely be deleted.

**Comment by AlexKasaku** [comment]
Good spot, this can just be achieved by the one `using` block.

**Comment by yannisgu** [comment]
Wow, that was fast! Thanks

**Comment by AlexKasaku** [comment]
We aim to please! Plus it was a pretty straight-forward fix. Thanks for spotting it :)
