### ISSUE TITLE
How to Create Branch Template

### ISSUE THREAD

**Issue by HelenAtGitHub** [SitecorePowerShell/Console#937]
May I ask the command to create a Branch Template based on existing template? On standard value, how to deal with data source in rendering, etc?

**Comment by AdamNaj** [comment]
Hi Hellen, Can I ask you to ask the question on [Sitecore Stack Exchange](https://sitecore.stackexchange.com/)? Let's get the knowledge base be built up there as no one will be looking into the closed issues later.
