### ISSUE TITLE
Add-ItemVersion incorrectly copies empty fields like "__Final Renderings"

### ISSUE THREAD

**Issue by Krusen** [SitecorePowerShell/Console#940]
### Expected Behavior

The added version should be identical to the source version (except for ignored fields), including layout and renderings (both shared and final layout).

### Actual Behavior

The `__Final Renderings` field is copied over with an empty string value instead of `null`/nothing, which Sitecore interprets as if the final layout has been changed to "nothing".

![image](https://user-images.githubusercontent.com/1381368/30073357-cb907298-926d-11e7-887f-0d352905aeea.png)

### Steps to Reproduce the Problem

1. Run `Add-ItemVersion` on item with no changes to Final Layout (i.e. an empty `__Final Renderings` field
2. The Final Layout tab will have no layout/renderings.

**Comment by AdamNaj** [comment]
Weirdly... while you're right that the field reports that it doesn't contain the standard value - it does indeed report to be holding empty string rather than null on the original field. (I'm on Sitecore 8.2 U5 - maybe that's why?)

**Comment by AdamNaj** [comment]
Oh, I didn't notice your pull request until after my comment. Pure gold! Thank you for cracking that one!

**Comment by Krusen** [comment]
Ah, yea I forgot to link the issue in the PR.
