### ISSUE TITLE
PowerShell Console UX improvements (shortcuts, features)

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#945]
### Expected Behavior

- [x] `Ctrl+A` - allows me to select whole text in the PS Console
- [x] `Ctrl+C` - allows me to clear console whether selected text is empty otherwise it should copy text into clipboard (2nd part already works fine). 
- [ ] When I hold `Shift` key and press `Left`, `Right` keys I should be able to highlight/unhighlight text
- [ ] When I hold `Shift` + `Ctrl` keys and press `Left`, `Right` keys I should be able to highlight/unhighlight text chunks 

### Actual Behavior
- `Ctrl+A` - set position to `0`
- `Ctrl+C` - This is partially covered by Ctrl+K however I cannot clean all text when my current `position` >`command.length`
- `Shift` + `Left`, `Right`  - unsupported
- `Shift`, `Ctrl` + `Left`, `Right`  - unsupported

Some of the functionalities are missing, some of the shortcuts have different mapping than in Windows PS Console. Those are commonly used by my which I found, there might be more.

### Steps to Reproduce the Problem

- Open Sitecore instance
- Run PowerShell Console
- Test shortcuts

**Comment by michaellwest** [comment]
@alan-null I upgraded the terminal plugin. These now work:

> Ctrl+A - allows me to select whole text in the PS Console
> Ctrl+C - allows me to clear console whether selected text is empty otherwise it should copy text into clipboard

**Comment by alan-null** [comment]
@michaellwest Great!
1st comment updated.
