### ISSUE TITLE
Package Generator : Version and Language filter

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#948]
Perhaps a "latest version" and "Spanish Language" would be helpful.

**Comment by AdamNaj** [comment]
@michaellwest, 7 years... I don't think we'll ever get to this one. If anyone has an appetite to implement this, they can reopen and contribute then.

**Comment by michaellwest** [comment]
> @michaellwest, 7 years... I don't think we'll ever get to this one. If anyone has an appetite to implement this, they can reopen and contribute then.

So you're saying there's a chance?
