### ISSUE TITLE
missing Function documentation

### ISSUE THREAD

**Issue by reedyd** [SitecorePowerShell/Console#952]
### Expected Behavior

SPE documentation should teach about Functions.

### Actual Behavior

That page is empty.

### Steps to Reproduce the Problem

Visit https://doc.sitecorepowershell.com/functions.html 

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Thanks @reedyd . Updated the page on Functions. Let me know if it hit the points you needed.

**Comment by reedyd** [comment]
Fantastic! Thank you.
