### ISSUE TITLE
Multilist with search as editor option not there in powershell extension

### ISSUE THREAD

**Issue by nakerkapil** [SitecorePowerShell/Console#953]
### Expected Behavior

_When we use "Multilist with Search" as editor option using powsershell extension, it shows multilist with out any search. It seems the multilist with search is not enabled._

### Actual Behavior

_When Multilist with Search is used as editor option, it should show the multilistwith search field in the form._

### Steps to Reproduce the Problem

_Sitecore version 8.1._
Use the below line in powershell script
 - @{ Name = "multilistwithsearch";  Title="MultilistDemo"; 
  Source="StartSearchLocation={CC4E9B0A-17B2-4D78-917A-419620A80D06}&TemplateFilter={18050423-3FCF-4AAC-ACA4-B2EEA541000B}"; 
  editor="multilist with Search";             
     }
Can some one tell us that multilist with search is enabled with powershell extension? If yes then could someone show how to configure it?

**Comment by michaellwest** [comment]
Thank you for reporting the issue @nakerkapil . Unfortunately, the `Multilist with Search` is not supported in the current version. I did however make some adjustments which would enable the support in a future version, probably 4.8.

```powershell
$result = Read-Variable -Width 740 -Parameters @{ 
    Name = "selectedItems"; Editor="multilist search"; Title="My Editor"; Tooltip="Multilist Selection";
}
```

![image](https://user-images.githubusercontent.com/933163/31319693-a4d9715c-ac2d-11e7-8893-594d9623d2f2.png)

Using your example here is what it would look like.

```powershell
$result = Read-Variable -Width 740 -Parameters @{ 
    Name = "selectedItems"; Editor="multilist search"; Title="My Editor"; Tooltip="Multilist Selection"; Source="StartSearchLocation={A3572733-5062-43E9-A447-54698BC1C637}&TemplateFilter={DD22F1B3-BD87-4DB2-9E7D-F7A496888D43}";
}
```

![image](https://user-images.githubusercontent.com/933163/31319793-ef0dd866-ac2e-11e7-8a75-61d93d767b61.png)

**Comment by michaellwest** [comment]
TODO:

[ ] Update stylesheet for v7
[ ] Test in v7
