### ISSUE TITLE
Item.Editing.EndEdit() is not triggering save event when called from Powershell extension

### ISSUE THREAD

**Issue by nakerkapil** [SitecorePowerShell/Console#955]
### Expected Behavior

_We have written one rule for bucket items and it gets triggered when an bucket item is created or item is saved. for creating an bucket item we use below code

$updatedItem=New-Item -Path "$parentPath" -Name $Title -ItemType $Template
Now when the item is created , the rule is triggered which is expected. After that I want to trigger the same rule again when the item's fields get updated. I have used below code to update the item fields
$updatedItem.Editing.BeginEdit()
$updatedItem.Title=$NewsTitle      
$updatedItem.DateTime=$NewsDate
$updatedItem.Editing.EndEdit() 
Now these fields get updated silently in sitecore but the save event is not fired and because of that the rule is not triggered. I also used below code to explicitly trigger the event but that too did not work.

$updatedItem.Editing.EndEdit($false,$true)
Is there any way where I can trigger the rule from power shell script or trigger the save event._

### Actual Behavior

_There should be some provision to decide whether the save event or any event should trigger or not ._

### Steps to Reproduce the Problem

_Please create a rule in sitecore which gets triggered on item creation and on item save event.  We had created rule for bucket items. Use below line of code and run the script
$updatedItem=New-Item -Path "$parentPath" -Name $Title -ItemType $Template
$updatedItem.Editing.BeginEdit()
$updatedItem.Title=$NewsTitle      
$updatedItem.DateTime=$NewsDate
$updatedItem.Editing.EndEdit()  or  $updatedItem.Editing.EndEdit($false,$true)

you will observe that on new-item cmdlet , rule will trigger but after updating the fields the event is not triggered._

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Hopefully this is no longer an issue for you. Please reopen if I closed this in error.
