### ISSUE TITLE
Invoke-RemoteScript Errors

### ISSUE THREAD

**Issue by chrisdefrank** [SitecorePowerShell/Console#956]
### Expected Behavior
Call Invoke-RemoteScript from Windows PowerShell to invoke SPE script

### Actual Behavior
Receive the following errors:

Exception calling "Invoke" with "1" argument(s): "Data at the root level is invalid. Line 1, position 1."
At C:\Program Files\WindowsPowerShell\Modules\SPE\ConvertFrom-CliXml.ps1:22 char:9
+         $deserializer = $ctor.Invoke($xr)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : XmlException
 
Exception calling "InvokeMember" with "5" argument(s): "Non-static method requires a target."
At C:\Program Files\WindowsPowerShell\Modules\SPE\ConvertFrom-CliXml.ps1:24 char:16
+         while (!$type.InvokeMember("Done", "InvokeMethod,NonPublic,Instance", $n ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TargetException

### Steps to Reproduce the Problem
Used basic example script:

Import-Module -Name SPE

$session = New-ScriptSession -Username admin -Password xxx -ConnectionUri http://xxx

Invoke-RemoteScript -Session $session -ScriptBlock { Get-User -id admin }

Stop-ScriptSession -Session $session

_Please include the version number of SPE and Sitecore._
Sitecore.NET 8.1 (rev. 160519)
Remoting for SPE 4.7 (same issue on 4.6)

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Have you followed the documentation here? https://doc.sitecorepowershell.com/remoting.html and https://doc.sitecorepowershell.com/security.html

**Comment by chrisdefrank** [comment]
Yes sir, I've been thru that backwards and forwards and it cleared up some initial security issues I had logging in, but unless I'm reading thing wrong it seems like I'm logged in but just getting XML errors on the return?

**Comment by michaellwest** [comment]
Did you perform a clean installation of SPE or was this an upgrade?

**Comment by chrisdefrank** [comment]
Tried initially with 4.6 and then did a replace with 4.7 to see if that would help but same results.  Perhaps I will just try to wipe it out and do a clean install.  I do appreciate the assistance!

**Comment by michaellwest** [comment]
Just to confirm, are you using Windows PowerShell 3 or newer? Does SPE work fine inside of Sitecore?

**Comment by chrisdefrank** [comment]
I completely scoured my environment and removed SPE and just re-installed from scratch and now it's working as expected.  Thanks so much for the help, and sorry for being a pest!!!
