### ISSUE TITLE
Add ability to control field editability

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#957]
As a developer, I want to be able to define field editability.

Right now we have `Validation` which allow us to validate field values and output error messages in case of validation failure. 
I would like to disable(gray out)/hide some fields when certain criteria are not meet.
With that, I could create more interactive dialogs.

Example:
I've got a dialog with a checkbox `Perform action as an admin`
Once the checkbox is checked I could enable/show additional input fields (`login`, `password`) that were disabled/hidden previously.

**Comment by michaellwest** [comment]
What if each field parameter could include a value like control id `data-control-id=1` and the enable state value and disabled state value. Whenever the element changes, such as a checkbox or dropdown, client-side code would respond.

For each parameter that needs to listen for the value change, add a state control id `data-state-control-id=1` and default state value. When the client-side code fires, it toggles the element.

**Comment by michaellwest** [comment]
![snag-0030](https://user-images.githubusercontent.com/933163/40588279-bf05405a-61a0-11e8-9945-ff9e26406f17.gif)
