### ISSUE TITLE
Package Generator is adding undesired referenced items

### ISSUE THREAD

**Issue by krzysztofchmiel** [SitecorePowerShell/Console#960]
### Expected Behavior

Quick download tree as package creates package with only the items in that tree.

### Actual Behavior

Package contains referenced items. Package contains multiple xml files under the same path.

### Steps to Reproduce the Problem

SPE 4.7 Sitecore 8.2 IR

 - Not Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - Not Asked questions on the Sitecore Slack Chat channel.
 
 - Not Reviewed questions and answers on the Sitecore Stack Exchange.

### Additional info
There are no problems in that area with SPE 4.4.1

**Comment by krzysztofchmiel** [comment]
As this occurred during our deployment day and broke it as one of our devs updated PSE without testing if it is not broken. We are still fighting to restore proper live content - thus no test on clean install and proper reproduction steps.

**Comment by michaellwest** [comment]
Hi @krzysztofchmiel , sorry to hear that you encountered an issue during your deployment. The default behavior of the Quick download tree should include the root & descendants, overwriting the children, and not include any referenced items. When I test I don't see multiple xml files under the same path. Perhaps you can shed some more light on what the tree looks like and which items are duplicated.

**Comment by michaellwest** [comment]
Please reopen this issue if you can duplicate using SPE 5.1 or newer. Will need some additional steps (video?) to help reproduce in a vanilla instance.
