### ISSUE TITLE
PageEditorNotificationScript not in use in Sitecore 9.0

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#961]
Pipelines grouping in **Sitecore 9.0** do not respect old patches, thus
`Cognifide.PowerShell.VersionSpecific.Integrations.Pipelines.PageEditorNotificationScript, Cognifide.PowerShell.VersionSpecific`
processor will not be used in Sitecore 9.0.

Notice additional level (`group` node)
![image](https://user-images.githubusercontent.com/6848691/32441177-a9d4f2c8-c2f6-11e7-8688-99e8619af520.png)

We could solve it by 
* creating another version specific config only for 9.0
* duplicating the same patch for both structures (one of them will be redundant but we don't need version specific for 9.0)

**Comment by michaellwest** [comment]
Includes changes from 869d1f3c375e6019f1c4e56951d4700605c74044.

**Comment by AdamNaj** [comment]
Confirmed with Michael that this one should be closed as done
