### ISSUE TITLE
Can't disable user using Set-User and Enabled switch parameter

### ISSUE THREAD

**Issue by GlennHaworth** [SitecorePowerShell/Console#964]
### Expected Behavior

When using `Set-User -Identity "sitecore\TestUser"` or `Set-User -Identity "sitecore\TestUser" -Enabled:$false` I would expect the user to be disabled.

### Actual Behavior

User is not disabled and I'm unable to disable a user using Set-User with the Enabled switch parameter set to false or not specified. Although I can enable a user using `Set-User -Identity "sitecore\TestUser" -Enabled` if that user has been disabled using the Sitecore User Manager.

### Steps to Reproduce the Problem

1. Create test user "sitecore\TestUser" using Sitecore User Manager
2. Run `Set-User -Identity "sitecore\TestUser" -Enabled:$false`
3. Check to see if user is disabled either in Sitecore user manager or using `Get-User -Identity "sitecore\TestUser"`

Sitecore PowerShell Extensions 4.7.0.25828
Sitecore 8.2 Update 5
Windows PowerShell 5.1

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
Thanks.

**Comment by michaellwest** [comment]
@GlennHaworth this will be included in the next release of SPE, probably 4.8.

**Comment by GlennHaworth** [comment]
Excellent, thanks Michael.
