### ISSUE TITLE
Reports : List all unused controller or view renderings

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#969]
Going for something like this:

![snag-0345](https://user-images.githubusercontent.com/933163/34474080-d258e900-ef3f-11e7-9814-fa2354a1e303.png)

**Comment by qinxiaoapp** [comment]
Hello Michael thank you for the great work, I have a question, how can I automate the reports to run in a weekly schedule?

**Comment by qinxiaoapp** [comment]
Hello Michael thank you for the great work, I have a question, how do I automate the report in a weekly schedule, for example auto run broken link report weekly, I tried task schedule and select broken link, set to run every half minute for testing but nothing happens.

**Comment by michaellwest** [comment]
That's a really good question. I don't believe we have setup any of the OOTB reports to run as scheduled tasks and emailed anywhere. They also do not export automatically.

If you have not already, check out the book for configuring scheduled tasks. 

https://doc.sitecorepowershell.com/tasks.html

I suggest you create a new report based on an existing one. You won't need to call `Show-ListView` because that command is only for the visual report in Sitecore. Instead pass the data to `Export-Csv` with whatever path you need. Also, you should take out the calls to `Read-Variable` since in a scheduled task you will not be promoting a user for input.

Let me know if you need more help.

**Comment by qinxiaoapp** [comment]
Thank you for the detailed explanation and suggestions, I'll create a new report script!

**Comment by michaellwest** [comment]
Implemented.

**Comment by michaellwest** [comment]
Combined into a single report to show all renderings and their count.
