### ISSUE TITLE
Change copyrights year of PSE window from 2017 to 2018

### ISSUE THREAD

**Issue by artstashchenko** [SitecorePowerShell/Console#973]
### Expected Behavior

_Please describe the expected behavior._

### Actual Behavior

_Please describe the actual behavior._

### Steps to Reproduce the Problem

_Please include the version number of SPE and Sitecore._

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
Would love for this to be automatic @AdamNaj .

**Comment by michaellwest** [comment]
All of the dates are automatic now, except the PS Module and Version.cs.

**Comment by AdamNaj** [comment]
I'm not sure our copyright is protected if we do it this way.

**Comment by michaellwest** [comment]
I think we're fine. The original date is still there. 

https://stackoverflow.com/a/28850974/1277533
