### ISSUE TITLE
Incorrect path in config file

### ISSUE THREAD

**Issue by MatyasHavel** [SitecorePowerShell/Console#976]
Hi,

I've just dowlnoaded SPE Mininal-4.7 for SC8 and there is wrong path in Cognifide.Powershell.config in
source mode="on" namespace="Cognifide.PowerShell.Client.Applications" folder="**/sitecore modules/Shell/PowerShell/**" deep="true"

Zip file contains **/sitecore modules/PowerShell/** path.

**Comment by michaellwest** [comment]
Please let me know if you still encounter this issue with SPE 5.1 or newer.
