### ISSUE TITLE
Get-ScriptSession and Receive-RemoteSession cmdlets missing?

### ISSUE THREAD

**Issue by psx790** [SitecorePowerShell/Console#979]
In the SPE Remoting documentation here:

https://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/remoting.html

There is a reference to 'Get-ScriptSession' and 'Receive-RemoteSession' cmdlets that don't appear to exist in the SPE Remoting-4.7.zip package available in the Sitecore Marketplace.

Is this an oversight, or intentional? I am working on a remote deployment scenario and would like to use the functionality described for these cmdlets. Thanks!

**Comment by michaellwest** [comment]
The commands `Get-ScriptSession` and `Receive-ScriptSession` are only available in the context of Sitecore at the moment. So you'll need to call those from within `Invoke-RemoteScript`.

**Comment by psx790** [comment]
Thanks @michaellwest . Is there a way you could recommend sending a return code from the remotely run PowerShell script block, to the calling PowerShell script ? I am able to dump errors to the console from the remote block by using Write-Verbose, but I want to be able to check for an error code and stop the deployment if an error occurs.

**Comment by michaellwest** [comment]
Returning data can be done with the following.

```powershell
$result = Invoke-RemoteScript -ScriptBlock {
    $result = 1
    $result
} -Session $session

$result -eq 1
```

**Comment by psx790** [comment]
Hi @michaellwest , thanks for the info. I was able to get the functionality I wanted by copying some code from the Wait-RemoteScript script. The script polls the job periodically to check its status.

This worked perfectly on our dev box. However I have been noticing that it does not work as expected on our staging box. I am using the following snippet to poll for the currently running update job:

```
$session = New-ScriptSession -Username $SitecoreUser -Password $SitecorePassword -ConnectionUri $SitecoreServer

$data = @{"UpdatePackagePath"=$UpdatePackagePath}

$jobId = Invoke-RemoteScript -Session $session -ScriptBlock {

	#force script to fail if an error occurs
	$ErrorActionPreference = "Stop"
	
	#LONG RUNNING TASK HERE
    Install-UpdatePackage -Path $(($using:data).UpdatePackagePath) -UpgradeAction Upgrade -InstallMode Update
		
    Start-Sleep -Seconds 5
		
} -AsJob -Verbose

#dump jobId to console
Write-Host "Current Job ID: $jobId"

$doneScript = {
	$backgroundScriptSession = Get-ScriptSession -Id $using:jobId
	$isDone = $backgroundScriptSession -eq $null -or $backgroundScriptSession.State -ne "Busy"
	[PSCustomObject]@{
		"Name" = $backgroundScriptSession.Id
		"IsDone" = $isDone
		"Status" = "$($backgroundScriptSession.State)"
		"Errors" = $backgroundScriptSession.LastErrors
	}
}

$jobFailed = $false

$keepRunning = $true

while($keepRunning) {		
	$response = Invoke-RemoteScript -Session $session -ScriptBlock $doneScript -Verbose
	if($response -eq $null) {
		$jobFailed = $true
		Write-Error -Message "Job with ID $($jobId) not found."
		break
	} elseif ($response -eq "login failed") {
		$jobFailed = $true
		Write-Error -Message "Login with the specified account failed."
		break            
	}
	
	if($response -and $response.IsDone) {
		$keepRunning = $false
		Write-Host "Polling job $($response.Name). Status : $($response.Status)."
		Write-Host "Finished polling job $($jobId)."
		Write-Host "Job Completed"

		if($response.Errors) {
			$jobFailed = $true
			Write-Error -Message "Job failed"
			$response.Errors | ForEach-Object { Write-Error -Message $_.Exception }
		}
	} else {
		Write-Host "Polling job $($response.Name). Status : $($response.Status)."
		Write-Host "Waiting for $($updateJobPollingTimeInSeconds) seconds..."
		Start-Sleep -Seconds $updateJobPollingTimeInSeconds
	}
}
```


For some reason on our staging box the script will immediately report an "Available" status, even if the job is still running. Deployment log snippet and screenshot here:


> 2018-03-09T23:03:29.5786617Z VERBOSE: Checking the Runspace for the variable data.
> 2018-03-09T23:04:24.1760559Z Current Job ID: 2e3729a2-0bfa-4a4c-8895-7569c02b6dbd
> 2018-03-09T23:04:24.1815585Z VERBOSE: Checking the Runspace for the variable jobId.
> 2018-03-09T23:04:24.3277997Z Polling job 2e3729a2-0bfa-4a4c-8895-7569c02b6dbd. Status : Available.
> 2018-03-09T23:04:24.3284819Z Finished polling job 2e3729a2-0bfa-4a4c-8895-7569c02b6dbd.
> 2018-03-09T23:04:24.3291784Z Job Completed


![powershell_sessions_2](https://user-images.githubusercontent.com/16650627/37299411-9f4beb16-25f9-11e8-9ede-ca92295652c0.png)

Our deployment scenario involves deploying binaries, views, and other related content to IIS before running the script above, so I am wondering if the necessary IIS restart after deploying code is causing issues with the script from running as expected. I did notice some oddities in the SPE.log file on the server, where it appears the polling jobs executed and completed about 10 or 15 seconds before the actual update jobs kicked off.

Any thoughts? Thanks again!

**Comment by michaellwest** [comment]
Please reopen if this is still an issue for you with SPE 5.1 or newer. Would need some additional dialog to pinpoint a solution.
