### ISSUE TITLE
Sitecore 9 - Type initializer exception when executing script via WebAPI 

### ISSUE THREAD

**Issue by jindrichpiroutek** [SitecorePowerShell/Console#982]
Hey guys, I know there already is a related issue to this one #696 which was supposed to be fixed, but it seems that this is still a problem for Sitecore 9.

**Setup**
- Extensions - 4.7.2 for Sitecore 8/9
- Remoting for SPE 4.7
- Sitecore 9 Initial Release
- Azure WebApp hosting

**Steps to Reproduce the Problem**
- Restart the SC9 instance (in Azure Portal)
- Make first script call remotely via WebApi (Install-UpdatePackage -Path $package -UpgradeAction Upgrade -InstallMode Install)
- The script call is unsuccessful, then any other "Install-UpdatePackage" call keeps failing remotely & locally in ISE

**Error**
`Install-UpdatePackage : The type initializer for 'Sitecore.Install.Serialization.IOUtils' threw an exception.
At line:1 char:1
+ Install-UpdatePackage -Path "d:\home\site\wwwroot\App_Data\packages\0 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-UpdatePackage], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Cognifide.PowerShell.Commandlets.UpdatePackages.InstallUpdatePackageCommand`

**If I execute the "Install-UpdatePackage" script from ISE first then the upcoming remote calls via WebAPI work as well.**

We have an automated Octopus deployment and we use the "Remoting" for .update package installation. Is there any quick workaround how to tackle this issue?

**Comment by michaellwest** [comment]
Hey @jindrichpiroutek, sorry to see that you are having an issue with the module. Have you tried testing this on your local machine? Would like to know if the same issue happens outside of Azure.

**Comment by jindrichpiroutek** [comment]
Hello @michaellwest,

I have tried following:
- copy pasted the whole website from WebApp to my local PC
- I kept all the configs as they were deployed/transformed on Azure via Octopus (I just changed the connection strings for DB, adjusted Windows "hosts" file locally so I could use the very same site definitions)
- recycled app-pool, started up a Sitecore backend (just a login screen) and then used the Windows Power-Shell ISE to execute the "Invoke-RemoteScript" with "Install-UpdatePackage"
- I am using the same user having a "sitecore\PowerShell Extensions Remoting" role
- locally, even though this was a first remote request on PSE, it worked just fine - no exceptions, I could see items being installed in log file

- if I execute this on WebApp (as a first PSE remote request) the task is quickly finished and unsuccessful -> then if I execute the same command in Sitecore backend via PowerShell ISE (on WebApp environment) -> I am getting this _Sitecore.Install.Serialization.IOUtils_ exception.

**Comment by criscorra** [comment]
I am having this exact issue in Azure running Sitecore 8.2.6, SPE 4.7.2, and Octopus for deployments. I can verify this process DOES work outside of Azure, as our QA site is on-premise and uses the same Octopus steps/SPE script to install the .update package and publish the site. 

I also experience the issue where the update package wizard in Sitecore is broken until the app is restarted.

I've added a call to test if the file is found to verify SPE can get to the filesystem and see the file from Octopus. It returns true. `$FileExists = Test-Path $package`

Any update on this issue @michaellwest ?

Thanks,
Cris

**Comment by michaellwest** [comment]
To be clear, the issue is currently only reproduced while sitecore is hosted in Azure?

**Comment by criscorra** [comment]
That is my experience, yes.

**Comment by michaellwest** [comment]
I wonder if this is related to issue #997.

**Comment by criscorra** [comment]
This isn't specific to Azure tho, correct? This works for me on our on-premise instance.

Also, in my deployment, I deploy the TDS .update package first and install it, publish. The site is already up and running.

**Comment by michaellwest** [comment]
Up to this point I've only seen reports of issues with the Web API in Azure. Not sure if there is a correlation between the issues or not. 

Can you add this before your call to `Install-UpdatePackage`?

```powershell
$database = Get-Database -Name "core"
New-UsingBlock (New-Object Sitecore.Data.DatabaseSwitcher $database) {
    $context = [Sitecore.Install.Serialization.IOUtils]::SerializationContext
}
```

**Comment by criscorra** [comment]
Do i need to pass $context to the Install-UpdatePackage call somehow?

    New-UsingBlock (New-Object Sitecore.Data.DatabaseSwitcher((Get-Database -Name "core"))) {
	    $context = [Sitecore.Install.Serialization.IOUtils]::SerializationContext
    }
    Install-UpdatePackage -Path $package -UpgradeAction Upgrade -InstallMode Install

**Comment by michaellwest** [comment]
No, just run it like you have in the snippet.

**Comment by jindrichpiroutek** [comment]
Unfortunately, it seems it did not resolve the issue.

**Comment by criscorra** [comment]
The snippet above worked for me to install my package.
My smart-publish defined in my next deployment step did not seem to publish my items thow:

```
Write-Output "Logging into Sitecore, starting a SPE session"
$session = New-ScriptSession -Username $SitecoreSPEUserName  -Password $SitecoreSPEUserPassword -ConnectionUri $SitecoreSPEUrl
Write-Output "Executing Remote Script"
$jobId = Invoke-RemoteScript -Session $session -ScriptBlock {
  Write-Log "Smart publishing site"
  $sourceDb = [Sitecore.Data.Database]::GetDatabase("master")
  $targetDb = [Sitecore.Data.Database]::GetDatabase("web")
  $languages = [Sitecore.Globalization.Language]::GetLanguages($sourceDb)
  [Sitecore.Publishing.PublishManager]::PublishSmart($sourceDb, @($targetDb), $languages)
} -ErrorAction Stop -AsJob
Write-Output "Script Execution started with Job ID $jobId"
Wait-RemoteSitecoreJob  -Session $session -Id $jobId -Delay 5 -ErrorAction Stop
Write-Output "Script Execution complete, ending SPE session" 
Stop-ScriptSession  -Session $session 
$session = $null
```

**Comment by criscorra** [comment]
@michaellwest - can you take a look at my smart-publish script I posted? It's not working for remote powershell to azure. It works fine in our on-prem QA environment.
Thanks.

**Comment by michaellwest** [comment]
So the error as described in the original issue is no longer a barrier?

**Comment by criscorra** [comment]
Correct. The package installs successfully.

**Comment by michaellwest** [comment]
One user suggested making sure the user inherits directly from the role `sitecore\PowerShell Extensions Remoting`.

**Comment by michaellwest** [comment]
Please reopen the issue if you can reproduce using 5.1+ SPE and SPE Remoting on a vanilla instance.
