### ISSUE TITLE
Scripted datasource should learn how to work with an ID

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#983]
Would like to have the following work:

![image](https://user-images.githubusercontent.com/933163/37857480-56a8f452-2ec9-11e8-85cc-a58bcca12ec9.png)

**Comment by jammykam** [comment]
What would be the point of this? Why not just use the GUID directly without the `script:` and let Sitecore handle this natively?

**Comment by michaellwest** [comment]
Because I want it to run the script without a changed path breaking the source.

**Comment by jammykam** [comment]
Ahhh, a guid to the script and not the root item. This makes sense. 🖒
