### ISSUE TITLE
Wildcard items (*) not returned

### ISSUE THREAD

**Issue by AlekseiRusanov** [SitecorePowerShell/Console#992]
I'm not sure it's a bug, probably I'm doing something wrong here, but I could not find any answer anywhere, including the manual, Sitecore Stack Exchange and this issue tracker.
I have created a "``*``" item under under "/sitecore/content"
When I go to find it with Get-Item -Path "master:/sitecore/content/*", I get nothing in the results.

### Expected Behavior
When I run Get-Item -Path "master:/sitecore/content/*", I expect to see the "``*``" item

### Actual Behavior
I see nothing in the console.

### Steps to Reproduce the Problem
Just run
Get-Item -Path "master:/sitecore/content/*"

The versions of Sitecore & SPE:
?spe=4.7.2.26422&ps=5.1&sc=8.2

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [-] Asked questions on the Sitecore Slack Chat channel.
 
 - [x] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
I created a new item under home with the name of "*" and this is what I get on 4.7.0.

![image](https://user-images.githubusercontent.com/933163/38563052-9767a0b6-3ca1-11e8-8741-e10520b22024.png)

![image](https://user-images.githubusercontent.com/933163/38563064-a0128d98-3ca1-11e8-9b26-fb6005a888ff.png)

![image](https://user-images.githubusercontent.com/933163/38563090-b07318f6-3ca1-11e8-8684-238671f9a508.png)

**Comment by AlekseiRusanov** [comment]
Thanks. 
Your sitecore version is 8.2, right?

**Comment by michaellwest** [comment]
Yes it is. I'm upgrading to 4.7.2 to see if the behavior changed.

**Comment by michaellwest** [comment]
That also worked. 

![image](https://user-images.githubusercontent.com/933163/38563975-c17c8c7a-3ca3-11e8-8d0a-e71853fa14eb.png)

**Comment by AlekseiRusanov** [comment]
But you're using "master:/content/home/*" instead of "master:/sitecore/content/home/*"
The root node is "sitecore" (at least in my installation)
If I do it your way, it works too, however it fetches all items/subitems that match the wildcard 
In other words, if I run this Get-Item 'master:/*', I will get the following:

![image](https://user-images.githubusercontent.com/26303770/38564613-2e18fc1c-3ce8-11e8-9eb6-8bf6eaba6368.png)

I would expect only one item, that matches the path exactly.

**Comment by michaellwest** [comment]
If you were running this against the FileSystem, what behavior would you expect?

**Comment by AlekseiRusanov** [comment]
I would expect the same behavior as with Sitecore.Configuration.Factory.GetDatabase("master").GetItem("sitecore/content/*") :)
Is it possible to achieve with Get-Item (or some other function)?
Thanks.

**Comment by michaellwest** [comment]
@AlekseiRusanov so it turns out that when you use `master:/content/home/*` SPE converts it to `master:/sitecore/home/*`. Unfortunately it prefixes with `/sitecore` which you end up with `master:/sitecore/sitecore/content/home/*`. Silly.

**Comment by michaellwest** [comment]
Fixed with commit 108b1d5846b27dae0c92296998dc7a8e2e85eb44.

**Comment by michaellwest** [comment]
@AlekseiRusanov for now you can simply use "master:/content" rather than "master:/sitecore/content" and you will get the proper results. By default SPE prefixed "/sitecore" to all of the literal paths.
