### ISSUE TITLE
Web API - line breaks in JSON output

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#998]
### Expected Behavior

My Web API response returns a well-formatted JSON response
![image](https://user-images.githubusercontent.com/6848691/39178727-bd3304d6-47b2-11e8-9486-0ba6f3708573.png)

### Actual Behavior

For some reason, if a "single line" in response exceed 200 characters, a line break appears which breaks my JSON 
![image](https://user-images.githubusercontent.com/6848691/39178741-c40c7cba-47b2-11e8-9e7e-df15f6a3fd71.png)

### Steps to Reproduce the Problem
1. Create Web API integration point and add example file
2. Set following content
```powershell
[System.Web.HttpContext]::Current.Response.ContentType = "application/json";
$responseObject = @{
    "PROPERTY" = (0..186 | % {"."}) -join ""
}
[Newtonsoft.Json.JsonConvert]::SerializeObject($responseObject)
```

**Comments**:
if you change `186` to `185` you will see well formated string in the output (without line breaks)

**Environment**:
- Sitecore PowerShell Extensions-4.7.2 for Sitecore 8.zip
- Sitecore.NET 9.0.1 (rev. 171219)

</hr>

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
@alan-null does the same issue happen if you use `ConvertTo-Json` instead of Newtonsoft?

**Comment by alan-null** [comment]
@michaellwest yup, the same.

**Comment by AdamNaj** [comment]
Put this at the beginning of your script:
```powershell
Set-HostProperty -HostWidth 2000
```

**Comment by alan-null** [comment]
@AdamNaj It helps but I am not sure if this is a workaround or setting that everyone should set manually.
Feel free to change the status of the issue if you want.

**Comment by michaellwest** [comment]
@AdamNaj Is there a way to avoid formatting when using web api?
