### ISSUE TITLE
Requested registry access is not allowed

### ISSUE THREAD

**Issue by antonyjackson** [SitecorePowerShell/Console#999]
Seems like we have an issue with Windows Registry permissions which prevents us from running SPE. Any assistance you could provide would be appreciated - if you were able to tell me which registry key it is trying to read from for example? I have used Process Monitor to monitor the registry keys being accessed by the w3wp.exe process but it doesn't indicate any unsuccessful registry access attempts.

### Expected Behavior

Execute the example script in PowerShell ISE. 

### Actual Behavior

The following security exception is thrown:

[SecurityException: Requested registry access is not allowed.]
   System.ThrowHelper.ThrowSecurityException(ExceptionResource resource) +56
   Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable) +14612744
   System.Environment.GetEnvironmentVariable(String variable, EnvironmentVariableTarget target) +268
   System.Management.Automation.ModuleIntrinsics.GetExpandedEnvironmentVariable(String name, EnvironmentVariableTarget target) +10
   System.Management.Automation.ModuleIntrinsics.SetModulePath() +56
   System.Management.Automation.ExecutionContext.InitializeCommon(AutomationEngine engine, PSHost hostInterface) +665
   System.Management.Automation.AutomationEngine..ctor(PSHost hostInterface, RunspaceConfiguration runspaceConfiguration, InitialSessionState iss) +401
   System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper() +1169
   System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean syncCall) +390
   System.Management.Automation.PowerShell.get_Runspace() +192
   Cognifide.PowerShell.Core.Host.ScriptSession..cctor() +259

### Steps to Reproduce the Problem

Installed SPE version 4.7.2 in localhost Sitecore 8.1 update 3. Navigate to PowerShell ISE - click Execute.

**Comment by michaellwest** [comment]
SPE does not make use of the Windows registry. SPE spins up Windows PowerShell runspaces.

Will have to research this issue. Please let us know if you discover the solution.

**Comment by michaellwest** [comment]
Are you using a Windows service account? What Windows group or privileges did you grant?

**Comment by antonyjackson** [comment]
Thanks for responding. I have a workaround available because I can run SPE on our test server. The problem is on our workstations which presumably have had some tighter restrictions placed on Windows Registry access. IIS was running as the built in Windows service account - I changed it to use my account which is in the local administrators group but that didn't help.

**Comment by michaellwest** [comment]
Thanks @antonyjackson for the update. If you find a cause and resolution for your workstation please update the ticket.

**Comment by victorlaloggia** [comment]
Hello Folks;
I've been able to solve this issue two ways:

 1. On your IIS endpoint, disable ASP.NET Impersonation
 2. Or, edit the ASP.NET Impersonation to use an account with enough permissions to read the following registry keys:
    - Computer\HKEY_CURRENT_USER\Environment
    - Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
